-- rtl/embed.vhd
-- Token embedding lookup.
--
-- ROM-loads mem/weights/embed.mem (VOCAB*DIM int16 mantissas) plus the
-- per-row embed_mult.mem/embed_shift.mem scale (the SAME per-row
-- mult/shift-quantised format every other weight matrix in this project
-- uses -- dumped by dump_weight_matrix/dump_all_weights, consumed by
-- lm_head.vhd's dot products via scale_mul).
--
-- That per-row (mant, mult, shift) format is NOT directly a block-fp value
-- (mult/shift approximate an arbitrary real row-scale, not a power of two),
-- so it cannot be fed straight into layer.vhd's x_mant/x_exp port, which
-- expects value[j] = mant[j] * 2^(-exp). This unit bridges the two: it
-- reconstructs row `token` to real precision (mant[j] * mult * 2^-shift --
-- the same VHDL-`real` float-glue convention layer.vhd itself uses for its
-- own BFP-from-real requantise steps, e.g. the attention-output / residual
-- BFP encode blocks) and then re-BFP-encodes that reconstructed row to a
-- single power-of-two exponent, using the identical max-search loop
-- layer.vhd uses everywhere it does a "BFP encode from real". This matches
-- forward_fx's raw (float) embedding-lookup row being re-quantised by
-- fx_bfp_from_float the moment it reaches the first matmul_fx/rmsnorm_fx
-- call -- see ref/run_fx.c's dump_embed_prompt / fx_embed.txt, which applies
-- write_bfp_section (== fx_bfp_from_float) directly to the same float row.
--
-- Block-fp convention: value[j] = mant[j] * 2^(-exp).
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.embed_rom_pkg.all;

entity embed is
  generic(
    DIM        : integer := 64;
    VOCAB      : integer := 512;
    WEIGHT_DIR : string  := "../mem/weights/"  -- retained for port compat; ROM is now a package
  );
  port(
    clk    : in  std_logic;
    token  : in  integer;
    done   : out std_logic;
    x_mant : out std_logic_vector(DIM*16-1 downto 0);
    x_exp  : out integer
  );
end entity;

architecture rtl of embed is

  -- Weight ROMs now come from work.embed_rom_pkg (generated by
  -- tools/gen_embed_rom_pkg.py from mem/weights/embed*.mem) instead of a
  -- std.textio load at elaboration -- makes this unit synthesizable.
  --   EMBED_MANT : integer_vector(0 to VOCAB*DIM-1)  (int16 mantissas)
  --   EMBED_MULT : integer_vector(0 to VOCAB-1)      (int32 per-row mult)
  --   EMBED_SHFT : integer_vector(0 to VOCAB-1)      (per-row shift, 0..31)

begin

  -- Behavioral, single-cycle, no start/rst handshake (matches the brief's
  -- port list): `token` is sampled every rising edge and the reconstructed
  -- BFP row for that token is registered on x_mant/x_exp with `done`
  -- pulsing high the same cycle -- a sequencer just drives `token` and reads
  -- the result one clock later (or holds `token` steady and samples once
  -- `done`='1'; with no start pulse, `done` is simply "output valid",
  -- continuously true after the first clock edge).
  -- Bit-exact integer reimplementation of the former `real` datapath.
  --
  -- The reconstructed value is v[j] = prod[j] * 2^(-shift), where
  --   prod[j] = EMBED_MANT[tok*DIM+j] * EMBED_MULT[tok]   (|prod| < 2^47)
  --   shift   = EMBED_SHFT[tok]   (0..31)
  -- Since |prod| < 2^47 is exactly representable and 2^(-shift) is an exact
  -- power of two, the original double-precision math was exact; doing the
  -- same in 64-bit signed integers with round-half-away-from-zero reproduces
  -- it bit-for-bit. All shift arithmetic uses signed(63 downto 0) so it never
  -- overflows.
  process(clk)
    variable tok     : integer;
    variable mant    : signed(63 downto 0);
    variable mult    : signed(63 downto 0);
    variable shft    : integer;
    variable prod    : signed(63 downto 0);
    variable absprod : signed(63 downto 0);
    variable max_prod: signed(63 downto 0);
    variable e       : integer;
    variable net     : integer;
    variable sh      : integer;
    variable r       : signed(63 downto 0);
    variable m       : signed(63 downto 0);
    variable found   : boolean;
  begin
    if rising_edge(clk) then
      tok  := token;
      mult := to_signed(EMBED_MULT(tok), 64);
      shft := EMBED_SHFT(tok);

      -- max_prod = max_j |prod[j]|.
      max_prod := (others => '0');
      for j in 0 to DIM-1 loop
        mant    := to_signed(EMBED_MANT(tok*DIM + j), 64);
        prod    := resize(mant * mult, 64);
        absprod := abs(prod);
        if absprod > max_prod then max_prod := absprod; end if;
      end loop;

      if max_prod = 0 then
        -- All-zero row: matches the original all-zero branch.
        x_exp <= 14;
        for j in 0 to DIM-1 loop
          x_mant((j+1)*16-1 downto j*16) <= (others => '0');
        end loop;
      else
        -- Find the largest e in [-30,30] with round(max_prod*2^(e-shift)) <= 32767
        -- (round-half-up; max_prod >= 0). Values are monotone-decreasing as e
        -- decreases, so the first satisfying e (scanning 30 downto -30) is it.
        e     := -30;
        found := false;
        for ti in 0 to 60 loop
          e   := 30 - ti;
          net := e - shft;
          if net >= 0 then
            -- Positive left shift of a nonzero max always exceeds 32767 -> skip.
            r := to_signed(32768, 64);
          else
            sh := -net;
            -- r = (max_prod + 2^(sh-1)) >> sh   (round half up)
            r := shift_right(max_prod + (to_signed(1, 64) sll (sh-1)), sh);
          end if;
          if r <= 32767 then found := true; exit; end if;
        end loop;
        -- (found is always true here: for e=-30 and shft<=31, net<=-61 so
        --  r = (max_prod + 2^60) >> 61 = 0 <= 32767; max_prod < 2^47.)
        assert found report "embed: no valid BFP exponent found" severity failure;

        x_exp <= e;
        net := e - shft;
        for j in 0 to DIM-1 loop
          mant := to_signed(EMBED_MANT(tok*DIM + j), 64);
          prod := resize(mant * mult, 64);
          if net >= 0 then
            m := shift_left(prod, net);           -- exact
          else
            sh := -net;
            if prod >= 0 then
              m := shift_right(prod + (to_signed(1, 64) sll (sh-1)), sh);
            else
              m := -( shift_right((-prod) + (to_signed(1, 64) sll (sh-1)), sh) );
            end if;
          end if;
          -- saturate to [-32768, 32767]
          if    m >  32767 then m := to_signed( 32767, 64);
          elsif m < -32768 then m := to_signed(-32768, 64);
          end if;
          x_mant((j+1)*16-1 downto j*16) <= std_logic_vector(resize(m, 16));
        end loop;
      end if;

      done <= '1';
    end if;
  end process;

end architecture;
