-- rtl/hbm_tg_ip.vhd -- GENERATED by tools/gen_hbm_tg_ip.py, do not hand-edit.
--
-- Board-facing wrapper for hbm_tg (rtl/hbm_tg.vhd): the same unit with its
-- 15 read masters exposed as individually NAMED AXI interfaces, which is
-- what Vivado's block designer needs in order to see them as AXI at all.
-- All logic, and every counter, lives in hbm_tg; this file is wiring.
--
-- Regenerate with:  python3 tools/gen_hbm_tg_ip.py 15
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity hbm_tg_ip is
  port(
    clk  : in std_logic;
    rstn : in std_logic;
    -- HBM per-stack thermal, straight from the IP.  Unconnected in
    -- the stock design, which is the gap this build closes.
    hbm_temp0    : in std_logic_vector(6 downto 0);
    hbm_temp1    : in std_logic_vector(6 downto 0);
    hbm_cattrip0 : in std_logic;
    hbm_cattrip1 : in std_logic;
    -- AXI4-Lite control/status, from jtag_axi
    s_axi_awvalid : in  std_logic;
    s_axi_awready : out std_logic;
    s_axi_awaddr  : in  std_logic_vector(15 downto 0);
    s_axi_awprot  : in  std_logic_vector(2 downto 0);
    s_axi_wvalid  : in  std_logic;
    s_axi_wready  : out std_logic;
    s_axi_wdata   : in  std_logic_vector(31 downto 0);
    s_axi_wstrb   : in  std_logic_vector(3 downto 0);
    s_axi_bvalid  : out std_logic;
    s_axi_bready  : in  std_logic;
    s_axi_bresp   : out std_logic_vector(1 downto 0);
    s_axi_arvalid : in  std_logic;
    s_axi_arready : out std_logic;
    s_axi_araddr  : in  std_logic_vector(15 downto 0);
    s_axi_arprot  : in  std_logic_vector(2 downto 0);
    s_axi_rvalid  : out std_logic;
    s_axi_rready  : in  std_logic;
    s_axi_rdata   : out std_logic_vector(31 downto 0);
    s_axi_rresp   : out std_logic_vector(1 downto 0)
    ;
    -- HBM SAXI port 0
    m00_axi_awvalid : out std_logic;
    m00_axi_awready : in  std_logic;
    m00_axi_awaddr  : out std_logic_vector(32 downto 0);
    m00_axi_awid    : out std_logic_vector(5 downto 0);
    m00_axi_awlen   : out std_logic_vector(3 downto 0);
    m00_axi_awsize  : out std_logic_vector(2 downto 0);
    m00_axi_awburst : out std_logic_vector(1 downto 0);
    m00_axi_wvalid  : out std_logic;
    m00_axi_wready  : in  std_logic;
    m00_axi_wdata   : out std_logic_vector(255 downto 0);
    m00_axi_wstrb   : out std_logic_vector(31 downto 0);
    m00_axi_wlast   : out std_logic;
    m00_axi_bvalid  : in  std_logic;
    m00_axi_bready  : out std_logic;
    m00_axi_bid     : in  std_logic_vector(5 downto 0);
    m00_axi_bresp   : in  std_logic_vector(1 downto 0);
    m00_axi_arvalid : out std_logic;
    m00_axi_arready : in  std_logic;
    m00_axi_araddr  : out std_logic_vector(32 downto 0);
    m00_axi_arid    : out std_logic_vector(5 downto 0);
    m00_axi_arlen   : out std_logic_vector(3 downto 0);
    m00_axi_arsize  : out std_logic_vector(2 downto 0);
    m00_axi_arburst : out std_logic_vector(1 downto 0);
    m00_axi_rvalid  : in  std_logic;
    m00_axi_rready  : out std_logic;
    m00_axi_rdata   : in  std_logic_vector(255 downto 0);
    m00_axi_rlast   : in  std_logic;
    m00_axi_rid     : in  std_logic_vector(5 downto 0);
    m00_axi_rresp   : in  std_logic_vector(1 downto 0)
    ;
    -- HBM SAXI port 1
    m01_axi_awvalid : out std_logic;
    m01_axi_awready : in  std_logic;
    m01_axi_awaddr  : out std_logic_vector(32 downto 0);
    m01_axi_awid    : out std_logic_vector(5 downto 0);
    m01_axi_awlen   : out std_logic_vector(3 downto 0);
    m01_axi_awsize  : out std_logic_vector(2 downto 0);
    m01_axi_awburst : out std_logic_vector(1 downto 0);
    m01_axi_wvalid  : out std_logic;
    m01_axi_wready  : in  std_logic;
    m01_axi_wdata   : out std_logic_vector(255 downto 0);
    m01_axi_wstrb   : out std_logic_vector(31 downto 0);
    m01_axi_wlast   : out std_logic;
    m01_axi_bvalid  : in  std_logic;
    m01_axi_bready  : out std_logic;
    m01_axi_bid     : in  std_logic_vector(5 downto 0);
    m01_axi_bresp   : in  std_logic_vector(1 downto 0);
    m01_axi_arvalid : out std_logic;
    m01_axi_arready : in  std_logic;
    m01_axi_araddr  : out std_logic_vector(32 downto 0);
    m01_axi_arid    : out std_logic_vector(5 downto 0);
    m01_axi_arlen   : out std_logic_vector(3 downto 0);
    m01_axi_arsize  : out std_logic_vector(2 downto 0);
    m01_axi_arburst : out std_logic_vector(1 downto 0);
    m01_axi_rvalid  : in  std_logic;
    m01_axi_rready  : out std_logic;
    m01_axi_rdata   : in  std_logic_vector(255 downto 0);
    m01_axi_rlast   : in  std_logic;
    m01_axi_rid     : in  std_logic_vector(5 downto 0);
    m01_axi_rresp   : in  std_logic_vector(1 downto 0)
    ;
    -- HBM SAXI port 2
    m02_axi_awvalid : out std_logic;
    m02_axi_awready : in  std_logic;
    m02_axi_awaddr  : out std_logic_vector(32 downto 0);
    m02_axi_awid    : out std_logic_vector(5 downto 0);
    m02_axi_awlen   : out std_logic_vector(3 downto 0);
    m02_axi_awsize  : out std_logic_vector(2 downto 0);
    m02_axi_awburst : out std_logic_vector(1 downto 0);
    m02_axi_wvalid  : out std_logic;
    m02_axi_wready  : in  std_logic;
    m02_axi_wdata   : out std_logic_vector(255 downto 0);
    m02_axi_wstrb   : out std_logic_vector(31 downto 0);
    m02_axi_wlast   : out std_logic;
    m02_axi_bvalid  : in  std_logic;
    m02_axi_bready  : out std_logic;
    m02_axi_bid     : in  std_logic_vector(5 downto 0);
    m02_axi_bresp   : in  std_logic_vector(1 downto 0);
    m02_axi_arvalid : out std_logic;
    m02_axi_arready : in  std_logic;
    m02_axi_araddr  : out std_logic_vector(32 downto 0);
    m02_axi_arid    : out std_logic_vector(5 downto 0);
    m02_axi_arlen   : out std_logic_vector(3 downto 0);
    m02_axi_arsize  : out std_logic_vector(2 downto 0);
    m02_axi_arburst : out std_logic_vector(1 downto 0);
    m02_axi_rvalid  : in  std_logic;
    m02_axi_rready  : out std_logic;
    m02_axi_rdata   : in  std_logic_vector(255 downto 0);
    m02_axi_rlast   : in  std_logic;
    m02_axi_rid     : in  std_logic_vector(5 downto 0);
    m02_axi_rresp   : in  std_logic_vector(1 downto 0)
    ;
    -- HBM SAXI port 3
    m03_axi_awvalid : out std_logic;
    m03_axi_awready : in  std_logic;
    m03_axi_awaddr  : out std_logic_vector(32 downto 0);
    m03_axi_awid    : out std_logic_vector(5 downto 0);
    m03_axi_awlen   : out std_logic_vector(3 downto 0);
    m03_axi_awsize  : out std_logic_vector(2 downto 0);
    m03_axi_awburst : out std_logic_vector(1 downto 0);
    m03_axi_wvalid  : out std_logic;
    m03_axi_wready  : in  std_logic;
    m03_axi_wdata   : out std_logic_vector(255 downto 0);
    m03_axi_wstrb   : out std_logic_vector(31 downto 0);
    m03_axi_wlast   : out std_logic;
    m03_axi_bvalid  : in  std_logic;
    m03_axi_bready  : out std_logic;
    m03_axi_bid     : in  std_logic_vector(5 downto 0);
    m03_axi_bresp   : in  std_logic_vector(1 downto 0);
    m03_axi_arvalid : out std_logic;
    m03_axi_arready : in  std_logic;
    m03_axi_araddr  : out std_logic_vector(32 downto 0);
    m03_axi_arid    : out std_logic_vector(5 downto 0);
    m03_axi_arlen   : out std_logic_vector(3 downto 0);
    m03_axi_arsize  : out std_logic_vector(2 downto 0);
    m03_axi_arburst : out std_logic_vector(1 downto 0);
    m03_axi_rvalid  : in  std_logic;
    m03_axi_rready  : out std_logic;
    m03_axi_rdata   : in  std_logic_vector(255 downto 0);
    m03_axi_rlast   : in  std_logic;
    m03_axi_rid     : in  std_logic_vector(5 downto 0);
    m03_axi_rresp   : in  std_logic_vector(1 downto 0)
    ;
    -- HBM SAXI port 4
    m04_axi_awvalid : out std_logic;
    m04_axi_awready : in  std_logic;
    m04_axi_awaddr  : out std_logic_vector(32 downto 0);
    m04_axi_awid    : out std_logic_vector(5 downto 0);
    m04_axi_awlen   : out std_logic_vector(3 downto 0);
    m04_axi_awsize  : out std_logic_vector(2 downto 0);
    m04_axi_awburst : out std_logic_vector(1 downto 0);
    m04_axi_wvalid  : out std_logic;
    m04_axi_wready  : in  std_logic;
    m04_axi_wdata   : out std_logic_vector(255 downto 0);
    m04_axi_wstrb   : out std_logic_vector(31 downto 0);
    m04_axi_wlast   : out std_logic;
    m04_axi_bvalid  : in  std_logic;
    m04_axi_bready  : out std_logic;
    m04_axi_bid     : in  std_logic_vector(5 downto 0);
    m04_axi_bresp   : in  std_logic_vector(1 downto 0);
    m04_axi_arvalid : out std_logic;
    m04_axi_arready : in  std_logic;
    m04_axi_araddr  : out std_logic_vector(32 downto 0);
    m04_axi_arid    : out std_logic_vector(5 downto 0);
    m04_axi_arlen   : out std_logic_vector(3 downto 0);
    m04_axi_arsize  : out std_logic_vector(2 downto 0);
    m04_axi_arburst : out std_logic_vector(1 downto 0);
    m04_axi_rvalid  : in  std_logic;
    m04_axi_rready  : out std_logic;
    m04_axi_rdata   : in  std_logic_vector(255 downto 0);
    m04_axi_rlast   : in  std_logic;
    m04_axi_rid     : in  std_logic_vector(5 downto 0);
    m04_axi_rresp   : in  std_logic_vector(1 downto 0)
    ;
    -- HBM SAXI port 5
    m05_axi_awvalid : out std_logic;
    m05_axi_awready : in  std_logic;
    m05_axi_awaddr  : out std_logic_vector(32 downto 0);
    m05_axi_awid    : out std_logic_vector(5 downto 0);
    m05_axi_awlen   : out std_logic_vector(3 downto 0);
    m05_axi_awsize  : out std_logic_vector(2 downto 0);
    m05_axi_awburst : out std_logic_vector(1 downto 0);
    m05_axi_wvalid  : out std_logic;
    m05_axi_wready  : in  std_logic;
    m05_axi_wdata   : out std_logic_vector(255 downto 0);
    m05_axi_wstrb   : out std_logic_vector(31 downto 0);
    m05_axi_wlast   : out std_logic;
    m05_axi_bvalid  : in  std_logic;
    m05_axi_bready  : out std_logic;
    m05_axi_bid     : in  std_logic_vector(5 downto 0);
    m05_axi_bresp   : in  std_logic_vector(1 downto 0);
    m05_axi_arvalid : out std_logic;
    m05_axi_arready : in  std_logic;
    m05_axi_araddr  : out std_logic_vector(32 downto 0);
    m05_axi_arid    : out std_logic_vector(5 downto 0);
    m05_axi_arlen   : out std_logic_vector(3 downto 0);
    m05_axi_arsize  : out std_logic_vector(2 downto 0);
    m05_axi_arburst : out std_logic_vector(1 downto 0);
    m05_axi_rvalid  : in  std_logic;
    m05_axi_rready  : out std_logic;
    m05_axi_rdata   : in  std_logic_vector(255 downto 0);
    m05_axi_rlast   : in  std_logic;
    m05_axi_rid     : in  std_logic_vector(5 downto 0);
    m05_axi_rresp   : in  std_logic_vector(1 downto 0)
    ;
    -- HBM SAXI port 6
    m06_axi_awvalid : out std_logic;
    m06_axi_awready : in  std_logic;
    m06_axi_awaddr  : out std_logic_vector(32 downto 0);
    m06_axi_awid    : out std_logic_vector(5 downto 0);
    m06_axi_awlen   : out std_logic_vector(3 downto 0);
    m06_axi_awsize  : out std_logic_vector(2 downto 0);
    m06_axi_awburst : out std_logic_vector(1 downto 0);
    m06_axi_wvalid  : out std_logic;
    m06_axi_wready  : in  std_logic;
    m06_axi_wdata   : out std_logic_vector(255 downto 0);
    m06_axi_wstrb   : out std_logic_vector(31 downto 0);
    m06_axi_wlast   : out std_logic;
    m06_axi_bvalid  : in  std_logic;
    m06_axi_bready  : out std_logic;
    m06_axi_bid     : in  std_logic_vector(5 downto 0);
    m06_axi_bresp   : in  std_logic_vector(1 downto 0);
    m06_axi_arvalid : out std_logic;
    m06_axi_arready : in  std_logic;
    m06_axi_araddr  : out std_logic_vector(32 downto 0);
    m06_axi_arid    : out std_logic_vector(5 downto 0);
    m06_axi_arlen   : out std_logic_vector(3 downto 0);
    m06_axi_arsize  : out std_logic_vector(2 downto 0);
    m06_axi_arburst : out std_logic_vector(1 downto 0);
    m06_axi_rvalid  : in  std_logic;
    m06_axi_rready  : out std_logic;
    m06_axi_rdata   : in  std_logic_vector(255 downto 0);
    m06_axi_rlast   : in  std_logic;
    m06_axi_rid     : in  std_logic_vector(5 downto 0);
    m06_axi_rresp   : in  std_logic_vector(1 downto 0)
    ;
    -- HBM SAXI port 7
    m07_axi_awvalid : out std_logic;
    m07_axi_awready : in  std_logic;
    m07_axi_awaddr  : out std_logic_vector(32 downto 0);
    m07_axi_awid    : out std_logic_vector(5 downto 0);
    m07_axi_awlen   : out std_logic_vector(3 downto 0);
    m07_axi_awsize  : out std_logic_vector(2 downto 0);
    m07_axi_awburst : out std_logic_vector(1 downto 0);
    m07_axi_wvalid  : out std_logic;
    m07_axi_wready  : in  std_logic;
    m07_axi_wdata   : out std_logic_vector(255 downto 0);
    m07_axi_wstrb   : out std_logic_vector(31 downto 0);
    m07_axi_wlast   : out std_logic;
    m07_axi_bvalid  : in  std_logic;
    m07_axi_bready  : out std_logic;
    m07_axi_bid     : in  std_logic_vector(5 downto 0);
    m07_axi_bresp   : in  std_logic_vector(1 downto 0);
    m07_axi_arvalid : out std_logic;
    m07_axi_arready : in  std_logic;
    m07_axi_araddr  : out std_logic_vector(32 downto 0);
    m07_axi_arid    : out std_logic_vector(5 downto 0);
    m07_axi_arlen   : out std_logic_vector(3 downto 0);
    m07_axi_arsize  : out std_logic_vector(2 downto 0);
    m07_axi_arburst : out std_logic_vector(1 downto 0);
    m07_axi_rvalid  : in  std_logic;
    m07_axi_rready  : out std_logic;
    m07_axi_rdata   : in  std_logic_vector(255 downto 0);
    m07_axi_rlast   : in  std_logic;
    m07_axi_rid     : in  std_logic_vector(5 downto 0);
    m07_axi_rresp   : in  std_logic_vector(1 downto 0)
    ;
    -- HBM SAXI port 8
    m08_axi_awvalid : out std_logic;
    m08_axi_awready : in  std_logic;
    m08_axi_awaddr  : out std_logic_vector(32 downto 0);
    m08_axi_awid    : out std_logic_vector(5 downto 0);
    m08_axi_awlen   : out std_logic_vector(3 downto 0);
    m08_axi_awsize  : out std_logic_vector(2 downto 0);
    m08_axi_awburst : out std_logic_vector(1 downto 0);
    m08_axi_wvalid  : out std_logic;
    m08_axi_wready  : in  std_logic;
    m08_axi_wdata   : out std_logic_vector(255 downto 0);
    m08_axi_wstrb   : out std_logic_vector(31 downto 0);
    m08_axi_wlast   : out std_logic;
    m08_axi_bvalid  : in  std_logic;
    m08_axi_bready  : out std_logic;
    m08_axi_bid     : in  std_logic_vector(5 downto 0);
    m08_axi_bresp   : in  std_logic_vector(1 downto 0);
    m08_axi_arvalid : out std_logic;
    m08_axi_arready : in  std_logic;
    m08_axi_araddr  : out std_logic_vector(32 downto 0);
    m08_axi_arid    : out std_logic_vector(5 downto 0);
    m08_axi_arlen   : out std_logic_vector(3 downto 0);
    m08_axi_arsize  : out std_logic_vector(2 downto 0);
    m08_axi_arburst : out std_logic_vector(1 downto 0);
    m08_axi_rvalid  : in  std_logic;
    m08_axi_rready  : out std_logic;
    m08_axi_rdata   : in  std_logic_vector(255 downto 0);
    m08_axi_rlast   : in  std_logic;
    m08_axi_rid     : in  std_logic_vector(5 downto 0);
    m08_axi_rresp   : in  std_logic_vector(1 downto 0)
    ;
    -- HBM SAXI port 9
    m09_axi_awvalid : out std_logic;
    m09_axi_awready : in  std_logic;
    m09_axi_awaddr  : out std_logic_vector(32 downto 0);
    m09_axi_awid    : out std_logic_vector(5 downto 0);
    m09_axi_awlen   : out std_logic_vector(3 downto 0);
    m09_axi_awsize  : out std_logic_vector(2 downto 0);
    m09_axi_awburst : out std_logic_vector(1 downto 0);
    m09_axi_wvalid  : out std_logic;
    m09_axi_wready  : in  std_logic;
    m09_axi_wdata   : out std_logic_vector(255 downto 0);
    m09_axi_wstrb   : out std_logic_vector(31 downto 0);
    m09_axi_wlast   : out std_logic;
    m09_axi_bvalid  : in  std_logic;
    m09_axi_bready  : out std_logic;
    m09_axi_bid     : in  std_logic_vector(5 downto 0);
    m09_axi_bresp   : in  std_logic_vector(1 downto 0);
    m09_axi_arvalid : out std_logic;
    m09_axi_arready : in  std_logic;
    m09_axi_araddr  : out std_logic_vector(32 downto 0);
    m09_axi_arid    : out std_logic_vector(5 downto 0);
    m09_axi_arlen   : out std_logic_vector(3 downto 0);
    m09_axi_arsize  : out std_logic_vector(2 downto 0);
    m09_axi_arburst : out std_logic_vector(1 downto 0);
    m09_axi_rvalid  : in  std_logic;
    m09_axi_rready  : out std_logic;
    m09_axi_rdata   : in  std_logic_vector(255 downto 0);
    m09_axi_rlast   : in  std_logic;
    m09_axi_rid     : in  std_logic_vector(5 downto 0);
    m09_axi_rresp   : in  std_logic_vector(1 downto 0)
    ;
    -- HBM SAXI port 10
    m10_axi_awvalid : out std_logic;
    m10_axi_awready : in  std_logic;
    m10_axi_awaddr  : out std_logic_vector(32 downto 0);
    m10_axi_awid    : out std_logic_vector(5 downto 0);
    m10_axi_awlen   : out std_logic_vector(3 downto 0);
    m10_axi_awsize  : out std_logic_vector(2 downto 0);
    m10_axi_awburst : out std_logic_vector(1 downto 0);
    m10_axi_wvalid  : out std_logic;
    m10_axi_wready  : in  std_logic;
    m10_axi_wdata   : out std_logic_vector(255 downto 0);
    m10_axi_wstrb   : out std_logic_vector(31 downto 0);
    m10_axi_wlast   : out std_logic;
    m10_axi_bvalid  : in  std_logic;
    m10_axi_bready  : out std_logic;
    m10_axi_bid     : in  std_logic_vector(5 downto 0);
    m10_axi_bresp   : in  std_logic_vector(1 downto 0);
    m10_axi_arvalid : out std_logic;
    m10_axi_arready : in  std_logic;
    m10_axi_araddr  : out std_logic_vector(32 downto 0);
    m10_axi_arid    : out std_logic_vector(5 downto 0);
    m10_axi_arlen   : out std_logic_vector(3 downto 0);
    m10_axi_arsize  : out std_logic_vector(2 downto 0);
    m10_axi_arburst : out std_logic_vector(1 downto 0);
    m10_axi_rvalid  : in  std_logic;
    m10_axi_rready  : out std_logic;
    m10_axi_rdata   : in  std_logic_vector(255 downto 0);
    m10_axi_rlast   : in  std_logic;
    m10_axi_rid     : in  std_logic_vector(5 downto 0);
    m10_axi_rresp   : in  std_logic_vector(1 downto 0)
    ;
    -- HBM SAXI port 11
    m11_axi_awvalid : out std_logic;
    m11_axi_awready : in  std_logic;
    m11_axi_awaddr  : out std_logic_vector(32 downto 0);
    m11_axi_awid    : out std_logic_vector(5 downto 0);
    m11_axi_awlen   : out std_logic_vector(3 downto 0);
    m11_axi_awsize  : out std_logic_vector(2 downto 0);
    m11_axi_awburst : out std_logic_vector(1 downto 0);
    m11_axi_wvalid  : out std_logic;
    m11_axi_wready  : in  std_logic;
    m11_axi_wdata   : out std_logic_vector(255 downto 0);
    m11_axi_wstrb   : out std_logic_vector(31 downto 0);
    m11_axi_wlast   : out std_logic;
    m11_axi_bvalid  : in  std_logic;
    m11_axi_bready  : out std_logic;
    m11_axi_bid     : in  std_logic_vector(5 downto 0);
    m11_axi_bresp   : in  std_logic_vector(1 downto 0);
    m11_axi_arvalid : out std_logic;
    m11_axi_arready : in  std_logic;
    m11_axi_araddr  : out std_logic_vector(32 downto 0);
    m11_axi_arid    : out std_logic_vector(5 downto 0);
    m11_axi_arlen   : out std_logic_vector(3 downto 0);
    m11_axi_arsize  : out std_logic_vector(2 downto 0);
    m11_axi_arburst : out std_logic_vector(1 downto 0);
    m11_axi_rvalid  : in  std_logic;
    m11_axi_rready  : out std_logic;
    m11_axi_rdata   : in  std_logic_vector(255 downto 0);
    m11_axi_rlast   : in  std_logic;
    m11_axi_rid     : in  std_logic_vector(5 downto 0);
    m11_axi_rresp   : in  std_logic_vector(1 downto 0)
    ;
    -- HBM SAXI port 12
    m12_axi_awvalid : out std_logic;
    m12_axi_awready : in  std_logic;
    m12_axi_awaddr  : out std_logic_vector(32 downto 0);
    m12_axi_awid    : out std_logic_vector(5 downto 0);
    m12_axi_awlen   : out std_logic_vector(3 downto 0);
    m12_axi_awsize  : out std_logic_vector(2 downto 0);
    m12_axi_awburst : out std_logic_vector(1 downto 0);
    m12_axi_wvalid  : out std_logic;
    m12_axi_wready  : in  std_logic;
    m12_axi_wdata   : out std_logic_vector(255 downto 0);
    m12_axi_wstrb   : out std_logic_vector(31 downto 0);
    m12_axi_wlast   : out std_logic;
    m12_axi_bvalid  : in  std_logic;
    m12_axi_bready  : out std_logic;
    m12_axi_bid     : in  std_logic_vector(5 downto 0);
    m12_axi_bresp   : in  std_logic_vector(1 downto 0);
    m12_axi_arvalid : out std_logic;
    m12_axi_arready : in  std_logic;
    m12_axi_araddr  : out std_logic_vector(32 downto 0);
    m12_axi_arid    : out std_logic_vector(5 downto 0);
    m12_axi_arlen   : out std_logic_vector(3 downto 0);
    m12_axi_arsize  : out std_logic_vector(2 downto 0);
    m12_axi_arburst : out std_logic_vector(1 downto 0);
    m12_axi_rvalid  : in  std_logic;
    m12_axi_rready  : out std_logic;
    m12_axi_rdata   : in  std_logic_vector(255 downto 0);
    m12_axi_rlast   : in  std_logic;
    m12_axi_rid     : in  std_logic_vector(5 downto 0);
    m12_axi_rresp   : in  std_logic_vector(1 downto 0)
    ;
    -- HBM SAXI port 13
    m13_axi_awvalid : out std_logic;
    m13_axi_awready : in  std_logic;
    m13_axi_awaddr  : out std_logic_vector(32 downto 0);
    m13_axi_awid    : out std_logic_vector(5 downto 0);
    m13_axi_awlen   : out std_logic_vector(3 downto 0);
    m13_axi_awsize  : out std_logic_vector(2 downto 0);
    m13_axi_awburst : out std_logic_vector(1 downto 0);
    m13_axi_wvalid  : out std_logic;
    m13_axi_wready  : in  std_logic;
    m13_axi_wdata   : out std_logic_vector(255 downto 0);
    m13_axi_wstrb   : out std_logic_vector(31 downto 0);
    m13_axi_wlast   : out std_logic;
    m13_axi_bvalid  : in  std_logic;
    m13_axi_bready  : out std_logic;
    m13_axi_bid     : in  std_logic_vector(5 downto 0);
    m13_axi_bresp   : in  std_logic_vector(1 downto 0);
    m13_axi_arvalid : out std_logic;
    m13_axi_arready : in  std_logic;
    m13_axi_araddr  : out std_logic_vector(32 downto 0);
    m13_axi_arid    : out std_logic_vector(5 downto 0);
    m13_axi_arlen   : out std_logic_vector(3 downto 0);
    m13_axi_arsize  : out std_logic_vector(2 downto 0);
    m13_axi_arburst : out std_logic_vector(1 downto 0);
    m13_axi_rvalid  : in  std_logic;
    m13_axi_rready  : out std_logic;
    m13_axi_rdata   : in  std_logic_vector(255 downto 0);
    m13_axi_rlast   : in  std_logic;
    m13_axi_rid     : in  std_logic_vector(5 downto 0);
    m13_axi_rresp   : in  std_logic_vector(1 downto 0)
    ;
    -- HBM SAXI port 14
    m14_axi_awvalid : out std_logic;
    m14_axi_awready : in  std_logic;
    m14_axi_awaddr  : out std_logic_vector(32 downto 0);
    m14_axi_awid    : out std_logic_vector(5 downto 0);
    m14_axi_awlen   : out std_logic_vector(3 downto 0);
    m14_axi_awsize  : out std_logic_vector(2 downto 0);
    m14_axi_awburst : out std_logic_vector(1 downto 0);
    m14_axi_wvalid  : out std_logic;
    m14_axi_wready  : in  std_logic;
    m14_axi_wdata   : out std_logic_vector(255 downto 0);
    m14_axi_wstrb   : out std_logic_vector(31 downto 0);
    m14_axi_wlast   : out std_logic;
    m14_axi_bvalid  : in  std_logic;
    m14_axi_bready  : out std_logic;
    m14_axi_bid     : in  std_logic_vector(5 downto 0);
    m14_axi_bresp   : in  std_logic_vector(1 downto 0);
    m14_axi_arvalid : out std_logic;
    m14_axi_arready : in  std_logic;
    m14_axi_araddr  : out std_logic_vector(32 downto 0);
    m14_axi_arid    : out std_logic_vector(5 downto 0);
    m14_axi_arlen   : out std_logic_vector(3 downto 0);
    m14_axi_arsize  : out std_logic_vector(2 downto 0);
    m14_axi_arburst : out std_logic_vector(1 downto 0);
    m14_axi_rvalid  : in  std_logic;
    m14_axi_rready  : out std_logic;
    m14_axi_rdata   : in  std_logic_vector(255 downto 0);
    m14_axi_rlast   : in  std_logic;
    m14_axi_rid     : in  std_logic_vector(5 downto 0);
    m14_axi_rresp   : in  std_logic_vector(1 downto 0)
    ;
    aresetn_o : out std_logic
  );
end entity;

architecture rtl of hbm_tg_ip is
  constant NPORT  : positive := 15;
  constant ADDR_W : positive := 33;
  signal arvalid, arready, rvalid, rready, rlast
       : std_logic_vector(NPORT-1 downto 0);
  -- rresp was DECLARED on every port and then dropped on the floor:
  -- the wrapper accepted it and connected nothing, so the generator
  -- counted error beats as good ones and a mis-decoded address would
  -- have reported HIGHER bandwidth, not a failure.  Now carried.
  signal rresp   : std_logic_vector(NPORT*2-1 downto 0);
  signal araddr  : std_logic_vector(NPORT*ADDR_W-1 downto 0);
  signal arlen   : std_logic_vector(NPORT*8-1 downto 0);
  signal arsize  : std_logic_vector(NPORT*3-1 downto 0);
  signal arburst : std_logic_vector(NPORT*2-1 downto 0);
begin
  u : entity work.hbm_tg
    generic map(NPORT => NPORT, AXI_DW => 256, ADDR_W => ADDR_W,
                REGION_LOG2 => 28, PORT0 => 1)
    port map(clk => clk, rstn => rstn,
      hbm_temp0 => hbm_temp0, hbm_temp1 => hbm_temp1,
      hbm_cattrip0 => hbm_cattrip0, hbm_cattrip1 => hbm_cattrip1,
      s_awvalid => s_axi_awvalid, s_awready => s_axi_awready,
      s_awaddr  => s_axi_awaddr,
      s_wvalid  => s_axi_wvalid,  s_wready  => s_axi_wready,
      s_wdata   => s_axi_wdata,
      s_bvalid  => s_axi_bvalid,  s_bready  => s_axi_bready,
      s_arvalid => s_axi_arvalid, s_arready => s_axi_arready,
      s_araddr  => s_axi_araddr,
      s_rvalid  => s_axi_rvalid,  s_rready  => s_axi_rready,
      s_rdata   => s_axi_rdata,
      m_arvalid => arvalid, m_arready => arready, m_araddr => araddr,
      m_arlen   => arlen,   m_arsize  => arsize,  m_arburst => arburst,
      m_rvalid  => rvalid,  m_rready  => rready,  m_rlast   => rlast,
      m_rresp   => rresp, aresetn_o => aresetn_o);

  s_axi_bresp <= "00";
  s_axi_rresp <= "00";

  -- port 0
  m00_axi_arvalid <= arvalid(0);
  arready(0) <= m00_axi_arready;
  m00_axi_araddr  <= araddr(32 downto 0);
  -- AXI3: 4-bit ARLEN.  hbm_tg's register is 8-bit and protocol
  -- agnostic; anything above 15 would silently wrap, so it is
  -- truncated HERE, where the protocol is known.
  m00_axi_arlen   <= arlen(3 downto 0);
  m00_axi_arid    <= (others => '0');
  m00_axi_arsize  <= arsize(2 downto 0);
  m00_axi_arburst <= arburst(1 downto 0);
  m00_axi_rready  <= rready(0);
  rvalid(0) <= m00_axi_rvalid;
  rlast(0)  <= m00_axi_rlast;
  rresp(1 downto 0) <= m00_axi_rresp;
  -- write channel tied off: this design never writes, and leaving
  -- the ports floating would let the tool infer a write path.
  m00_axi_awvalid <= '0';
  m00_axi_awaddr  <= (others => '0');
  m00_axi_awlen   <= (others => '0');
  m00_axi_awid    <= (others => '0');
  m00_axi_awsize  <= (others => '0');
  m00_axi_awburst <= (others => '0');
  m00_axi_wvalid  <= '0';
  m00_axi_wdata   <= (others => '0');
  m00_axi_wstrb   <= (others => '0');
  m00_axi_wlast   <= '0';
  m00_axi_bready  <= '1';

  -- port 1
  m01_axi_arvalid <= arvalid(1);
  arready(1) <= m01_axi_arready;
  m01_axi_araddr  <= araddr(65 downto 33);
  -- AXI3: 4-bit ARLEN.  hbm_tg's register is 8-bit and protocol
  -- agnostic; anything above 15 would silently wrap, so it is
  -- truncated HERE, where the protocol is known.
  m01_axi_arlen   <= arlen(11 downto 8);
  m01_axi_arid    <= (others => '0');
  m01_axi_arsize  <= arsize(5 downto 3);
  m01_axi_arburst <= arburst(3 downto 2);
  m01_axi_rready  <= rready(1);
  rvalid(1) <= m01_axi_rvalid;
  rlast(1)  <= m01_axi_rlast;
  rresp(3 downto 2) <= m01_axi_rresp;
  -- write channel tied off: this design never writes, and leaving
  -- the ports floating would let the tool infer a write path.
  m01_axi_awvalid <= '0';
  m01_axi_awaddr  <= (others => '0');
  m01_axi_awlen   <= (others => '0');
  m01_axi_awid    <= (others => '0');
  m01_axi_awsize  <= (others => '0');
  m01_axi_awburst <= (others => '0');
  m01_axi_wvalid  <= '0';
  m01_axi_wdata   <= (others => '0');
  m01_axi_wstrb   <= (others => '0');
  m01_axi_wlast   <= '0';
  m01_axi_bready  <= '1';

  -- port 2
  m02_axi_arvalid <= arvalid(2);
  arready(2) <= m02_axi_arready;
  m02_axi_araddr  <= araddr(98 downto 66);
  -- AXI3: 4-bit ARLEN.  hbm_tg's register is 8-bit and protocol
  -- agnostic; anything above 15 would silently wrap, so it is
  -- truncated HERE, where the protocol is known.
  m02_axi_arlen   <= arlen(19 downto 16);
  m02_axi_arid    <= (others => '0');
  m02_axi_arsize  <= arsize(8 downto 6);
  m02_axi_arburst <= arburst(5 downto 4);
  m02_axi_rready  <= rready(2);
  rvalid(2) <= m02_axi_rvalid;
  rlast(2)  <= m02_axi_rlast;
  rresp(5 downto 4) <= m02_axi_rresp;
  -- write channel tied off: this design never writes, and leaving
  -- the ports floating would let the tool infer a write path.
  m02_axi_awvalid <= '0';
  m02_axi_awaddr  <= (others => '0');
  m02_axi_awlen   <= (others => '0');
  m02_axi_awid    <= (others => '0');
  m02_axi_awsize  <= (others => '0');
  m02_axi_awburst <= (others => '0');
  m02_axi_wvalid  <= '0';
  m02_axi_wdata   <= (others => '0');
  m02_axi_wstrb   <= (others => '0');
  m02_axi_wlast   <= '0';
  m02_axi_bready  <= '1';

  -- port 3
  m03_axi_arvalid <= arvalid(3);
  arready(3) <= m03_axi_arready;
  m03_axi_araddr  <= araddr(131 downto 99);
  -- AXI3: 4-bit ARLEN.  hbm_tg's register is 8-bit and protocol
  -- agnostic; anything above 15 would silently wrap, so it is
  -- truncated HERE, where the protocol is known.
  m03_axi_arlen   <= arlen(27 downto 24);
  m03_axi_arid    <= (others => '0');
  m03_axi_arsize  <= arsize(11 downto 9);
  m03_axi_arburst <= arburst(7 downto 6);
  m03_axi_rready  <= rready(3);
  rvalid(3) <= m03_axi_rvalid;
  rlast(3)  <= m03_axi_rlast;
  rresp(7 downto 6) <= m03_axi_rresp;
  -- write channel tied off: this design never writes, and leaving
  -- the ports floating would let the tool infer a write path.
  m03_axi_awvalid <= '0';
  m03_axi_awaddr  <= (others => '0');
  m03_axi_awlen   <= (others => '0');
  m03_axi_awid    <= (others => '0');
  m03_axi_awsize  <= (others => '0');
  m03_axi_awburst <= (others => '0');
  m03_axi_wvalid  <= '0';
  m03_axi_wdata   <= (others => '0');
  m03_axi_wstrb   <= (others => '0');
  m03_axi_wlast   <= '0';
  m03_axi_bready  <= '1';

  -- port 4
  m04_axi_arvalid <= arvalid(4);
  arready(4) <= m04_axi_arready;
  m04_axi_araddr  <= araddr(164 downto 132);
  -- AXI3: 4-bit ARLEN.  hbm_tg's register is 8-bit and protocol
  -- agnostic; anything above 15 would silently wrap, so it is
  -- truncated HERE, where the protocol is known.
  m04_axi_arlen   <= arlen(35 downto 32);
  m04_axi_arid    <= (others => '0');
  m04_axi_arsize  <= arsize(14 downto 12);
  m04_axi_arburst <= arburst(9 downto 8);
  m04_axi_rready  <= rready(4);
  rvalid(4) <= m04_axi_rvalid;
  rlast(4)  <= m04_axi_rlast;
  rresp(9 downto 8) <= m04_axi_rresp;
  -- write channel tied off: this design never writes, and leaving
  -- the ports floating would let the tool infer a write path.
  m04_axi_awvalid <= '0';
  m04_axi_awaddr  <= (others => '0');
  m04_axi_awlen   <= (others => '0');
  m04_axi_awid    <= (others => '0');
  m04_axi_awsize  <= (others => '0');
  m04_axi_awburst <= (others => '0');
  m04_axi_wvalid  <= '0';
  m04_axi_wdata   <= (others => '0');
  m04_axi_wstrb   <= (others => '0');
  m04_axi_wlast   <= '0';
  m04_axi_bready  <= '1';

  -- port 5
  m05_axi_arvalid <= arvalid(5);
  arready(5) <= m05_axi_arready;
  m05_axi_araddr  <= araddr(197 downto 165);
  -- AXI3: 4-bit ARLEN.  hbm_tg's register is 8-bit and protocol
  -- agnostic; anything above 15 would silently wrap, so it is
  -- truncated HERE, where the protocol is known.
  m05_axi_arlen   <= arlen(43 downto 40);
  m05_axi_arid    <= (others => '0');
  m05_axi_arsize  <= arsize(17 downto 15);
  m05_axi_arburst <= arburst(11 downto 10);
  m05_axi_rready  <= rready(5);
  rvalid(5) <= m05_axi_rvalid;
  rlast(5)  <= m05_axi_rlast;
  rresp(11 downto 10) <= m05_axi_rresp;
  -- write channel tied off: this design never writes, and leaving
  -- the ports floating would let the tool infer a write path.
  m05_axi_awvalid <= '0';
  m05_axi_awaddr  <= (others => '0');
  m05_axi_awlen   <= (others => '0');
  m05_axi_awid    <= (others => '0');
  m05_axi_awsize  <= (others => '0');
  m05_axi_awburst <= (others => '0');
  m05_axi_wvalid  <= '0';
  m05_axi_wdata   <= (others => '0');
  m05_axi_wstrb   <= (others => '0');
  m05_axi_wlast   <= '0';
  m05_axi_bready  <= '1';

  -- port 6
  m06_axi_arvalid <= arvalid(6);
  arready(6) <= m06_axi_arready;
  m06_axi_araddr  <= araddr(230 downto 198);
  -- AXI3: 4-bit ARLEN.  hbm_tg's register is 8-bit and protocol
  -- agnostic; anything above 15 would silently wrap, so it is
  -- truncated HERE, where the protocol is known.
  m06_axi_arlen   <= arlen(51 downto 48);
  m06_axi_arid    <= (others => '0');
  m06_axi_arsize  <= arsize(20 downto 18);
  m06_axi_arburst <= arburst(13 downto 12);
  m06_axi_rready  <= rready(6);
  rvalid(6) <= m06_axi_rvalid;
  rlast(6)  <= m06_axi_rlast;
  rresp(13 downto 12) <= m06_axi_rresp;
  -- write channel tied off: this design never writes, and leaving
  -- the ports floating would let the tool infer a write path.
  m06_axi_awvalid <= '0';
  m06_axi_awaddr  <= (others => '0');
  m06_axi_awlen   <= (others => '0');
  m06_axi_awid    <= (others => '0');
  m06_axi_awsize  <= (others => '0');
  m06_axi_awburst <= (others => '0');
  m06_axi_wvalid  <= '0';
  m06_axi_wdata   <= (others => '0');
  m06_axi_wstrb   <= (others => '0');
  m06_axi_wlast   <= '0';
  m06_axi_bready  <= '1';

  -- port 7
  m07_axi_arvalid <= arvalid(7);
  arready(7) <= m07_axi_arready;
  m07_axi_araddr  <= araddr(263 downto 231);
  -- AXI3: 4-bit ARLEN.  hbm_tg's register is 8-bit and protocol
  -- agnostic; anything above 15 would silently wrap, so it is
  -- truncated HERE, where the protocol is known.
  m07_axi_arlen   <= arlen(59 downto 56);
  m07_axi_arid    <= (others => '0');
  m07_axi_arsize  <= arsize(23 downto 21);
  m07_axi_arburst <= arburst(15 downto 14);
  m07_axi_rready  <= rready(7);
  rvalid(7) <= m07_axi_rvalid;
  rlast(7)  <= m07_axi_rlast;
  rresp(15 downto 14) <= m07_axi_rresp;
  -- write channel tied off: this design never writes, and leaving
  -- the ports floating would let the tool infer a write path.
  m07_axi_awvalid <= '0';
  m07_axi_awaddr  <= (others => '0');
  m07_axi_awlen   <= (others => '0');
  m07_axi_awid    <= (others => '0');
  m07_axi_awsize  <= (others => '0');
  m07_axi_awburst <= (others => '0');
  m07_axi_wvalid  <= '0';
  m07_axi_wdata   <= (others => '0');
  m07_axi_wstrb   <= (others => '0');
  m07_axi_wlast   <= '0';
  m07_axi_bready  <= '1';

  -- port 8
  m08_axi_arvalid <= arvalid(8);
  arready(8) <= m08_axi_arready;
  m08_axi_araddr  <= araddr(296 downto 264);
  -- AXI3: 4-bit ARLEN.  hbm_tg's register is 8-bit and protocol
  -- agnostic; anything above 15 would silently wrap, so it is
  -- truncated HERE, where the protocol is known.
  m08_axi_arlen   <= arlen(67 downto 64);
  m08_axi_arid    <= (others => '0');
  m08_axi_arsize  <= arsize(26 downto 24);
  m08_axi_arburst <= arburst(17 downto 16);
  m08_axi_rready  <= rready(8);
  rvalid(8) <= m08_axi_rvalid;
  rlast(8)  <= m08_axi_rlast;
  rresp(17 downto 16) <= m08_axi_rresp;
  -- write channel tied off: this design never writes, and leaving
  -- the ports floating would let the tool infer a write path.
  m08_axi_awvalid <= '0';
  m08_axi_awaddr  <= (others => '0');
  m08_axi_awlen   <= (others => '0');
  m08_axi_awid    <= (others => '0');
  m08_axi_awsize  <= (others => '0');
  m08_axi_awburst <= (others => '0');
  m08_axi_wvalid  <= '0';
  m08_axi_wdata   <= (others => '0');
  m08_axi_wstrb   <= (others => '0');
  m08_axi_wlast   <= '0';
  m08_axi_bready  <= '1';

  -- port 9
  m09_axi_arvalid <= arvalid(9);
  arready(9) <= m09_axi_arready;
  m09_axi_araddr  <= araddr(329 downto 297);
  -- AXI3: 4-bit ARLEN.  hbm_tg's register is 8-bit and protocol
  -- agnostic; anything above 15 would silently wrap, so it is
  -- truncated HERE, where the protocol is known.
  m09_axi_arlen   <= arlen(75 downto 72);
  m09_axi_arid    <= (others => '0');
  m09_axi_arsize  <= arsize(29 downto 27);
  m09_axi_arburst <= arburst(19 downto 18);
  m09_axi_rready  <= rready(9);
  rvalid(9) <= m09_axi_rvalid;
  rlast(9)  <= m09_axi_rlast;
  rresp(19 downto 18) <= m09_axi_rresp;
  -- write channel tied off: this design never writes, and leaving
  -- the ports floating would let the tool infer a write path.
  m09_axi_awvalid <= '0';
  m09_axi_awaddr  <= (others => '0');
  m09_axi_awlen   <= (others => '0');
  m09_axi_awid    <= (others => '0');
  m09_axi_awsize  <= (others => '0');
  m09_axi_awburst <= (others => '0');
  m09_axi_wvalid  <= '0';
  m09_axi_wdata   <= (others => '0');
  m09_axi_wstrb   <= (others => '0');
  m09_axi_wlast   <= '0';
  m09_axi_bready  <= '1';

  -- port 10
  m10_axi_arvalid <= arvalid(10);
  arready(10) <= m10_axi_arready;
  m10_axi_araddr  <= araddr(362 downto 330);
  -- AXI3: 4-bit ARLEN.  hbm_tg's register is 8-bit and protocol
  -- agnostic; anything above 15 would silently wrap, so it is
  -- truncated HERE, where the protocol is known.
  m10_axi_arlen   <= arlen(83 downto 80);
  m10_axi_arid    <= (others => '0');
  m10_axi_arsize  <= arsize(32 downto 30);
  m10_axi_arburst <= arburst(21 downto 20);
  m10_axi_rready  <= rready(10);
  rvalid(10) <= m10_axi_rvalid;
  rlast(10)  <= m10_axi_rlast;
  rresp(21 downto 20) <= m10_axi_rresp;
  -- write channel tied off: this design never writes, and leaving
  -- the ports floating would let the tool infer a write path.
  m10_axi_awvalid <= '0';
  m10_axi_awaddr  <= (others => '0');
  m10_axi_awlen   <= (others => '0');
  m10_axi_awid    <= (others => '0');
  m10_axi_awsize  <= (others => '0');
  m10_axi_awburst <= (others => '0');
  m10_axi_wvalid  <= '0';
  m10_axi_wdata   <= (others => '0');
  m10_axi_wstrb   <= (others => '0');
  m10_axi_wlast   <= '0';
  m10_axi_bready  <= '1';

  -- port 11
  m11_axi_arvalid <= arvalid(11);
  arready(11) <= m11_axi_arready;
  m11_axi_araddr  <= araddr(395 downto 363);
  -- AXI3: 4-bit ARLEN.  hbm_tg's register is 8-bit and protocol
  -- agnostic; anything above 15 would silently wrap, so it is
  -- truncated HERE, where the protocol is known.
  m11_axi_arlen   <= arlen(91 downto 88);
  m11_axi_arid    <= (others => '0');
  m11_axi_arsize  <= arsize(35 downto 33);
  m11_axi_arburst <= arburst(23 downto 22);
  m11_axi_rready  <= rready(11);
  rvalid(11) <= m11_axi_rvalid;
  rlast(11)  <= m11_axi_rlast;
  rresp(23 downto 22) <= m11_axi_rresp;
  -- write channel tied off: this design never writes, and leaving
  -- the ports floating would let the tool infer a write path.
  m11_axi_awvalid <= '0';
  m11_axi_awaddr  <= (others => '0');
  m11_axi_awlen   <= (others => '0');
  m11_axi_awid    <= (others => '0');
  m11_axi_awsize  <= (others => '0');
  m11_axi_awburst <= (others => '0');
  m11_axi_wvalid  <= '0';
  m11_axi_wdata   <= (others => '0');
  m11_axi_wstrb   <= (others => '0');
  m11_axi_wlast   <= '0';
  m11_axi_bready  <= '1';

  -- port 12
  m12_axi_arvalid <= arvalid(12);
  arready(12) <= m12_axi_arready;
  m12_axi_araddr  <= araddr(428 downto 396);
  -- AXI3: 4-bit ARLEN.  hbm_tg's register is 8-bit and protocol
  -- agnostic; anything above 15 would silently wrap, so it is
  -- truncated HERE, where the protocol is known.
  m12_axi_arlen   <= arlen(99 downto 96);
  m12_axi_arid    <= (others => '0');
  m12_axi_arsize  <= arsize(38 downto 36);
  m12_axi_arburst <= arburst(25 downto 24);
  m12_axi_rready  <= rready(12);
  rvalid(12) <= m12_axi_rvalid;
  rlast(12)  <= m12_axi_rlast;
  rresp(25 downto 24) <= m12_axi_rresp;
  -- write channel tied off: this design never writes, and leaving
  -- the ports floating would let the tool infer a write path.
  m12_axi_awvalid <= '0';
  m12_axi_awaddr  <= (others => '0');
  m12_axi_awlen   <= (others => '0');
  m12_axi_awid    <= (others => '0');
  m12_axi_awsize  <= (others => '0');
  m12_axi_awburst <= (others => '0');
  m12_axi_wvalid  <= '0';
  m12_axi_wdata   <= (others => '0');
  m12_axi_wstrb   <= (others => '0');
  m12_axi_wlast   <= '0';
  m12_axi_bready  <= '1';

  -- port 13
  m13_axi_arvalid <= arvalid(13);
  arready(13) <= m13_axi_arready;
  m13_axi_araddr  <= araddr(461 downto 429);
  -- AXI3: 4-bit ARLEN.  hbm_tg's register is 8-bit and protocol
  -- agnostic; anything above 15 would silently wrap, so it is
  -- truncated HERE, where the protocol is known.
  m13_axi_arlen   <= arlen(107 downto 104);
  m13_axi_arid    <= (others => '0');
  m13_axi_arsize  <= arsize(41 downto 39);
  m13_axi_arburst <= arburst(27 downto 26);
  m13_axi_rready  <= rready(13);
  rvalid(13) <= m13_axi_rvalid;
  rlast(13)  <= m13_axi_rlast;
  rresp(27 downto 26) <= m13_axi_rresp;
  -- write channel tied off: this design never writes, and leaving
  -- the ports floating would let the tool infer a write path.
  m13_axi_awvalid <= '0';
  m13_axi_awaddr  <= (others => '0');
  m13_axi_awlen   <= (others => '0');
  m13_axi_awid    <= (others => '0');
  m13_axi_awsize  <= (others => '0');
  m13_axi_awburst <= (others => '0');
  m13_axi_wvalid  <= '0';
  m13_axi_wdata   <= (others => '0');
  m13_axi_wstrb   <= (others => '0');
  m13_axi_wlast   <= '0';
  m13_axi_bready  <= '1';

  -- port 14
  m14_axi_arvalid <= arvalid(14);
  arready(14) <= m14_axi_arready;
  m14_axi_araddr  <= araddr(494 downto 462);
  -- AXI3: 4-bit ARLEN.  hbm_tg's register is 8-bit and protocol
  -- agnostic; anything above 15 would silently wrap, so it is
  -- truncated HERE, where the protocol is known.
  m14_axi_arlen   <= arlen(115 downto 112);
  m14_axi_arid    <= (others => '0');
  m14_axi_arsize  <= arsize(44 downto 42);
  m14_axi_arburst <= arburst(29 downto 28);
  m14_axi_rready  <= rready(14);
  rvalid(14) <= m14_axi_rvalid;
  rlast(14)  <= m14_axi_rlast;
  rresp(29 downto 28) <= m14_axi_rresp;
  -- write channel tied off: this design never writes, and leaving
  -- the ports floating would let the tool infer a write path.
  m14_axi_awvalid <= '0';
  m14_axi_awaddr  <= (others => '0');
  m14_axi_awlen   <= (others => '0');
  m14_axi_awid    <= (others => '0');
  m14_axi_awsize  <= (others => '0');
  m14_axi_awburst <= (others => '0');
  m14_axi_wvalid  <= '0';
  m14_axi_wdata   <= (others => '0');
  m14_axi_wstrb   <= (others => '0');
  m14_axi_wlast   <= '0';
  m14_axi_bready  <= '1';

end architecture;
