-- rtl/matvec_core.vhd -- subsystem A datapath core.
--
-- Implements the numeric contract of
--   docs/superpowers/specs/2026-08-20-int4-streaming-matvec-design.md  7.4
-- and is validated STAGE BY STAGE against ref/matvec_int4.c via
-- sim/matvec_trace.txt (see sim/tb_matvec_core.vhd).
--
-- The five arithmetic primitives come from work.mv4i_arith_pkg, which is
-- GENERATED by tools/gen_arith.py from the same description that emits the C
-- reference's mv4i_arith.h and the golden vectors both are checked against.
-- They are deliberately not hand-written here: every defect found in this
-- contract so far has been in exactly those functions.
--
-- Per spec 7.1 this is the CORE only: it consumes weight, scale and activation
-- read ports, not AXI.  weight_streamer sits above it and is device-specific
-- (DDR4 on the AXU3EG, HBM on the FK33); the core is not.
--
-- Synthesizable: no `real`, no TEXTIO.  Note the datapath rules of 7.8/8:
-- data never travels through a VHDL `integer` (only exponents, descriptor
-- fields and loop counters do), and the scale multiply occupies its own state
-- so it never shares a cycle with the product multiplies.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.mv4i_arith_pkg.all;

entity matvec_core is
  generic(
    BLK       : positive := 32;     -- weights per scale block, spec 6.1
    MAXCOLS     : positive := 17408;  -- spec 14.1, 27B FFN
    MAXROWS_BFP : positive := 17408
  );
  port(
    clk, rst  : in  std_logic;
    start     : in  std_logic;

    -- descriptor
    n_rows    : in  integer;
    n_cols    : in  integer;                        -- TRUE K, spec 6.3
    out_shift : in  integer;                        -- 0..40, spec 7.4
    w_exp     : in  integer;
    x_exp     : in  integer;
    out_mode  : in  std_logic_vector(1 downto 0);   -- 00 BFP, 01 raw, 10 partial

    -- codebook, 16 x int8, runtime-loadable (spec 6.1).  Illegal outside idle.
    cb_we     : in  std_logic;
    cb_addr   : in  std_logic_vector(3 downto 0);
    cb_data   : in  std_logic_vector(7 downto 0);

    -- weight read: one row-block chunk of BLK nibbles
    w_raddr   : out std_logic_vector(31 downto 0);
    w_rdata   : in  std_logic_vector(BLK*4-1 downto 0);
    -- scale read: uint15 in a 16-bit field, MSB must be 0
    s_raddr   : out std_logic_vector(31 downto 0);
    s_rdata   : in  std_logic_vector(15 downto 0);
    -- activation read: one BLK of int16, by BLK index
    x_rbaddr  : out std_logic_vector(15 downto 0);
    x_rdata   : in  std_logic_vector(BLK*16-1 downto 0);

    -- result
    y_we      : out std_logic;
    y_addr    : out std_logic_vector(15 downto 0);
    y_data    : out std_logic_vector(31 downto 0);  -- int16 mant in BFP mode
    y_exp     : out integer;
    done      : out std_logic;                      -- one-cycle pulse
    err       : out std_logic;
    sat_event : out std_logic;                      -- sticky, spec 14.2

    -- STAGE TAPS.  Present so the testbench can localize a divergence to one
    -- stage on the first failing vector rather than bisecting a wrong output.
    -- Pruned when TAPS is false.
    tap_valid   : out std_logic;
    tap_kind    : out std_logic_vector(2 downto 0); -- 1 part 2 contrib 3 acc 4 ydata 5 ymant
    tap_r       : out integer;
    tap_b       : out integer;
    tap_val     : out std_logic_vector(63 downto 0);
    tap_ns      : out integer
  );
end entity;

architecture rtl of matvec_core is
  type cb_t is array(0 to 15) of signed(7 downto 0);
  signal cb : cb_t := (others => (others => '0'));

  type ybuf_t is array(0 to MAXROWS_BFP-1) of signed(31 downto 0);
  signal ybuf : ybuf_t;

  type st_t is (S_IDLE, S_BLK_ISSUE, S_BLK_WAIT, S_PROD, S_SCALE, S_ACCUM,
                S_ROW_END, S_SCAN, S_EMIT, S_DONE);
  signal st : st_t := S_IDLE;

  signal r_i, b_i   : integer := 0;
  signal nb         : integer := 0;
  signal acc        : signed(47 downto 0) := (others => '0');
  signal partial    : signed(27 downto 0) := (others => '0');
  signal contrib    : signed(28 downto 0) := (others => '0');
  signal scale_r    : unsigned(15 downto 0) := (others => '0');
  signal amax       : unsigned(35 downto 0) := (others => '0');
  signal ns_r       : integer := 0;
  signal sat_r      : std_logic := '0';
  signal err_r      : std_logic := '0';
begin

  w_raddr  <= std_logic_vector(to_unsigned(r_i * nb + b_i, 32));
  s_raddr  <= std_logic_vector(to_unsigned(r_i * nb + b_i, 32));
  x_rbaddr <= std_logic_vector(to_unsigned(b_i, 16));

  process(clk)
    variable p    : signed(27 downto 0);
    variable prod : signed(24 downto 0);
    variable k    : integer;
    variable idx  : integer;
    variable xw   : signed(15 downto 0);
    variable sh   : signed(47 downto 0);
    variable a32  : signed(31 downto 0);
    variable mag  : unsigned(35 downto 0);
  begin
    if rising_edge(clk) then
      y_we      <= '0';
      done      <= '0';
      tap_valid <= '0';

      if rst = '1' then
        st <= S_IDLE; sat_r <= '0'; err_r <= '0';

      elsif cb_we = '1' and st = S_IDLE then
        cb(to_integer(unsigned(cb_addr))) <= signed(cb_data);

      else
        case st is

          when S_IDLE =>
            if start = '1' then
              -- spec 7.6 descriptor checks
              if n_rows <= 0 or n_cols <= 0 or n_cols > MAXCOLS
                 or out_shift < 0 or out_shift > 40
                 or (out_mode = "00" and n_rows > MAXROWS_BFP) then
                err_r <= '1'; st <= S_DONE;
              else
                nb    <= (n_cols + BLK - 1) / BLK;   -- ceil, spec 6.3
                r_i   <= 0; b_i <= 0;
                acc   <= (others => '0');
                amax  <= (others => '0');
                sat_r <= '0'; err_r <= '0';
                st    <= S_BLK_ISSUE;
              end if;
            end if;

          -- read addresses are registered a cycle ahead, exactly as matmul_rt
          -- does, so the memories can be synchronous.
          when S_BLK_ISSUE => st <= S_BLK_WAIT;
          when S_BLK_WAIT  => scale_r <= unsigned(s_rdata); st <= S_PROD;

          -- one state: BLK products and their reduction.  The scale multiply
          -- is NOT here -- see S_SCALE -- because 7.8 forbids two multiplies
          -- sharing a state, which is the hazard that broke residual/swiglu/
          -- bfp_pack on silicon.
          when S_PROD =>
            p := (others => '0');
            for j in 0 to BLK-1 loop
              k   := b_i * BLK + j;
              idx := to_integer(unsigned(w_rdata(j*4+3 downto j*4)));
              xw  := signed(x_rdata(j*16+15 downto j*16));
              if k < n_cols then                 -- COLUMN MASK, spec 6.2:
                prod := resize(cb(idx) * xw, 25);  -- codebook has NO zero entry
              else                               -- entry, so padding must be
                prod := (others => '0');         -- masked, not zero-filled
              end if;
              p := p + resize(prod, 28);
            end loop;
            partial <= p;
            tap_valid <= '1'; tap_kind <= "001"; tap_r <= r_i; tap_b <= b_i;
            tap_val   <= std_logic_vector(resize(p, 64));
            st <= S_SCALE;

          -- SITE 1: floor(partial * scale / 2^15).  Its own state.
          when S_SCALE =>
            contrib <= resize(floor_shr(partial * signed('0' & scale_r), 15), 29);
            st <= S_ACCUM;

          when S_ACCUM =>
            acc <= acc + resize(contrib, 48);
            tap_valid <= '1'; tap_kind <= "010"; tap_r <= r_i; tap_b <= b_i;
            tap_val   <= std_logic_vector(resize(contrib, 64));
            if b_i = nb - 1 then st <= S_ROW_END;
            else b_i <= b_i + 1; st <= S_BLK_ISSUE; end if;

          when S_ROW_END =>
            tap_valid <= '1'; tap_kind <= "011"; tap_r <= r_i; tap_b <= 0;
            tap_val   <= std_logic_vector(resize(acc, 64));
            -- SITES 2/3 then sat32
            sh  := round_shift(acc, out_shift);
            a32 := sat32(sh);
            if sh /= resize(a32, 48) then sat_r <= '1'; end if;
            ybuf(r_i) <= a32;
            mag := unsigned(abs(resize(a32, 36)));
            if mag > amax then amax <= mag; end if;   -- SCAN r < n_rows only
            if out_mode /= "00" then                  -- raw / partial emit now
              y_we   <= '1';
              y_addr <= std_logic_vector(to_unsigned(r_i, 16));
              y_data <= std_logic_vector(a32);
            end if;
            if r_i = n_rows - 1 then
              st <= S_SCAN;
            else
              r_i <= r_i + 1; b_i <= 0; acc <= (others => '0');
              st  <= S_BLK_ISSUE;
            end if;

          when S_SCAN =>
            if out_mode = "00" then
              -- ns = max(0, msb_pos(amax) - 14), msb_pos(0) = 0 NORMATIVE
              if msb_pos_u(amax) > 14 then ns_r <= msb_pos_u(amax) - 14;
              else ns_r <= 0; end if;
              r_i <= 0;
              st  <= S_EMIT;
            else
              st <= S_DONE;
            end if;

          when S_EMIT =>
            tap_ns <= ns_r;
            -- SITE 4: round_shift then sat16
            y_we   <= '1';
            y_addr <= std_logic_vector(to_unsigned(r_i, 16));
            y_data <= std_logic_vector(resize(sat16(round_shift(ybuf(r_i), ns_r)), 32));
            tap_valid <= '1'; tap_kind <= "101"; tap_r <= r_i; tap_b <= 0;
            tap_val   <= std_logic_vector(resize(sat16(round_shift(ybuf(r_i), ns_r)), 64));
            if r_i = n_rows - 1 then st <= S_DONE;
            else r_i <= r_i + 1; end if;

          when S_DONE =>
            done <= '1';
            st   <= S_IDLE;
        end case;
      end if;
    end if;
  end process;

  -- y_exp: BFP subtracts ns (spec 7.4); partial carries NO out_shift term
  -- (spec 14.2), because its payload was never shifted.
  y_exp <= (w_exp + x_exp)                        when out_mode = "10" else
           (w_exp + x_exp - out_shift - ns_r)     when out_mode = "00" else
           (w_exp + x_exp - out_shift);

  err       <= err_r;
  sat_event <= sat_r;
end architecture;
