-- ooc_cattnadapt_top.vhd -- GENERATED by sim/ooc_cattnadapt_extract.py.
-- DO NOT EDIT.  The body below is `rtl/llama_top.vhd`'s `gcr` generate block,
-- subsystem C's data mover, copied verbatim from rtl/llama_top.vhd.
--
-- Regenerate with:
--   python3 sim/ooc_cattnadapt_extract.py rtl/llama_top.vhd /tmp/claude-1000/-home-orencollaco-GitHub-llama-vhdl/4d84bf97-4b0d-407d-ac40-96158eb597e1/scratchpad/cmover/ooc_cattnadapt_top.vhd
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

use work.util_pkg.all;
use work.model_cfg_pkg.all;
use work.llama_map_pkg.all;

entity ooc_cattnadapt_top is
  generic(
    SHAPE       : shape_t  := mk_shape(QWEN35_9B, 1);
    MANT_W      : positive := 16;
    EXP_W       : positive := 16;
    EPOCH_W     : positive := 4;
    ADDR_W      : positive := 16;
    NORM_LANES  : positive := 4;
    STRICT      : boolean  := true;
    SHOUT       : boolean  := false;
    C_REAL      : boolean  := true;
    C_MAXPOS    : positive := 4;
    C_CTXLEN    : positive := 4;
    C_KV_BLOCK  : positive := 4;
    C_N_ROT     : positive := 8;
    C_QKN_EXP   : natural  := 12;
    C_CM_W      : positive := 8;
    C_KV_AXI    : boolean  := false;
    C_KV_AXI_DW : positive := 256;
    C_KV_ADDR_W : positive := 33;
    C_KV_MAXB   : positive := 16;
    C_KV_MAXOUT : positive := 4;
    C_KV_RBUF   : positive := 64;
    C_K_BASE_CH : natural  := 0;
    C_V_BASE_CH : natural  := 0;
    NVOP        : positive := 3
  );
  port(
    clk : in std_logic;
    rst : in std_logic;

    -- D's job fields, and the unit handshake back to it (slot U_C only)
    job_issue    : in  std_logic;
    job_unit     : in  unsigned(2 downto 0);
    job_dst      : in  unsigned(7 downto 0);
    job_n_rows   : in  unsigned(31 downto 0);
    job_epoch    : in  unsigned(EPOCH_W-1 downto 0);
    job_ordinal  : in  unsigned(7 downto 0);
    u_ack_c      : in  std_logic;
    u_ready_c    : out std_logic;
    u_done_c     : out std_logic;
    u_err_c      : out std_logic;
    u_epoch_c    : out std_logic_vector(EPOCH_W-1 downto 0);
    u_yexp_c     : out std_logic_vector(EXP_W-1 downto 0);

    -- the region-file element port, FLATTENED (see the header)
    ur_en_c      : out std_logic;
    ur_reg_c     : out std_logic_vector(7 downto 0);
    ur_addr_c    : out std_logic_vector(ADDR_W-1 downto 0);
    uw_en_c      : out std_logic;
    uw_reg_c     : out std_logic_vector(7 downto 0);
    uw_addr_c    : out std_logic_vector(ADDR_W-1 downto 0);
    uw_data_c    : out std_logic_vector(MANT_W-1 downto 0);
    el_rdata     : in  signed(MANT_W-1 downto 0);

    -- the exponent side-channel D presents
    exp_rd_valid : in  std_logic;
    exp_rd_data  : in  signed(EXP_W-1 downto 0);
    c_exp_region : out std_logic_vector(7 downto 0);
    c_exp_seg    : out std_logic_vector(1 downto 0);

    tok_pos      : in  natural range 0 to C_MAXPOS-1;
    kv_seam_bad  : out std_logic;
    f_lost_c     : out std_logic;

    -- THE KV AXI FACE, copied verbatim from `llama_top`'s own port clause
    -- with the same names, directions, widths and defaults.
    --
    -- THE MECHANICAL SEAM PASS MISSED ALL 26 OF THESE, and GHDL is what
    -- found them.  They are llama_top ENTITY PORTS, not architecture signals,
    -- so a classifier looking for `signal`/`constant` declarations cannot see
    -- them at all -- a sixth way for the derivation to be wrong, on top of
    -- the five sim/ooc_gdnadapt_extract.py records.  `kv_rdata` additionally
    -- spans two lines in llama_top (:751-752), which is the same two-line
    -- declaration trap that hid `u_start` from B's pass.
    kv_arvalid : out std_logic_vector(1 downto 0);
    kv_arready : in  std_logic_vector(1 downto 0) := (others => '0');
    kv_araddr  : out std_logic_vector(2*C_KV_ADDR_W-1 downto 0);
    kv_arlen   : out std_logic_vector(15 downto 0);
    kv_arsize  : out std_logic_vector(5 downto 0);
    kv_arburst : out std_logic_vector(3 downto 0);
    kv_rvalid  : in  std_logic_vector(1 downto 0) := (others => '0');
    kv_rready  : out std_logic_vector(1 downto 0);
    kv_rdata   : in  std_logic_vector(2*C_KV_AXI_DW-1 downto 0)
               := (others => '0');
    kv_rlast   : in  std_logic_vector(1 downto 0) := (others => '0');
    kv_rresp   : in  std_logic_vector(3 downto 0) := (others => '0');
    kv_awvalid : out std_logic;
    kv_awready : in  std_logic := '0';
    kv_awaddr  : out std_logic_vector(C_KV_ADDR_W-1 downto 0);
    kv_awlen   : out std_logic_vector(7 downto 0);
    kv_awsize  : out std_logic_vector(2 downto 0);
    kv_awburst : out std_logic_vector(1 downto 0);
    kv_wvalid  : out std_logic;
    kv_wready  : in  std_logic := '0';
    kv_wdata   : out std_logic_vector(C_KV_AXI_DW-1 downto 0);
    kv_wstrb   : out std_logic_vector(C_KV_AXI_DW/8-1 downto 0);
    kv_wlast   : out std_logic;
    kv_bvalid  : in  std_logic := '0';
    kv_bready  : out std_logic;
    kv_bresp   : in  std_logic_vector(1 downto 0) := (others => '0');
    kv_err     : out std_logic
  );
end entity;

architecture rtl of ooc_cattnadapt_top is
  -- `llama_top`'s architecture-local types and signals, reproduced with the
  -- same names and types so the block text below needs no edit.
  constant NPORT : natural := NUNIT + NVOP;
  -- `buf_t` is llama_top's, and the block declares process variables of it.
  type buf_t  is array (natural range <>) of signed(MANT_W-1 downto 0);
  type nat_u  is array (0 to NPORT-1) of natural;
  type sig_u  is array (0 to NPORT-1) of signed(MANT_W-1 downto 0);

  signal ur_en   : std_logic_vector(NPORT-1 downto 0) := (others => '0');
  signal ur_reg  : nat_u := (others => 0);
  signal ur_addr : nat_u := (others => 0);
  signal uw_en   : std_logic_vector(NPORT-1 downto 0) := (others => '0');
  signal uw_reg  : nat_u := (others => 0);
  signal uw_addr : nat_u := (others => 0);
  signal uw_data : sig_u := (others => (others => '0'));

  signal u_ready      : std_logic_vector(NUNIT-1 downto 0) := (others => '0');
  signal u_done       : std_logic_vector(NUNIT-1 downto 0) := (others => '0');
  signal u_err        : std_logic_vector(NUNIT-1 downto 0) := (others => '0');
  signal u_ack        : std_logic_vector(NUNIT-1 downto 0) := (others => '0');
  signal u_done_epoch : std_logic_vector(NUNIT*EPOCH_W-1 downto 0)
                      := (others => '0');
  signal u_y_exp      : std_logic_vector(NUNIT*EXP_W-1 downto 0)
                      := (others => '0');

  signal c_exp_region_i : unsigned(7 downto 0) := (others => '0');
  signal c_exp_seg_i    : unsigned(1 downto 0) := "00";
  signal f_lost_c_i     : std_logic := '0';
  signal kv_seam_bad_i  : std_logic := '0';

  -- `kv_err_i` IS AN OUTPUT OF THE BLOCK, and the mechanical pass called it an
  -- input.  It is DRIVEN THROUGH A PORT MAP -- `err => kv_err_i` on the
  -- attn_kv_axi instance -- and never by a `<=` assignment, so an
  -- assignment-based classifier cannot see it drive.  That is a SEVENTH
  -- failure mode beyond the five sim/ooc_gdnadapt_extract.py records and the
  -- entity-port one above; GHDL caught it as "cannot associate out port 'err'
  -- with actual port of mode in".
  --
  -- llama_top:5795 combines it exactly this way, and that line is reproduced
  -- below rather than invented.
  signal kv_err_i       : std_logic := '0';
begin
  -- the conversion, OUTSIDE the verbatim block
  u_ack(U_C)   <= u_ack_c;
  u_ready_c    <= u_ready(U_C);
  u_done_c     <= u_done(U_C);
  u_err_c      <= u_err(U_C);
  u_epoch_c    <= u_done_epoch((U_C+1)*EPOCH_W-1 downto U_C*EPOCH_W);
  u_yexp_c     <= u_y_exp((U_C+1)*EXP_W-1 downto U_C*EXP_W);

  ur_en_c      <= ur_en(U_C);
  ur_reg_c     <= std_logic_vector(to_unsigned(ur_reg(U_C), 8));
  ur_addr_c    <= std_logic_vector(to_unsigned(ur_addr(U_C), ADDR_W));
  uw_en_c      <= uw_en(U_C);
  uw_reg_c     <= std_logic_vector(to_unsigned(uw_reg(U_C), 8));
  uw_addr_c    <= std_logic_vector(to_unsigned(uw_addr(U_C), ADDR_W));
  uw_data_c    <= std_logic_vector(uw_data(U_C));

  c_exp_region <= std_logic_vector(c_exp_region_i);
  c_exp_seg    <= std_logic_vector(c_exp_seg_i);
  f_lost_c     <= f_lost_c_i;
  kv_seam_bad  <= kv_seam_bad_i;
  -- llama_top:5795, verbatim
  kv_err       <= kv_err_i or kv_seam_bad_i;

  gcr : if C_REAL generate
    function nlay(s : shape_t) return positive is
      variable n : natural := n_attn_blocks(s);
    begin
      if n = 0 then return 1; else return n; end if;
    end function;

    constant C_HD   : positive := SHAPE.attn_head_dim;
    constant C_NQH  : positive := SHAPE.attn_q_heads;
    constant C_NKVH : positive := SHAPE.attn_kv_heads;
    constant C_NBLK : positive := C_HD / C_KV_BLOCK;
    constant C_LAY  : positive := nlay(SHAPE);
    constant QGN    : positive := att_qg(SHAPE);   -- 2*HEAD_DIM*N_QH
    constant KVN    : positive := att_kv(SHAPE);   -- HEAD_DIM*N_KVH
    constant YN     : positive := att_q(SHAPE);    -- HEAD_DIM*N_QH
    -- POSITION WIDTH.  `clog2(C_MAXPOS + 1)` and NOT `clog2(C_MAXPOS)`.
    -- POS_W has to carry two different quantities: a POSITION, which runs
    -- 0 .. C_MAXPOS-1, and `ctx_len`, which is a COUNT and runs 1 .. C_MAXPOS.
    -- `attn_kv_axi` range-checks the count with `to_integer(ctx_len) > MAXCTX`
    -- (rtl/attn_kv_axi.vhd:542), so the count must be representable.  At a
    -- power-of-two cache depth the old width could not hold it: MAXPOS 256
    -- gave POSW 8, `to_unsigned(256, 8)` is 0, and the guard below -- which
    -- demanded BOTH `C_CTXLEN <= C_MAXPOS` and `C_CTXLEN < 2**POSW` -- became
    -- self-contradictory at exactly `C_CTXLEN = C_MAXPOS`.  MEASURED: 256
    -- failed and 255 passed, i.e. the last cache position could never be
    -- used and the assert blamed the caller for it.  One extra bit fixes the
    -- count and costs nothing the position cares about.
    constant POSW   : positive := clog2(C_MAXPOS + 1);

    -- THE QK-NORM GAINS.  Deterministic in the element index and centred on
    -- 1.0 at C_QKN_EXP, which is what an RMSNorm gain is initialised to.
    -- Distinct per port so a q/k swap in the wiring is a wrong number.
    function qkn_const(seed : integer) return std_logic_vector is
      variable r : std_logic_vector(C_HD*MANT_W-1 downto 0);
      variable v : integer;
    begin
      for i in 0 to C_HD-1 loop
        v := 2**C_QKN_EXP + ((i * seed) mod 512) - 256;
        r((i+1)*MANT_W-1 downto i*MANT_W)
          := std_logic_vector(to_signed(v, MANT_W));
      end loop;
      return r;
    end function;
    constant QN_CONST : std_logic_vector(C_HD*MANT_W-1 downto 0) := qkn_const(37);
    constant KN_CONST : std_logic_vector(C_HD*MANT_W-1 downto 0) := qkn_const(53);

    signal rdy  : std_logic := '1';
    signal dn   : std_logic := '0';
    signal uerr : std_logic := '0';
    signal ep   : unsigned(EPOCH_W-1 downto 0) := (others => '0');
    signal yexp : signed(EXP_W-1 downto 0) := (others => '0');

    -- control
    signal c_start  : std_logic := '0';
    signal c_layer  : integer range 0 to C_LAY-1 := 0;
    signal c_cpos   : unsigned(POSW-1 downto 0) := (others => '0');
    signal c_ctx    : unsigned(POSW-1 downto 0) := to_unsigned(C_CTXLEN, POSW);
    signal c_busy, c_cfgtk, c_wntk : std_logic;
    signal c_seqrst : std_logic := '1';
    signal c_srtk   : std_logic;
    signal c_done   : std_logic;
    signal c_dack   : std_logic := '0';
    signal c_err, c_ropes, c_kvs, c_ys, c_zs, c_eplost : std_logic;
    signal c_rsmax  : unsigned(15 downto 0);

    -- the prefetched activation planes
    signal qg_buf  : buf_t(0 to QGN-1) := (others => (others => '0'));
    signal kin_buf : buf_t(0 to KVN-1) := (others => (others => '0'));
    signal vin_buf : buf_t(0 to KVN-1) := (others => (others => '0'));
    signal qg_e, kin_e, vin_e : signed(EXP_W-1 downto 0) := (others => '0');

    -- the block's memory ports
    signal qg_raddr  : unsigned(clog2(QGN)-1 downto 0);
    signal qg_re     : std_logic;
    signal qg_rdata  : signed(MANT_W-1 downto 0) := (others => '0');
    signal kin_raddr : unsigned(clog2(KVN)-1 downto 0);
    signal kin_re    : std_logic;
    signal kin_rdata : signed(MANT_W-1 downto 0) := (others => '0');
    signal vin_raddr : unsigned(clog2(KVN)-1 downto 0);
    signal vin_re    : std_logic;
    signal vin_rdata : signed(MANT_W-1 downto 0) := (others => '0');

    -- the KV cache
    signal kv_layer : unsigned(clog2(C_LAY)-1 downto 0);
    signal kw_sel   : std_logic;
    signal kw_head  : unsigned(clog2(C_NKVH)-1 downto 0);
    signal kw_pos   : unsigned(POSW-1 downto 0);
    signal kw_hen   : std_logic;
    signal kw_hdr   : std_logic_vector(C_NBLK*8-1 downto 0);
    signal kw_en    : std_logic;
    signal kw_blk   : unsigned(clog2(C_NBLK)-1 downto 0);
    signal kw_mant  : std_logic_vector(C_KV_BLOCK*C_CM_W-1 downto 0);
    signal kr_en, vr_en : std_logic;
    signal kr_head, vr_head : unsigned(clog2(C_NKVH)-1 downto 0);
    signal kr_pos, vr_pos   : unsigned(POSW-1 downto 0);
    signal kr_blk, vr_blk   : unsigned(clog2(C_NBLK)-1 downto 0);
    signal kr_hdr, vr_hdr   : std_logic_vector(C_NBLK*8-1 downto 0)
                            := (others => '0');
    signal kr_mant, vr_mant : std_logic_vector(C_KV_BLOCK*C_CM_W-1 downto 0)
                            := (others => '0');

    -- THE FOUR HANDSHAKES `attn_block` GAINED AT THE SEAM.  Every one of them
    -- defaults to '1' on the block's port, which is a memory that can never
    -- refuse -- correct for the behavioural cache below, and a SILENT WRONG
    -- ANSWER for any cache with latency.  They are signals here rather than
    -- open, so both cache branches have to say what they are.
    signal kw_rdy_s  : std_logic;
    signal kr_rdy_s  : std_logic;
    signal vr_rdy_s  : std_logic;
    signal wr_idle_s : std_logic;
    signal kv_busy_s, kv_cfgt_s : std_logic;

    -- NO EXPRESSIONS IN THE PORT MAP, same rule as qg_e8 below.
    --
    -- THE DOMAIN CHANGES BACK TO BYTES HERE, AND ONLY HERE.  `attn_kv_axi`'s
    -- `k_base`/`v_base` are BYTE addresses: rtl/attn_kv_axi.vhd:403-408
    -- computes `rec_addr = unsigned(base) + idx*REC_B` with REC_B in bytes.
    -- So the generics are chunks, these two constants are the shift back to
    -- bytes, and everything downstream of the port map is bytes as before.
    -- That is why `attn_kv_axi` needed no change for this: the seam is one
    -- shift wide and it is written out here rather than implied.
    constant KBASE_C : std_logic_vector(C_KV_ADDR_W-1 downto 0)
                     := std_logic_vector(shift_left(
                          to_unsigned(C_K_BASE_CH, C_KV_ADDR_W), 4));
    constant VBASE_C : std_logic_vector(C_KV_ADDR_W-1 downto 0)
                     := std_logic_vector(shift_left(
                          to_unsigned(C_V_BASE_CH, C_KV_ADDR_W), 4));
    constant REC_B_C : natural := 16 + C_HD*C_CM_W/8;

    -- The behavioural cache's storage.  The TYPES stay here because the
    -- `gkvmem` generate is the only user and a type is free; the two ARRAYS
    -- moved INTO that generate.  They used to be declared at this level, so
    -- they were elaborated even with C_KV_AXI true, i.e. with the real AXI
    -- cache in their place and nothing reading them.  MEASURED at the real
    -- attention geometry, C_KV_AXI on throughout: 29.8 MB of GHDL signal
    -- storage per cache position, 8.9 GB at C_MAXPOS 256, all of it dead.
    type hdr_arr is array (natural range <>) of
         std_logic_vector(C_NBLK*8-1 downto 0);
    type man_arr is array (natural range <>) of
         std_logic_vector(C_KV_BLOCK*C_CM_W-1 downto 0);

    -- the y stream
    signal y_valid, y_last, y_hdrv : std_logic;
    signal y_mant : signed(MANT_W-1 downto 0);
    signal y_index : unsigned(clog2(C_NQH*C_HD)-1 downto 0);
    signal c_yexp : signed(7 downto 0);

    -- NO EXPRESSIONS IN THE PORT MAP.  GHDL 1.0 mcode raised
    -- `TYPES.INTERNAL_ERROR : trans.adb:553` on `resize(qg_e, 8)` written as
    -- an actual, which is an internal error and not a diagnostic, so it reads
    -- as a broken design.  Every actual below is a plain signal or constant.
    signal qg_e8, kin_e8, vin_e8 : signed(7 downto 0) := (others => '0');
    constant QKN_E8 : signed(7 downto 0) := to_signed(C_QKN_EXP, 8);
    constant Y_RDY  : std_logic := '1';
  begin
    u_ready(U_C) <= rdy;
    u_done(U_C)  <= dn;
    u_err(U_C)   <= uerr;
    u_done_epoch((U_C+1)*EPOCH_W-1 downto U_C*EPOCH_W) <= std_logic_vector(ep);
    u_y_exp((U_C+1)*EXP_W-1 downto U_C*EXP_W) <= std_logic_vector(yexp);

    -- ---- elaboration-time shape checks.  attn_block asserts these itself;
    -- they are repeated here so the message names the caller that has to
    -- change rather than the unit that refused.
    assert 2**clog2(C_HD) = C_HD and clog2(C_HD) mod 2 = 0
      report "llama_top: C_REAL needs an EVEN power-of-two attn_head_dim, "
           & "because attn_block folds kq_scale = 1/sqrt(HEAD_DIM) into an "
           & "exponent.  mk_shape_scaled's default is 32 = 2**5; build the "
           & "shape with attn_head_dim => 16."
      severity failure;
    assert C_HD mod C_KV_BLOCK = 0 and C_NBLK >= 2
      report "llama_top: C_KV_BLOCK must divide attn_head_dim and leave at "
           & "least two blocks." severity failure;
    assert C_NQH mod C_NKVH = 0 and C_NQH / C_NKVH >= 2
      report "llama_top: attn_q_heads / attn_kv_heads is the GQA group and "
           & "attn_mac_array needs it to be at least 2." severity failure;
    -- NOTHING ELSE ASSERTS THIS.  `attn_emit.vhd:400` writes `grp <= 1` at
    -- S_IDLE with `grp` ranged `0 to NGRP-1`, so ONE KV head is a run-time
    -- bound check failure deep inside the first attention block rather than
    -- an elaboration refusal.  Caught here, where the caller can act on it.
    assert C_NKVH >= 2
      report "llama_top: attn_kv_heads must be at least 2.  attn_emit is "
           & "elaborated at NGRP = attn_kv_heads and assigns grp <= 1 with "
           & "grp ranged 0 to NGRP-1, so one KV head aborts mid-job with a "
           & "bound check failure at attn_emit.vhd:400." severity failure;
    assert C_N_ROT mod 2 = 0 and C_N_ROT <= C_HD
      report "llama_top: C_N_ROT must be even and at most attn_head_dim."
      severity failure;

    cbanner : process is
    begin
      if SHOUT then
        if C_KV_AXI then
          report "llama_top: unit C is the REAL attn_block against the REAL "
               & "attn_kv_axi, over three AXI masters.  The cache read path "
               & "runs from the second token of a sequence onward.  NOTHING "
               & "here establishes that what the block computes is "
               & "attention: that claim belongs to ref/attn_block_seq_vec.c "
               & "and sim/tb_attn_kv_seam.vhd, at the BLOCK level."
            severity note;
        else
          report "llama_top: unit C is the REAL attn_block.  It sequences "
               & "ten real units; NOTHING establishes that it computes "
               & "attention, because C has no block-level reference.  "
               & "attn_kv_axi is NOT instantiated (C_KV_AXI is false) -- the "
               & "KV cache is a behavioural memory port that can never "
               & "refuse, and attn_block's four handshake inputs are "
               & "therefore held high.  That is correct for THIS memory and "
               & "silently wrong for any cache with latency."
            severity note;
        end if;
      end if;
      wait;
    end process;

    -- ---- the per-SEQUENCE v_ref reset.  A LEVEL held until taken. -------
    srp : process(clk) is
    begin
      if rising_edge(clk) then
        if rst = '1' then      c_seqrst <= '1';
        elsif c_srtk = '1' then c_seqrst <= '0'; end if;
      end if;
    end process;

    -- ---- A's activation memory, served from the prefetched planes.
    -- The HOLD is the contract, not an optimisation: updating
    -- unconditionally lets a unit read at the wrong instant and pass.
    amem : process(clk) is
    begin
      if rising_edge(clk) then
        if qg_re  = '1' then qg_rdata  <= qg_buf(to_integer(qg_raddr));   end if;
        if kin_re = '1' then kin_rdata <= kin_buf(to_integer(kin_raddr)); end if;
        if vin_re = '1' then vin_rdata <= vin_buf(to_integer(vin_raddr)); end if;
      end if;
    end process;

    -- ======================================================================
    -- THE KV CACHE, TWO WAYS.
    --
    -- `gkvmem` is the one-cycle behavioural memory this file has always had:
    -- exactly the shape `sim/tb_attn_block.vhd` models, and the shape
    -- `attn_block` was written against.  It can never refuse, so all four
    -- handshakes are tied high, and THAT IS ONLY CORRECT FOR THIS MEMORY.
    --
    -- `gkvaxi` is `rtl/attn_kv_axi.vhd`, the real cache in HBM.  It refuses,
    -- it has O(100) cycles of read latency, and it does not make a write
    -- visible until BRESP.  The four handshakes are what make that legal.
    -- ======================================================================
    gkvmem : if not C_KV_AXI generate
      -- DECLARED HERE AND NOT ONE LEVEL UP.  These are the behavioural
      -- cache's storage and nothing outside this generate touches them; at
      -- the outer level they cost 29.8 MB of elaboration per cache position
      -- even when `gkvaxi` had replaced them.
      signal kvhdr : hdr_arr(0 to C_LAY*2*C_NKVH*C_MAXPOS-1)
                   := (others => (others => '0'));
      signal kvmem : man_arr(0 to C_LAY*2*C_NKVH*C_MAXPOS*C_NBLK-1)
                   := (others => (others => '0'));
    begin
      kw_rdy_s  <= '1';
      kr_rdy_s  <= '1';
      vr_rdy_s  <= '1';
      wr_idle_s <= '1';
      kv_busy_s <= '0';
      kv_cfgt_s <= '0';
    kvp : process(clk) is
      variable a : integer;
    begin
      if rising_edge(clk) then
        if kw_hen = '1' or kw_en = '1' then
          assert to_integer(kw_pos) < C_MAXPOS
            report "llama_top: the KV cache model is " & integer'image(C_MAXPOS)
                 & " positions deep and position " & integer'image(to_integer(kw_pos))
                 & " was written." severity failure;
        end if;
        if kw_hen = '1' then
          a := ((to_integer(kv_layer)*2
                 + to_integer(unsigned'("" & kw_sel)))*C_NKVH
                + to_integer(kw_head))*C_MAXPOS + to_integer(kw_pos);
          kvhdr(a) <= kw_hdr;
        end if;
        if kw_en = '1' then
          a := (((to_integer(kv_layer)*2
                  + to_integer(unsigned'("" & kw_sel)))*C_NKVH
                 + to_integer(kw_head))*C_MAXPOS + to_integer(kw_pos))*C_NBLK
               + to_integer(kw_blk);
          kvmem(a) <= kw_mant;
        end if;
        if kr_en = '1' then
          a := ((to_integer(kv_layer)*2 + 0)*C_NKVH + to_integer(kr_head))
               *C_MAXPOS + to_integer(kr_pos);
          kr_hdr  <= kvhdr(a);
          kr_mant <= kvmem(a*C_NBLK + to_integer(kr_blk));
        end if;
        if vr_en = '1' then
          a := ((to_integer(kv_layer)*2 + 1)*C_NKVH + to_integer(vr_head))
               *C_MAXPOS + to_integer(vr_pos);
          vr_hdr  <= kvhdr(a);
          vr_mant <= kvmem(a*C_NBLK + to_integer(vr_blk));
        end if;
      end if;
    end process;
    end generate;

    -- ---- the real cache ---------------------------------------------------
    gkvaxi : if C_KV_AXI generate
      -- ---- CHECKS THAT RUN DURING DECLARATION ELABORATION ----------------
      -- Everything below the `begin` is a concurrent assert, and a concurrent
      -- assert runs only after the WHOLE design has elaborated.  That is too
      -- late for two of these: at HEAD_DIM 256 with a too-small C_KV_BLOCK,
      -- `attn_kv_axi`'s P_WR overflows while its statement part is being
      -- elaborated and GHDL prints `overflow detected` with no file and no
      -- line, so the named asserts never get to speak.  A `natural` constant
      -- that goes negative is evaluated HERE, before `u_kv` is elaborated at
      -- all, and it also survives Vivado, which ignores a failing
      -- severity-failure assert in synthesis.  The asserts are kept: where
      -- they are reachable their message is better than a range error.
      --
      -- The legal case is >= 0 in every one; the name is the diagnostic.

      -- The block exponents must fit the 16-byte header chunk of the record.
      -- This is `attn_kv_axi`'s own :455 assert, mirrored here so the CALLER
      -- is named.  C_NBLK = attn_head_dim / C_KV_BLOCK, and EXP_W is 8.
      constant CHK_KV_NBLK : natural := 16 - C_NBLK*8/8;
      -- One KV block must be a whole number of 16-byte record granules.
      constant CHK_KV_GRAN : natural := 0 - ((C_KV_BLOCK*C_CM_W/8) mod 16);
      -- `ctx_len` is a COUNT, 1 .. C_MAXPOS.  POSW is now wide enough to
      -- hold C_MAXPOS itself (see its declaration), so this is the whole
      -- constraint and the old second clause is gone rather than restated.
      constant CHK_KV_CTX  : natural := C_MAXPOS - C_CTXLEN;
      -- THE K AND V REGIONS MUST FIT THE ADDRESS SPACE, not merely miss each
      -- other.  Nothing checked this before: MEASURED, two 34,816-byte
      -- regions based at 0 and 34,816 in a 16-bit space need 69,632 bytes,
      -- elaborated clean, and the top 4,096 bytes of V wrapped onto the
      -- first records of K.  Written with clog2 rather than 2**C_KV_ADDR_W
      -- so a 32-bit address width does not overflow the check itself.
      --
      -- IN CHUNKS, NOT BYTES, AND THAT IS WHAT MAKES THE CHECK EVALUATE AT
      -- THE REAL MAP.  `clog2` in rtl/util_pkg.vhd is a `while v < n loop
      -- v := v*2` doubling loop over `natural`, so it OVERFLOWS for any
      -- argument above 2**30.  In the byte domain the real pair ends at
      -- 6,803,283,968, which both overflows `natural` in the sum itself and
      -- is far past that loop's ceiling; MEASURED, `overflow detected ...
      -- from work.llama_top(rtl).DECL_ELAB` and the elaboration dies.  In
      -- chunks the same quantity is 425,205,248, under 2**30, and clog2
      -- returns 29.
      --
      -- The two forms are EXACTLY equivalent, not merely similar: every term
      -- is a whole number of 16-byte chunks, and clog2(16*y) = clog2(y) + 4
      -- for y >= 1, so `clog2(bytes) <= C_KV_ADDR_W` and
      -- `clog2(chunks) <= C_KV_ADDR_W - 4` accept and refuse the same
      -- layouts.  Nothing was loosened to make the real map fit.
      --
      -- REC_B must itself be a whole number of chunks or the conversion is
      -- lossy.  `attn_kv_axi.vhd:483` asserts `MANT_B mod CH_B = 0`; it is
      -- mirrored here as a natural constant because a concurrent assert runs
      -- after the whole design has elaborated, which is too late.
      --
      -- IT IS UNREACHABLE TODAY AND IT IS KEPT ANYWAY, WHICH IS A CLAIM
      -- ABOUT THE FUTURE AND NOT EVIDENCE ABOUT NOW.  `C_HD` is
      -- `SHAPE.attn_head_dim` and SHAPE is a RECORD generic that GHDL cannot
      -- override, so C_HD is 256 in every configuration this file can be
      -- elaborated at; `C_HD*C_CM_W/8` is then `32*C_CM_W`, always a multiple
      -- of 16, and no value of any overridable generic makes this constant
      -- negative.  It has therefore never been shown to refuse anything.  It
      -- would bite at a head dim below 32, which is the shape a future
      -- retarget could bring, and it costs one elaboration-time subtraction.
      constant CHK_KV_REC  : natural := 0 - ((C_HD*C_CM_W/8) mod 16);
      constant REC_CH_C    : natural := REC_B_C / 16;
      constant KVREG_CH    : natural := C_LAY*C_NKVH*C_MAXPOS*REC_CH_C;
      constant CHK_KV_FIT  : natural :=
        (C_KV_ADDR_W - 4)
        - clog2(maximum(C_K_BASE_CH, C_V_BASE_CH) + KVREG_CH);
    begin
      -- ELABORATION CHECKS.  The three-way geometry constraint is stated in
      -- the C_KV_AXI generic's header; these name the caller rather than
      -- letting `attn_kv_axi`'s own asserts read as a bug in that file.
      assert C_CM_W = 8
        report "llama_top: C_KV_AXI needs C_CM_W = 8.  attn_kv_axi's record "
             & "is an int8 byte layout and it asserts CM_W = 8 itself."
        severity failure;
      assert (C_KV_BLOCK*C_CM_W/8) mod 16 = 0
        report "llama_top: C_KV_AXI needs KV_BLOCK*CM_W/8 to be a multiple of "
             & "16, the record granule.  At CM_W = 8 that means C_KV_BLOCK "
             & "at least 16, and with attn_block's HEAD_DIM/KV_BLOCK >= 2 and "
             & "HEAD_DIM an even power of two the smallest legal head dim is "
             & "64.  Build the shape with attn_head_dim => 64."
        severity failure;
      assert C_CTXLEN <= C_MAXPOS
        report "llama_top: C_CTXLEN must fit in the cache."
        severity failure;
      -- clog2, not 2**C_KV_ADDR_W: the right-hand side would overflow a
      -- 32-bit integer at C_KV_ADDR_W = 32, so the check would fail on the
      -- widest legal address space rather than on an illegal layout.
      -- Reported in CHUNKS.  The byte figure is not printed because at the
      -- real map it is 6,803,283,968, which `integer'image` cannot render:
      -- the argument would overflow before the message was built, replacing
      -- the diagnostic with an unattributed `overflow detected`.
      assert clog2(maximum(C_K_BASE_CH, C_V_BASE_CH) + KVREG_CH)
             <= C_KV_ADDR_W - 4
        report "llama_top: the KV regions do not fit C_KV_ADDR_W.  The pair "
             & "ends at 16-byte chunk "
             & integer'image(maximum(C_K_BASE_CH, C_V_BASE_CH) + KVREG_CH)
             & ", which needs "
             & integer'image(clog2(maximum(C_K_BASE_CH, C_V_BASE_CH)
                                   + KVREG_CH) + 4)
             & " address bits, and C_KV_ADDR_W is "
             & integer'image(C_KV_ADDR_W)
             & ".  The high end wraps onto the low region."
        severity failure;
      -- The two regions must not overlap.  Nothing else checks this: both
      -- masters would work perfectly and the V records would be K records.
      -- K and V are SEPARATE regions with separate bases (C spec 2.2), so
      -- each is LAYERS*N_KVH*MAXCTX*REC_B and there is no factor of two.
      assert C_K_BASE_CH + KVREG_CH <= C_V_BASE_CH
          or C_V_BASE_CH + KVREG_CH <= C_K_BASE_CH
        report "llama_top: the K and V KV regions overlap.  Each is "
             & integer'image(KVREG_CH) & " chunks of 16 bytes."
        severity failure;
      -- THE 16-BYTE ALIGNMENT ASSERT IS RETIRED, NOT DROPPED.  It read
      -- `C_K_BASE mod 16 = 0 and C_V_BASE mod 16 = 0`.  With the bases
      -- counted in 16-byte chunks the constraint is STRUCTURAL -- there is no
      -- longer a representable value that violates it -- so the assert could
      -- never fire again, and a check that cannot fail is decoration rather
      -- than evidence.  The requirement itself has not gone away; it is now
      -- enforced by the encoding, and `KBASE_C` above is where it is made
      -- true.  `attn_kv_axi.vhd:44-50` still states it.

      u_kv : entity work.attn_kv_axi
        generic map(
          HEAD_DIM => C_HD, KV_BLOCK => C_KV_BLOCK, N_KVH => C_NKVH,
          LAYERS => C_LAY, MAXCTX => C_MAXPOS, POS_W => POSW,
          CM_W => C_CM_W, EXP_W => 8,
          AXI_DW => C_KV_AXI_DW, ADDR_W => C_KV_ADDR_W,
          MAXB => C_KV_MAXB, MAXOUT => C_KV_MAXOUT, RBUF => C_KV_RBUF)
        port map(
          clk => clk, rst => rst,
          start => c_start, layer => c_layer,
          cur_pos => c_cpos, ctx_len => c_ctx,
          k_base => KBASE_C, v_base => VBASE_C,
          cfg_taken => kv_cfgt_s, busy => kv_busy_s, wr_idle => wr_idle_s,
          err => kv_err_i,
          kw_sel => kw_sel, kw_head => kw_head, kw_pos => kw_pos,
          kw_hen => kw_hen, kw_hdr => kw_hdr, kw_en => kw_en,
          kw_blk => kw_blk, kw_mant => kw_mant, kw_rdy => kw_rdy_s,
          kr_head => kr_head, kr_pos => kr_pos, kr_rdy => kr_rdy_s,
          kr_en => kr_en, kr_blk => kr_blk, kr_hdr => kr_hdr,
          kr_mant => kr_mant,
          vr_head => vr_head, vr_pos => vr_pos, vr_rdy => vr_rdy_s,
          vr_en => vr_en, vr_blk => vr_blk, vr_hdr => vr_hdr,
          vr_mant => vr_mant,
          r_arvalid => kv_arvalid, r_arready => kv_arready,
          r_araddr => kv_araddr, r_arlen => kv_arlen, r_arsize => kv_arsize,
          r_arburst => kv_arburst, r_rvalid => kv_rvalid,
          r_rready => kv_rready, r_rdata => kv_rdata, r_rlast => kv_rlast,
          r_rresp => kv_rresp,
          w_awvalid => kv_awvalid, w_awready => kv_awready,
          w_awaddr => kv_awaddr, w_awlen => kv_awlen, w_awsize => kv_awsize,
          w_awburst => kv_awburst, w_wvalid => kv_wvalid,
          w_wready => kv_wready, w_wdata => kv_wdata, w_wstrb => kv_wstrb,
          w_wlast => kv_wlast, w_bvalid => kv_bvalid, w_bready => kv_bready,
          w_bresp => kv_bresp);

      -- The three handshakes, as properties.  A beat offered while its gate
      -- is low is a SILENT WRONG ANSWER on the read side -- the cache does
      -- not update its output, so the block captures whatever it last held --
      -- and a vanished record on the write side, because attn_kv_axi drops
      -- an unaccepted header and every following beat of that record with it.
      seamchk : process(clk) is
        variable said : boolean := false;
      begin
        if rising_edge(clk) then
          if (kr_en = '1' and kr_rdy_s = '0')
             or (vr_en = '1' and vr_rdy_s = '0')
             or ((kw_en = '1' or kw_hen = '1') and kw_rdy_s = '0') then
            kv_seam_bad_i <= '1';
            if not said then
              said := true;
              report "llama_top: a KV cache beat was offered while its "
                   & "handshake was low.  On a read that is a silent wrong "
                   & "answer -- attn_kv_axi leaves kr_mant/vr_mant at their "
                   & "last value and the block captures it -- and on a write "
                   & "the whole record vanishes.  Reported once; the fault "
                   & "is sticky on kv_err." severity error;
            end if;
          end if;
        end if;
      end process;

      -- THE TWO SIDES MUST AGREE ABOUT WHICH LAYER THIS IS.  `attn_block`
      -- publishes `kv_layer` with every write; `attn_kv_axi` takes `layer`
      -- once, at `start`.  Nothing connects them, so a skew between the job
      -- ordinal and the block's own latch would put a whole layer's records
      -- at another layer's addresses and every read would still be served.
      glchk : if C_LAY > 1 generate
        lchk : process(clk) is
        begin
          if rising_edge(clk) then
            if kw_en = '1' or kw_hen = '1' then
              assert to_integer(kv_layer) = c_layer
                report "llama_top: attn_block is writing layer "
                     & integer'image(to_integer(kv_layer))
                     & " and attn_kv_axi was configured for layer "
                     & integer'image(c_layer) severity error;
            end if;
          end if;
        end process;
      end generate;
    end generate;

    -- THE INT8 NARROWING IS A REAL RAIL, NOT A CAST.  Subsystem C's exponent
    -- ports are 8-bit signed by spec, and the residual stream's exponent is
    -- 16-bit here and reaches -387 in the unanchored configuration PART 3
    -- measured.  `resize` would WRAP silently -- which is defect class
    -- "8-bit exponent wrap", already paid for once in subsystem B -- so the
    -- narrowing is checked rather than assumed.
    qg_e8  <= resize(qg_e, 8);
    kin_e8 <= resize(kin_e, 8);
    vin_e8 <= resize(vin_e, 8);


    u_attn : entity work.attn_block
      generic map(
        HEAD_DIM => C_HD, N_QH => C_NQH, N_KVH => C_NKVH,
        KV_BLOCK => C_KV_BLOCK, N_ROT => C_N_ROT, LAYERS => C_LAY,
        POS_W => POSW, MANT_W => MANT_W, CM_W => C_CM_W, EXP_W => 8,
        NORM_LANES => 1, STRICT_PRODUCER => true)
      port map(
        clk => clk, rst => rst,
        start => c_start, layer => c_layer, cur_pos => c_cpos,
        ctx_len => c_ctx, busy => c_busy, cfg_taken => c_cfgtk,
        kv_seq_rst => c_seqrst, seq_rst_taken => c_srtk,
        qg_raddr => qg_raddr, qg_re => qg_re, qg_rdata => qg_rdata,
        qg_exp => qg_e8,
        kin_raddr => kin_raddr, kin_re => kin_re, kin_rdata => kin_rdata,
        kin_exp => kin_e8,
        vin_raddr => vin_raddr, vin_re => vin_re, vin_rdata => vin_rdata,
        vin_exp => vin_e8,
        qn_mant => QN_CONST, qn_exp => QKN_E8,
        kn_mant => KN_CONST, kn_exp => QKN_E8,
        wn_taken => c_wntk,
        kv_layer => kv_layer, kw_sel => kw_sel, kw_head => kw_head,
        kw_pos => kw_pos, kw_hen => kw_hen, kw_hdr => kw_hdr,
        kw_en => kw_en, kw_blk => kw_blk, kw_mant => kw_mant,
        kw_rdy => kw_rdy_s,
        kr_en => kr_en, kr_head => kr_head, kr_pos => kr_pos,
        kr_blk => kr_blk, kr_hdr => kr_hdr, kr_mant => kr_mant,
        kr_rdy => kr_rdy_s,
        vr_en => vr_en, vr_head => vr_head, vr_pos => vr_pos,
        vr_blk => vr_blk, vr_hdr => vr_hdr, vr_mant => vr_mant,
        vr_rdy => vr_rdy_s, kv_wr_idle => wr_idle_s,
        y_valid => y_valid, y_mant => y_mant, y_index => y_index,
        y_last => y_last, y_exp => c_yexp, y_ready => Y_RDY,
        y_hdr_valid => y_hdrv,
        done => c_done, done_ack => c_dack,
        err => c_err, rope_sat => c_ropes, kv_sat => c_kvs, y_sat => c_ys,
        z_sat => c_zs, rescale_max => c_rsmax, dbg_ep_lost => c_eplost);

    cp : process(clk) is
      type st_t is (S_IDLE, S_QGRD, S_KRD, S_VRD, S_GO, S_RUN, S_DRAIN, S_DONE);
      variable st : st_t := S_IDLE;
      variable yb : buf_t(0 to YN-1);
      variable j_dst, j_rows, j_lay : natural := 0;
      variable k, r, ycnt : natural := 0;
      variable e_said : boolean := false;
    begin
      if rising_edge(clk) then
        ur_en(U_C) <= '0';
        uw_en(U_C) <= '0';
        c_start    <= '0';
        c_dack     <= '0';

        if rst = '1' then
          st := S_IDLE; rdy <= '1'; dn <= '0'; uerr <= '0';
        else
          if job_issue = '1' and to_integer(job_unit) = U_C then
            j_dst  := to_integer(job_dst(6 downto 0));
            j_rows := to_integer(job_n_rows(15 downto 0));
            j_lay  := to_integer(job_ordinal);
            -- `job_ordinal` IS the attention-layer ordinal, 0 .. attn-1.  It
            -- is taken, not derived: D spec 4.1 gives the host generator
            -- `attn_ord(i) = (i - (attn_interval-1)) / attn_interval` and
            -- spec 6.1 fixes the field as per-KIND ("B: 0..47, C: 0..15").
            --
            -- THIS LINE USED TO RE-DERIVE IT FROM A BLOCK INDEX, defect
            -- ORD-1, and it was the worse of the two halves: at the 9B shape
            -- the manifest-stamped ordinals 0, 1 and 2 (attention blocks 3,
            -- 7 and 11) each produced c_layer = -1.  MEASURED on this RTL --
            -- `ghdl-mcode:error: bound check failure at
            -- rtl/llama_top.vhd:3804` at `-gBLOCKS=8 -gC_REAL=true`.  On the
            -- card there is no bound check: -1 truncates to the declared
            -- width and aliases onto a legal KV layer.  See
            -- `docs/debugging/2026-08-29_ordinal-two-meanings.md`.
            --
            -- SIMULATION ONLY, and before the assignment; see `b_layer`.
            assert j_lay < C_LAY
              report "llama_top: unit C was issued ordinal "
                   & integer'image(j_lay) & " but this shape has only "
                   & integer'image(C_LAY) & " attention layers.  `ordinal` "
                   & "is the PER-KIND layer index (D spec 4.1), not the "
                   & "block index."
              severity failure;
            c_layer <= j_lay;
            -- THE SEQUENCE POSITION, not a constant 0.  See `tok_pos`.
            c_cpos  <= to_unsigned(tok_pos, POSW);
            c_ctx   <= to_unsigned(C_CTXLEN, POSW);
            ep      <= job_epoch;
            uerr    <= '0';
            rdy     <= '0';
            k       := 0;
            ycnt    := 0;
            c_exp_region_i <= to_unsigned(R_QG, 8);
            c_exp_seg_i    <= "00";
            st := S_QGRD;
            assert j_rows = YN
              report "llama_top: the C job asked for " & integer'image(j_rows)
                   & " rows and attn_block emits " & integer'image(YN)
              severity failure;
          end if;

          -- The un-refusable side of the y stream.  `y_ready` is tied high
          -- here, so this can only fire if the block emits outside its run
          -- window, which would be a lost element.
          if y_valid = '1' then
            if st /= S_RUN then
              f_lost_c_i <= '1';
              report "llama_top: unit C emitted a y element outside its run "
                   & "window." severity error;
            end if;
            if to_integer(y_index) < YN then
              yb(to_integer(y_index)) := y_mant;
            end if;
            ycnt := ycnt + 1;
          end if;
          if c_eplost = '1' then f_lost_c_i <= '1'; end if;

          -- THE INT8 NARROWING, CHECKED ONCE.  Free-running it fires 175,313
          -- times in the unanchored 32-block run and buries every other line
          -- in the log; a guard nobody can read past is a guard nobody reads.
          -- It lives in THIS process and not its own so that the C branch
          -- contributes exactly ONE driver to `f_lost_c_i`.  That constraint is
          -- now enforced by construction rather than by this comment: each
          -- adapter drives its OWN signal and they are OR-ed at the
          -- declaration.  The old arrangement -- three processes driving the
          -- resolved `f_lost` directly -- did NOT do what this comment used to
          -- claim: one '1' against two initial '0's resolves to 'X'.
          if not e_said
             and (qg_e < -128 or qg_e > 127 or kin_e < -128 or kin_e > 127
                  or vin_e < -128 or vin_e > 127) then
            e_said := true;
            f_lost_c_i <= '1';
            report "llama_top: a source exponent for unit C is outside int8 "
                 & "and would WRAP on the way into attn_block -- R_QG "
                 & integer'image(to_integer(qg_e)) & ", R_KIN "
                 & integer'image(to_integer(kin_e)) & ", R_VIN "
                 & integer'image(to_integer(vin_e))
              severity error;
          end if;

          case st is
            when S_IDLE => null;

            -- Three prefetch phases, each claiming its own region's captured
            -- exponent and consuming at k-2.  Consuming at k-1 is defect 3.
            when S_QGRD =>
              if k < QGN then
                ur_en(U_C)   <= '1';
                ur_reg(U_C)  <= R_QG;
                ur_addr(U_C) <= k;
              end if;
              if k >= 2 then qg_buf(k-2) <= el_rdata; end if;
              if k = QGN+1 then
                assert exp_rd_valid = '1'
                  report "llama_top: unit C read R_QG's exponent before "
                       & "anything captured it." severity error;
                qg_e <= exp_rd_data;
                c_exp_region_i <= to_unsigned(R_KIN, 8);
                k := 0; st := S_KRD;
              else
                k := k + 1;
              end if;

            when S_KRD =>
              if k < KVN then
                ur_en(U_C)   <= '1';
                ur_reg(U_C)  <= R_KIN;
                ur_addr(U_C) <= k;
              end if;
              if k >= 2 then kin_buf(k-2) <= el_rdata; end if;
              if k = KVN+1 then
                assert exp_rd_valid = '1'
                  report "llama_top: unit C read R_KIN's exponent before "
                       & "anything captured it." severity error;
                kin_e <= exp_rd_data;
                c_exp_region_i <= to_unsigned(R_VIN, 8);
                k := 0; st := S_VRD;
              else
                k := k + 1;
              end if;

            when S_VRD =>
              if k < KVN then
                ur_en(U_C)   <= '1';
                ur_reg(U_C)  <= R_VIN;
                ur_addr(U_C) <= k;
              end if;
              if k >= 2 then vin_buf(k-2) <= el_rdata; end if;
              if k = KVN+1 then
                assert exp_rd_valid = '1'
                  report "llama_top: unit C read R_VIN's exponent before "
                       & "anything captured it." severity error;
                vin_e <= exp_rd_data;
                k := 0; st := S_GO;
              else
                k := k + 1;
              end if;

            when S_GO =>
              c_start <= '1';
              st := S_RUN;

            when S_RUN =>
              if c_done = '1' then
                c_dack <= '1';
                -- The CACHE's sticky error is subsystem C's error too.  A
                -- cache fault that only reached its own port would leave the
                -- schedule reporting success on a token whose records were
                -- never written.
                uerr   <= c_err or kv_err_i or kv_seam_bad_i;
                -- A REPORT IS NOT A VERDICT.  This sets `f_lost`, which P3
                -- in the bench reads, so a short y stream FAILS the run
                -- instead of printing a line nobody greps for.
                if ycnt /= YN then
                  f_lost_c_i <= '1';
                  report "llama_top: unit C emitted " & integer'image(ycnt)
                       & " y elements, the job needs " & integer'image(YN)
                    severity error;
                end if;
                r  := 0;
                st := S_DRAIN;
              end if;

            when S_DRAIN =>
              uw_en(U_C)   <= '1';
              uw_reg(U_C)  <= j_dst;
              uw_addr(U_C) <= r;
              uw_data(U_C) <= yb(r);
              if r = j_rows-1 then st := S_DONE; else r := r + 1; end if;

            when S_DONE =>
              dn   <= '1';
              -- The block's OWN y_exp, published before its first y_valid.
              -- Not the source region's: this unit computes, so its output
              -- scale is its own.
              yexp <= resize(c_yexp, EXP_W);
              if u_ack(U_C) = '1' then
                dn <= '0'; rdy <= '1'; st := S_IDLE;
              end if;
          end case;
        end if;
      end if;
    end process;
  end generate;
end architecture;
