#!/usr/bin/env python3
"""Derive the post-synthesis testbench from the RTL one.

The netlist and the RTL must be checked by the SAME testbench against the SAME
vectors, or the comparison proves nothing.  Hand-copying it would let the two
drift silently -- the exact failure mode this project keeps designing against --
so the netlist variant is generated, and only two things change:

  * the entity/architecture is renamed, and
  * the DUT instantiation drops its `generic map`, because a netlist has no
    generics: they were baked in at synthesis.

ROWS_IF is pinned to 4 because that is what the netlist was built for (spec
14.4); the generated file asserts it rather than trusting the caller.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "tb_matvec_int4.vhd")
DST = os.path.join(HERE, "tb_matvec_int4_net.vhd")

s = open(SRC).read()

banner = ("-- GENERATED by sim/funcsim_mv/gen_net_tb.py from sim/tb_matvec_int4.vhd\n"
          "-- DO NOT EDIT.  Edit the RTL testbench; this is derived from it so the\n"
          "-- netlist and the RTL are checked by the same code against the same\n"
          "-- vectors.\n")

s = s.replace("entity tb_matvec_int4 is", "entity tb_matvec_int4_net is", 1)
s = s.replace("architecture sim of tb_matvec_int4 is",
              "architecture sim of tb_matvec_int4_net is", 1)

# drop the generic map: a netlist has no generics
m = re.search(r"(  dut : entity work\.matvec_int4\n)(    generic map\(.*?\)\n)(    port map)",
              s, re.S)
if not m:
    sys.exit("could not find the DUT instantiation to strip")
s = s[:m.start(2)] + s[m.end(2):]

# the netlist is built for ROWS_IF=4 only
s = s.replace("begin\n  rst <= '1', '0' after 40 ns;",
              "begin\n  assert RI = 4\n    report \"the netlist is built for ROWS_IF=4 (spec 14.4)\"\n"
              "    severity failure;\n  rst <= '1', '0' after 40 ns;", 1)

open(DST, "w").write(banner + s)
print("wrote", os.path.relpath(DST, os.path.join(HERE, "..", "..")))
