#!/usr/bin/env python3
"""Generate a SCALED-SHAPE wrapper around llama_top, for browsing in the Vivado
GUI.  Written 2026-08-30 after the real-shape elaboration CRASHED Vivado.

WHY THIS EXISTS.  `llama_top` defaults to the true 9B shape, and its region
scratch at rtl/llama_top.vhd:1085 is a FLAT array
`buf_t(0 to NREGION*REGMAX-1)` of `signed(MANT_W-1 downto 0)` with 16 access
ports.  At 9B that is 14 * 12288 * 16 = 2,752,512 bits.  Vivado cannot infer a
RAM from a 16-port flat array, falls back to dissolving it into individual
bits, exceeds its own `dissolveMemorySizeLimit`, and then SEGFAULTS inside
HOptDfg::dissolveRam.  MEASURED 2026-08-30, `vivado.log` + `hs_err_pid478670`:

  ERROR: [Synth 8-3391] Unable to infer a block/distributed RAM for 'mem_reg'
  because the memory pattern used is not supported.  Failed to dissolve the
  memory into bits because the number of bits (2752512) is too large.

That is a property of `llama_top` being a SIMULATION top, not of the browse
project.  Scaling the shape shrinks REGMAX and the array with it; the
STRUCTURE and every port list are unchanged, so the schematic you browse is the
same schematic.

WHY IT IS GENERATED RATHER THAN WRITTEN.  The port list is long and its widths
depend on the generics.  A hand-written copy would be a SECOND statement of
llama_top's interface and could drift from it silently, which is the defect
class this project keeps finding.  This reads the entity and emits the
pass-through, so a port added to llama_top appears here or the build fails
loudly.

OUTPUT goes outside the repo by default, because sim/ and rtl/ are scanned by
regress.sh's planner and TRACK GATEGREEN is establishing BASELINE_PASS.
"""
import re, sys, os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC  = os.path.join(REPO, "rtl", "llama_top.vhd")
OUT  = sys.argv[1] if len(sys.argv) > 1 else "/mnt/storage/llama-browse/llama_top_browse.vhd"
BLOCKS, ATTN_INT, ATTN_HD = (sys.argv[2:5] + ["4", "4", "32"])[:3]

src = open(SRC, encoding="utf-8").read()

m = re.search(r"^entity\s+llama_top\s+is\b(.*?)^end\b", src, re.S | re.M)
if not m:
    sys.exit("could not find llama_top's entity declaration")
body = m.group(1)

pm = re.search(r"^\s*port\s*\((.*)\)\s*;\s*$", body, re.S | re.M)
if not pm:
    sys.exit("could not find llama_top's port clause")
ports_txt = pm.group(1)

# A port declaration line: <names> : <mode> <type>.  Names may be a comma list.
names = []
for line in ports_txt.splitlines():
    line = line.split("--")[0]
    d = re.match(r"\s*([A-Za-z_][\w\s,]*?)\s*:\s*(in|out|inout)\b", line, re.I)
    if d:
        names.extend(n.strip() for n in d.group(1).split(",") if n.strip())
if not names:
    sys.exit("parsed zero ports -- refusing to emit a wrapper that hides the design")

gen = re.sub(r"^\s*SHAPE\s*:.*?;\s*$",
             "    SHAPE   : shape_t := mk_shape_scaled(%s, %s, %s);"
             % (BLOCKS, ATTN_INT, ATTN_HD),
             body, count=1, flags=re.S | re.M)

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8") as f:
    f.write("-- GENERATED by sim/mk_browse_wrapper.py.  Do not edit.\n")
    f.write("-- A scaled-shape wrapper around llama_top for the Vivado GUI.\n")
    f.write("-- Shape: mk_shape_scaled(%s, %s, %s).  Structure identical to the\n"
            "-- real build; only counts and widths shrink.\n" % (BLOCKS, ATTN_INT, ATTN_HD))
    f.write("library ieee; use ieee.std_logic_1164.all; use ieee.numeric_std.all;\n")
    f.write("use work.util_pkg.all; use work.llama_map_pkg.all;\n")
    f.write("use work.model_cfg_pkg.all;\n\n")
    f.write("entity llama_top_browse is%s\nend entity;\n\n" % gen)
    f.write("architecture browse of llama_top_browse is\nbegin\n")
    f.write("  u_llama_top : entity work.llama_top\n")
    f.write("    generic map(SHAPE => SHAPE)\n")
    f.write("    port map(\n")
    f.write(",\n".join("      %-11s => %s" % (n, n) for n in names))
    f.write("\n    );\nend architecture;\n")

print("WROTE %s" % OUT)
print("  %d ports passed through, shape mk_shape_scaled(%s, %s, %s)"
      % (len(names), BLOCKS, ATTN_INT, ATTN_HD))
