#!/usr/bin/env bash
# Mutation test of rtl/seq_vec_issue.vhd -- the D-ctrl / D-vec issue seam --
# against sim/tb_seq_vec_seam.vhd, over seven configurations.
#
# EVERY SURVIVOR IS READ, and the survivors are the point of the exercise.
# Three of them below are EQUIVALENT MUTANTS with a structural argument, and
# the argument is stated in the debugging note rather than assumed: today the
# walker's job_* broadcast is stable for the whole of a job, because live_bank
# moves only in S_ISSUE and D runs one job at a time.  So reading a job_* port
# live rather than from the adapter's latch is indistinguishable from reading
# the latch -- for THIS walker.  It stops being indistinguishable the moment
# anything overlaps, which is the same shape as the M7/M8 argument in
# docs/debugging/2026-08-27_d-sequencer-first-units.md.
#
# THE SEVEN CONFIGURATIONS, and what each one alone can reach:
#   A  memory fast, stub units slow                the reference walk
#   B  the D-vec engine done is a ONE-CYCLE PULSE
#   C  the engine leaves start unaccepted for 20 cycles and withholds ready
#      for 20 after every completion (both longer than the adapter's 8 states
#      and than seq_vec_res's 11)
#   D  LANES = 4 with a slow memory
#   E  two tokens back to back
#   F  a D-vec element count that does not fit the engine port
#   G  a generator that appends into a D-vec destination
#
# NOTE THE ASYMMETRY OF F AND G.  Both abort the token in the first few steps
# BY DESIGN, so they reach almost none of the chain -- they are there to kill
# the two range checks and nothing else, and a mutation surviving F and G alone
# means only that it lives past step 3.  Every kill column is printed so that
# reading "survived: F" as a coverage hole is not possible.
#
# A mutation is KILLED if the run does not print PASS.  The testbench states its
# verdict as a single PASS line and asserts at severity failure on the ordering
# guards, so a wedged run (no PASS, cycle cap) counts as a kill.
#
# The mutant sources are generated by ONE python pass rather than by shell
# argument quoting: the anchors are VHDL and are full of single quotes, and
# quoting those through bash is how an anchor silently stops matching.
#
# Usage: bash sim/mutate_seq_vec_issue.sh
# Env:   SCRATCH=<dir>  NELEM=<n>  NRES=<k>  SEED=<n>
set -uo pipefail

# ---------------------------------------------------------------------------
# SELF-ISOLATION.  bash reads a script by BYTE OFFSET as it runs, so editing
# this file while an instance of it is running corrupts that run silently.
# Several agents share this repo and the one who gets hit is not the one who
# edited the file.  So take a private copy, refuse it if it does not parse
# (which is what a half-written source looks like), and re-exec that.  Same
# guard, same reasons, as sim/regress.sh:307.  MUT_NO_REEXEC=1 disables it.
if [ -z "${MUT_REPO:-}" ]; then
  MUT_REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)" || exit 2
  export MUT_REPO
fi
if [ -z "${MUT_SELF:-}" ] && [ -z "${MUT_NO_REEXEC:-}" ]; then
  _self="$(mktemp -t mutself.XXXXXXXX.sh)" || exit 2
  if ! cat "${BASH_SOURCE[0]}" > "$_self"; then
    rm -f "$_self"; echo "could not take a private copy" >&2; exit 2
  fi
  if ! "${BASH:-/bin/bash}" -n "$_self" 2>/dev/null; then
    rm -f "$_self"
    echo "the private copy does not parse -- this script was probably being" >&2
    echo "  written at the instant it was copied.  Try again." >&2
    exit 2
  fi
  chmod 0700 "$_self"; export MUT_SELF="$_self"
  exec "${BASH:-/bin/bash}" "$_self" "$@"
fi
trap 'if [ -n "${MUT_SELF:-}" ]; then rm -f "$MUT_SELF"; fi' EXIT

# THREE VERDICTS, NOT TWO.  This harness used to judge a mutation with
#   ghdl -r ... && grep -q PASS
# under which a run that DIED -- an elaboration error, a language bound check,
# the DUT's own assert, a wedge to --stop-time -- scored as a KILL even though
# the checker never ran.  sim/mutverdict.py separates the two: KILLED means the
# CHECKER noticed and said so, ABORT means the run never reached a verdict the
# checker owns.  An ABORT is reported under its own name and counted apart.
# Read the header of sim/mutverdict.py for the full rule.
MUTV="$MUT_REPO/sim/mutverdict.py"
NKILL=0; NABORT=0; NSURV=0; NTOT=0
cd "$MUT_REPO"
SCRATCH="${SCRATCH:-$(mktemp -d)}"
NELEM="${NELEM:-250}"
NRES="${NRES:-8}"
SEED="${SEED:-20260827}"
mkdir -p "$SCRATCH"

CFG_A="-gURAM_LAT=1 -gJOB_LAT=40 -gLAT_SKEW=7"
CFG_B="-gVDONE_STYLE=1"
CFG_C="-gVTAKEN_LAG=20 -gVREADY_GAP=20"
CFG_D="-gLANES=4 -gURAM_LAT=12"
CFG_E="-gTOKENS=2"
CFG_F="-gROWS_BIG_AT=2"
CFG_G="-gOFF_APPEND=true"
NAMES="A B C D E F G"

BASE="$SCRATCH/base"
mkdir -p "$BASE"
cc -O2 -w -I ref -o "$BASE/gen" ref/seq_vec_chain_vec.c -lm
( cd "$BASE" && ./gen seq_vec_chain_vec.txt "$NELEM" "$NRES" "$SEED" ) 2>/dev/null

python3 - "$SCRATCH" <<'PY'
import os, sys
scratch = sys.argv[1]
src = open('rtl/seq_vec_issue.vhd').read()

M = []
def mut(tag, desc, *pairs):
    M.append((tag, desc, pairs))

mut('P1', 'the element count is driven from the LIVE job_n_rows, not the latch (class a)',
    '  v_n     <= j_n;',
    '  v_n     <= resize(job_n_rows(VN_W-1 downto 0), VN_W);')

mut('P2', 'the two source exponents are swapped',
    '  v_exp_a <= e_a;\n  v_exp_b <= e_b;',
    '  v_exp_a <= e_b;\n  v_exp_b <= e_a;')

mut('P3', 'both exponents are read from src: the second lookup never moves the address',
    '            e_a   <= exp_rd_data;\n            erd_r <= j_src2;',
    '            e_a   <= exp_rd_data;\n            erd_r <= j_src;')

mut('P4', 'the first exponent is captured one state LATE, after the address moved to src2',
    '            e_a   <= exp_rd_data;\n            erd_r <= j_src2;',
    '            erd_r <= j_src2;')

mut('P5', 'u_y_exp is a live pass-through of the engine port instead of the capture (class c)',
    '  u_y_exp <= y_r;',
    "  u_y_exp <= signed(v_y_exp((j_sel+1)*EXP_W-1 downto j_sel*EXP_W));")

mut('P6', 'u_done is driven from the RAW engine done, one state before the payload is final',
    "  u_done  <= '1' when st = V_HOLD or st = V_FAIL else '0';",
    "  u_done  <= '1' when (st = V_RUN and v_done(j_sel) = '1')\n"
    "                     or st = V_HOLD or st = V_FAIL else '0';")

mut('P7', 'the job shadow is latched at the ACCEPT, one cycle before job_issue',
    "            if u_start = '1' and rdy_all = '1' then\n"
    "              eerr  <= '0';\n"
    "              ecode <= EC_NONE;\n"
    "              st    <= V_ARM;\n"
    "            end if;",
    "            if u_start = '1' and rdy_all = '1' then\n"
    "              eerr  <= '0';\n"
    "              ecode <= EC_NONE;\n"
    "              j_src <= job_src; j_src2 <= job_src2; j_dst <= job_dst;\n"
    "              erd_r <= job_src;\n"
    "              st    <= V_ARM;\n"
    "            end if;",
    "              j_src  <= job_src;\n"
    "              j_src2 <= job_src2;\n"
    "              j_dst  <= job_dst;\n"
    "              erd_r  <= job_src;\n",
    "")

mut('P8', 'the completion payload is never captured: u_y_exp keeps the previous value',
    "              y_r   <= signed(v_y_exp((j_sel+1)*EXP_W-1 downto j_sel*EXP_W));",
    "              null;")

mut('P9', 'the element-count range check is removed (the lm_head truncation trap)',
    "              if job_n_rows = 0 or job_n_rows >= 2**VN_W then",
    "              if job_n_rows = 0 then")

mut('P10', 'the destination-offset check is removed: a D-vec op may append',
    "              if job_dst /= NO_REGION and job_dst_off /= 0 then",
    "              if false then")

mut('P11', 'v_start is PULSED for one cycle instead of held until the engine takes it',
    "          when V_ISS =>",
    "          when V_ISS =>\n            strt <= (others => '0');")

mut('P12', 'the region numbers are driven live from job_src/src2/dst (class a)',
    '  v_reg_a <= j_src;\n  v_reg_b <= j_src2;\n  v_reg_d <= j_dst;',
    '  v_reg_a <= job_src;\n  v_reg_b <= job_src2;\n  v_reg_d <= job_dst;')

mut('P13', 'the engine select for the ack is taken from the LIVE job_opcode (class a)',
    "    v_ack(v) <= '1' when st = V_HOLD and v = j_sel and u_ack = '1' else '0';",
    "    v_ack(v) <= '1' when st = V_HOLD and u_ack = '1'\n"
    "                     and v = to_integer(job_opcode) - OP_BASE else '0';")

mut('P14', 'the completion is waited on at a FIXED engine instead of the selected one',
    "            if v_done(j_sel) = '1' then",
    "            if v_done(1) = '1' then")

mut('P15', 'the exp_rd_valid check is removed (EXPECTED SURVIVOR, see the note)',
    "            if exp_rd_valid = '0' then\n"
    "              eerr  <= '1';\n"
    "              ecode <= EC_NOEXP;\n"
    "              st    <= V_FAIL;\n"
    "            else\n"
    "              st <= V_RDB;\n"
    "            end if;",
    "            st <= V_RDB;")

mut('P16', 'u_done_epoch is driven from the LIVE job_epoch (EXPECTED SURVIVOR, class a)',
    '  u_done_epoch <= j_ep;',
    '  u_done_epoch <= job_epoch;')

man = open(os.path.join(scratch, 'manifest'), 'w')
for tag, desc, pairs in M:
    s = src
    ok = True
    for i in range(0, len(pairs), 2):
        old, new = pairs[i], pairs[i+1]
        n = s.count(old)
        if n != 1:
            sys.stderr.write('%s: ANCHOR %d MATCHED %d TIMES\n' % (tag, i//2, n))
            ok = False
            break
        s = s.replace(old, new)
    if not ok:
        man.write('%s|ANCHOR_FAILED|%s\n' % (tag, desc))
        continue
    d = os.path.join(scratch, tag)
    os.makedirs(d, exist_ok=True)
    open(os.path.join(d, 'm.vhd'), 'w').write(s)
    man.write('%s|OK|%s\n' % (tag, desc))
man.close()
PY

NKILL=0; NABORT=0; NSURV=0; NTOT=0
echo "======= mutations of rtl/seq_vec_issue.vhd, 7 configurations ==========="

while IFS='|' read -r tag state desc; do
  NTOT=$((NTOT+1))
  dir="$SCRATCH/$tag"
  if [ "$state" != OK ]; then
    echo "$tag  ANCHOR FAILED  -- $desc"
    continue
  fi
  cp "$BASE/seq_vec_chain_vec.txt" "$dir/"
  ok=1
  for f in util_pkg model_cfg_pkg seq_desc_fetch seq_region_lock seq_opdec \
           seq_vec_res; do
    ghdl -a --std=08 -frelaxed --workdir="$dir" "rtl/$f.vhd" \
      >>"$dir/an.log" 2>&1 || ok=0
  done
  ghdl -a --std=08 -frelaxed --workdir="$dir" "$dir/m.vhd" >>"$dir/an.log" 2>&1 || ok=0
  ghdl -a --std=08 -frelaxed --workdir="$dir" sim/seq_tbl_pkg.vhd >>"$dir/an.log" 2>&1 || ok=0
  ghdl -a --std=08 -frelaxed --workdir="$dir" sim/tb_seq_vec_seam.vhd >>"$dir/an.log" 2>&1 || ok=0
  if [ $ok -eq 0 ]; then
    echo "$tag  DID NOT ANALYSE -- a mutation that will not build has tested nothing"
    continue
  fi
  killed=""; survived=""; aborted=""
  for n in $NAMES; do
    eval "cfg=\$CFG_$n"
    # shellcheck disable=SC2086
    ( cd "$dir" && timeout 400 ghdl -r --std=08 -frelaxed --workdir="$dir" \
        tb_seq_vec_seam -gNELEM="$NELEM" -gNRES="$NRES" $cfg \
        --max-stack-alloc=0 --stop-time=900ms ) >"$dir/run_$n.log" 2>&1
    rcv=$?
    v=$(python3 "$MUTV" "$dir/run_$n.log" tb_seq_vec_seam "$rcv")
    case "$v" in
      PASS)   survived="$survived $n" ;;
      KILLED) killed="$killed $n" ;;
      *)      aborted="$aborted $n(${v#ABORT:})" ;;
    esac
  done
  if [ -n "$killed" ]; then
    NKILL=$((NKILL+1))
    echo "$tag  KILLED by$killed   (aborted:${aborted:- --}  survived:${survived:- --})  -- $desc"
  elif [ -n "$aborted" ]; then
    NABORT=$((NABORT+1))
    echo "$tag  ABORT  aborted:$aborted  (survived:${survived:- --})  -- $desc"
    echo "      the run DIED before the checker reached a verdict, so the checker"
    echo "      was NOT shown to catch this.  Not counted as a kill."
  else
    NSURV=$((NSURV+1))
    echo "$tag  SURVIVED ALL  -- $desc"
  fi
done < "$SCRATCH/manifest"

echo
echo
echo "--------------------------------------------------------------------"
echo "verdicts: $NKILL killed by the checker, $NABORT aborted before the"
echo "  checker reached a verdict, $NSURV survived all, of $NTOT attempted."
echo "  An ABORT is NOT a kill: the run died and the checker never spoke."
echo "  $(( NTOT - NKILL - NABORT - NSURV )) mutation(s) never ran at all"
echo "  (anchor failure or did-not-analyse); those are printed above."
echo "scratch dir with every mutant and every log: $SCRATCH"
