#!/usr/bin/env bash
# ooc_nwrom_run.sh -- TRACK NWROM, 2026-08-29.
#
# THE QUESTION.  Every area number TRACK NORMADAPT took for the D-vec norm
# adapter was taken with `NORM_W_IMAGE` EMPTY.  With it empty `NW_N = 1`,
# `NW_TBL` is a single elaboration-time constant, `wsel` folds to a constant,
# and `rmsnorm_rs`'s gain-fetch mux collapses from 17,916 LUT standalone to 480.
# A build that actually normalises needs a REAL gain image, and at the 9B shape
# that is 65 norm ops x 4096 elements x 16 bits = 4.26 Mbit behind a 65:1 mux of
# 65,536 bits.  NORMADAPT flagged that as ESTIMATE and said it might be bigger
# than the 76,613 LUT it had just removed.  This script measures it.
#
# Each point goes through TRACK LUTDIET's `sim/ooc_lutdiet_run.sh` and
# `sim/ooc_lutdiet_ports.tcl` UNMODIFIED, with the same flags NORMADAPT used
# (`-flatten_hierarchy none`, `LUTDIET_NOOPT=1`, `LUTDIET_CENSUS=1`,
# xcvu33p-fsvh2104-2L-e, 5.0 ns), so `nw_empty` here is directly comparable to
# NORMADAPT's `na_after` and every other number in this project's area table.
#
# The top is `ooc_normadapt`, generated by `sim/ooc_normadapt_extract.py` from a
# PINNED `rtl/llama_top.vhd`, i.e. the landed adapter and not a model.  The only
# thing that moves between points is the `NORM_W_IMAGE` generic.
#
# ONE VIVADO AT A TIME -- 31 GB box, systemd-oomd history (2026-07-04), and
# NORMADAPT measured 12.50 GiB peak on this exact top.  Same wait rule as
# NORMADAPT's run_synth.sh, including its bounded patience: a strict
# "wait for zero vivado" livelocks against a track running short points back to
# back.
#
# NO HARDWARE.  synth_design and report_* only.
#
# usage: ooc_nwrom_run.sh <scratchdir> <tag>:<image-or-empty>[:<top>[:<rtldir>[:<GEN=v>]]] ...
set -u

# NWROM_REPO lets this script be run from a SNAPSHOT outside the repo.
# Editing a shell script that a running instance is reading corrupts that
# instance -- MEASURED here at 21:52 on 2026-08-29, it killed batch 1's
# sentinel -- so long batches run from a copy in the scratch tree.
REPO="${NWROM_REPO:-$(cd "$(dirname "$0")/.." && pwd)}"
SCR="${1:?usage: ooc_nwrom_run.sh <scratchdir> <tag>:<image> ...}"
shift
OUT="$SCR/out"

mkdir -p "$OUT"

PATIENCE="${NWROM_PATIENCE:-2700}"
BIGRSS_KIB="${NWROM_BIGRSS:-4194304}"
MINAVAIL_G="${NWROM_MINAVAIL:-18}"

wait_for_vivado_idle () {
    local t0 n avail big
    t0=$(date +%s)
    while :; do
        n=$(ps -eo comm | grep -cx vivado)
        [ "$n" -eq 0 ] && return 0
        if [ $(( $(date +%s) - t0 )) -ge "$PATIENCE" ]; then
            avail=$(free -g | awk '/^Mem:/{print $7}')
            big=$(ps -eo comm=,rss= | awk -v b="$BIGRSS_KIB" '$1=="vivado" && $2>b' | wc -l)
            if [ "$avail" -ge "$MINAVAIL_G" ] && [ "$big" -eq 0 ]; then
                echo "== patience expired; proceeding with $n small vivado(s), avail=${avail}G"
                return 0
            fi
        fi
        sleep 5
    done
}

for spec in "$@"; do
    IFS=: read -r tag img top rtld extra <<<"$spec"
    top="${top:-ooc_normadapt}"
    RTL="${rtld:-$SCR/rtl}"
    wait_for_vivado_idle
    echo "== $tag start $(date -Is) image='$img' avail=$(free -g | awk '/^Mem:/{print $7}')G"
    if [ -n "$img" ] && [ ! -r "$img" ]; then
        echo "== $tag ABORT: image '$img' is not readable"
        continue
    fi
    # An EMPTY image passes NO generic rather than `NORM_W_IMAGE=`: the entity's
    # own default is "" and an empty -generic value is not a documented Vivado
    # form.  So `nw_empty` is the entity default, which is exactly the
    # configuration NORMADAPT measured.
    if [ -n "$img" ]; then
        LUTDIET_FLATTEN=none LUTDIET_NOOPT=1 LUTDIET_CENSUS=1 \
          bash "$REPO/sim/ooc_lutdiet_run.sh" "$tag" "$top" "$OUT" "$RTL" \
               "NORM_W_IMAGE=$img" ${extra:+$extra}
    else
        LUTDIET_FLATTEN=none LUTDIET_NOOPT=1 LUTDIET_CENSUS=1 \
          bash "$REPO/sim/ooc_lutdiet_run.sh" "$tag" "$top" "$OUT" "$RTL" ${extra:+$extra}
    fi
    echo "== $tag rc=$? $(date -Is)"
    tail -1 "$OUT/result_$tag.csv" 2>/dev/null || echo "== $tag NO CSV"
done
echo "NWROM_SYNTH_ALL_DONE"
