#!/usr/bin/env python3
"""ooc_normadapt_extract.py -- TRACK NORMADAPT, 2026-08-29.

Generate an out-of-context synthesis top (and a GHDL-simulable entity) that
carries `rtl/llama_top.vhd`'s D-vec norm adapter -- the `gvr` generate block --
VERBATIM, with the handful of names it reads from `llama_top`'s enclosing scope
turned into ports and local constants.

WHY EXTRACT RATHER THAN MODEL.  TRACK LUTDIET measured this cost on a
hand-written stand-in, `lutdiet_rms_flat`, and TRACK WRITEDEC quoted its
residual (`xv` 88,640 + `wv` 88,640 + `ord` 17,472) as the adapter's cost.  A
stand-in is a model, and this one differs from the shipping adapter in at least
one way that matters: `llama_top` drives `w_mant` from a CONSTANT
(`NW_TBL(nidx)`, and `NW_N = 1` whenever `NORM_W_IMAGE` is empty, which is the
synthesis default), while the stand-in streams `w` into a written register.
So the stand-in's `wv` row has no counterpart in the shipping design.

WHY MECHANICAL RATHER THAN COPIED.  The before/after attribution is only valid
if the two harnesses differ by exactly the edit under test.  This script is run
against BOTH trees and the block text is taken verbatim from whichever
`llama_top.vhd` it is pointed at, so the diff between the two generated files
IS the diff between the two `llama_top.vhd` files, restricted to the block.
It aborts if the anchors do not match exactly once.

NO HARDWARE.  This script reads and writes text files and nothing else.

usage: ooc_normadapt_extract.py <path/to/llama_top.vhd> <out.vhd> [ENTITY] [--shift]

`--shift` additionally rewrites the whole-word write into a plain SHIFT
REGISTER, which is the `na_shift` probe in the write-up.  It is a PROBE and is
deliberately not in `rtl/`: it is correct only because the read pass writes
exactly NN elements in order before anything reads the vector, and the only
thing enforcing that is an `assert ... severity failure` that Vivado IGNORES in
synthesis.  It is here so the number in the write-up is reproducible, not so it
can be adopted.
"""

import re
import sys

START_RE = re.compile(r"^    gvr : if NORM_REAL and vi = V_NORM generate\s*$")
END_RE = re.compile(r"^    end generate;\s*$")

PROLOGUE = """\
-- ooc_normadapt_top.vhd -- GENERATED by sim/ooc_normadapt_extract.py.
-- DO NOT EDIT.  The body below is `rtl/llama_top.vhd`'s `gvr` generate block,
-- copied verbatim from {src}.
--
-- Everything the block reads from `llama_top`'s enclosing scope is declared
-- here with the same name and the same type, so the block text is unchanged.
-- The port list is the adapter's real seam: the `seq_vec_issue` handshake, the
-- region-file element port, and the observation taps.
--
-- WHAT THIS IS NOT.  It is not a routability result and it is not `llama_top`.
-- It is one generate block of `llama_top` synthesised alone, which is exactly
-- the resolution the question needs and no more.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;
use work.model_cfg_pkg.all;
use work.llama_map_pkg.all;

entity {ent} is
  generic(
    SHAPE        : shape_t  := mk_shape(MODEL, NCARDS);
    MANT_W       : positive := 16;
    EXP_W        : positive := 16;
    VN_W         : positive := 14;
    NORM_LANES   : positive := 4;
    NORM_Q       : integer  := 12;
    NORM_W_EXP   : integer  := 12;
    NORM_W_IMAGE : string   := "";
    SHOUT        : boolean  := false;
    NORM_REAL    : boolean  := true
  );
  port(
    clk        : in  std_logic;
    rst        : in  std_logic;
    go         : in  std_logic;
    i_v_start  : in  std_logic;
    i_v_ack    : in  std_logic;
    i_v_n      : in  unsigned(VN_W-1 downto 0);
    i_v_exp_a  : in  signed(EXP_W-1 downto 0);
    i_v_reg_a  : in  unsigned(7 downto 0);
    i_v_reg_d  : in  unsigned(7 downto 0);
    i_el_rdata : in  signed(MANT_W-1 downto 0);
    o_v_ready  : out std_logic;
    o_v_done   : out std_logic;
    o_v_taken  : out std_logic;
    o_v_err    : out std_logic;
    o_v_y_exp  : out std_logic_vector(EXP_W-1 downto 0);
    o_ur_en    : out std_logic;
    o_ur_reg   : out std_logic_vector(15 downto 0);
    o_ur_addr  : out std_logic_vector(31 downto 0);
    o_uw_en    : out std_logic;
    o_uw_reg   : out std_logic_vector(15 downto 0);
    o_uw_addr  : out std_logic_vector(31 downto 0);
    o_uw_data  : out std_logic_vector(MANT_W-1 downto 0);
    obs_norm_pub : out std_logic;
    obs_norm_exp : out signed(EXP_W-1 downto 0);
    obs_norm_ssq : out unsigned(63 downto 0);
    obs_norm_n   : out unsigned(15 downto 0)
  );
end entity;

architecture rtl of {ent} is
  -- llama_top's enclosing-scope names, same names and same types.
  constant NUNIT  : natural := 4;
  constant NVOP   : natural := 4;
  constant NPORT  : natural := NUNIT + NVOP;
  constant V_NORM : natural := 1;
  constant vi     : natural := V_NORM;

  type nat_u is array (0 to NPORT-1) of natural;
  type sig_u is array (0 to NPORT-1) of signed(MANT_W-1 downto 0);

  signal ur_en   : std_logic_vector(NPORT-1 downto 0) := (others => '0');
  signal ur_reg  : nat_u := (others => 0);
  signal ur_addr : nat_u := (others => 0);
  signal uw_en   : std_logic_vector(NPORT-1 downto 0) := (others => '0');
  signal uw_reg  : nat_u := (others => 0);
  signal uw_addr : nat_u := (others => 0);
  signal uw_data : sig_u := (others => (others => '0'));

  signal v_start, v_ready, v_taken, v_done, v_ack, v_err
    : std_logic_vector(NVOP-1 downto 0) := (others => '0');
  signal v_y_exp : std_logic_vector(NVOP*EXP_W-1 downto 0) := (others => '0');
  signal v_n     : unsigned(VN_W-1 downto 0);
  signal v_exp_a : signed(EXP_W-1 downto 0);
  signal v_reg_a, v_reg_d : unsigned(7 downto 0);
  signal el_rdata : signed(MANT_W-1 downto 0) := (others => '0');
begin
  v_start(vi) <= i_v_start;
  v_ack(vi)   <= i_v_ack;
  v_n         <= i_v_n;
  v_exp_a     <= i_v_exp_a;
  v_reg_a     <= i_v_reg_a;
  v_reg_d     <= i_v_reg_d;
  el_rdata    <= i_el_rdata;

  o_v_ready <= v_ready(vi);
  o_v_done  <= v_done(vi);
  o_v_taken <= v_taken(vi);
  o_v_err   <= v_err(vi);
  o_v_y_exp <= v_y_exp((vi+1)*EXP_W-1 downto vi*EXP_W);

  o_ur_en   <= ur_en(NUNIT+vi);
  o_ur_reg  <= std_logic_vector(to_unsigned(ur_reg(NUNIT+vi), 16));
  o_ur_addr <= std_logic_vector(to_unsigned(ur_addr(NUNIT+vi), 32));
  o_uw_en   <= uw_en(NUNIT+vi);
  o_uw_reg  <= std_logic_vector(to_unsigned(uw_reg(NUNIT+vi), 16));
  o_uw_addr <= std_logic_vector(to_unsigned(uw_addr(NUNIT+vi), 32));
  o_uw_data <= std_logic_vector(uw_data(NUNIT+vi));

-- ==== BEGIN VERBATIM llama_top gvr BLOCK ====
"""

EPILOGUE = """\
-- ==== END VERBATIM llama_top gvr BLOCK ====
end architecture;
"""


def main() -> int:
    if not (3 <= len(sys.argv) <= 5):
        sys.stderr.write(__doc__)
        return 2
    argv = [a for a in sys.argv[1:] if a != "--shift"]
    shift = "--shift" in sys.argv
    src, dst = argv[0], argv[1]
    ent = argv[2] if len(argv) == 3 else "ooc_normadapt"

    lines = open(src).read().split("\n")

    starts = [i for i, l in enumerate(lines) if START_RE.match(l)]
    if len(starts) != 1:
        sys.stderr.write("EXTRACT ABORT: %d start anchors, expected 1\n" % len(starts))
        return 3
    s = starts[0]
    ends = [i for i in range(s + 1, len(lines)) if END_RE.match(lines[i])]
    if not ends:
        sys.stderr.write("EXTRACT ABORT: no end anchor after the start\n")
        return 4
    e = ends[0]

    body = lines[s:e + 1]
    # The block must be self-contained: an unbalanced generate would mean the
    # end anchor matched the wrong line.
    ng = sum(1 for l in body if re.search(r"\bgenerate\s*$", l))
    ne = sum(1 for l in body if re.search(r"^\s*end generate;", l))
    if ng != ne:
        sys.stderr.write("EXTRACT ABORT: %d generate vs %d end generate\n" % (ng, ne))
        return 5

    if shift:
        a = "                  xw(k-2) <= std_logic_vector(el_rdata);"
        body_s = "\n".join(body)
        if body_s.count(a) != 1:
            sys.stderr.write("EXTRACT ABORT: --shift needs exactly one xw(k-2) write\n")
            return 6
        body_s = body_s.replace(a,
            "                  -- SHIFT-REGISTER PROBE, not the landed form.\n"
            "                  for j in 0 to NN-2 loop xw(j) <= xw(j+1); end loop;\n"
            "                  xw(NN-1) <= std_logic_vector(el_rdata);")
        body = body_s.split("\n")

    with open(dst, "w") as fh:
        fh.write(PROLOGUE.format(src=src, ent=ent))
        fh.write("\n".join(body))
        fh.write("\n")
        fh.write(EPILOGUE)
    sys.stderr.write("EXTRACT OK %s lines %d..%d (%d lines) -> %s\n"
                     % (src, s + 1, e + 1, len(body), dst))
    return 0


if __name__ == "__main__":
    sys.exit(main())
