#!/usr/bin/env python3
"""ooc_cattnadapt_extract.py -- subsystem C's data mover, extracted.

Carries `rtl/llama_top.vhd`'s `gcr` generate block VERBATIM, with the names it
reads from `llama_top`'s enclosing scope turned into ports, generics and local
declarations.  SAME METHOD as `sim/ooc_gdnadapt_extract.py`, which did this for
subsystem B's `gb_real`; that file's docstring states the reasoning this one
inherits, including why extraction is preferred to a rewrite (a model written
by the author of the thing it checks is not evidence, so the block text is
taken verbatim and the diff between two generated files IS the diff between
two `llama_top.vhd` files restricted to the block).

WHY THIS BLOCK.  `docs/debugging/2026-09-03_b-mover-does-not-fit.md` closes
with "C's mover (`gcr`, 762 lines) has not been extracted.  The method
transfers; the seam does not, and mapping it is the same day of work."  This
is that day.  `docs/debugging/2026-08-31_cardtop-design-note.md` section 14
lists the B and C data movers among the pieces still absent from the wired
`compose4_top`, which under D6 is the card build.

THE SEAM, and how it was derived rather than guessed.  A mechanical pass
classified the 50 names the block reads from the enclosing scope: 22 that are
`llama_top` GENERICS, 16 the block ASSIGNS, and 12 it only READS.  The
assignment test matches a name followed by an optional balanced index or slice
and then `<=`, which is what the B extractor's docstring records getting wrong
five separate ways -- in particular `u_done_epoch((U_C+1)*EPOCH_W-1 downto
U_C*EPOCH_W) <= ...`, whose nested parentheses defeat a `\\([^)]*\\)` pattern.
THE CLASSIFICATION IS STILL NOT THE PROOF.  GHDL is: it rejects an `in` port
that is assigned, a name declared twice, and a name with no declaration, so an
output miscalled an input cannot analyse.

THE SEAM IS FLATTENED, AND IT HAS TO BE, for the same reason B's was:
`llama_top` declares `nat_u` and `sig_u` as ARCHITECTURE-local types whose
bounds depend on its own generics, and such a type cannot appear on a port
list, which is elaborated before the generics are known.  So the region-file
ports below are scalars, the block keeps the exact `nat_u`/`sig_u` signals it
was written against as architecture-local declarations, and a conversion joins
the two.  THE BLOCK TEXT IS STILL VERBATIM; the conversion is outside it.

THE BLOCK TOUCHES EXACTLY ONE PORT SLOT.  MEASURED: every array reference in
it is `(U_C)`, and the two slice writes are `u_done_epoch` and `u_y_exp` at
`U_C`.  So the arrays are local and only slot `U_C` is joined to a port; no
other slot is driven, which is what makes the scalar seam faithful.

WHAT THIS IS NOT.  Not a routability result, not `llama_top`, and NOT a claim
that C can run a token.  It is one generate block synthesised alone.

NO HARDWARE.  This script reads and writes text files and nothing else.

usage: ooc_cattnadapt_extract.py <path/to/llama_top.vhd> <out.vhd> [ENTITY]
"""

import re
import sys

START = "  gcr : if C_REAL generate"
END   = "  end generate;"

PROLOGUE = """\
-- {ent}.vhd -- GENERATED by sim/ooc_cattnadapt_extract.py.
-- DO NOT EDIT.  The body below is `rtl/llama_top.vhd`'s `gcr` generate block,
-- subsystem C's data mover, copied verbatim from {src}.
--
-- Regenerate with:
--   python3 sim/ooc_cattnadapt_extract.py rtl/llama_top.vhd {out}
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

use work.util_pkg.all;
use work.model_cfg_pkg.all;
use work.llama_map_pkg.all;

entity {ent} is
  generic(
    SHAPE       : shape_t  := mk_shape(QWEN35_9B, 1);
    MANT_W      : positive := 16;
    EXP_W       : positive := 16;
    EPOCH_W     : positive := 4;
    ADDR_W      : positive := 16;
    NORM_LANES  : positive := 4;
    STRICT      : boolean  := true;
    SHOUT       : boolean  := false;
    C_REAL      : boolean  := true;
    C_MAXPOS    : positive := 4;
    C_CTXLEN    : positive := 4;
    C_KV_BLOCK  : positive := 4;
    C_N_ROT     : positive := 8;
    C_QKN_EXP   : natural  := 12;
    C_CM_W      : positive := 8;
    C_KV_AXI    : boolean  := false;
    C_KV_AXI_DW : positive := 256;
    C_KV_ADDR_W : positive := 33;
    C_KV_MAXB   : positive := 16;
    C_KV_MAXOUT : positive := 4;
    C_KV_RBUF   : positive := 64;
    C_K_BASE_CH : natural  := 0;
    C_V_BASE_CH : natural  := 0;
    NVOP        : positive := 3
  );
  port(
    clk : in std_logic;
    rst : in std_logic;

    -- D's job fields, and the unit handshake back to it (slot U_C only)
    job_issue    : in  std_logic;
    job_unit     : in  unsigned(2 downto 0);
    job_dst      : in  unsigned(7 downto 0);
    job_n_rows   : in  unsigned(31 downto 0);
    job_epoch    : in  unsigned(EPOCH_W-1 downto 0);
    job_ordinal  : in  unsigned(7 downto 0);
    u_ack_c      : in  std_logic;
    u_ready_c    : out std_logic;
    u_done_c     : out std_logic;
    u_err_c      : out std_logic;
    u_epoch_c    : out std_logic_vector(EPOCH_W-1 downto 0);
    u_yexp_c     : out std_logic_vector(EXP_W-1 downto 0);

    -- the region-file element port, FLATTENED (see the header)
    ur_en_c      : out std_logic;
    ur_reg_c     : out std_logic_vector(7 downto 0);
    ur_addr_c    : out std_logic_vector(ADDR_W-1 downto 0);
    uw_en_c      : out std_logic;
    uw_reg_c     : out std_logic_vector(7 downto 0);
    uw_addr_c    : out std_logic_vector(ADDR_W-1 downto 0);
    uw_data_c    : out std_logic_vector(MANT_W-1 downto 0);
    el_rdata     : in  signed(MANT_W-1 downto 0);

    -- the exponent side-channel D presents
    exp_rd_valid : in  std_logic;
    exp_rd_data  : in  signed(EXP_W-1 downto 0);
    c_exp_region : out std_logic_vector(7 downto 0);
    c_exp_seg    : out std_logic_vector(1 downto 0);

    tok_pos      : in  natural range 0 to C_MAXPOS-1;
    kv_seam_bad  : out std_logic;
    f_lost_c     : out std_logic;

    -- THE KV AXI FACE, copied verbatim from `llama_top`'s own port clause
    -- with the same names, directions, widths and defaults.
    --
    -- THE MECHANICAL SEAM PASS MISSED ALL 26 OF THESE, and GHDL is what
    -- found them.  They are llama_top ENTITY PORTS, not architecture signals,
    -- so a classifier looking for `signal`/`constant` declarations cannot see
    -- them at all -- a sixth way for the derivation to be wrong, on top of
    -- the five sim/ooc_gdnadapt_extract.py records.  `kv_rdata` additionally
    -- spans two lines in llama_top (:751-752), which is the same two-line
    -- declaration trap that hid `u_start` from B's pass.
    kv_arvalid : out std_logic_vector(1 downto 0);
    kv_arready : in  std_logic_vector(1 downto 0) := (others => '0');
    kv_araddr  : out std_logic_vector(2*C_KV_ADDR_W-1 downto 0);
    kv_arlen   : out std_logic_vector(15 downto 0);
    kv_arsize  : out std_logic_vector(5 downto 0);
    kv_arburst : out std_logic_vector(3 downto 0);
    kv_rvalid  : in  std_logic_vector(1 downto 0) := (others => '0');
    kv_rready  : out std_logic_vector(1 downto 0);
    kv_rdata   : in  std_logic_vector(2*C_KV_AXI_DW-1 downto 0)
               := (others => '0');
    kv_rlast   : in  std_logic_vector(1 downto 0) := (others => '0');
    kv_rresp   : in  std_logic_vector(3 downto 0) := (others => '0');
    kv_awvalid : out std_logic;
    kv_awready : in  std_logic := '0';
    kv_awaddr  : out std_logic_vector(C_KV_ADDR_W-1 downto 0);
    kv_awlen   : out std_logic_vector(7 downto 0);
    kv_awsize  : out std_logic_vector(2 downto 0);
    kv_awburst : out std_logic_vector(1 downto 0);
    kv_wvalid  : out std_logic;
    kv_wready  : in  std_logic := '0';
    kv_wdata   : out std_logic_vector(C_KV_AXI_DW-1 downto 0);
    kv_wstrb   : out std_logic_vector(C_KV_AXI_DW/8-1 downto 0);
    kv_wlast   : out std_logic;
    kv_bvalid  : in  std_logic := '0';
    kv_bready  : out std_logic;
    kv_bresp   : in  std_logic_vector(1 downto 0) := (others => '0');
    kv_err     : out std_logic
  );
end entity;

architecture rtl of {ent} is
  -- `llama_top`'s architecture-local types and signals, reproduced with the
  -- same names and types so the block text below needs no edit.
  constant NPORT : natural := NUNIT + NVOP;
  -- `buf_t` is llama_top's, and the block declares process variables of it.
  type buf_t  is array (natural range <>) of signed(MANT_W-1 downto 0);
  type nat_u  is array (0 to NPORT-1) of natural;
  type sig_u  is array (0 to NPORT-1) of signed(MANT_W-1 downto 0);

  signal ur_en   : std_logic_vector(NPORT-1 downto 0) := (others => '0');
  signal ur_reg  : nat_u := (others => 0);
  signal ur_addr : nat_u := (others => 0);
  signal uw_en   : std_logic_vector(NPORT-1 downto 0) := (others => '0');
  signal uw_reg  : nat_u := (others => 0);
  signal uw_addr : nat_u := (others => 0);
  signal uw_data : sig_u := (others => (others => '0'));

  signal u_ready      : std_logic_vector(NUNIT-1 downto 0) := (others => '0');
  signal u_done       : std_logic_vector(NUNIT-1 downto 0) := (others => '0');
  signal u_err        : std_logic_vector(NUNIT-1 downto 0) := (others => '0');
  signal u_ack        : std_logic_vector(NUNIT-1 downto 0) := (others => '0');
  signal u_done_epoch : std_logic_vector(NUNIT*EPOCH_W-1 downto 0)
                      := (others => '0');
  signal u_y_exp      : std_logic_vector(NUNIT*EXP_W-1 downto 0)
                      := (others => '0');

  signal c_exp_region_i : unsigned(7 downto 0) := (others => '0');
  signal c_exp_seg_i    : unsigned(1 downto 0) := "00";
  signal f_lost_c_i     : std_logic := '0';
  signal kv_seam_bad_i  : std_logic := '0';

  -- `kv_err_i` IS AN OUTPUT OF THE BLOCK, and the mechanical pass called it an
  -- input.  It is DRIVEN THROUGH A PORT MAP -- `err => kv_err_i` on the
  -- attn_kv_axi instance -- and never by a `<=` assignment, so an
  -- assignment-based classifier cannot see it drive.  That is a SEVENTH
  -- failure mode beyond the five sim/ooc_gdnadapt_extract.py records and the
  -- entity-port one above; GHDL caught it as "cannot associate out port 'err'
  -- with actual port of mode in".
  --
  -- llama_top:5795 combines it exactly this way, and that line is reproduced
  -- below rather than invented.
  signal kv_err_i       : std_logic := '0';
begin
  -- the conversion, OUTSIDE the verbatim block
  u_ack(U_C)   <= u_ack_c;
  u_ready_c    <= u_ready(U_C);
  u_done_c     <= u_done(U_C);
  u_err_c      <= u_err(U_C);
  u_epoch_c    <= u_done_epoch((U_C+1)*EPOCH_W-1 downto U_C*EPOCH_W);
  u_yexp_c     <= u_y_exp((U_C+1)*EXP_W-1 downto U_C*EXP_W);

  ur_en_c      <= ur_en(U_C);
  ur_reg_c     <= std_logic_vector(to_unsigned(ur_reg(U_C), 8));
  ur_addr_c    <= std_logic_vector(to_unsigned(ur_addr(U_C), ADDR_W));
  uw_en_c      <= uw_en(U_C);
  uw_reg_c     <= std_logic_vector(to_unsigned(uw_reg(U_C), 8));
  uw_addr_c    <= std_logic_vector(to_unsigned(uw_addr(U_C), ADDR_W));
  uw_data_c    <= std_logic_vector(uw_data(U_C));

  c_exp_region <= std_logic_vector(c_exp_region_i);
  c_exp_seg    <= std_logic_vector(c_exp_seg_i);
  f_lost_c     <= f_lost_c_i;
  kv_seam_bad  <= kv_seam_bad_i;
  -- llama_top:5795, verbatim
  kv_err       <= kv_err_i or kv_seam_bad_i;

"""

EPILOGUE = """
end architecture;
"""


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__.strip().splitlines()[-1])
    src, out = sys.argv[1], sys.argv[2]
    ent = sys.argv[3] if len(sys.argv) > 3 else "ooc_cattnadapt_top"

    lines = open(src).read().split("\n")
    starts = [i for i, l in enumerate(lines) if l.rstrip() == START]
    if len(starts) != 1:
        sys.exit("ooc_cattnadapt_extract: the block header %r matched %d "
                 "times, expected exactly 1.  The block moved or was renamed; "
                 "fix this anchor deliberately rather than relaxing it to a "
                 "substring." % (START, len(starts)))
    st = starts[0]
    ind = len(lines[st]) - len(lines[st].lstrip())
    en = None
    for j in range(st + 1, len(lines)):
        t = lines[j]
        if t.strip().startswith("end generate") and \
           (len(t) - len(t.lstrip())) == ind:
            en = j
            break
    if en is None:
        sys.exit("ooc_cattnadapt_extract: no `end generate;` at the block's "
                 "own indentation after line %d." % (st + 1))

    body = "\n".join(lines[st:en + 1])

    # The block's own signals for these four are what the wrapper renames, so
    # that the block text stays verbatim while the entity has clean names.
    for n in ("c_exp_region", "c_exp_seg", "f_lost_c", "kv_seam_bad"):
        body = re.sub(r"\b%s\b" % n, n + "_i", body)

    text = PROLOGUE.format(ent=ent, src=src, out=out) + body + EPILOGUE
    open(out, "w").write(text)
    print("wrote %s (%d lines, block %d..%d of %s)"
          % (out, text.count("\n") + 1, st + 1, en + 1, src))


if __name__ == "__main__":
    main()
