#!/usr/bin/env bash
# sim/regress.sh -- ONE verdict for every testbench in the repo, both suites.
#
# WHY THIS EXISTS.  65 testbenches in sim/, 27 more in tb/, 80 files in rtl/,
# and about twenty
# ad-hoc run_*.sh / mutate_*.sh scripts, each of which knows how to build one
# unit.  Nothing ran them all, so verification was whatever anyone happened to
# remember, and shared units -- gdn_conv, rmsnorm_bf and gdn_emit_chain are
# each consumed by several subsystems -- were changed by one workstream and
# spot-checked by another.  That is the shape of a cross-subsystem regression
# that escapes.  This script runs everything, always, and returns non-zero if
# anything is not demonstrably green.
#
#   bash sim/regress.sh                 # full run, BOTH suites
#   bash sim/regress.sh --suite sim     # the current generation only
#   bash sim/regress.sh --suite tb      # the older tb/ set only
#   bash sim/regress.sh --quick         # pre-commit subset, 45 s at --jobs 2
#   bash sim/regress.sh --jobs 4        # more parallelism (default 2)
#   bash sim/regress.sh --only gdn      # only testbenches matching a pattern
#   bash sim/regress.sh --list          # print the plan, run nothing
#   bash sim/regress.sh --coverage      # only the RTL-without-a-testbench report
#   bash sim/regress.sh --keep          # keep the scratch tree for post-mortem
#
# ---------------------------------------------------------------------------
# TWO SUITES, KEPT SEPARATE
# ---------------------------------------------------------------------------
# sim/tb_*.vhd is the current generation.  tb/tb_*.vhd is an older set that
# sim/Makefile drives and that nothing else ran; between them they are the only
# thing reaching fifteen rtl/ files including engine, engine_shared, layer,
# layer_ar, layer_fsm, llama_engine_axi, matmul, matvec_engine, sampler and
# seq_ctrl.  Leaving tb/ out meant a headline "42 PASS" that quietly excluded a
# quarter of rtl/.
#
# They are run as separate suites rather than merged into one list, because:
#
#   * they are different generations of the design and a failure in the older
#     one means something different from a failure in the current one.  The
#     summary is printed PER SUITE as well as overall.
#   * they use opposite conventions for data files.  Every path in tb/ is
#     "../mem/golden/...", while sim/ mostly opens bare vector names in the
#     working directory.  One workdir layout serves both, but only because it
#     provides both forms.
#   * SEVEN testbench names exist in both: tb_embed, tb_lm_head, tb_matmul_rt,
#     tb_rmsnorm, tb_rope, tb_softmax and tb_swiglu are each declared by a tb/
#     file and by a sim/tb_*_ps.vhd file.  Every key in this script is
#     therefore <suite>:<name>, and the scratch directories are keyed the same
#     way, or the two suites would share a GHDL library.
#
# --suite selects one; the default runs both.  A tb/ testbench that cannot be
# run is reported SKIPPED with its reason, exactly like an xsim-only one, and
# never fails the run silently.
#
# ---------------------------------------------------------------------------
# WARNING: DO NOT EDIT THIS FILE WHILE A RUN OF IT IS IN PROGRESS
# ---------------------------------------------------------------------------
# bash reads a script lazily, by BYTE OFFSET, as it executes.  Editing the file
# under a running instance shifts every offset after the edit, and the shell
# resumes mid-token somewhere it was never meant to be.  This happened during
# bring-up: a run produced a full, correct-looking set of per-test results and
# then died with "syntax error near unexpected token `fi'" at a line that is
# perfectly valid, having silently skipped the summary.  The per-test results
# were fine and the conclusion was missing, which is the worst combination.
# Copy the file elsewhere and edit that, or wait for the run to finish.
#
# ---------------------------------------------------------------------------
# THE THINGS THIS GETS RIGHT, AND WHY EACH ONE IS HERE
# ---------------------------------------------------------------------------
#
# 1. GHDL HERE IS THE MCODE BACKEND.  `ghdl -e` produces NO binary and exits 0.
#    A runner built on `-e && ./tb` therefore reports a green build and runs
#    nothing.  This has already cost this project time; see the header of
#    sim/run_gdn_block.sh.  `ghdl -r <entity>` is run directly, always.
#
#    Related trap, and it bit this script during bring-up: the top-level entity
#    is NOT always the file stem.  sim/tb_rope_ps.vhd declares `entity tb_rope`,
#    sim/tb_rmsnorm_ps.vhd declares `entity tb_rmsnorm`, and five others do the
#    same.  Running the stem gives "cannot find entity or configuration", which
#    reads like a broken analysis.  The entity name is parsed out of the file.
#
# 2. ANALYSIS ORDER IS DERIVED, NOT LISTED.  A hardcoded order rots the moment
#    somebody adds a package.  Every rtl/, sim/ and sim/micro/ source is parsed
#    for the design units it DEFINES (entity/package) and the ones it
#    REFERENCES (`use work.X`, `entity work.X`, and component instantiation),
#    and the per-testbench closure is emitted in topological order.  The only
#    hardcoded part is a tie-break that pulls fixed_luts_pkg, fixed_pkg,
#    util_pkg and model_cfg_pkg to the front when the graph leaves them
#    unordered relative to each other; every real edge still comes from the
#    files.  A dependency cycle is reported as a SKIP, not silently ignored.
#
# 3. -frelaxed IS PASSED TO BOTH -a AND -r, UNCONDITIONALLY.  tb_rmsnorm_bf
#    uses non-protected shared variables; giving the flag to `-a` alone leaves
#    `-r` re-elaborating (mcode elaborates at run time) and failing with
#    analysis errors and no simulation, which reads as a broken testbench.
#    Detecting the need per file is possible but pointless: -frelaxed relaxes
#    LRM strictness, it does not change simulation semantics and it cannot
#    suppress an assertion, so applying it everywhere is strictly safer than
#    any list and cannot rot.  Same reasoning for --max-stack-alloc=0, which
#    several testbenches need because they build their vector tables as
#    function-local temporaries and ghdl-mcode's 128 KB default rejects them
#    with "declaration of a too large object" rather than a VHDL error.
#
# 4. EVERY TEST GETS ITS OWN WORKING DIRECTORY, POPULATED.  Testbenches open
#    vector files by bare name ("gdn_emit_chain_vec.txt") and golden files as
#    "../mem/golden/...".  Run from the wrong place they abort with "cannot
#    open vectors", which is a spurious failure.  Each test runs in
#    $SCRATCH/<tb>/run with every non-VHDL file in sim/ symlinked in and
#    $SCRATCH/<tb>/mem -> $REPO/mem, so both forms resolve.  That is also what
#    makes parallelism safe: no two tests share a workdir or a GHDL library.
#    Nothing is ever written into sim/.
#
# 5. GENERICS, STOP-TIMES AND GENERATED VECTORS ARE LIFTED FROM THE EXISTING
#    SCRIPTS, not reinvented.  See the EXTRAS tables below; each row cites the
#    run_*.sh or mutate_*.sh it came from.  Six vector files are NOT committed
#    and are produced by a C generator in ref/; those are built into the test's
#    own workdir.  A testbench whose vector file is missing and whose generator
#    is not in the table is still handled: the vector name is parsed out of the
#    testbench and ref/<stem>.c is built with its own defaults.  That is what
#    lets a testbench added by another workstream today run without an edit
#    here -- tb_attn_twiddle appeared mid-development and needed no row.
#
# 6. A VERDICT COMES FROM EVIDENCE, NOT FROM AN EXIT CODE ALONE.  This repo has
#    had an assertion at `severity note`: a genuine defect printed and the run
#    exited 0 (sim/tb_b_audit_ser_handshake.vhd line 203 documents the case).
#    A test is PASS only if it exits 0, prints NO failure marker, AND prints a
#    recognised success marker.  A run that produces no output at all is a
#    FAILURE, not a pass.  A run that produces output with no trustworthy
#    marker either way is NOVERDICT and counted as a failure -- it is not
#    evidence of anything.  Four testbenches in this repo are genuinely not
#    self-checking (they dump values for the netlist-compare flow, or measure
#    cycles); they are declared NOCHECK below, with the reason, and are
#    reported in their own bucket rather than being quietly counted as passes.
#
#    The inverse mistake is guarded too.  A line that reports a failure COUNT
#    of zero is not a failure: tb/tb_divider_rs ends a clean run with
#    "DIVIDER TB RESULT: PASS=608 FAIL=0", and a bare \bFAIL\b match called
#    that a failed test until the neutralisation in the judge was added.  Only
#    ZERO-valued counters are neutralised, and only on the failure scan.
#
# 7. TIMEOUTS ARE REPORTED SEPARATELY FROM FAILURES.  They mean different
#    things: a timeout is usually an unguarded clock or a deadlock, a failure
#    is usually arithmetic.  Four testbenches in this project once ran forever
#    on an unguarded clock, one of them for 4h58m at 99.5% CPU.
#
# 8. EVERY RESULT LINE CARRIES ITS ELAPSED SECONDS.  Not decoration: --quick's
#    exclusion list is only honest if it was chosen from measurement, and the
#    one slow test in a twenty-minute run is the first thing anyone wants to
#    know.  It is also what caught the SLOW_SET bug -- --quick was running a
#    408 s testbench it was documented as excluding.
#
# 9. THE SCRIPT RUNS FROM A PRIVATE COPY OF ITSELF.  bash reads a script by
#    byte offset as it executes, so an edit to sim/regress.sh corrupts any run
#    already in flight -- and with several agents in this repo, the one who
#    gets hit is not the one who edited it.  It happened three times during
#    this script's own development, once to a third party.  A comment could
#    not fix that, so section 0 copies the file to a private temp path and
#    re-execs it; from then on the running process reads a file nobody else
#    can name.  Arguments pass through, the exit status is the payload's
#    because `exec` replaces the process, the repo root is resolved BEFORE the
#    re-exec and exported, and the copy is syntax-checked first in case it was
#    taken mid-write.  Editing sim/regress.sh during a run is now merely
#    pointless rather than destructive.
#
# 10. THE PASS COUNT HAS A FLOOR.  Every other check here watches for a test
#    going RED; a test that goes MISSING makes the suite GREENER and nothing
#    would have noticed.  BASELINE_PASS is checked on full unfiltered runs and
#    fails the run when the count DROPS, saying in as many words that this is
#    a disappearance and not a failure.
#
# 11. PARALLELISM IS CONSERVATIVE BY DEFAULT.  --jobs defaults to 2 because this
#    workstation regularly has a Vivado synthesis running, and Vivado is the
#    memory hog that has already triggered a systemd-oomd kill of the whole
#    session cgroup.  Raise it when the box is idle.
#
# ---------------------------------------------------------------------------
# WHAT --quick SKIPS, AND WHY.  --quick IS NOT COVERAGE.
# ---------------------------------------------------------------------------
# --quick runs the fast unit testbenches only.  MEASURED at --jobs 2 with a
# Vivado place-and-route competing for the box: 45 s wall, 48 PASS + 3 NOCHECK,
# slowest single test 7 s; against 1069 s for the full both-suite run in the
# same conditions.  Wall time swings a lot with machine load, so treat those as
# ratios rather than budgets.  --quick exists for the minute before a commit
# and it is NOT a substitute for a full run.  It deliberately omits, by name:
#
#   tb_gdn_block                the six-unit top level, minutes per skew point
#   tb_gdn_emit_chain           four units and four seams
#   tb_gdn_recur_pipe           384 cases at DIM=128
#   tb_gdn_y_emit               24 heads x 128 elements over two blocks
#   tb_engine_dump              the whole shared-datapath engine, token loop
#   tb_matvec_int4              full AXI weight-stream end to end
#   tb_matvec_axi               the PS register-map sequence
#   tb_matvec_core              trace-driven, thousands of trace lines
#   tb_gdn_conv_cycles          CH_MAX=3072 cycle accounting
#   tb_b_audit_ser_handshake    serialiser handshake audit over 3 blocks
#   tb_hbm_tg                   HBM traffic generator, long burst program
#   tb_llama_top                the integration top level: the whole D core,
#                               the real matvec_int4 over five AXI masters and
#                               the real gdn_block, 4 blocks x 4 descriptor-
#                               memory latencies.  MEASURED 86 s, which would
#                               nearly triple --quick on its own.
#   tb_llama_top_seq            the same integration top level at the
#                               multi-token KV-cache configuration: four
#                               tokens of one sequence through the real
#                               rtl/attn_kv_axi.vhd over three modelled AXI
#                               slaves, two attention layers, two latency
#                               points.  MEASURED 302 s through this runner.
#   tb_llama_top_real           the same integration top level with EVERY
#                               computing unit real AND real Qwen3.5-9B
#                               weights: real matvec_int4, real gdn_block,
#                               real attn_block, real rmsnorm_rs on the D-vec
#                               norm op, weights from the committed
#                               sim/llama_top_w_b4_pool.hex.  MEASURED 75 s
#                               through this runner (127 s standalone on a
#                               box that was running nine other simulations).
#                               Until this row existed the gate ran ONLY the
#                               generic defaults, which are the attention STUB
#                               and the probe norm.
#   tb_seq_desc_fetch           491-descriptor walk
#   tb_seq_opdec                491-step walk through three units
#   tb_seq_region_lock          491-step plan
#
# tb_seq_vec_seam is deliberately NOT on that list even though it is a seam
# test: five real units, but a short synthetic schedule, so it runs in about
# two seconds and there is no reason to lose the seam coverage in --quick.
#
# and from the tb/ suite:
#
#   tb_e2e                      seq_ctrl over 16 tokens, all layers
#   tb_engine                   24 tokens through the whole engine
#   tb_engine_shared            24 tokens through the shared datapath
#   tb_engine_dbg               the same, as a register dump
#   tb_llama_engine_axi         24 tokens through the AXI register map
#   tb_layer, tb_layer_fsm      a whole layer, weights loaded from mem/
#   tb_matmul, tb_weights_pkg   both pull in rtl/weights_pkg.vhd, 1.9 MB of
#                               constants whose ANALYSIS is the slow part
#
# Those are exactly the ones that cover the SEAMS between units, which is where
# the cross-subsystem regressions live.  Never conclude "regression is green"
# from a --quick run.
#
# ---------------------------------------------------------------------------
# WHAT IS SKIPPED AND WHY, IN A FULL RUN
# ---------------------------------------------------------------------------
# Nothing is dropped quietly.  Every testbench appears in the output with a
# verdict, and a testbench that cannot be run is printed as SKIPPED with its
# reason.  There are three automatically-detected reasons:
#
#   (a) the testbench declares `library beh` -- it is a post-synthesis
#       netlist-versus-behavioral comparison and needs TWO libraries plus
#       UNISIM/SECUREIP, which is Vivado xsim, not GHDL.  Run those with the
#       matching sim/run_*_cmp.sh after regenerating the netlist.
#   (b) the testbench's closure needs a design unit that only a netlist-side
#       file provides (post_*.vhd, *_net*.vhd, *_ps_wrap*.vhd).  Same reason.
#   (c) the closure names a design unit nothing in rtl/, sim/ or sim/micro/
#       defines.  That is a real hole and it is named in the output.
#
# Both suites are in scope, so "no testbench" in the coverage section means no
# testbench anywhere.  The coverage report also names the files only the tb/
# suite reaches, because those are the ones that go untested if somebody runs
# with --suite sim out of habit.
# ---------------------------------------------------------------------------
set -uo pipefail

# ===========================================================================
# 0. SELF-ISOLATION.  Run from a PRIVATE COPY, so an edit to sim/regress.sh
#    cannot corrupt a run that is already in flight.
# ===========================================================================
# bash reads a script lazily, by BYTE OFFSET, as it executes.  Editing the file
# under a running instance shifts every offset after the edit and the shell
# resumes mid-token.  The symptom is a full, correct-looking set of per-test
# results followed by "syntax error" at a line that is perfectly valid, with
# the summary silently missing -- results without a conclusion, which is the
# worst of the possible failures.
#
# A comment warning about it was not enough, and could not be: with several
# agents sharing this repo, the one who gets hit is not the one who edited the
# file.  So the script copies itself somewhere private and re-execs that copy.
# From then on the running process is reading a file nobody else can name.
#
# Four things this has to get right, all easy to get subtly wrong:
#
#   * ARGUMENTS.  `exec ... "$@"` passes them through unchanged, including
#     empty ones and ones containing spaces.  --list, --only, --suite and the
#     rest behave identically either side of the re-exec.
#   * EXIT STATUS.  `exec` REPLACES this process, so the payload's status is
#     the status the caller sees.  There is no wrapper left to mask it.  That
#     matters more here than usual: the whole value of this runner is that a
#     non-zero exit means something.
#   * PATHS.  Everything below derives from $REPO, and $REPO derives from
#     ${BASH_SOURCE[0]}, which after the re-exec points at /tmp.  So the repo
#     root is resolved HERE, from the original location, and exported.  Get
#     this wrong and the copy resolves rtl/ and sim/ somewhere they are not.
#   * A HALF-WRITTEN SOURCE.  If the copy happens to be taken while somebody
#     is mid-write, the copy is garbage and re-execing it would produce
#     exactly the failure this guard exists to prevent.  `bash -n` on the copy
#     refuses that case loudly instead.
#
# REGRESS_NO_REEXEC=1 disables the guard, for debugging the guard itself.
if [ -z "${REGRESS_REPO:-}" ]; then
  REGRESS_REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)" || exit 2
  export REGRESS_REPO
fi

if [ -z "${REGRESS_SELF:-}" ] && [ -z "${REGRESS_NO_REEXEC:-}" ]; then
  _self="$(mktemp -t regress-self.XXXXXXXX.sh)" || exit 2
  if ! cat "${BASH_SOURCE[0]}" > "$_self"; then
    rm -f "$_self"; echo "regress.sh: could not take a private copy" >&2; exit 2
  fi
  if ! "${BASH:-/bin/bash}" -n "$_self" 2>/dev/null; then
    rm -f "$_self"
    echo "regress.sh: the private copy does not parse -- sim/regress.sh was" >&2
    echo "  probably being written at the instant it was copied.  Try again." >&2
    exit 2
  fi
  chmod 0700 "$_self"
  export REGRESS_SELF="$_self"
  exec "${BASH:-/bin/bash}" "$_self" "$@"
  # Only reached if exec itself failed.
  rm -f "$_self"
  echo "regress.sh: could not re-exec the private copy" >&2
  exit 2
fi

REPO="$REGRESS_REPO"
SIM="$REPO/sim"

# The cleanup trap is armed HERE, before option parsing, not later next to the
# scratch directory.  --help and an unknown option both exit during parsing,
# and a trap armed after that point leaks a private copy into /tmp every time
# somebody types --help.  ${SCRATCH:-} and ${KEEP:-0} are not yet set at this
# point, hence the defaults.
cleanup() {
  [ -n "${REGRESS_SELF:-}" ] && rm -f "$REGRESS_SELF"
  [ "${KEEP:-0}" = 0 ] && [ -n "${SCRATCH:-}" ] && rm -rf "$SCRATCH"
  return 0
}
trap cleanup EXIT
GHDL="${GHDL:-ghdl}"
STD="--std=08"
RELAX="-frelaxed"

JOBS=2
TIMEOUT=900
QUICK=0
ONLY=""
LIST_ONLY=0
COVERAGE_ONLY=0
KEEP=0
SUITES="sim tb"

# ---------------------------------------------------------------------------
# THE BASELINE FLOOR.  A test that DISAPPEARS makes the suite greener.
# ---------------------------------------------------------------------------
# Everything else in this script watches for a test going RED.  Nothing watched
# for a test going MISSING, and the two are different failures: a testbench
# deleted, renamed out of the tb_*.vhd glob, or newly unresolvable and so
# reported SKIPPED, REMOVES a red line rather than adding one.  The headline
# then reads greener than the day before while covering less, which is the one
# way this runner could mislead the project it gates.
#
# So the gate has a floor.  It is a FLOOR, not an equality: adding a testbench
# must not fail the run, it prints a note asking for the floor to be raised.
# Dropping below it fails the run, and says explicitly that this is a
# disappearance rather than a failure, because the fix is completely different.
#
# Raise this whenever a testbench is added.  It is checked ONLY on a full,
# unfiltered both-suite run -- --quick, --only and --suite all legitimately
# pass fewer, and a floor that fired on those would be noise inside a week.
BASELINE_PASS=83   # +1 sim/tb_llama_top_real, the integration top level with
                   #    C_REAL, NORM_REAL and the committed real-weight image
                   #    all on.  Before it, EVERY tb_llama_top gate row
                   #    elaborated with the attention stub and the probe norm,
                   #    so a regression in the real path left the gate green.
                   #    Its vector sim/llama_top_w_b4_pool.hex is COMMITTED --
                   #    the generator needs an 18 GB GGUF that is not in git --
                   #    so it needs no row in the vector tables, 2026-08-29
                   # +1 sim/tb_llama_top_seq, rtl/llama_top.vhd joined to
                   #    rtl/attn_kv_axi.vhd over a multi-token sequence.  It
                   #    is a WRAPPER around sim/tb_llama_top.vhd, because this
                   #    script keys a test by name and cannot run one
                   #    testbench at two generic sets, 2026-08-29
                   # +1 sim/tb_attn_kv_seam, rtl/attn_block.vhd joined to
                   #    rtl/attn_kv_axi.vhd over a 4-token sequence, 2026-08-28
                   # +1 sim/tb_mv4i_desc_image, the gateware judging a
                   #    descriptor image written by tools/gen_mv4i_desc.py.
                   #    Its vector sim/mv4i_desc_image.txt is COMMITTED, so it
                   #    needs no row in this script and no model set, 2026-08-28
                   # +1 sim/tb_matvec_fk33_desc, subsystem A through the
                   #    descriptor control plane plus its mutation matrix,
                   #    2026-08-28
                   # +1 sim/tb_matvec_fk33, subsystem A at ROWS_IF=48 /
                   #    AXI_DW=256 from a real .mv4i file, 2026-08-28
                   # +1 sim/tb_llama_top, the integration top level, 2026-08-28
                   # +1 sim/tb_weight_streamer, 6.5a reassembly, 2026-08-28
                   # +1 sim/tb_attn_mac_array, subsystem C's MAC array, 2026-08-28
                   # +1 sim/tb_attn_block, subsystem C's top level, 2026-08-28
                   # +1 sim/tb_attn_kv_axi, subsystem C's KV cache in HBM at
                   #    two AXI widths, 2026-08-28

usage() { sed -n '2,237p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0; }

while [ $# -gt 0 ]; do
  case "$1" in
    --quick)     QUICK=1; shift ;;
    --jobs)      JOBS="$2"; shift 2 ;;
    --jobs=*)    JOBS="${1#*=}"; shift ;;
    --timeout)   TIMEOUT="$2"; shift 2 ;;
    --timeout=*) TIMEOUT="${1#*=}"; shift ;;
    --only)      ONLY="$2"; shift 2 ;;
    --only=*)    ONLY="${1#*=}"; shift ;;
    --list)      LIST_ONLY=1; shift ;;
    --coverage)  COVERAGE_ONLY=1; shift ;;
    --suite)     SUITES="$2"; shift 2 ;;
    --suite=*)   SUITES="${1#*=}"; shift ;;
    --keep)      KEEP=1; shift ;;
    -h|--help)   usage ;;
    *) echo "regress.sh: unknown option '$1' (try --help)" >&2; exit 2 ;;
  esac
done

command -v "$GHDL" >/dev/null 2>&1 || { echo "regress.sh: ghdl not found on PATH" >&2; exit 2; }

SCRATCH="${REGRESS_SCRATCH:-$(mktemp -d -t regress.XXXXXX)}"
mkdir -p "$SCRATCH"
# The trap is already armed (see cleanup() above).  --keep governs the per-test
# scratch tree, which is evidence; it never keeps the private copy, which is
# not.
[ "$KEEP" = 1 ] && echo "scratch: $SCRATCH"

# --quick's exclusion list, keyed <suite>:<name>.  Suite-qualified because the
# two suites share SEVEN testbench names: tb_embed, tb_lm_head, tb_matmul_rt,
# tb_rmsnorm, tb_rope, tb_softmax and tb_swiglu are each declared by a tb/ file
# AND by a sim/tb_*_ps.vhd file.  A bare name would match both.
SLOW_TBS="sim:tb_gdn_block sim:tb_gdn_emit_chain sim:tb_gdn_recur_pipe
          sim:tb_gdn_y_emit sim:tb_engine_dump sim:tb_matvec_int4
          sim:tb_matvec_axi sim:tb_matvec_core sim:tb_gdn_conv_cycles
          sim:tb_b_audit_ser_handshake sim:tb_hbm_tg sim:tb_seq_desc_fetch
          sim:tb_seq_opdec sim:tb_seq_region_lock sim:tb_llama_top
          sim:tb_llama_top_seq sim:tb_llama_top_real
          tb:tb_e2e tb:tb_engine tb:tb_engine_shared tb:tb_engine_dbg
          tb:tb_llama_engine_axi tb:tb_layer tb:tb_layer_fsm tb:tb_matmul
          tb:tb_weights_pkg"
# NORMALISED to single-space separated, and this is load bearing.  SLOW_TBS is
# written across several lines for readability, so the separator between the
# last entry on one line and the first on the next is a NEWLINE.  A membership
# test of the form  [[ " $SLOW_TBS " == *" $key "* ]]  then silently fails for
# every entry that happens to sit at a line end, and those tests run anyway.
# That is not hypothetical: it is why --quick was 452 s -- tb:tb_engine_dbg sat
# at a line end, was never excluded, and cost 408 s of the 452 on its own.
SLOW_SET=" $(echo $SLOW_TBS) "

# ===========================================================================
# 1. PLAN.  Parse every source, resolve each testbench's closure, order it.
#    Emits, per testbench:  name  status  reason  files  top-entity  vectors
# ===========================================================================
PLAN="$SCRATCH/plan.tsv"
COVER="$SCRATCH/coverage.txt"

python3 - "$REPO" "$PLAN" "$COVER" <<'PYEOF'
import re, os, sys, glob

repo, plan_out, cover_out = sys.argv[1], sys.argv[2], sys.argv[3]

# Netlist-side artefacts.  These are post-synthesis outputs (write_vhdl
# -mode funcsim) and the thin wrappers that give them their PS-facing port
# profile.  They are UNISIM/SECUREIP structural netlists: GHDL has no such
# libraries, so anything that needs one is an xsim job, not a GHDL job.
# This is a NAMING CONVENTION rule, deliberately, and it is the only
# hardcoded classification in the plan.  sim/rope_ps_rtl.vhd is the one
# hand-written RTL stand-in for such a wrapper and is correctly not matched.
NETLIST_RE = re.compile(r'^(post_.*|.*_net(_ren)?|.*_ps_wrap\d*|attn_net_wrap|attn_probe_wrap)\.vhd$')

def strip(src):
    """Drop VHDL comments without disturbing string literals or line count."""
    lines = []
    for ln in src.split('\n'):
        out, i, instr = [], 0, False
        while i < len(ln):
            c = ln[i]
            if c == '"':
                instr = not instr
            if not instr and c == '-' and i + 1 < len(ln) and ln[i+1] == '-':
                break
            out.append(c); i += 1
        lines.append(''.join(out))
    return '\n'.join(lines)

def parse(path):
    raw = strip(open(path, errors='replace').read())
    txt = raw.lower()

    entities = re.findall(r'^[ \t]*entity[ \t]+(\w+)[ \t]+is', txt, re.M)
    defines = set(entities)
    defines |= set(re.findall(r'^[ \t]*package[ \t]+(?!body\b)(\w+)[ \t]+is', txt, re.M))

    refs = set()
    refs |= set(re.findall(r'\buse[ \t]+work\.(\w+)', txt))
    refs |= set(re.findall(r'\bentity[ \t]+work\.(\w+)', txt))
    refs |= set(re.findall(r'\bfor[ \t]+[\w,\s]+:[ \t]*\w+[ \t]+use[ \t]+entity[ \t]+work\.(\w+)', txt))
    # Component instantiation:  label : name [generic map|port map].  The name
    # may sit on its own line, so the match crosses the newline.
    refs |= set(re.findall(r'\n[ \t]*\w+[ \t]*:[ \t]*(\w+)[ \t\n]*(?:generic[ \t]+map|port[ \t]+map)', txt))
    # A component declared and bound by default binding still needs its entity.
    refs |= set(re.findall(r'^[ \t]*component[ \t]+(\w+)', txt, re.M))

    for kw in ('process', 'block', 'if', 'for', 'case', 'while', 'null',
               'entity', 'configuration', 'others', 'work', 'generate'):
        refs.discard(kw)
    refs -= defines

    # Data files opened by bare name (no directory part).  "../mem/golden/..."
    # is deliberately excluded: those are committed golden files reached
    # through the per-test workdir's mem symlink, not generated vectors.
    vecs = set()
    for lit in re.findall(r'"([^"\n]+)"', raw):
        if lit.endswith('.txt') and '/' not in lit and ' ' not in lit:
            vecs.add(lit)
    return defines, refs, entities, sorted(vecs)

# tb/ comes LAST so that, on the seven names both suites declare, the sim/
# file wins the `provider` slot.  It never matters in practice -- a testbench
# entity is referenced by nothing -- but a deterministic rule beats a lucky one.
sources = []
for pat in ('rtl/*.vhd', 'sim/*.vhd', 'sim/micro/*.vhd', 'tb/*.vhd'):
    sources += sorted(glob.glob(os.path.join(repo, pat)))

files = {}          # relpath -> (defines, refs, entities, vecs)
provider = {}       # design unit -> relpath  (first non-netlist wins)
netlist_provider = {}
for p in sources:
    rel = os.path.relpath(p, repo)
    base = os.path.basename(p)
    files[rel] = parse(p)
    isnet = bool(NETLIST_RE.match(base))
    for name in files[rel][0]:
        if isnet:
            netlist_provider.setdefault(name, rel)
        elif name not in provider:
            provider[name] = rel

PIN = ['rtl/fixed_luts_pkg.vhd', 'rtl/fixed_pkg.vhd', 'rtl/util_pkg.vhd',
       'rtl/model_cfg_pkg.vhd']

def closure_of(relpath):
    """Transitive closure over the non-netlist provider set."""
    got, netonly, missing = set(), set(), set()
    stack = [relpath]
    while stack:
        f = stack.pop()
        if f in got:
            continue
        got.add(f)
        for r in files[f][1]:
            if r in provider:
                stack.append(provider[r])
            elif r in netlist_provider:
                netonly.add(r)
            else:
                missing.add(r)
    return got, netonly, missing

def toposort(closure, last):
    dep = {}
    for f in closure:
        dep[f] = set()
        for r in files[f][1]:
            q = provider.get(r)
            if q and q in closure and q != f:
                dep[f].add(q)
    ordered, done = [], set()
    pending = [p for p in PIN if p in closure] + \
              sorted(f for f in closure if f not in PIN)
    while pending:
        rest, progressed = [], False
        for f in pending:
            if dep[f] <= done:
                ordered.append(f); done.add(f); progressed = True
            else:
                rest.append(f)
        pending = rest
        if not progressed:
            return None, pending
    return [f for f in ordered if f != last] + [last], []

# The two suites.  sim/ is the current generation; tb/ is the older set that
# sim/Makefile drives.  They are kept SEPARATE rather than merged: they are
# different generations of the design, they use opposite conventions for where
# their data files live (sim/ mostly opens bare names, tb/ always opens
# "../mem/golden/..."), and a merged list would hide which generation a failure
# came from.
SUITE_DIRS = [('sim', 'sim'), ('tb', 'tb')]

rows = []
covered = {'sim': {}, 'tb': {}}

for suite, d in SUITE_DIRS:
    tbs = sorted(os.path.relpath(p, repo)
                 for p in glob.glob(os.path.join(repo, d, 'tb_*.vhd')))
    for tb in tbs:
        name = os.path.basename(tb)[:-4]

        # (a) two-library netlist compare -- detected, not listed.
        raw = strip(open(os.path.join(repo, tb), errors='replace').read()).lower()
        if re.search(r'^[ \t]*library[ \t]+beh[ \t]*;', raw, re.M):
            rows.append((name, suite, 'SKIP',
                         'declares `library beh`: post-synthesis netlist-vs-behavioral '
                         'compare, needs xsim + UNISIM (see sim/run_*_cmp.sh)',
                         '', '', ''))
            continue

        cl, netonly, missing = closure_of(tb)
        if netonly:
            who = sorted(netonly)
            rows.append((name, suite, 'SKIP',
                         'needs %s, provided only by a post-synthesis netlist file (%s): '
                         'xsim job, not GHDL' % (', '.join(who), netlist_provider[who[0]]),
                         '', '', ''))
            continue
        if missing:
            rows.append((name, suite, 'SKIP',
                         'unresolved design unit(s): %s -- nothing in rtl/, sim/, '
                         'sim/micro/ or tb/ defines them' % ', '.join(sorted(missing)),
                         '', '', ''))
            continue

        ordered, stuck = toposort(cl, tb)
        if ordered is None:
            rows.append((name, suite, 'SKIP',
                         'dependency cycle among: %s' % ', '.join(sorted(stuck)),
                         '', '', ''))
            continue

        # The top-level entity is NOT always the file stem: sim/tb_rope_ps.vhd
        # declares `entity tb_rope`.  In tb/ the stem always IS the entity, but
        # the rule is derived rather than assumed, so neither suite needs a list.
        ents = files[tb][2]
        top = name if name in ents else next((e for e in ents if e.startswith('tb_')),
                                             ents[0] if ents else name)

        for f in ordered:
            if f.startswith('rtl/'):
                covered[suite].setdefault(f, []).append(name)
        rows.append((name, suite, 'RUN', '', ' '.join(ordered), top,
                     ' '.join(files[tb][3])))

# Tab is IFS whitespace in bash, so an EMPTY field would collapse and shift
# every field after it.  '-' stands in for an empty field.
with open(plan_out, 'w') as fh:
    for r in rows:
        fh.write('\t'.join(x if x else '-' for x in r) + '\n')

# --- coverage: RTL files with no testbench -------------------------------
# Both suites are measured the SAME way, by transitive closure rather than by
# direct instantiation, or rtl/layer_ar.vhd would read as uncovered merely
# because tb/tb_engine.vhd reaches it through engine.vhd.
sim_cov, tb_cov = covered['sim'], covered['tb']

rtl = sorted(os.path.relpath(p, repo)
             for p in glob.glob(os.path.join(repo, 'rtl/*.vhd')))
with open(cover_out, 'w') as fh:
    uncov = [f for f in rtl if not sim_cov.get(f) and not tb_cov.get(f)]
    fh.write('TOTAL_RTL %d\n' % len(rtl))
    fh.write('UNCOVERED %d\n' % len(uncov))
    fh.write('BYSIM %d\n' % len([f for f in rtl if sim_cov.get(f)]))
    fh.write('BYTB %d\n' % len([f for f in rtl if tb_cov.get(f)]))
    fh.write('BYBOTH %d\n' % len([f for f in rtl if sim_cov.get(f) and tb_cov.get(f)]))
    for f in uncov:
        fh.write('NOTB %s\n' % f)
    for f in rtl:
        if not sim_cov.get(f) and tb_cov.get(f):
            fh.write('TBONLY %s %s\n' % (f, ','.join(sorted(set(tb_cov[f])))))
PYEOF

[ -s "$PLAN" ] || { echo "regress.sh: plan generation failed" >&2; exit 2; }

# ===========================================================================
# 2. EXTRAS.  Per-testbench generics, stop-time, vector generation and success
#    marker, lifted from the existing scripts rather than reinvented.  Every
#    row cites its source.  A testbench not named here runs on its own generic
#    defaults, which is the common case: most of these testbenches declare
#    sensible defaults and a committed vector file next to them in sim/.
# ===========================================================================
# All four tables below are keyed <suite>:<name>, never a bare name, for the
# seven-name collision reason given at SLOW_TBS.
tb_args() {   # extra `ghdl -r` arguments for $1
  case "$1" in
    # sim/run_gdn_emit_chain.sh.  OVERLAP=true is how the chain actually runs
    # and is the mode that catches the w_mant hazard; --stop-time is a backstop
    # only, the testbench drops `running` itself.
    #
    # Z_DELAY=640 IS LOAD BEARING AND WAS ADDED 2026-08-29.  The bench defaults
    # it to 0 and this row used to leave it there, which is the ONE setting at
    # which the chain's own z_have handshake cannot be checked -- the bench's
    # header says so in as many words ("0 makes it run maximally ahead, which
    # is what MASKED the z_have defect").  MEASURED with the mutation that
    # drops z_have from S_IDLE's condition, at exactly the generics on this
    # line, 3 blocks x 24 heads:
    #
    #   Z_DELAY    0 PASS    7 PASS   40 PASS  520 PASS
    #             540 FAIL  560 FAIL 580 FAIL  600 FAIL  640 FAIL  1024 FAIL
    #   CONTROL, unmutated, at 640: PASS
    #
    # So the kill threshold is in (520, 540] and 640 sits 18.5% above it.  It
    # is DERIVED rather than picked: the measured per-head period is 44394
    # cycles / 72 heads = 616, so 640 makes z late for every head, and the
    # mutant then diverges at head 4 instead of head 10 as it does at 540.
    # Cost, MEASURED: the unmutated run goes 52 s -> 61 s.  Do not lower it;
    # 512 is the column pass alone and is not enough.
    #
    # It does move "refused-column cycles" from 0 to 7255, because making z
    # late is exactly what backs the column path up.  That counter is REPORTED
    # and never asserted at STRICT=false, so nothing that was being gated stops
    # being gated; the refusal-is-a-failure property lives at STRICT=true and
    # is a separate manual run either way.
    sim:tb_gdn_emit_chain)   echo "-gOVERLAP=true -gCOL_GAP=4 -gSTRICT=false -gSILU_LANES=16 -gRMS_LANES=4 -gZ_DELAY=640 --stop-time=300ms" ;;
    # sim/run_gdn_block.sh reference point: every producer maximally ahead.
    sim:tb_gdn_block)        echo "-gOUTFILE=gdn_block_out.txt --stop-time=200ms" ;;
    # sim/run_matvec.sh stage 5/6/7 baselines.  --stop-delta is raised because
    # the trace loader spends one delta per line, which trips ghdl's 5000
    # default and looks exactly like a zero-delay loop.  It is not one.
    sim:tb_matvec_core)      echo "-gTRACE=../tr.txt -gRI=4 -gSTALL=0 --stop-time=50ms --stop-delta=1000000" ;;
    sim:tb_matvec_int4)      echo "-gTRACE=../tr.txt -gRI=4 -gSTALL=3 --stop-time=30ms --stop-delta=1000000" ;;
    sim:tb_matvec_axi)       echo "-gTRACE=../tr.txt -gRI=4 -gSTALL=3 --stop-time=50ms --stop-delta=1000000" ;;
    # The FK33 geometry.  Its trace is a BARE name, not ../tr.txt, so it is
    # generated into the test's own workdir by the vector machinery below
    # rather than symlinked from sim/ -- see the mv_fk33_tr.txt row.  Every
    # generic defaults to the FK33 configuration, so none is passed here; the
    # trace's own GEOM line is asserted against them.
    sim:tb_matvec_fk33)      echo "--stop-time=50ms --stop-delta=1000000" ;;
    # The same trace and the same geometry, driven through the descriptor
    # control plane, plus 21 descriptor mutations in one run.  Every generic
    # defaults to the FK33 configuration; -gDUAL=true additionally runs the
    # whole AXI side on a faster clock through axi_rd_port's CDC and is a
    # separate manual run rather than a second gate row, because regress keys
    # a test by name and cannot run one testbench twice.
    sim:tb_matvec_fk33_desc) echo "--stop-time=200ms --stop-delta=1000000" ;;
    # sim/run_matvec.sh stages 4 and 4b, first row of each sweep.
    sim:tb_act_mem)          echo "-gELEMS=544 -gBLK=32 -gLANES=4 --stop-time=500ms" ;;
    sim:tb_axi_rd_port)      echo "-gMAXOUT=2 -gDEPTH=64 -gSTALL=3 --stop-time=200ms" ;;
    # sim/run_seq_*.sh named configuration: the one the real system runs
    # closest to (memory fast, units slow, so the prefetch gets far ahead).
    sim:tb_seq_desc_fetch)   echo "-gURAM_LAT=1 -gJOB_LAT=120 -gLAT_SKEW=11 -gSTRICT=true --stop-time=400ms" ;;
    sim:tb_seq_opdec)        echo "-gURAM_LAT=1 -gJOB_LAT=40 -gLAT_SKEW=7 -gSTRICT=true --stop-time=400ms" ;;
    sim:tb_seq_region_lock)  echo "-gWR_N=6 -gWR_GAP=0 -gJOB_LAT=12 -gSTRICT=true --stop-time=400ms" ;;
    # sim/run_seq_vec_res.sh: ACK_LAG=0 is NOT the weak case, see that header.
    sim:tb_seq_vec_res)      echo "-gNCASE=64 -gACK_LAG=0 --stop-time=900ms" ;;
    # sim/run_seq_vec_seam.sh row 1: the D-ctrl/D-vec seam with five real units
    # in the loop, at the skew that gets the descriptor prefetch furthest ahead.
    sim:tb_seq_vec_seam)     echo "-gURAM_LAT=1 -gJOB_LAT=40 -gLAT_SKEW=7 -gSTRICT=true --stop-time=900ms" ;;
    *)                   echo "--stop-time=900ms" ;;
  esac
}

# Generator arguments for vector files that are not committed.  Lifted from
# the mutate_*.sh / run_*.sh that owns each one, and chosen to match the
# testbench's own generic defaults -- the vector file carries a shape header
# that the testbench asserts against, so a mismatch is loud, not silent.
# A vector with no row here falls back to the generator's own defaults.
tb_vector_args() {   # <vector-file-name> -> generator argv after the filename
  case "$1" in
    # ref/attn_block_vec.c, subsystem C's BLOCK-level oracle.  The argument
    # order is HEAD_DIM N_QH N_KVH KV_BLOCK N_ROT cur_pos ctx_len seed and it
    # must match sim/tb_attn_block.vhd's generic defaults; the vector file
    # carries a shape header the bench asserts against them, so a mismatch here
    # is loud rather than a wrong answer.  N_KVH stays 2 because
    # ref/attn_block_vec.c refuses fewer, NOT because attn_emit cannot take it:
    # OI-2, the bound violation at rtl/attn_emit.vhd:400 that made NGRP = 1
    # abort, is FIXED, and sim/tb_attn_emit.vhd now runs a second instance at
    # NGRP = 1 on every gate run.
    attn_block_vec.txt)     echo "16 4 2 4 8 3 4 0" ;;
    # ref/attn_kv_axi_vec.c, the KV-cache-in-HBM oracle for rtl/attn_kv_axi.vhd.
    # Argument order is HEAD_DIM KV_BLOCK N_KVH LAYERS MAXCTX LAYER CUR_POS SEED
    # and it must match sim/tb_attn_kv_axi.vhd's generic defaults; the vector
    # file carries a shape header the harness asserts against them, so a
    # mismatch here is loud rather than a wrong answer.  HEAD_DIM 256 /
    # KV_BLOCK 32 is the BUILD geometry and is not reduced for the bench: the
    # 272-byte record is what makes REC_B indivisible by the 32-byte beat, and
    # that indivisibility is the 16-byte record phase the unit exists to handle.
    attn_kv_axi_vec.txt)    echo "256 32 2 2 32 1 20 20260828" ;;
    # ref/attn_block_seq_vec.c, the MULTI-TOKEN oracle for the attn_block <->
    # attn_kv_axi seam.  Argument order is HEAD_DIM N_QH N_KVH KV_BLOCK N_ROT
    # NTOK SEED and it must match sim/tb_attn_kv_seam.vhd's generic defaults;
    # the vector file carries a shape header the bench asserts against them.
    # KV_BLOCK 16 is the SMALLEST legal value: rtl/attn_kv_axi.vhd's record is
    # a byte layout on a 16-byte granule, so KV_BLOCK*CM_W/8 must be a
    # multiple of 16, and HEAD_DIM 64 then gives REC_B = 80, which is not a
    # multiple of the 32-byte beat -- which is the whole point, because the
    # 16-byte record phase is what the realignment mux exists for.
    #
    # The SEED is 2 and it was CHOSEN, not defaulted.  v_ref is a per-sequence
    # minimum, and at most seeds every token's own record already carries the
    # sequence minimum, so resetting the fold per TOKEN changes nothing -- the
    # oracle itself is byte-identical under that mutation at seeds 1, 3, 7, 11,
    # 42, 123, 999, 20260828 and 31337.  At seed 2 it moves 358 of the vector
    # file's 5,328 integers, so the mutation is observable and the bench's
    # v_ref property has teeth.  Do not "tidy" this back to a round number.
    attn_block_seq_vec.txt) echo "64 4 2 16 16 4 2" ;;
    attn_emit_vec.txt)      echo "40 2 48" ;;      # sim/mutate_attn_emit.sh
    attn_gate_vec.txt)      echo "35 64" ;;        # sim/mutate_attn_gate.sh
    attn_recip_vec.txt)     echo "24 12" ;;        # sim/mutate_attn_recip.sh
    attn_softmax_vec.txt)   echo "44 24" ;;        # sim/mutate_attn_softmax.sh
    attn_twiddle_vec.txt)   echo "24 32" ;;        # sim/mutate_attn_twiddle.sh
    seq_vec_res_vec.txt)    echo "64 12345" ;;     # sim/run_seq_vec_res.sh
    # n nres seed.  n and nres are asserted against the testbench's generics by
    # the vector file's shape header, so a mismatch here is loud, not silent.
    seq_vec_chain_vec.txt)  echo "250 8 20260827" ;; # sim/run_seq_vec_seam.sh
    gdn_emit_chain_vec.txt) echo "3 24 128" ;;     # sim/run_gdn_emit_chain.sh
    # ref/l2norm_rs_vec.c, subsystem B 2.1.3's fixed-point reference.  Args are
    # N and the LCG seed; the vector file carries an N header that
    # sim/tb_l2norm_rs.vhd asserts against its own generic, so a mismatch is
    # loud.  Pinned here rather than left to the generator's defaults so that
    # committing sim/l2norm_rs_vec.txt later cannot silently freeze a stale
    # golden: with a row present regress.sh regenerates unconditionally.
    l2norm_rs_vec.txt)      echo "128 20260828" ;;
    # sim/tb_matvec_fk33.  ref/mv_fk33_tr reads a REAL packed tensor and dumps
    # the sub-region bytes its 27 AXI masters will read, plus the expected
    # result from ref/matvec_int4.c.  The file is one of the 250 .mv4i written
    # for the FK33 by tools/pack_int4.py; the model set is NOT in git, so this
    # is a genuine external prerequisite and a missing file is reported as
    # VECTORGEN_RUN_FAILED with the path in the message rather than as a wrong
    # answer.  Override the path with MV4I_FK33_FILE.  n_rows=100 is chosen,
    # not arbitrary: 100 = 2*48 + 4, so it spans THREE tiles -- 384 beats per
    # sub-region, which at the bench's MAXB=16 is 24 bursts -- and the last
    # tile carries 44 pad rows.  (CORRECTED 2026-08-28: this comment used to
    # say "3 bursts of 128 beats at MAXB=128".  The 4 KB rule allows 128 at
    # 256 bits but the FK33's HBM slave is AXI3, whose ARLEN is four bits, so
    # 16 is the hard cap.  See 809ada7 and section 10 of
    # docs/debugging/2026-08-28_fk33-subsystem-a-sim.md.)  n_cols is NOT
    # subsettable -- the block stride in a sub-region is the file's own nb --
    # so the whole K is used.
    mv_fk33_tr.txt)         echo "${MV4I_FK33_FILE:-/mnt/storage/llama-models/qwen35-9b-mv4i/blk.11.attn_k.weight.mv4i} 100 5" ;;
    *) : ;;
  esac
}

# Success markers for testbenches whose pass is stated as a counter rather
# than as the word PASS.  Where a run_*.sh already greps for a phrase to
# decide OK, that same phrase is used here, so the two agree by construction.
tb_pass_marker() {
  case "$1" in
    sim:tb_axi_rd_port)  echo '0 bad beats' ;;                                   # sim/run_matvec.sh 4b
    # Two geometries in one run (ROWS_IF=4/AXI_DW=128 and ROWS_IF=48/AXI_DW=256,
    # spec 6.5a), so the verdict is one counter over both.
    sim:tb_weight_streamer) echo '0 reassembly errors across both geometries' ;;
    # PASS_RE would already match this bench's 'bit-exact', but an explicit
    # marker is what makes a TRUNCATED run a NOVERDICT instead of a pass: the
    # phrase is only printed after the row count, y_exp and sat_event have all
    # been checked, so nothing earlier in the log can produce it.
    sim:tb_matvec_fk33)  echo 'bit-exact with ref/matvec_int4.c from the real .mv4i bytes up' ;;
    # Printed only after all 22 cases have been judged and the failure count
    # asserted to zero, so a truncated run is a NOVERDICT rather than a pass.
    sim:tb_matvec_fk33_desc) echo 'every checked mutation is refused' ;;
    sim:tb_hbm_tg)       echo 'recovers a known bandwidth at every port count' ;;
    # The tb/ suite states its verdict as "PASS:<unit>" almost everywhere and
    # \bPASS\b already matches that.  These two phrase it differently.
    tb:tb_bfp_stress)    echo 'ALL BFP-PACK STRESS CASES PASSED' ;;
    tb:tb_divider_rs)    echo 'ALL TESTS PASS' ;;
    sim:tb_l2norm_rs)    echo 'within tolerance of x/\|\|x\|\| on every case' ;;
    sim:tb_rope_pair)    echo "is exactly ADJACENT's rotation" ;;
    sim:tb_exp_cone)     echo 'VALUES AGREE' ;;
    # The audit bench asserts at severity FAILURE (see its line 203 note) but
    # states its result as three counters.  All three must be zero/complete.
    sim:tb_b_audit_ser_handshake)
      echo 'more than DIM elements: 0.*FEWER than DIM: 0' ;;
    *) : ;;
  esac
}

# Failure-shaped lines that a testbench PROVOKES ON PURPOSE as a negative
# control.  These are filtered out before the failure check, per testbench, by
# exact phrase, with the reason.  Deliberately NOT generic: a blanket "ignore
# assertion errors" would defeat clause 6 entirely.  A testbench that ends by
# proving its DUT's own guard fires is a good testbench, and it must still be
# able to report PASS.
tb_expected_noise() {
  case "$1" in
    # sim/tb_attn_recip.vhd line 39: "nothing in the main loop exercises the
    # s = 0 trap", so the bench drives s = 0 deliberately at the end, and its
    # own PASS line says "the s = 0 trap fires and terminates".  The RTL guard
    # at rtl/attn_recip.vhd:282 is severity ERROR, so ghdl prints an assertion
    # error and still exits 0.
    sim:tb_attn_recip) echo 'attn_recip: s = 0 offered' ;;
    *) : ;;
  esac
}

# Testbenches that are genuinely NOT self-checking.  Each still runs -- a
# crash, an assertion or a hang is still caught -- but a clean exit is not
# evidence of correctness, so they are reported as NOCHECK rather than being
# counted as passes.  This list is short and every entry states why.
tb_nocheck_reason() {
  case "$1" in
    sim:tb_attn_beh)        echo 'observation only: prints per-position xb_exp then BEH_DONE. It is the behavioral half of the xsim netlist compare (sim/run_attn_cmp.sh), not a self-checking bench' ;;
    sim:tb_swchain_beh)     echo 'observation only: prints one o_exp/checksum line. Its header says "GHDL-only sanity bench"; the real check is tb_swchain_cmp under xsim' ;;
    sim:tb_rms_sweep)       echo 'observation only: sweeps xe and prints oe/o0, then SWEEP_DONE. Has no pass criterion; it exists to compare against a recorded hardware reading' ;;
    sim:tb_gdn_conv_cycles) echo 'measurement only: emits a CSV cycle table (CYC,...) and "done". There is no expected value to check it against' ;;
    # tb/tb_engine_dbg has ZERO assertions and zero severity error/failure: it
    # is a register-dump debug harness that reports at severity note and then
    # calls finish, so it exits 0 no matter how broken the design is.  Exactly
    # the hazard clause 6 exists for.
    tb:tb_engine_dbg) echo 'debug register dump: zero assertions, every report at severity note, exits 0 unconditionally. Running it proves it elaborates and terminates, nothing more' ;;
    *) : ;;
  esac
}

# ===========================================================================
# 3. VERDICT.  See point 6 of the header.
# ===========================================================================
# A failure marker anywhere wins over a success marker anywhere.
FAIL_RE='\(assertion (error|failure)\)|\(report (error|failure)\)|:error:|MISMATCH|\bFAIL\b|FAILED|cannot open|error: |simulation failed|DIVERGES|IS NOT|IS WRONG|OUT OF TOLERANCE'
# A success marker must be present or the run is NOVERDICT, never PASS.
# A bare "OK" is deliberately NOT a marker: it is too easy to hit in prose.
PASS_RE='\bPASS\b|\bALL OK\b|all green|0 mismatches|no mismatch|matches ref|bit-exact|bit-identical|within tolerance'

run_one() {   # run_one <suite:name> <top-entity> <vectors-csv> <files...>
  local key="$1" top="$2" vecs="$3"; shift 3
  [ "$vecs" = "-" ] && vecs=""
  local tb="${key#*:}" suite="${key%%:*}"
  # The scratch directory is keyed by the SUITE-QUALIFIED name: tb/tb_rope and
  # sim/tb_rope_ps both elaborate an entity called tb_rope, and a bare-name
  # directory would have the two suites sharing a GHDL library.
  local dir="$SCRATCH/${suite}_${tb}" log="$SCRATCH/${suite}_${tb}/log"
  local run="$dir/run" work="$dir/work"
  local t0; t0=$(date +%s)
  mkdir -p "$run" "$work"
  # Both suites reach golden data as ../mem/... from the run directory.  The
  # tb/ suite uses ONLY that form; sim/ mixes it with bare vector names.
  ln -sfn "$REPO/mem" "$dir/mem"

  # Everything a testbench might open by bare name.  Committed vectors and
  # golden fixtures live in sim/; symlinking keeps them read-only in practice
  # and means nothing is ever written back into the repo.
  local f
  # `.hex` was added 2026-08-29 for sim/llama_top_w_b4_pool.hex, the committed
  # real Qwen3.5-9B weight image sim/tb_llama_top_real.vhd opens by bare name.
  # Without it that row fails with "cannot open the weight image", which reads
  # like a missing file and is a missing GLOB.
  for f in "$SIM"/*.txt "$SIM"/*.dat "$SIM"/*.csv "$SIM"/*.mem "$SIM"/*.bin \
           "$SIM"/*.hex; do
    [ -e "$f" ] && ln -sfn "$f" "$run/$(basename "$f")"
  done
  # tb_matvec_* address their trace one level up, as ../tr.txt.
  for f in "$SIM"/tr.txt "$SIM"/arith_vectors.txt; do
    [ -e "$f" ] && ln -sfn "$f" "$dir/$(basename "$f")"
  done

  # NOTE: a subshell, so that an `exit` on a build failure inside it cannot
  # skip the judging code below.  An earlier revision used a brace group and
  # six tests silently produced no result at all.
  (
    echo "### $key  (top entity: $top)"
    # --- vectors -------------------------------------------------------
    local v stem gen args
    for v in $vecs; do
      stem="${v%.txt}"
      gen="$REPO/ref/$stem.c"
      args="$(tb_vector_args "$v")"
      if [ ! -r "$gen" ]; then
        # No generator.  If sim/ committed one, the symlink above already
        # provides it; otherwise the run will fail loudly on "cannot open".
        continue
      fi
      if [ -e "$SIM/$v" ] && [ -z "$args" ]; then
        continue          # committed, and no curated shape to re-derive
      fi
      if ! cc -O2 -w -I "$REPO/ref" -o "$dir/gen_$stem" "$gen" -lm 2>&1; then
        echo "VECTORGEN_BUILD_FAILED $gen"; exit 90
      fi
      rm -f "$run/$v"
      # shellcheck disable=SC2086
      if ! ( cd "$run" && "$dir/gen_$stem" "$v" $args ) >/dev/null 2>&1; then
        echo "VECTORGEN_RUN_FAILED $gen"; exit 90
      fi
    done

    # --- analysis ------------------------------------------------------
    for f in "$@"; do
      if ! "$GHDL" -a $STD $RELAX --workdir="$work" "$REPO/$f" 2>&1; then
        echo "ANALYSIS_FAILED $f"; exit 91
      fi
    done

    # --- run.  mcode: -e emits nothing, so -r is called directly. -------
    # shellcheck disable=SC2046,SC2086
    ( cd "$run" && timeout -k 5 "$TIMEOUT" \
        "$GHDL" -r $STD $RELAX --workdir="$work" "$top" \
        $(tb_args "$key") --max-stack-alloc=0 2>&1 )
    echo "GHDL_EXIT=$?"
  ) > "$log" 2>&1

  # ---- judge --------------------------------------------------------
  local rc body marker nocheck
  rc=$(grep -oE '^GHDL_EXIT=[0-9]+' "$log" | tail -1 | cut -d= -f2)
  body=$(grep -avE '^(### |GHDL_EXIT=)' "$log")

  # Elapsed seconds are part of the result, not decoration: --quick's exclusion
  # list is only honest if it was chosen from measurement, and the slow test in
  # a 20 minute run is the first thing anyone wants to know.
  verdict() {
    printf '%s\t%s\t%s\t%s\n' "$key" "$1" "$(( $(date +%s) - t0 ))" "$2" \
      > "$SCRATCH/res.${suite}_${tb}"
  }

  if grep -q '^VECTORGEN' "$log"; then
    verdict ERROR "reference vector generator failed: $(grep -m1 '^VECTORGEN' "$log")"; return
  fi
  if grep -q '^ANALYSIS_FAILED' "$log"; then
    verdict ERROR "ghdl -a failed on $(grep -m1 '^ANALYSIS_FAILED' "$log" | cut -d' ' -f2): $(printf '%s' "$body" | grep -aiE 'error' | head -1 | cut -c1-120)"; return
  fi
  [ -n "${rc:-}" ] || rc=1
  if [ "$rc" = "124" ] || [ "$rc" = "137" ]; then
    verdict TIMEOUT "no result within ${TIMEOUT}s -- unguarded clock or deadlock, NOT the same thing as a failure"; return
  fi
  if [ -z "$(printf '%s' "$body" | tr -d '[:space:]')" ]; then
    verdict FAIL "produced NO output at all (exit $rc)"; return
  fi
  local noise; noise="$(tb_expected_noise "$key")"
  if [ -n "$noise" ]; then
    body="$(printf '%s' "$body" | grep -avE "$noise")"
  fi

  # A line that REPORTS A FAILURE COUNT OF ZERO is not a failure.  tb/
  # tb_divider_rs ends a clean run with "DIVIDER TB RESULT: PASS=608 FAIL=0",
  # and a bare \bFAIL\b match calls that a failed test -- which is exactly the
  # inverse of the mistake clause 6 guards against, and just as wrong.  Only
  # ZERO-valued counters are neutralised: "FAIL=3" still matches, and the
  # neutralisation is applied to the FAILURE scan only, never to the success
  # scan, so it cannot manufacture a pass.
  local scan
  scan="$(printf '%s' "$body" | sed -E 's/\b(FAIL|FAILURE|FAILURES|MISMATCH|MISMATCHES|ERROR|ERRORS)[[:space:]]*[=:][[:space:]]*0+\b//g')"
  if [ "$rc" != "0" ]; then
    verdict FAIL "exit $rc: $(printf '%s' "$scan" | grep -aE "$FAIL_RE" | head -1 | cut -c1-160)"; return
  fi
  if printf '%s' "$scan" | grep -aqE "$FAIL_RE"; then
    verdict FAIL "$(printf '%s' "$scan" | grep -aE "$FAIL_RE" | head -1 | cut -c1-160)"; return
  fi

  marker="$(tb_pass_marker "$key")"
  if [ -n "$marker" ]; then
    if printf '%s' "$body" | grep -aqE "$marker"; then
      verdict PASS "$(printf '%s' "$body" | grep -aE "$marker" | head -1 | cut -c1-140)"; return
    fi
    verdict NOVERDICT "ran clean but its declared success marker ('$marker') never appeared"; return
  fi

  nocheck="$(tb_nocheck_reason "$key")"
  if [ -n "$nocheck" ]; then
    verdict NOCHECK "$nocheck"; return
  fi

  if printf '%s' "$body" | grep -aqiE "$PASS_RE"; then
    verdict PASS "$(printf '%s' "$body" | grep -aiE "$PASS_RE" | head -1 | cut -c1-140)"; return
  fi
  verdict NOVERDICT "exit 0 and no failure marker, but NO success marker either -- that is not evidence of a pass"
}

# ===========================================================================
# 4. DRIVE
# ===========================================================================
selected=()
skipped_names=(); skipped_reasons=()
while IFS=$'\t' read -r name suite status reason flist top vecs; do
  key="$suite:$name"
  [[ " $SUITES " == *" $suite "* ]] || continue
  [ -n "$ONLY" ] && [[ "$name" != *"$ONLY"* ]] && continue
  if [ "$status" = "SKIP" ]; then
    skipped_names+=("$key"); skipped_reasons+=("$reason"); continue
  fi
  if [ "$QUICK" = 1 ] && [[ "$SLOW_SET" == *" $key "* ]]; then
    skipped_names+=("$key")
    skipped_reasons+=("--quick: slow seam/top-level test, deliberately excluded -- run without --quick")
    continue
  fi
  # Keep the '-' placeholder: with IFS=tab an EMPTY field collapses and every
  # field after it shifts, which is how the analysis file list once ended up in
  # the vectors slot and every test reported "cannot find entity".
  selected+=("$key"$'\t'"$top"$'\t'"$vecs"$'\t'"$flist")
done < "$PLAN"

if [ "$LIST_ONLY" = 1 ]; then
  echo "== plan =="
  for e in "${selected[@]}"; do
    IFS=$'\t' read -r n t v fl <<< "$e"
    printf 'RUN  %-34s entity=%-24s %2d files  vectors=%s\n' \
           "$n" "$t" "$(echo "$fl" | wc -w)" "$([ "$v" = "-" ] && echo none || echo "$v")"
  done
  for i in "${!skipped_names[@]}"; do
    printf 'SKIP %-34s %s\n' "${skipped_names[$i]}" "${skipped_reasons[$i]}"
  done
  exit 0
fi

if [ "$COVERAGE_ONLY" = 0 ]; then
  echo "================================================================================"
  echo " llama.vhdl regression -- $( [ "$QUICK" = 1 ] && echo 'QUICK subset (NOT coverage)' || echo 'FULL run' ), ${JOBS} job(s), ${TIMEOUT}s per test"
  echo " $(date '+%Y-%m-%d %H:%M:%S')   ghdl: $($GHDL --version | head -1)"
  echo "================================================================================"

  for e in "${selected[@]}"; do
    IFS=$'\t' read -r n t v fl <<< "$e"
    while [ "$(jobs -rp | wc -l)" -ge "$JOBS" ]; do sleep 0.4; done
    # shellcheck disable=SC2086
    run_one "$n" "$t" "$v" $fl &
  done
  wait

  npass=0; nfail=0; ntime=0; nerr=0; nnov=0; nnoc=0
  failed_list=()
  # Per-suite tallies, so a failure in the older generation is never hidden
  # inside a headline number dominated by the current one.
  declare -A sp sf st se sv sn
  for q in $SUITES; do sp[$q]=0; sf[$q]=0; st[$q]=0; se[$q]=0; sv[$q]=0; sn[$q]=0; done
  echo
  for q in $SUITES; do
    printf -- '-- suite %s ---------------------------------------------------------------\n' "$q"
    for e in "${selected[@]}"; do
      k="${e%%$'\t'*}"
      [ "${k%%:*}" = "$q" ] || continue
      rf="$SCRATCH/res.${k%%:*}_${k#*:}"
      if [ -r "$rf" ]; then
        IFS=$'\t' read -r rn rv rs rd < "$rf"
      else
        rv="FAIL"; rs="?"; rd="the runner produced no result file for this test"
      fi
      printf '%-10s %-34s %5ss  %s\n' "$rv" "$k" "$rs" "$rd"
      case "$rv" in
        PASS)      npass=$((npass+1)); sp[$q]=$(( ${sp[$q]} + 1 )) ;;
        NOCHECK)   nnoc=$((nnoc+1));   sn[$q]=$(( ${sn[$q]} + 1 )) ;;
        TIMEOUT)   ntime=$((ntime+1)); st[$q]=$(( ${st[$q]} + 1 )); failed_list+=("$k (timeout)") ;;
        ERROR)     nerr=$((nerr+1));   se[$q]=$(( ${se[$q]} + 1 )); failed_list+=("$k (build error)") ;;
        NOVERDICT) nnov=$((nnov+1));   sv[$q]=$(( ${sv[$q]} + 1 )); failed_list+=("$k (no verdict)") ;;
        *)         nfail=$((nfail+1)); sf[$q]=$(( ${sf[$q]} + 1 )); failed_list+=("$k") ;;
      esac
    done
    echo
  done

  echo
  echo "-- SKIPPED (listed, never dropped silently) ------------------------------------"
  if [ "${#skipped_names[@]}" = 0 ]; then
    echo "(none)"
  else
    for i in "${!skipped_names[@]}"; do
      printf 'SKIPPED    %-34s %s\n' "${skipped_names[$i]}" "${skipped_reasons[$i]}"
    done
  fi
fi

# ===========================================================================
# 5. COVERAGE: RTL with no testbench anywhere
# ===========================================================================
echo
echo "-- RTL COVERAGE ----------------------------------------------------------------"
echo "   (transitive closure from every testbench in BOTH suites)"
tot=$(awk '/^TOTAL_RTL/{print $2}' "$COVER")
unc=$(awk '/^UNCOVERED/{print $2}' "$COVER")
bys=$(awk '/^BYSIM/{print $2}' "$COVER")
byt=$(awk '/^BYTB/{print $2}' "$COVER")
byb=$(awk '/^BYBOTH/{print $2}' "$COVER")
printf '   %d files in rtl/: %d reached by the sim/ suite, %d by tb/, %d by both.\n' \
       "$tot" "$bys" "$byt" "$byb"
echo
echo "   RTL FILES REACHED BY NO TESTBENCH IN EITHER SUITE:"
if grep -q '^NOTB ' "$COVER"; then
  awk '/^NOTB /{print "     " $2}' "$COVER"
else
  echo "     (none)"
fi
echo "   $unc of $tot."
if grep -q '^TBONLY' "$COVER"; then
  echo
  echo "   reached ONLY by the tb/ suite (run it with --suite tb, or leave the"
  echo "   default which runs both):"
  awk '/^TBONLY /{printf "     %-32s %s\n", $2, $3}' "$COVER"
fi

[ "$COVERAGE_ONLY" = 1 ] && exit 0

# ---- the baseline floor, full unfiltered runs only ------------------------
baseline_note=""
baseline_drop=0
if [ "$QUICK" = 0 ] && [ -z "$ONLY" ] && [ "$(echo $SUITES)" = "sim tb" ]; then
  if [ "$npass" -lt "$BASELINE_PASS" ]; then
    baseline_drop=1
    baseline_note="BASELINE DROP: $npass passing, expected at least $BASELINE_PASS"
  elif [ "$npass" -gt "$BASELINE_PASS" ]; then
    baseline_note="baseline: $npass passing, above the recorded floor of $BASELINE_PASS -- raise BASELINE_PASS in this script"
  else
    baseline_note="baseline: $npass passing, matches the recorded floor of $BASELINE_PASS"
  fi
fi

echo
echo "================================================================================"
for q in $SUITES; do
  printf ' suite %-4s  PASS %d   FAIL %d   NOVERDICT %d   TIMEOUT %d   BUILD-ERROR %d   NOCHECK %d\n' \
    "$q" "${sp[$q]}" "${sf[$q]}" "${sv[$q]}" "${st[$q]}" "${se[$q]}" "${sn[$q]}"
done
printf ' OVERALL     PASS %d   FAIL %d   NOVERDICT %d   TIMEOUT %d   BUILD-ERROR %d   NOCHECK %d   SKIPPED %d\n' \
  "$npass" "$nfail" "$nnov" "$ntime" "$nerr" "$nnoc" "${#skipped_names[@]}"
echo "================================================================================"
if [ -n "$baseline_note" ]; then
  echo " $baseline_note"
  if [ "$baseline_drop" = 1 ]; then
    echo "   Nothing went red.  Something went MISSING: a testbench was deleted,"
    echo "   renamed out of the tb_*.vhd glob, or has become unresolvable and is"
    echo "   now being reported SKIPPED.  Check the SKIPPED list above against"
    echo "   git, then either restore the test or lower BASELINE_PASS on purpose."
  fi
  echo "================================================================================"
fi
if [ "${#failed_list[@]}" -gt 0 ] || [ "$baseline_drop" = 1 ]; then
  if [ "${#failed_list[@]}" -gt 0 ]; then
    echo " NOT GREEN:"
    for f in "${failed_list[@]}"; do echo "   - $f"; done
    echo
  fi
  echo " REGRESSION: FAIL"
  exit 1
fi

echo " REGRESSION: PASS"
exit 0
