/* GENERATED by hw/fk33/gen_fk33_regs.py from hw/fk33/gen_pcieep.py.
 *
 * DO NOT EDIT.  gen_pcieep.py configures the block design, so it decides what
 * the hardware does; this file only reports it.  An edit here changes what the
 * host believes and not what the card implements, which is the one failure
 * mode this header exists to prevent.
 *
 * Verify with:  python3 hw/fk33/gen_fk33_regs.py --check
 */
#ifndef FK33_REGS_H
#define FK33_REGS_H

#include <stdint.h>

/* ---- AXI-Lite BAR, 128 KB, /dev/xdma0_user ----------------------------- */

/* Read-only identity, axi_gpio with both channels all-inputs.  A correct read
 * is not something a merely-loaded driver can fake: 0xFFFFFFFF means the BAR
 * is mapped with nothing answering, and 0x00000000 means the fabric is in
 * reset, so both of the plausible wrong answers are distinguishable. */
#define FK33_ID_BASE        0x0000A000u
#define FK33_ID_MAGIC_OFF   (FK33_ID_BASE + 0x0u)
#define FK33_ID_BUILD_OFF   (FK33_ID_BASE + 0x8u)
#define FK33_ID_MAGIC       0x464B3333u   /* "FK33" in ASCII */
#define FK33_ID_BUILD       0x20260827u   /* yyyymmdd */

/* Read/write scratch BRAM.  The only thing in the design that proves MMIO
 * WRITES land without driving a real board pin. */
#define FK33_SCRATCH_BASE   0x00010000u
#define FK33_SCRATCH_SIZE   0x2000u

/* ---- DMA master space, /dev/xdma0_h2c_0 and _c2h_0 --------------------- */
/* The file offset IS the AXI address, which is the whole reason XDMA was
 * chosen over QDMA. */

/* Deliberately ABOVE the 8 GB of HBM, so a DMA fault can never be confused
 * with an HBM fault and an off-by-one in a host offset lands on nothing
 * rather than silently in memory. */
#define FK33_DMABRAM_BASE   0x200000000ull
#define FK33_DMABRAM_SIZE   0x10000ull
#define FK33_HBM_TOP        0x200000000ull

/* ---- Thermal protection ------------------------------------------------ */
/* Five status words plus one control word, produced by rtl/fk33_thermal.vhd on
 * the free-running aux clock and resynchronised into the AXI-Lite clock domain
 * by the module itself.  The SAME five words are also readable over the
 * jtag_aux master with the PCIe link DOWN, at a different address space -- so a
 * card that has halted and dropped off the bus can still be asked why.
 *
 * THERM_STATUS bit 31 is a constant 1.  A bitstream WITHOUT the thermal guard
 * reads 0 there, so "is this card protected" is one read and not a guess. */
#define FK33_THERM_BASE     0x0000B000u
#define FK33_THERM_STATUS   (FK33_THERM_BASE  + 0x0u)
#define FK33_THERM_TEMPS    (FK33_THERM_BASE  + 0x8u)
#define FK33_THERMP_BASE    0x0000C000u
#define FK33_THERM_PEAK     (FK33_THERMP_BASE + 0x0u)
#define FK33_THERM_TRIP     (FK33_THERMP_BASE + 0x8u)
#define FK33_THERMC_BASE    0x0000D000u
#define FK33_THERM_CTL      (FK33_THERMC_BASE + 0x0u)   /* write */
#define FK33_THERM_CANARY   (FK33_THERMC_BASE + 0x8u)

/* THERM_CTL[31:16] must be the key or the write does nothing, and both clears
 * are EDGE triggered: write the key with the bit set, then write 0. */
#define FK33_THERM_KEY      0xC1EAu
#define FK33_THERM_CLR_TRIP 0x1u
#define FK33_THERM_CLR_PEAK 0x2u

/* THERM_STATUS fields */
#define FK33_THERM_HALTED   (1u << 0)
#define FK33_THERM_WARN     (1u << 1)
#define FK33_THERM_ARMED    (1u << 2)
#define FK33_THERM_DIE_OK   (1u << 3)
#define FK33_THERM_HBM_OK   (1u << 4)
#define FK33_THERM_DIE_HOT  (1u << 5)
#define FK33_THERM_HBM_HOT  (1u << 6)
#define FK33_THERM_TRIPPED  (1u << 7)
#define FK33_THERM_PRESENT  (1u << 31)
#define FK33_THERM_CAUSE(v)      (((v) >> 8) & 0xFu)
#define FK33_THERM_TRIP_CAUSE(v) (((v) >> 12) & 0xFu)
#define FK33_THERM_TRIP_COUNT(v) (((v) >> 16) & 0xFFu)

/* cause codes */
#define FK33_CAUSE_NONE      0u
#define FK33_CAUSE_DIE_OT    1u   /* SYSMON's armed over-temperature alarm */
#define FK33_CAUSE_DIE_ALARM 2u   /* SYSMON user temperature alarm */
#define FK33_CAUSE_DIE_OVER  3u
#define FK33_CAUSE_DIE_STALE 4u   /* not live, or an implausible reading */
#define FK33_CAUSE_HBM_CAT   5u   /* a stack asserted CATTRIP */
#define FK33_CAUSE_HBM_OVER  6u
#define FK33_CAUSE_HBM_STALE 7u

/* The thresholds the bitstream enforces, in degrees C.  The HBM ones are in
 * RAW 7-bit stack-code units: the code-to-Celsius mapping of
 * DRAM_x_STAT_TEMP is NOT calibrated on this card. */
#define FK33_THERM_DIE_WARN    80
#define FK33_THERM_DIE_HALT    90
#define FK33_THERM_DIE_RESUME  75
#define FK33_THERM_HBM_WARN    75
#define FK33_THERM_HBM_HALT    85
#define FK33_THERM_HBM_RESUME  70

/* ---- PCIe identity ------------------------------------------------------ */
/* Already carried by dma_ip_drivers, so new_id should not be needed. */
#define FK33_PCI_VENDOR     0x10EEu
#define FK33_PCI_DEVICE     0x9034u

#endif /* FK33_REGS_H */
