/* GENERATED by hw/fk33/gen_fk33_regs.py from hw/fk33/gen_pcieep.py.
 *
 * DO NOT EDIT.  gen_pcieep.py configures the block design, so it decides what
 * the hardware does; this file only reports it.  An edit here changes what the
 * host believes and not what the card implements, which is the one failure
 * mode this header exists to prevent.
 *
 * Verify with:  python3 hw/fk33/gen_fk33_regs.py --check
 */
#ifndef FK33_REGS_H
#define FK33_REGS_H

#include <stdint.h>

/* ---- AXI-Lite BAR, 128 KB, /dev/xdma0_user ----------------------------- */

/* Read-only identity, axi_gpio with both channels all-inputs.  A correct read
 * is not something a merely-loaded driver can fake: 0xFFFFFFFF means the BAR
 * is mapped with nothing answering, and 0x00000000 means the fabric is in
 * reset, so both of the plausible wrong answers are distinguishable. */
#define FK33_ID_BASE        0x0000A000u
#define FK33_ID_MAGIC_OFF   (FK33_ID_BASE + 0x0u)
#define FK33_ID_BUILD_OFF   (FK33_ID_BASE + 0x8u)
#define FK33_ID_MAGIC       0x464B3333u   /* "FK33" in ASCII */
#define FK33_ID_BUILD       0x20260827u   /* yyyymmdd */

/* Read/write scratch BRAM.  The only thing in the design that proves MMIO
 * WRITES land without driving a real board pin. */
#define FK33_SCRATCH_BASE   0x00010000u
#define FK33_SCRATCH_SIZE   0x2000u

/* ---- DMA master space, /dev/xdma0_h2c_0 and _c2h_0 --------------------- */
/* The file offset IS the AXI address, which is the whole reason XDMA was
 * chosen over QDMA. */

/* Deliberately ABOVE the 8 GB of HBM, so a DMA fault can never be confused
 * with an HBM fault and an off-by-one in a host offset lands on nothing
 * rather than silently in memory. */
#define FK33_DMABRAM_BASE   0x200000000ull
#define FK33_DMABRAM_SIZE   0x10000ull
#define FK33_HBM_TOP        0x200000000ull

/* ---- PCIe identity ------------------------------------------------------ */
/* Already carried by dma_ip_drivers, so new_id should not be needed. */
#define FK33_PCI_VENDOR     0x10EEu
#define FK33_PCI_DEVICE     0x9034u

#endif /* FK33_REGS_H */
