#!/usr/bin/env python3
"""Turn a packed-model manifest.json into the flat index ref/run9b.c reads.

WHY NOT PARSE JSON IN C.  run9b.c is the numeric reference; every line in it
that is not arithmetic is a line that can be wrong without any oracle noticing.
A hand-rolled JSON scanner is exactly that kind of line.  So the structural
read happens here, in the language the packer itself is written in, and the C
consumes a format that `fscanf` cannot misread.

WHAT IT DOES NOT DO.  It does not re-derive anything.  Every field is copied
out of the manifest that tools/pack_model_fk33.py wrote, so this file and a
packed set are incapable of disagreeing about geometry.  The one thing it adds
is the qkv SEGMENT plan, which the manifest already carries as `segments`, and
which run9b needs because subsystem A issues one job per segment.

Index format, one record per line, whitespace separated:

  GEOM <rows_if> <axi_dw> <block> <nports_w> <n_scale_sub> <qkv_segment_pad 0|1>
  MV4I <tensor> <relpath> <M> <K> <w_exp> <out_shift> <nseg> [<segname> <row_start> <n_rows> <logical_row>]*
  BLOB <relpath>
  F32  <name> <offset> <nbytes> <ne0> <ne1>

`<row_start>` is the PADDED start row the hardware windows on and `<n_rows>`
the logical length; `<logical_row>` is where the same segment sits in the
UNPADDED matrix, which is what a comparison against llama.cpp's contiguous
q|k|v tensor has to use.  A tensor with no segment plan gets `nseg=1` and the
single segment `all 0 <M> 0`.

usage: make_index.py PACKED_DIR [-o PACKED_DIR/index.txt]
"""
import argparse, json, os, sys


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("packed_dir")
    ap.add_argument("-o", "--out", default=None)
    a = ap.parse_args()

    mpath = os.path.join(a.packed_dir, "manifest.json")
    with open(mpath) as fp:
        man = json.load(fp)

    g = man["geometry"]
    out = a.out or os.path.join(a.packed_dir, "index.txt")
    n_mv, n_f32, n_blob = 0, 0, 0

    with open(out, "w") as w:
        w.write("# generated by tools/ref9b/make_index.py from %s\n" % mpath)
        w.write("GEOM %d %d %d %d %d %d\n" % (
            g["rows_if"], g["axi_dw"], g["block"], g["nports_w"],
            g["n_scale_sub"], 1 if g.get("qkv_segment_pad") else 0))

        for f in man["files"]:
            if f["kind"] == "mv4i":
                segs = f.get("segments")
                if segs:
                    # `row_start` is the PADDED start (the tile-aligned row the
                    # hardware windows on) and `n_rows` is the LOGICAL length.
                    # `logical_row` is where the same segment sits in the
                    # unpadded matrix, and it is what a comparison against
                    # llama.cpp's contiguous q|k|v tensor has to use.
                    plan = [(int(s["row_start"]), int(s["n_rows"]),
                             int(s["logical_row"]), s["name"]) for s in segs]
                else:
                    plan = [(0, int(f["M"]), 0, "all")]
                w.write("MV4I %s %s %d %d %d %d %d %s\n" % (
                    f["tensor"], f["file"], f["M"], f["K"],
                    f["w_exp"], f["out_shift"], len(plan),
                    " ".join("%s %d %d %d" % (p[3], p[0], p[1], p[2])
                             for p in plan)))
                n_mv += 1
            elif f["kind"] == "f32blob":
                w.write("BLOB %s\n" % f["file"])
                n_blob += 1
                for e in f["entries"]:
                    ne = list(e["shape_ne"]) + [1, 1]
                    w.write("F32 %s %d %d %d %d\n" % (
                        e["name"], e["offset"], e["nbytes"], ne[0], ne[1]))
                    n_f32 += 1
            else:
                print("make_index: unknown kind %r" % f["kind"], file=sys.stderr)
                return 1

    print("wrote %s: %d mv4i, %d blob, %d f32 entries" % (out, n_mv, n_blob, n_f32))
    return 0


if __name__ == "__main__":
    sys.exit(main())
