/* ref/matvec_int4.c -- bit-exact C reference for subsystem A.
 *
 * Implements EXACTLY the numeric contract of
 *   docs/superpowers/specs/2026-08-20-int4-streaming-matvec-design.md
 * sections 6.4 (file layout), 6.5 (bit ordering), 7.4 (numeric contract) and
 * 14.2 (partial-sum mode).  Section numbers below refer to that document.
 *
 * WHY THIS FILE EXISTS.  A spec is checked by reading; a reference is checked
 * by running.  The RTL is validated against this, and this is validated against
 * ggml -- so a defect shared by both models is invisible.  Rev 1 of the spec
 * specified an int48 accumulator in BOTH the RTL and the reference, which would
 * have made them bit-exact to each other AND wrong.  Every width here is
 * therefore int64_t and every bound is asserted at runtime, not assumed.
 *
 * WIDTH DISCIPLINE (spec 9).  partial*scale reaches 2^42 and acc reaches
 * ~2^36.1 at K=17408, both of which overflow 32-bit int.  All intermediates are
 * int64_t.  C's >> on a negative signed value is implementation-defined before
 * C23, so this file NEVER uses >> for arithmetic shifting -- see floor_shr().
 *
 * Build:  cc -O2 -Wall -Wextra -o matvec_int4 matvec_int4.c   (self-test main)
 *         cc -O2 -DMV4I_LIB -c matvec_int4.c                  (link into a host)
 */

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>

/* The s28/s29/s48 width discipline of 7.4 is enforced by assert() alone, so a
 * -DNDEBUG build would silently turn every width check into a no-op and still
 * print all-PASS.  That is precisely the "agrees with itself and is wrong"
 * failure this file exists to prevent. */
#ifdef NDEBUG
#error "matvec_int4.c must be built with assertions enabled (no -DNDEBUG)"
#endif

/* ---------------------------------------------------------------- 7.4 types */

#define MV4I_MAGIC      0x4D563449u   /* "MV4I" */
#define MV4I_BLOCK      32            /* weights per scale block          6.1  */
#define MV4I_HDR_BYTES  4096          /* header is 4 KB                   6.4  */
/* Sub-region offset tables are FIXED-SIZE arrays here.  The old code looped
 * `i < h->nports_w && i < 64`, which silently left offsets 64.. at whatever was
 * on the stack for a file declaring more, and then read through them.  The
 * bound is now a refusal (-8), not a truncation. */
#define MV4I_MAX_SUB    64

enum { MV4I_MODE_BFP = 0, MV4I_MODE_RAW = 1, MV4I_MODE_PARTIAL = 2 };

typedef struct {
    uint32_t magic, M, K, scale_offset, n_scale_sub;
    uint16_t version, flags, rows_if, nports_w, block, axi_dw;
    int32_t  w_exp, out_shift;
    int8_t   codebook[16];
    uint64_t w_sub_offset[MV4I_MAX_SUB];
    uint64_t s_sub_offset[MV4I_MAX_SUB];
} mv4i_hdr;

typedef struct {
    mv4i_hdr        h;
    const uint8_t  *base;   /* whole file image */
    int             nb;     /* ceil(K / BLOCK) */
    /* 6.5a derived geometry, computed once in mv4i_parse so the accessors read
     * as the spec rule rather than as arithmetic.  All redundant with the
     * header fields; none of them is a degree of freedom. */
    int             port_b; /* AXI_DW/8, bytes per beat of one sub-region     */
    int             grp;    /* scale groups per superword                     */
} mv4i_file;

/* ------------------------------------------------- arithmetic primitives 7.4 */

/* The five primitives are GENERATED by tools/gen_arith.py, which emits this
 * header AND rtl/mv4i_arith_pkg.vhd from one description, plus the golden
 * vectors both are checked against.  They are not hand-written twice, because
 * every defect found in this contract so far has been in exactly these
 * functions -- the four rounding sites, the ns sign, msb_pos(0), the
 * no-bias-at-zero case. */
#include "mv4i_arith.h"

#define floor_shr(v, sh)   mv4i_floor_shr((v), (sh))
#define round_shift(v, sh) mv4i_round_shift((v), (sh))
#define sat16(v)           mv4i_sat16((v))
#define msb_pos_u(a)       mv4i_msb_pos_u((a))

static int      g_sat_event;                  /* sticky, see 14.2 */
static uint64_t g_sat_count;

static int32_t sat32(int64_t v)
{
    int ev = 0;
    int32_t r = mv4i_sat32(v, &ev);
    if (ev) { g_sat_event = 1; g_sat_count++; }
    return r;
}

static uint64_t abs64(int64_t v) { return v < 0 ? (uint64_t)(-v) : (uint64_t)v; }

/* ------------------------------------------- 6.5a general geometry helpers */

/* Spec 6.5a (2026-08-28) states the byte layout at ARBITRARY AXI_DW.  Until
 * then 6.5 pinned it only at AXI_DW = 128, where one AXI lane is exactly one
 * row's BLOCK*4 = 128-bit chunk -- the "ROWS_IF = 4 coincidence" 6.5 itself
 * warns is load-bearing.  The FK33's HBM SAXI ports are 256 bits and a lane
 * there spans two rows, so this file used to REFUSE such a file (-7) rather
 * than misread it.  The three rules it now implements are:
 *
 *   TILE WORD.    For (tile t, block b) the word is ROWS_IF*BLOCK*4 bits with
 *                 row r at bits (r+1)*BLOCK*4-1 downto r*BLOCK*4, row 0 at the
 *                 LSB, i.e. at the LOWEST byte offset.
 *   WEIGHT SLICE. NPORTS_W = ROWS_IF*BLOCK*4 / AXI_DW, and weight sub-region p
 *                 carries bit slice p of every tile word, beats t-major then b.
 *   SCALE SLICE.  SW = ROWS_IF*16 bits per group; n_scale_sub is the smallest
 *                 n with n*AXI_DW a whole number of groups, the SUPERWORD is
 *                 n_scale_sub*AXI_DW bits and holds GRP = n*AXI_DW/SW
 *                 consecutive groups, and scale sub-region q carries bit slice
 *                 q of every superword.
 *
 * At ROWS_IF = 4, AXI_DW = 128 slice p IS row p and n_scale_sub is 1, so every
 * expression below reduces to the code it replaced.  That is checked by
 * byte-identity, not asserted.                                              */

static uint32_t u32_gcd(uint32_t a, uint32_t b)
{ while (b) { uint32_t t = a % b; a = b; b = t; } return a; }

/* n_scale_sub = lcm(SW, AXI_DW) / AXI_DW = SW / gcd(SW, AXI_DW).
 * Written as the division form because lcm() overflows for no reason. */
static uint32_t mv4i_n_scale_sub(uint32_t rows_if, uint32_t axi_dw)
{
    uint32_t sw = rows_if * 16u;
    if (!sw || !axi_dw) return 0;
    return sw / u32_gcd(sw, axi_dw);
}

/* GRP of 6.5a: scale groups carried by one superword. */
static uint32_t mv4i_grp(uint32_t rows_if, uint32_t axi_dw)
{
    uint32_t sw = rows_if * 16u;
    if (!sw) return 0;
    return mv4i_n_scale_sub(rows_if, axi_dw) * axi_dw / sw;
}

/* AXI4 defines exactly these data widths.  6.5a's slice rule is happy with any
 * multiple of 8, but rtl/axi_rd_port.vhd derives ARSIZE as clog2(AXI_DW/8) and
 * a 96-bit "port" is a file for a bus that cannot exist.  Same list as
 * tools/pack_int4.py:AXI4_WIDTHS -- the two must agree. */
static int mv4i_is_axi4_width(uint32_t w)
{
    return w == 8 || w == 16 || w == 32 || w == 64
        || w == 128 || w == 256 || w == 512 || w == 1024;
}

/* --------------------------------------------------------- file access 6.4/6.5 */

static uint16_t rd_u16(const uint8_t *p) { return (uint16_t)(p[0] | (p[1] << 8)); }
static uint32_t rd_u32(const uint8_t *p)
{ return (uint32_t)p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24); }
static uint64_t rd_u64(const uint8_t *p)
{ return (uint64_t)rd_u32(p) | ((uint64_t)rd_u32(p + 4) << 32); }

int mv4i_parse(mv4i_file *f, const uint8_t *img, size_t len)
{
    if (len < MV4I_HDR_BYTES) return -1;
    const uint8_t *p = img;
    mv4i_hdr *h = &f->h;

    h->magic      = rd_u32(p + 0x00);
    if (h->magic != MV4I_MAGIC) return -2;
    h->version    = rd_u16(p + 0x04);
    h->flags      = rd_u16(p + 0x06);
    h->M          = rd_u32(p + 0x08);
    h->K          = rd_u32(p + 0x0C);
    h->w_exp      = (int32_t)rd_u32(p + 0x10);   /* SIGNED, two's complement */
    h->out_shift  = (int32_t)rd_u32(p + 0x14);
    h->rows_if    = rd_u16(p + 0x18);
    h->nports_w   = rd_u16(p + 0x1A);
    h->block      = rd_u16(p + 0x1C);
    /* 0x1E was "reserved (0)" until 2026-08-27 and now carries AXI_DW.  Zero
     * therefore means "written before the field existed", which can only have
     * been 128 because that is the only width the layout was ever defined at. */
    h->axi_dw     = rd_u16(p + 0x1E);
    if (h->axi_dw == 0) h->axi_dw = 128;
    memcpy(h->codebook, p + 0x20, 16);          /* codebook TRAVELS IN THE FILE */
    h->scale_offset = rd_u32(p + 0x30);
    h->n_scale_sub  = rd_u32(p + 0x34);

    /* 6.5 invariant: NPORTS_W * AXI_DW = ROWS_IF * BLOCK * 4.
     *
     * Checked in its GENERAL form (-4).  The old code tested
     * `nports_w != rows_if`, which is the invariant already evaluated at
     * AXI_DW=128 -- correct for every file that existed, but it conflated
     * "this file is self-inconsistent" with "this reference cannot decode this
     * file", and only the second is about to become common as the FK33
     * geometry is settled.                                                   */
    if (h->block != MV4I_BLOCK) return -3;
    if (h->rows_if == 0) return -3;
    if ((uint32_t)h->nports_w * (uint32_t)h->axi_dw
        != (uint32_t)h->rows_if * (uint32_t)h->block * 4u) return -4;

    /* The GEOMETRY REFUSALS.  Generalising the byte layout to spec 6.5a
     * (2026-08-28) retired the blanket `axi_dw != 128` refusal, but it did NOT
     * turn this into a pass-through.  What survives is what is still either
     * unrepresentable or self-contradictory:
     *
     *  -7  AXI_DW is not an AXI4 data width.  6.5a's slice rule would happily
     *      cut a 96-bit sub-region; no AXI4 bus can carry one.
     *  -8  more sub-regions than the fixed offset tables hold, or an offset
     *      table that does not fit the 4 KB header (6.4).  The old code
     *      truncated the read at 64 and carried on.
     *  -9  n_scale_sub disagrees with 6.5a.  Minimality is not cosmetic: a
     *      larger n that also divides describes a DIFFERENT file, so a
     *      mismatch means the writer and this reader do not agree on where the
     *      scales are, and reading it anyway is exactly the silent misread
     *      this refusal exists to prevent.  n_scale_sub == 0 is the one
     *      accepted deviation -- 0x34 was written as a literal 1 by every
     *      emitter that ever ran, and 0 can only mean a file older than the
     *      field, which can only have been the single contiguous sub-region.
     *
     * Note AXI_DW < BLOCK*4 is NOT refused: a sub-region narrower than a row
     * chunk is a perfectly well defined slice under 6.5a (ROWS_IF=4/AXI_DW=64
     * gives NPORTS_W=8, two sub-regions per row), and refusing it would be
     * refusing the general rule this file now implements.                    */
    if (!mv4i_is_axi4_width(h->axi_dw)) return -7;
    if (h->nports_w == 0 || h->nports_w > MV4I_MAX_SUB) return -8;

    if (h->n_scale_sub == 0) {
        /* Legacy file: one contiguous scale region at scale_offset. */
        h->n_scale_sub    = 1;
        h->s_sub_offset[0] = h->scale_offset;
    }
    if (h->n_scale_sub > MV4I_MAX_SUB) return -8;
    if (h->n_scale_sub != mv4i_n_scale_sub(h->rows_if, h->axi_dw)) return -9;
    if (0x38u + 8u * ((uint32_t)h->nports_w + h->n_scale_sub) > MV4I_HDR_BYTES)
        return -8;

    for (unsigned i = 0; i < h->nports_w; i++)
        h->w_sub_offset[i] = rd_u64(p + 0x38 + 8 * i);
    if (rd_u32(p + 0x34) != 0)
        for (unsigned i = 0; i < h->n_scale_sub; i++)
            h->s_sub_offset[i] = rd_u64(p + 0x38 + 8 * h->nports_w + 8 * i);

    f->port_b = (int)(h->axi_dw / 8u);
    f->grp    = (int)mv4i_grp(h->rows_if, h->axi_dw);

    /* 7.4 normative range constraints.  Violating either overflows a declared
     * width in the RTL, so the reference refuses the file rather than silently
     * producing a result the hardware cannot reproduce.                      */
    for (int i = 0; i < 16; i++)
        if (h->codebook[i] == -128) return -5;   /* -128 FORBIDDEN */
    if (h->out_shift < 0 || h->out_shift > 40) return -6;

    f->base = img;
    f->nb   = (int)((h->K + MV4I_BLOCK - 1) / MV4I_BLOCK);
    return 0;
}

/* 6.5 bit ordering: weight j of a block sits at bits 4j+3..4j of the chunk,
 * so j even -> low nibble of byte j/2, j odd -> high nibble.
 *
 * 6.5a: the byte holding that nibble sits at offset `rr*(BLOCK/2) + j/2` of
 * the TILE WORD, and the tile word is cut into NPORTS_W sub-regions of port_b
 * bytes each, so the byte lives in sub-region wb/port_b at offset wb%port_b of
 * that sub-region's (t*nb+b)'th beat.
 *
 * At AXI_DW=128, BLOCK=32 this is port_b = 16 = one row chunk, so wb/port_b is
 * rr and wb%port_b is j/2 -- character for character the code it replaced.   */
static int get_widx(const mv4i_file *f, int r, int k)
{
    int RI = f->h.rows_if, t = r / RI, rr = r % RI;
    int b = k / MV4I_BLOCK, j = k % MV4I_BLOCK;
    size_t wb  = (size_t)rr * (MV4I_BLOCK / 2) + (size_t)(j >> 1);
    size_t p   = wb / (size_t)f->port_b;             /* weight sub-region     */
    size_t off = wb % (size_t)f->port_b;             /* byte within the beat  */
    const uint8_t *sub = f->base + f->h.w_sub_offset[p];
    uint8_t byte = sub[(size_t)(t * f->nb + b) * (size_t)f->port_b + off];
    return (j & 1) ? (byte >> 4) : (byte & 0x0F);
}

/* One byte of scale superword `super`, at bit-slice-flattened offset `bo`.
 *
 * Byte-at-a-time rather than a 16-bit read because at AXI_DW = 8 a scale
 * STRADDLES two sub-regions (port_b = 1), and the whole point of writing 6.5a
 * generally was to stop special-casing the widths that happen to be tidy. */
static uint8_t scale_byte(const mv4i_file *f, size_t super, size_t bo)
{
    size_t q   = bo / (size_t)f->port_b;             /* scale sub-region      */
    size_t off = bo % (size_t)f->port_b;
    return f->base[f->h.s_sub_offset[q] + super * (size_t)f->port_b + off];
}

/* Scale for row r, block b.  Little-endian int16; row r of a tile-block group
 * sits at byte offset 2r within that group (6.5).
 *
 * 6.5a: group g = t*nb + b of the flat t-major-then-b stream is chunk g%GRP of
 * superword g/GRP, and the superword is sliced across n_scale_sub sub-regions.
 * At n_scale_sub = 1 the superword is one beat of GRP groups, and
 * (g/GRP)*port_b + (g%GRP)*RI*2 + rr*2 collapses to (g*RI + rr)*2, which is
 * the contiguous offset this replaced.                                       */
static uint16_t get_scale(const mv4i_file *f, int r, int b)
{
    int RI = f->h.rows_if, t = r / RI, rr = r % RI;
    size_t g  = (size_t)(t * f->nb + b);
    size_t bo = (g % (size_t)f->grp) * (size_t)RI * 2u + (size_t)rr * 2u;
    size_t su = g / (size_t)f->grp;
    return (uint16_t)(scale_byte(f, su, bo)
                      | ((uint16_t)scale_byte(f, su, bo + 1) << 8));
}

/* ------------------------------------------------------------- the matvec 7.4 */

/* Stage-level trace.  When enabled, every intermediate the 7.4 contract names
 * is emitted, so sim/tb_matvec_core.vhd can compare the RTL STAGE BY STAGE
 * rather than only at the output.  A divergence then localizes to one pipeline
 * stage on the first failing vector, instead of surfacing as a wrong final
 * answer that has to be bisected -- which is what the v1.0-silicon debug
 * history had to do by hand. */
static FILE *g_trace;

typedef struct {
    int32_t *y_data;   /* raw: s32 per row */
    int64_t *y_acc;    /* PARTIAL: UNROUNDED s48 accumulator per row (14.2) */
    int16_t *y_mant;   /* BFP: int16 mantissa per row */
    int      y_exp;
    int      sat_event;
    uint64_t sat_count;
    int      ns;       /* BFP normalization shift, for inspection */
} mv4i_result;

int mv4i_matvec(const mv4i_file *f, const int16_t *x_mant, int x_exp,
                int n_rows, int n_cols, int out_mode, mv4i_result *out)
{
    if (n_rows <= 0 || n_cols <= 0)      return -1;   /* 7.6 abort */
    if ((uint32_t)n_cols > f->h.K)       return -2;
    if ((uint32_t)n_rows > f->h.M)       return -3;   /* else get_widx reads OOB */

    g_sat_event = 0;
    g_sat_count = 0;

    const int NB = (n_cols + MV4I_BLOCK - 1) / MV4I_BLOCK;

    for (int r = 0; r < n_rows; r++) {
        int64_t acc = 0;                                   /* s48 in hardware */

        for (int b = 0; b < NB; b++) {
            int64_t partial = 0;                           /* s28 in hardware */

            for (int j = 0; j < MV4I_BLOCK; j++) {
                int k = b * MV4I_BLOCK + j;
                if (k >= n_cols) continue;   /* COLUMN MASK (6.2).  Required
                                              * because the IQ4_NL codebook has
                                              * NO ZERO ENTRY -- index 0 decodes
                                              * to -127 -- so zero-padding would
                                              * contribute a nonzero product.  */
                int8_t cb = f->h.codebook[get_widx(f, r, k)];
                partial += (int64_t)cb * (int64_t)x_mant[k];
            }
            assert(partial < (1LL << 27) && partial > -(1LL << 27));  /* s28 */

            uint16_t sc = get_scale(f, r, b);
            assert(sc <= 32767);                     /* 7.4: uint15, MSB clear */

            /* SITE 1: floor, never C division. */
            if (g_trace) fprintf(g_trace, "PARTIAL %d %d %016llX\n",
                                 r, b, (unsigned long long)partial);
            int64_t contrib = floor_shr(partial * (int64_t)sc, 15);
            if (g_trace) fprintf(g_trace, "CONTRIB %d %d %016llX\n",
                                 r, b, (unsigned long long)contrib);
            assert(contrib < (1LL << 27) && contrib > -(1LL << 27));  /* s29 */

            acc += contrib;
        }
        /* At K=17408, NB=544 and |acc| <= 544 * 2^27 ~= 2^36.1; s48 holds. */
        assert(acc < (1LL << 47) && acc > -(1LL << 47));
        if (g_trace) fprintf(g_trace, "ACC %d %016llX\n", r, (unsigned long long)acc);

        if (out_mode == MV4I_MODE_PARTIAL) {
            /* 14.2 CORRECTED 2026-08-22: partial mode emits the accumulator
             * UNROUNDED.  round_shift is NOT additive, so rounding each shard
             * before the reduction accumulates up to N/2 ulp of error and can
             * never reproduce the full-K result.
             * WITHDRAWN 2026-08-24 (15.4b): the sentence that stood here
             * claiming the sharded path is then "BIT-EXACT with the
             * single-card path, because integer addition is associative"
             * holds ONLY when every card shares one grid (equal x_exp).  In
             * production each card BFP-packs its own x slice, so the grids
             * differ, the consumer must floor-align to the minimum y_exp, and
             * the reduction is NOT exact.  Bit-identity died upstream of the
             * reduction and is unattainable under any policy.  See 14.2.
             * What does survive: no sat32 runs here at all, so the
             * sat32-on-partial hazard is dissolved and sat_event must stay
             * clear in this mode.  sim/tb_matvec_core checks that.          */
            out->y_acc[r] = acc;
            continue;
        }
        /* SITES 2/3 */
        out->y_data[r] = sat32(round_shift(acc, f->h.out_shift));
        if (g_trace) fprintf(g_trace, "YDATA %d %016llX\n",
                             r, (unsigned long long)(int64_t)out->y_data[r]);
    }

    out->ns = 0;

    if (out_mode == MV4I_MODE_BFP) {
        /* SCAN DOMAIN is r < n_rows ONLY.  Padded tile rows and stale buffer
         * contents at indices >= n_rows would inflate ns and crush every real
         * mantissa -- the failure bfp_pack's own header documents.           */
        uint64_t amax = 0;
        for (int r = 0; r < n_rows; r++) {
            uint64_t a = abs64((int64_t)out->y_data[r]);
            if (a > amax) amax = a;
        }
        int ns = msb_pos_u(amax) - 14;
        if (ns < 0) ns = 0;
        out->ns = ns;

        if (g_trace) fprintf(g_trace, "NS %d\n", ns);
        for (int r = 0; r < n_rows; r++) {                /* SITE 4 */
            out->y_mant[r] = sat16(round_shift((int64_t)out->y_data[r], ns));
            if (g_trace) fprintf(g_trace, "YMANT %d %016llX\n",
                                 r, (unsigned long long)(int64_t)out->y_mant[r]);
        }

        /* ns is SUBTRACTED.  If mant' = mant >> ns then preserving the value
         * needs exp' = exp - ns.  Matches bfp_pack (o_exp = Q - shift_o) and
         * matmul_rt (o_exp <= xexp_l - sh).  Rev 2 of the spec had this as +ns. */
        out->y_exp = f->h.w_exp + x_exp - f->h.out_shift - ns;
    } else if (out_mode == MV4I_MODE_PARTIAL) {
        /* 14.2: the payload is the UNROUNDED accumulator, so its grid carries
         * no out_shift term.  Reporting w_exp + x_exp - out_shift (as this file
         * did until 2026-08-22) understates the exponent by exactly out_shift
         * and would misalign every cross-card reduction whose cards chose
         * different out_shift values -- which the corrected 14.2 permits. */
        out->y_exp = f->h.w_exp + x_exp;
    } else {
        out->y_exp = f->h.w_exp + x_exp - f->h.out_shift;
    }

    out->sat_event = g_sat_event;
    out->sat_count = g_sat_count;
    return 0;
}

/* ============================== SELF TEST ================================= */
#ifndef MV4I_LIB

/* Minimal packer, sufficient to exercise the reference.  Emits exactly the
 * 6.4/6.5a layout so that packer -> C -> RTL bit-identity is testable.
 *
 * GENERALISED 2026-08-28 from AXI_DW = 128 to any AXI4 width.  It is written as
 * a byte-offset computation on the TILE WORD (6.5a) rather than as a per-row
 * loop over sub-regions, because the general rule IS a slice and a per-row loop
 * can only express the case where a slice happens to be a row.  Substituting
 * AXI_DW = 128, BLOCK = 32 gives port_b = 16 = one row chunk and nports =
 * rows_if, so this reduces to the code it replaced; that is checked by
 * byte-identity against the pre-change binary, not asserted here.            */
static size_t align4k(size_t v) { return (v + 4095) & ~(size_t)4095; }

static uint8_t *pack_geom(int M, int K, int rows_if, int axi_dw,
                          int w_exp, int out_shift,
                          const int8_t cb[16], const uint8_t *idx /*M*K*/,
                          const uint16_t *scl /*M*NB*/, size_t *out_len)
{
    int NB     = (K + MV4I_BLOCK - 1) / MV4I_BLOCK;
    int tiles  = (M + rows_if - 1) / rows_if;
    int row_b  = MV4I_BLOCK / 2;                            /* 16 B */
    int word_b = rows_if * row_b;                           /* the tile word  */
    int port_b = axi_dw / 8;
    int nports = word_b / port_b;
    int nss    = (int)mv4i_n_scale_sub((uint32_t)rows_if, (uint32_t)axi_dw);
    int grp    = (int)mv4i_grp((uint32_t)rows_if, (uint32_t)axi_dw);
    assert(nports * port_b == word_b);       /* 6.5 invariant must divide     */
    assert(0x38 + 8 * (nports + nss) <= MV4I_HDR_BYTES);    /* 6.4 offset tbl */

    size_t sub_pad = align4k((size_t)tiles * NB * port_b);
    size_t nsuper  = ((size_t)tiles * NB + grp - 1) / grp;
    /* rounded up to a whole SUPERWORD, not to a whole group: the RTL pops
     * whole superwords and a short last one would starve the final tile. */
    size_t scl_pad = align4k(nsuper * port_b);
    size_t scl_off = MV4I_HDR_BYTES + sub_pad * nports;
    size_t len     = scl_off + scl_pad * nss;

    uint8_t *img = calloc(1, len);                          /* PAD FILL = 0x00 */
    uint8_t *p = img;
    *(uint32_t *)(void *)(p + 0x00) = MV4I_MAGIC;
    *(uint16_t *)(void *)(p + 0x04) = 1;
    *(uint16_t *)(void *)(p + 0x06) = 1;                    /* codebook present */
    *(uint32_t *)(void *)(p + 0x08) = (uint32_t)M;
    *(uint32_t *)(void *)(p + 0x0C) = (uint32_t)K;
    *(int32_t  *)(void *)(p + 0x10) = w_exp;
    *(int32_t  *)(void *)(p + 0x14) = out_shift;
    *(uint16_t *)(void *)(p + 0x18) = (uint16_t)rows_if;
    *(uint16_t *)(void *)(p + 0x1A) = (uint16_t)nports;     /* NPORTS_W */
    *(uint16_t *)(void *)(p + 0x1C) = MV4I_BLOCK;
    *(uint16_t *)(void *)(p + 0x1E) = (uint16_t)axi_dw; /* AXI_DW, see 6.4 */
    memcpy(p + 0x20, cb, 16);
    *(uint32_t *)(void *)(p + 0x34) = (uint32_t)nss;        /* n_scale_sub */
    for (int i = 0; i < nports; i++)
        *(uint64_t *)(void *)(p + 0x38 + 8 * i) = MV4I_HDR_BYTES + sub_pad * i;
    for (int q = 0; q < nss; q++)
        *(uint64_t *)(void *)(p + 0x38 + 8 * (nports + q)) = scl_off + scl_pad * q;
    *(uint32_t *)(void *)(p + 0x30) = (uint32_t)scl_off;

    for (int r = 0; r < M; r++) {
        int t = r / rows_if, rr = r % rows_if;
        for (int k = 0; k < K; k++) {
            int b = k / MV4I_BLOCK, j = k % MV4I_BLOCK;
            size_t wb  = (size_t)rr * row_b + (size_t)(j >> 1);
            size_t sr  = wb / (size_t)port_b, off = wb % (size_t)port_b;
            uint8_t *c = img + MV4I_HDR_BYTES + sub_pad * sr
                       + (size_t)(t * NB + b) * (size_t)port_b + off;
            uint8_t v = idx[(size_t)r * K + k] & 0x0F;
            if (j & 1) *c = (uint8_t)((*c & 0x0F) | (v << 4));
            else       *c = (uint8_t)((*c & 0xF0) | v);
        }
        for (int b = 0; b < NB; b++) {
            size_t g  = (size_t)(t * NB + b);
            size_t bo = (g % (size_t)grp) * (size_t)rows_if * 2u + (size_t)rr * 2u;
            size_t su = g / (size_t)grp;
            uint16_t v = scl[(size_t)r * NB + b];
            for (int by = 0; by < 2; by++) {
                size_t q = (bo + by) / (size_t)port_b;
                size_t o = (bo + by) % (size_t)port_b;
                img[scl_off + scl_pad * q + su * (size_t)port_b + o] =
                    (uint8_t)(v >> (8 * by));
            }
        }
    }
    *out_len = len;
    return img;
}

/* The AXU3EG geometry, which is what every existing call site wants. */
static uint8_t *pack(int M, int K, int rows_if, int w_exp, int out_shift,
                     const int8_t cb[16], const uint8_t *idx /*M*K*/,
                     const uint16_t *scl /*M*NB*/, size_t *out_len)
{
    return pack_geom(M, K, rows_if, 128, w_exp, out_shift, cb, idx, scl, out_len);
}

#ifndef MV4I_LIB
/* Self-tests and CLI.  Define MV4I_LIB to link this file as a library, which
 * is what hw/mv_driver.c does: 10 step 5 compares the PL against THIS code
 * running on the board's own cores, so it has to be the same source. */
static const int8_t IQ4_NL[16] = { -127,-104,-83,-65,-49,-35,-22,-10,
                                      1, 13, 25, 38, 53, 69, 89,113 };

static uint32_t rng = 12345;
static uint32_t rnd(void) { rng = rng * 1103515245u + 12345u; return rng >> 8; }

static int fails;
static void check(const char *name, int ok)
{
    printf("  %-46s %s\n", name, ok ? "PASS" : "FAIL");
    if (!ok) fails++;
}

/* ------------------------- 15.4b helpers: the differing-x_exp machinery ---- */

/* bfp_pack semantics (7.4 site 4) applied to raw s32-grid values: what the
 * PRODUCING op does to x before a row-parallel matvec consumes it.  Values sit
 * on grid 2^-exp0; returns the packed exponent exp0 - ns.  In production each
 * card runs this over ITS OWN slice (bfp_pack.vhd scans only local rows), so
 * ns -- and therefore x_exp -- is per-card and data-dependent.  That is the
 * mechanism 15.4b is about. */
static int bfp_pack_vec(const int64_t *u, int n, int exp0, int16_t *mant)
{
    uint64_t amax = 0;
    for (int i = 0; i < n; i++) { uint64_t a = abs64(u[i]); if (a > amax) amax = a; }
    int ns = msb_pos_u(amax) - 14;
    if (ns < 0) ns = 0;
    for (int i = 0; i < n; i++) mant[i] = sat16(round_shift(u[i], ns));
    return exp0 - ns;
}

/* 128-bit floor shift and round-half-toward-+infinity.  Needed ONLY by the
 * option-2 (max-align) emulation: an s48 partial left-shifted by the worst-case
 * exponent spread of 17 needs 48+17+clog2(N) bits, which does not fit int64.
 * That the C model needs __int128 here is itself a datum: the RTL analog is a
 * >64-bit adder and a >64-bit row buffer. */
static __int128 floor_shr128(__int128 v, int sh)
{
    if (sh <= 0) return v;
    __int128 d = (__int128)1 << sh;
    __int128 q = v / d;
    if (v % d != 0 && v < 0) q -= 1;
    return q;
}
static __int128 round_shift128(__int128 v, int sh)
{
    if (sh == 0) return v;
    return floor_shr128(v + ((__int128)1 << (sh - 1)), sh);
}

/* 2^e as a double without libm (the build line links no -lm). */
static double pow2i(int e)
{
    double r = 1.0;
    while (e > 0) { r *= 2.0;  e--; }
    while (e < 0) { r *= 0.5;  e++; }
    return r;
}

/* Cross-check mode: parse a packer-produced .mv4i, run a deterministic
 * activation vector through it, and print a checksum.  tools/pack_int4.py
 * --crosscheck computes the same number independently, so agreement proves the
 * 6.4/6.5 layout is interpreted identically by packer and reference. */
static int crosscheck(const char *path)
{
    FILE *fp = fopen(path, "rb");
    if (!fp) { perror(path); return 2; }
    fseek(fp, 0, SEEK_END); long len = ftell(fp); fseek(fp, 0, SEEK_SET);
    uint8_t *img = malloc((size_t)len);
    if (fread(img, 1, (size_t)len, fp) != (size_t)len) return 2;
    fclose(fp);

    mv4i_file f;
    int rc = mv4i_parse(&f, img, (size_t)len);
    if (rc) { fprintf(stderr, "parse failed: %d\n", rc); return 2; }

    int M = (int)f.h.M, K = (int)f.h.K;
    int16_t *x = malloc(sizeof(int16_t) * (size_t)K);
    uint32_t st = 2463534242u;                      /* xorshift32, seed fixed */
    for (int k = 0; k < K; k++) {
        st ^= st << 13; st ^= st >> 17; st ^= st << 5;
        x[k] = (int16_t)((int32_t)(st % 20001) - 10000);
    }
    mv4i_result r = { malloc(4*(size_t)M), malloc(8*(size_t)M),
                      malloc(2*(size_t)M), 0,0,0,0 };
    if (mv4i_matvec(&f, x, 0, M, K, MV4I_MODE_BFP, &r)) return 2;

    int64_t sum = 0;
    for (int i = 0; i < M; i++) sum += r.y_mant[i];
    printf("M=%d K=%d w_exp=%d out_shift=%d ns=%d y_exp=%d mant_sum=%lld sat=%d\n",
           M, K, f.h.w_exp, f.h.out_shift, r.ns, r.y_exp,
           (long long)sum, r.sat_event);
    return 0;
}

/* Emit a self-contained stage trace for a small deterministic case: the packed
 * weights, the activation vector, and every intermediate.  sim/tb_matvec_core
 * reads exactly this one file. */
/* `sat` selects the ADVERSARIAL vector instead of the random one: every
 * weight at the codebook's -127 extreme, every scale at 32767, every
 * activation at -32768 and out_shift 0, which is test 12's construction and
 * drives acc past 2^31 so sat32 clamps on every row.  It exists so the trace
 * exercises sat_event with a value other than 0.  Without it the flag was
 * wired through three testbenches and never once compared, which is how the
 * RTL came to assert it in PARTIAL mode -- where 14.2 runs no sat32 at all
 * and the reference therefore reports 0 -- undetected. */
static int emit_trace(const char *out_path, int M, int K, int RI, int sat)
{
    const int NB = (K + MV4I_BLOCK - 1) / MV4I_BLOCK;
    const int out_shift = sat ? 0 : 3;
    const int w_exp = sat ? 0 : 2, x_exp = sat ? 0 : 5;
    uint8_t  *idx = malloc((size_t)M * K);
    uint16_t *scl = malloc(sizeof(uint16_t) * M * NB);
    uint32_t st = 99;
    if (sat) {
        for (int i = 0; i < M * K; i++)  idx[i] = 0;         /* cb = -127 */
        for (int i = 0; i < M * NB; i++) scl[i] = 32767;
    } else {
    for (int i = 0; i < M * K; i++) { st = st * 1103515245u + 12345u; idx[i] = (st >> 16) & 15; }
    for (int i = 0; i < M * NB; i++) { st = st * 1103515245u + 12345u; scl[i] = (uint16_t)(8000 + ((st >> 12) % 24000)); }
    }
    size_t len; uint8_t *img = pack(M, K, RI, w_exp, out_shift, IQ4_NL, idx, scl, &len);
    mv4i_file f; if (mv4i_parse(&f, img, len)) return 2;

    int16_t *x = malloc(sizeof(int16_t) * K);
    if (sat) { for (int k = 0; k < K; k++) x[k] = -32768; }
    else { for (int k = 0; k < K; k++) { st = st * 1103515245u + 12345u; x[k] = (int16_t)((int32_t)((st >> 8) % 40001) - 20000); } }

    g_trace = fopen(out_path, "w");
    if (!g_trace) { perror(out_path); return 2; }
    fprintf(g_trace, "# GENERATED by ref/matvec_int4 --trace -- DO NOT EDIT\n");
    fprintf(g_trace, "DIMS %d %d %d %d %d %d %d\n",
            M, K, NB, out_shift, w_exp, x_exp, RI);
    for (int i = 0; i < 16; i++) fprintf(g_trace, "CB %d %d\n", i, IQ4_NL[i]);
    for (int k = 0; k < K; k++) fprintf(g_trace, "X %d %04X\n", k, (uint16_t)x[k]);
    for (int r = 0; r < M; r++)
        for (int b = 0; b < NB; b++) {
            fprintf(g_trace, "SCALE %d %d %04X\n", r, b, scl[r * NB + b]);
            for (int j = 0; j < MV4I_BLOCK; j++) {
                int k = b * MV4I_BLOCK + j;
                fprintf(g_trace, "IDX %d %d %d\n", r, k, k < K ? idx[(size_t)r * K + k] : 0);
            }
        }

    /* The PACKED IMAGE ITSELF, as AXI_DW=128-bit words, plus the sub-region
     * geometry the PS would program from the header.  sim/tb_matvec_int4 serves
     * these bytes over AXI, so the RTL's reassembly (6.5) is checked against
     * the real packer output rather than against a second derivation of the
     * layout -- which would agree with a wrong layout just as happily.        */
    {
        int    tiles   = (M + RI - 1) / RI;
        size_t chunk   = MV4I_BLOCK / 2;
        size_t sub_sz  = (size_t)tiles * NB * chunk;
        size_t sub_pad = (sub_sz + 4095) & ~(size_t)4095;
        size_t scl_sz  = (size_t)tiles * NB * RI * 2;
        for (int i = 0; i < RI; i++)
            fprintf(g_trace, "WBASE %d %zu\n", i, MV4I_HDR_BYTES + sub_pad * i);
        fprintf(g_trace, "SBASE %zu\n", MV4I_HDR_BYTES + sub_pad * RI);
        /* one 128-bit beat is exactly one row-block chunk at BLOCK=32 */
        fprintf(g_trace, "WBEATS %d\n", tiles * NB);
        fprintf(g_trace, "SBEATS %zu\n", (scl_sz + 15) / 16);
        fprintf(g_trace, "IMGWORDS %zu\n", len / 16);
        for (size_t wd = 0; wd < len / 16; wd++) {
            const uint8_t *q = img + wd * 16;
            int nz = 0;
            for (int i = 0; i < 16; i++) if (q[i]) { nz = 1; break; }
            if (!nz) continue;               /* zero words are the model default */
            fprintf(g_trace, "IMG %zu ", wd);
            for (int i = 15; i >= 0; i--) fprintf(g_trace, "%02X", q[i]);
            fprintf(g_trace, "\n");
        }
    }

    mv4i_result res = { malloc(4*(size_t)M), malloc(8*(size_t)M), malloc(2*(size_t)M), 0,0,0,0 };
    int rc = mv4i_matvec(&f, x, x_exp, M, K, MV4I_MODE_BFP, &res);
    fprintf(g_trace, "YEXP %d\n", res.y_exp);
    /* The sticky flag as the reference computes it, for THIS pass (BFP).  The
     * testbench compares it and additionally requires 0 from the PARTIAL pass,
     * which needs no expectation from here because 14.2 makes it invariant. */
    fprintf(g_trace, "SATEV %d\n", res.sat_event ? 1 : 0);
    fclose(g_trace); g_trace = NULL;
    printf("wrote %s (M=%d K=%d NB=%d)\n", out_path, M, K, NB);
    return rc;
}

/* --emit OUT [M K ROWS_IF AXI_DW] -- write the packed image itself, nothing else.
 *
 * WHY: tools/pack_int4.py --crosscheck and this file's crosscheck() both parse
 * a .mv4i and print one line, so pointing them at the same file compares two
 * independent readings of the 6.4/6.5 layout.  That was only ever done by hand,
 * and only on a file the PYTHON packer wrote.  This mode supplies the other
 * direction -- a file the C packer wrote -- and needs no GGUF, so
 * sim/run_matvec.sh can run it on every invocation.
 *
 * AXI_DW became an argument on 2026-08-28: without it this direction could
 * only ever exercise the one width whose layout was never in doubt.          */
static int emit_image(const char *out_path, int M, int K, int RI, int DW)
{
    const int NB = (K + MV4I_BLOCK - 1) / MV4I_BLOCK;
    const int out_shift = 3, w_exp = 2;
    uint8_t  *idx = malloc((size_t)M * K);
    uint16_t *scl = malloc(sizeof(uint16_t) * M * NB);
    uint32_t st = 99;
    for (int i = 0; i < M * K; i++) { st = st * 1103515245u + 12345u; idx[i] = (st >> 16) & 15; }
    for (int i = 0; i < M * NB; i++) { st = st * 1103515245u + 12345u; scl[i] = (uint16_t)(8000 + ((st >> 12) % 24000)); }
    size_t len;
    uint8_t *img = pack_geom(M, K, RI, DW, w_exp, out_shift, IQ4_NL, idx, scl, &len);
    mv4i_file f;
    int prc = mv4i_parse(&f, img, len);
    if (prc) { fprintf(stderr, "own file rejected: %d\n", prc); return 2; }
    FILE *fp = fopen(out_path, "wb");
    if (!fp) { perror(out_path); return 2; }
    if (fwrite(img, 1, len, fp) != len) { perror("write"); return 2; }
    fclose(fp);
    free(idx); free(scl); free(img);
    printf("wrote %s (M=%d K=%d ROWS_IF=%d AXI_DW=%d, %zu bytes)\n",
           out_path, M, K, RI, DW, len);
    return 0;
}

int main(int argc, char **argv)
{
    /* --trace OUT [M K ROWS_IF].  Defaults kept for the historical case; the
     * runner sweeps shapes that exercise the column mask (K not a multiple of
     * BLOCK) and pad rows (M not a multiple of ROWS_IF), neither of which the
     * original M=8 K=96 RI=4 case reached. */
    if (argc >= 3 && !strcmp(argv[1], "--trace")) {
        int M = argc > 3 ? atoi(argv[3]) : 8;
        int K = argc > 4 ? atoi(argv[4]) : 96;
        int R = argc > 5 ? atoi(argv[5]) : 4;
        int S = argc > 6 ? atoi(argv[6]) : 0;
        return emit_trace(argv[2], M, K, R, S);
    }
    if (argc >= 3 && !strcmp(argv[1], "--emit")) {
        int M = argc > 3 ? atoi(argv[3]) : 8;
        int K = argc > 4 ? atoi(argv[4]) : 96;
        int R = argc > 5 ? atoi(argv[5]) : 4;
        int D = argc > 6 ? atoi(argv[6]) : 128;
        return emit_image(argv[2], M, K, R, D);
    }
    if (argc >= 2) return crosscheck(argv[1]);
    printf("subsystem A reference self-test\n");

    /* ---- test 1: dequant, all 16 codebook indices ---- */
    {
        int ok = 1;
        for (int i = 0; i < 16; i++) if (IQ4_NL[i] == -128) ok = 0;
        check("1  codebook has no -128 (7.4 constraint)", ok);
    }

    /* ---- test 9/10: column and row masking, K not a multiple of BLOCK ---- */
    {
        const int M = 6, K = 40, RI = 4, NB = 2;   /* K=40 -> partial block */
        uint8_t *idx = calloc((size_t)M * K, 1);
        uint16_t *scl = malloc(sizeof(uint16_t) * M * NB);
        for (int i = 0; i < M * K; i++) idx[i] = (uint8_t)(rnd() & 15);
        for (int i = 0; i < M * NB; i++) scl[i] = 32767;
        size_t len; uint8_t *img = pack(M, K, RI, 0, 0, IQ4_NL, idx, scl, &len);

        mv4i_file f; assert(mv4i_parse(&f, img, len) == 0);
        int16_t *x = malloc(sizeof(int16_t) * K);
        for (int k = 0; k < K; k++) x[k] = (int16_t)(rnd() & 0x7FFF);

        mv4i_result r = { malloc(4*M), malloc(8*M), malloc(2*M), 0,0,0,0 };
        assert(mv4i_matvec(&f, x, 0, M, K, MV4I_MODE_RAW, &r) == 0);

        /* independent recompute, masking columns >= K */
        int ok = 1;
        for (int row = 0; row < M; row++) {
            int64_t acc = 0;
            for (int b = 0; b < NB; b++) {
                int64_t part = 0;
                for (int j = 0; j < MV4I_BLOCK; j++) {
                    int k = b * MV4I_BLOCK + j;
                    if (k >= K) continue;
                    part += (int64_t)IQ4_NL[idx[(size_t)row * K + k]] * x[k];
                }
                acc += floor_shr(part * 32767, 15);
            }
            if (r.y_data[row] != sat32(acc)) ok = 0;
        }
        check("9  column masking, K=40 (not a multiple of 32)", ok);
        /* M=6 with ROWS_IF=4 means rows 4-5 live in a partially filled tile,
         * so this checks that the packer's padded rows do not perturb the real
         * ones.  y_we suppression itself is RTL-only and not testable here.
         * The previous form asserted `M % RI != 0`, a constant-true statement
         * about the test's own parameters that exercised nothing.            */
        {
            mv4i_result r2 = { malloc(4*4), malloc(8*4), malloc(2*4), 0,0,0,0 };
            assert(mv4i_matvec(&f, x, 0, 4, K, MV4I_MODE_RAW, &r2) == 0);
            int same = 1;
            for (int i = 0; i < 4; i++) if (r2.y_data[i] != r.y_data[i]) same = 0;
            check("10 padded tile rows do not perturb real rows", same);
            free(r2.y_data); free(r2.y_acc); free(r2.y_mant);
        }
        free(idx); free(scl); free(img); free(x);
        free(r.y_data); free(r.y_acc); free(r.y_mant);
    }

    /* ---- test 11: accumulator corner.  The whole point of this test is that
     * -32768 is the TRUE corner, not +/-32767; an earlier spec revision said
     * 32767 and would have missed the overflow it existed to catch by one. ---- */
    {
        const int M = 4, K = 512, RI = 4, NB = K / MV4I_BLOCK;
        uint8_t *idx = malloc((size_t)M * K);
        uint16_t *scl = malloc(sizeof(uint16_t) * M * NB);
        for (int i = 0; i < M * K; i++) idx[i] = 0;    /* -127, the extreme */
        for (int i = 0; i < M * NB; i++) scl[i] = 32767;
        size_t len; uint8_t *img = pack(M, K, RI, 0, 0, IQ4_NL, idx, scl, &len);
        mv4i_file f; assert(mv4i_parse(&f, img, len) == 0);

        int16_t *x = malloc(sizeof(int16_t) * K);
        for (int k = 0; k < K; k++) x[k] = -32768;     /* TRUE corner */

        mv4i_result r = { malloc(4*M), malloc(8*M), malloc(2*M), 0,0,0,0 };
        int rc = mv4i_matvec(&f, x, 0, M, K, MV4I_MODE_RAW, &r);
        /* the asserts inside mv4i_matvec are the test: s28/s29/s48 must hold */
        check("11 accumulator bound at cb=-127, x=-32768", rc == 0);
        free(idx); free(scl); free(img); free(x);
        free(r.y_data); free(r.y_acc); free(r.y_mant);
    }

    /* ---- test 7: BFP mode, and the ns sign ---- */
    {
        const int M = 8, K = 64, RI = 4, NB = K / MV4I_BLOCK;
        uint8_t *idx = malloc((size_t)M * K);
        uint16_t *scl = malloc(sizeof(uint16_t) * M * NB);
        for (int i = 0; i < M * K; i++) idx[i] = (uint8_t)(rnd() & 15);
        for (int i = 0; i < M * NB; i++) scl[i] = 20000;
        size_t len; uint8_t *img = pack(M, K, RI, 3, 2, IQ4_NL, idx, scl, &len);
        mv4i_file f; assert(mv4i_parse(&f, img, len) == 0);
        int16_t *x = malloc(sizeof(int16_t) * K);
        for (int k = 0; k < K; k++) x[k] = (int16_t)(rnd() & 0x3FFF);

        mv4i_result r = { malloc(4*M), malloc(8*M), malloc(2*M), 0,0,0,0 };
        assert(mv4i_matvec(&f, x, 5, M, K, MV4I_MODE_BFP, &r) == 0);

        int mant_ok = 1;
        for (int i = 0; i < M; i++) if (r.y_data[i] != 0 && r.y_mant[i] == 0) mant_ok = 0;
        check("7a BFP mantissas fit int16", mant_ok);
        /* y_exp = w_exp + x_exp - out_shift - ns, MINUS ns */
        check("7b BFP y_exp subtracts ns", r.y_exp == 3 + 5 - 2 - r.ns);
        free(idx); free(scl); free(img); free(x);
        free(r.y_data); free(r.y_acc); free(r.y_mant);
    }

    /* ---- test 12: msb_pos(0) = 0 on an all-zero output ---- */
    {
        const int M = 4, K = 32, RI = 4, NB = 1;
        uint8_t *idx = malloc((size_t)M * K);
        uint16_t *scl = calloc(M * NB, sizeof(uint16_t));   /* scale 0 -> all zero */
        for (int i = 0; i < M * K; i++) idx[i] = (uint8_t)(rnd() & 15);
        size_t len; uint8_t *img = pack(M, K, RI, 0, 0, IQ4_NL, idx, scl, &len);
        mv4i_file f; assert(mv4i_parse(&f, img, len) == 0);
        int16_t *x = malloc(sizeof(int16_t) * K);
        for (int k = 0; k < K; k++) x[k] = 1000;
        mv4i_result r = { malloc(4*M), malloc(8*M), malloc(2*M), 0,0,0,0 };
        assert(mv4i_matvec(&f, x, 0, M, K, MV4I_MODE_BFP, &r) == 0);
        int zero = 1;
        for (int i = 0; i < M; i++) if (r.y_data[i] != 0 || r.y_mant[i] != 0) zero = 0;
        check("12 all-zero output: msb_pos(0)=0, ns=0", zero && r.ns == 0);
        free(idx); free(scl); free(img); free(x);
        free(r.y_data); free(r.y_acc); free(r.y_mant);
    }

    /* ---- THE 14.4 PROOF: one full-K job == two half-K partials, aligned and
     * summed.  This validates the CORRECTED 14.2 contract (partials carry
     * their own y_exp and are NOT directly summable) on a single card, with no
     * interconnect and no FK33 in existence. ---- */
    {
        const int M = 8, K = 128, RI = 4, NB = K / MV4I_BLOCK, HK = K / 2;
        uint8_t *idx = malloc((size_t)M * K);
        uint16_t *scl = malloc(sizeof(uint16_t) * M * NB);
        for (int i = 0; i < M * K; i++) idx[i] = (uint8_t)(rnd() & 15);
        for (int i = 0; i < M * NB; i++) scl[i] = 30000;
        int16_t *x = malloc(sizeof(int16_t) * K);
        for (int k = 0; k < K; k++) x[k] = (int16_t)((rnd() & 0x7FFF) - 16384);

        /* full-K reference */
        size_t l0; uint8_t *i0 = pack(M, K, RI, 2, 6, IQ4_NL, idx, scl, &l0);
        mv4i_file f0; assert(mv4i_parse(&f0, i0, l0) == 0);
        mv4i_result full = { malloc(4*M), malloc(8*M), malloc(2*M), 0,0,0,0 };
        assert(mv4i_matvec(&f0, x, 4, M, K, MV4I_MODE_RAW, &full) == 0);

        /* two half-K shards.  Each is a SEPARATE job with its own x slice, so
         * in the real system each would carry a different x_exp.  Here both
         * slices share x_exp, so the partials happen to be on one grid and sum
         * exactly -- THE SPECIAL CASE, kept because it is the one that is
         * bit-exact and so catches round-before-reduce regressions.  The
         * production case (per-slice packs, differing x_exp, min-align floor
         * reduction per the resolved 15.4b) is the 15.4b tests below.        */
        uint8_t  *ia = malloc((size_t)M * HK), *ib = malloc((size_t)M * HK);
        uint16_t *sa = malloc(sizeof(uint16_t) * M * (NB / 2));
        uint16_t *sb = malloc(sizeof(uint16_t) * M * (NB / 2));
        for (int r = 0; r < M; r++) {
            memcpy(ia + (size_t)r * HK, idx + (size_t)r * K,      HK);
            memcpy(ib + (size_t)r * HK, idx + (size_t)r * K + HK, HK);
            for (int b = 0; b < NB / 2; b++) {
                sa[r * (NB / 2) + b] = scl[r * NB + b];
                sb[r * (NB / 2) + b] = scl[r * NB + b + NB / 2];
            }
        }
        size_t la, lb;
        uint8_t *pa = pack(M, HK, RI, 2, 6, IQ4_NL, ia, sa, &la);
        uint8_t *pb = pack(M, HK, RI, 2, 6, IQ4_NL, ib, sb, &lb);
        mv4i_file fa, fb;
        assert(mv4i_parse(&fa, pa, la) == 0 && mv4i_parse(&fb, pb, lb) == 0);

        mv4i_result ra = { malloc(4*M), malloc(8*M), malloc(2*M), 0,0,0,0 };
        mv4i_result rb = { malloc(4*M), malloc(8*M), malloc(2*M), 0,0,0,0 };
        assert(mv4i_matvec(&fa, x,      4, M, HK, MV4I_MODE_PARTIAL, &ra) == 0);
        assert(mv4i_matvec(&fb, x + HK, 4, M, HK, MV4I_MODE_PARTIAL, &rb) == 0);

        /* Partials are UNROUNDED s48 on a shared grid (same w_exp/x_exp here),
         * so the reduction is EXACT integer addition and one round_shift at the
         * end reproduces the full-K job bit-for-bit. */
        int ok = 1;
        for (int r = 0; r < M; r++) {
            int64_t summed = ra.y_acc[r] + rb.y_acc[r];
            if (sat32(round_shift(summed, 6)) != full.y_data[r]) ok = 0;
        }
        /* Partial y_exp carries NO out_shift term (14.2), so it sits exactly
         * out_shift above the full-K raw job's exponent.  Asserting equality
         * here is what locked in the C1 defect. */
        check("14.4 partial-sum: 2 half-K shards == 1 full-K job, BIT-EXACT",
              ok && ra.y_exp == rb.y_exp && ra.y_exp == full.y_exp + 6);
        check("14.4 sat_event clean on this vector",
              !full.sat_event && !ra.sat_event && !rb.sat_event);

        free(idx); free(scl); free(x); free(i0); free(ia); free(ib);
        free(sa); free(sb); free(pa); free(pb);
        free(full.y_data); free(full.y_acc); free(full.y_mant);
        free(ra.y_data); free(ra.y_acc); free(ra.y_mant);
        free(rb.y_data); free(rb.y_acc); free(rb.y_mant);
    }

    /* ---- THE 15.4b MEASUREMENT: differing x_exp across shards, the case
     * production actually hits and the 14.4 test above deliberately avoids.
     * Each shard's x slice is BFP-packed LOCALLY (its own amax, its own ns),
     * exactly as bfp_pack.vhd does on each card, so the two partials arrive on
     * DIFFERENT grids.  Both candidate E reductions are run on the SAME
     * partials:
     *   option 1: align to min y_exp (floor right shift), sum in int64
     *   option 2: align to max y_exp (exact left shift),  sum in __int128
     * and both are compared against the exact unquantized-activation oracle
     * and against the single-card full-K job (which packs x on ONE global
     * grid).  What this settles: (a) the option-1 alignment error obeys its
     * derived bound and is measured, (b) option 2 buys no accuracy that
     * matters, (c) NEITHER option reproduces the single-card result, because
     * the per-slice x packing upstream already diverged -- bit-identity died
     * there, not in E. ---- */
    {
        const int M = 8, K = 256, RI = 4, NB = K / MV4I_BLOCK, HK = K / 2;
        const int NBH = NB / 2, w_exp = 2, out_shift = 6, E0 = 20;
        uint8_t  *idx = malloc((size_t)M * K);
        uint16_t *scl = malloc(sizeof(uint16_t) * M * NB);
        for (int i = 0; i < M * K; i++)  idx[i] = (uint8_t)(rnd() & 15);
        for (int i = 0; i < M * NB; i++) scl[i] = (uint16_t)(8000 + (rnd() % 24000));

        /* previous-op raw outputs on grid 2^-E0, with a real magnitude
         * disparity between the slices: slice 0 ~ 2^27, slice 1 ~ 2^19.
         * Per-slice packing then gives ns 13 vs 5 -> x_exp spread 8. */
        int64_t *u = malloc(sizeof(int64_t) * K);
        for (int k = 0; k < K;  k++) {
            int64_t span = (k < HK) ? (1LL << 27) : (1LL << 19);
            u[k] = (int64_t)(rnd() % (2 * span)) - span;
        }

        /* single-card path: ONE global pack, one full-K job */
        int16_t *xg = malloc(sizeof(int16_t) * K);
        int xg_exp = bfp_pack_vec(u, K, E0, xg);
        size_t l0; uint8_t *i0 = pack(M, K, RI, w_exp, out_shift, IQ4_NL, idx, scl, &l0);
        mv4i_file f0; assert(mv4i_parse(&f0, i0, l0) == 0);
        mv4i_result rs = { malloc(4*M), malloc(8*M), malloc(2*M), 0,0,0,0 };
        assert(mv4i_matvec(&f0, xg, xg_exp, M, K, MV4I_MODE_BFP, &rs) == 0);

        /* sharded path: per-slice packs (production), two PARTIAL jobs.
         * Same w_exp for both shards -- a packer POLICY the resolution makes
         * normative; without it the y_exp spread grows by |delta w_exp|.    */
        int16_t *xa = malloc(sizeof(int16_t) * HK), *xb = malloc(sizeof(int16_t) * HK);
        int ea = bfp_pack_vec(u,      HK, E0, xa);
        int eb = bfp_pack_vec(u + HK, HK, E0, xb);
        uint8_t  *ia = malloc((size_t)M * HK), *ib = malloc((size_t)M * HK);
        uint16_t *sa = malloc(sizeof(uint16_t) * M * NBH);
        uint16_t *sb = malloc(sizeof(uint16_t) * M * NBH);
        for (int r = 0; r < M; r++) {
            memcpy(ia + (size_t)r * HK, idx + (size_t)r * K,      HK);
            memcpy(ib + (size_t)r * HK, idx + (size_t)r * K + HK, HK);
            for (int b = 0; b < NBH; b++) {
                sa[r * NBH + b] = scl[r * NB + b];
                sb[r * NBH + b] = scl[r * NB + b + NBH];
            }
        }
        size_t la, lb;
        uint8_t *pa = pack(M, HK, RI, w_exp, out_shift, IQ4_NL, ia, sa, &la);
        uint8_t *pb = pack(M, HK, RI, w_exp, out_shift, IQ4_NL, ib, sb, &lb);
        mv4i_file fa, fb;
        assert(mv4i_parse(&fa, pa, la) == 0 && mv4i_parse(&fb, pb, lb) == 0);
        mv4i_result ra = { malloc(4*M), malloc(8*M), malloc(2*M), 0,0,0,0 };
        mv4i_result rb = { malloc(4*M), malloc(8*M), malloc(2*M), 0,0,0,0 };
        assert(mv4i_matvec(&fa, xa, ea, M, HK, MV4I_MODE_PARTIAL, &ra) == 0);
        assert(mv4i_matvec(&fb, xb, eb, M, HK, MV4I_MODE_PARTIAL, &rb) == 0);
        check("15.4b shards land on DIFFERENT grids (spread 8)",
              ra.y_exp != rb.y_exp && rb.y_exp - ra.y_exp == 8);

        /* E option 1: min-align (floor), int64 sum, one round, BFP pack */
        int ymin = ra.y_exp < rb.y_exp ? ra.y_exp : rb.y_exp;
        int ymax = ra.y_exp > rb.y_exp ? ra.y_exp : rb.y_exp;
        int D = ymax - ymin;
        int64_t  *s1  = malloc(sizeof(int64_t) * M);
        int32_t  *v1  = malloc(sizeof(int32_t) * M);
        int32_t  *v2  = malloc(sizeof(int32_t) * M);
        int bound_ok = 1, diff_max = 0;
        for (int r = 0; r < M; r++) {
            s1[r] = floor_shr(ra.y_acc[r], ra.y_exp - ymin)
                  + floor_shr(rb.y_acc[r], rb.y_exp - ymin);
            v1[r] = sat32(round_shift(s1[r], out_shift));

            /* E option 2: max-align (exact left shift), __int128 sum, then
             * ONE round by out_shift + D lands on the SAME grid as option 1
             * (ymin - out_shift), so v1/v2 are directly comparable. */
            __int128 s2 = ((__int128)ra.y_acc[r] << (ymax - ra.y_exp))
                        + ((__int128)rb.y_acc[r] << (ymax - rb.y_exp));
            __int128 w  = round_shift128(s2, out_shift + D);
            assert(w < (__int128)1 << 62 && w > -((__int128)1 << 62));
            v2[r] = sat32((int64_t)w);

            /* derived option-1 bound, checked by execution: the floor-aligned
             * sum sits AT OR BELOW the exact sum by less than (N-1) ulp of the
             * min grid.  s2 >> D is the exact sum on the min grid.           */
            __int128 diff = s2 - ((__int128)s1[r] << D);
            if (diff < 0 || diff >= (__int128)(2 - 1) << D) bound_ok = 0;

            int d = v2[r] - v1[r]; if (d < 0) d = -d;
            if (d > diff_max) diff_max = d;
        }
        check("15.4b option-1 error < (N-1) ulp of min grid", bound_ok);
        printf("     measured option1-vs-option2 max divergence: %d s32 count(s)\n",
               diff_max);
        check("15.4b option1 vs option2 post-round: <= 1 count", diff_max <= 1);

        /* exact oracle: same quantized weights, UNQUANTIZED activations.
         * O[r] = sum cb*sc*u[k] on grid 2^-(15 + w_exp + E0). */
        double e_sc = 0, e_o1 = 0, e_o2 = 0;   /* max rel err vs oracle */
        for (int r = 0; r < M; r++) {
            __int128 So = 0;
            for (int k = 0; k < K; k++)
                So += (__int128)IQ4_NL[idx[(size_t)r * K + k]]
                    * (__int128)scl[(size_t)r * NB + k / MV4I_BLOCK]
                    * (__int128)u[k];
            double O = (double)(int64_t)So * pow2i(-(15 + w_exp + E0));
            double A = O < 0 ? -O : O;  if (A < 1e-30) continue;
            double sc_v = (double)rs.y_mant[r] * pow2i(-rs.y_exp);
            double o1_v = (double)v1[r] * pow2i(-(ymin - out_shift));
            double o2_v = (double)v2[r] * pow2i(-(ymin - out_shift));
            double d;
            d = (sc_v - O) / A; if (d < 0) d = -d; if (d > e_sc) e_sc = d;
            d = (o1_v - O) / A; if (d < 0) d = -d; if (d > e_o1) e_o1 = d;
            d = (o2_v - O) / A; if (d < 0) d = -d; if (d > e_o2) e_o2 = d;
        }
        printf("     rel err vs exact oracle: single-card %.3g  opt1 %.3g  opt2 %.3g\n",
               e_sc, e_o1, e_o2);
        /* the sharded path is NOT bit-identical to the single card -- the
         * per-slice x pack upstream already diverged (slice 1 kept 8 more
         * bits of precision than the global pack gave it).  Option 2's
         * exactness therefore cannot buy back single-card bit-identity; here
         * the sharded result is CLOSER to the truth than the single card.   */
        check("15.4b sharded != single-card under EITHER option",
              !(e_o1 == e_sc && e_o2 == e_sc));
        check("15.4b opt1 within 2x opt2 error (alignment loss negligible)",
              e_o1 <= 2 * e_o2 + 1e-12);

        free(idx); free(scl); free(u); free(xg); free(i0);
        free(xa); free(xb); free(ia); free(ib); free(sa); free(sb);
        free(pa); free(pb); free(s1); free(v1); free(v2);
        free(rs.y_data); free(rs.y_acc); free(rs.y_mant);
        free(ra.y_data); free(ra.y_acc); free(ra.y_mant);
        free(rb.y_data); free(rb.y_acc); free(rb.y_mant);
    }

    /* ---- 15.4b error scaling with card count: N = 2, 4, 8.  Same structure
     * as above but N-way, with a per-slice magnitude ramp (2^27 down by 2^-2
     * per slice) so every slice packs to a different grid.  This measures how
     * the option-1 alignment loss grows with N: the bound is (N-1) ulp of the
     * coarsest grid, i.e. LINEAR in N, and the measured post-round divergence
     * from the exact (option-2) reduction stays at most 1 count. ---- */
    {
        const int M = 8, K = 1024, RI = 4, NB = K / MV4I_BLOCK;
        const int w_exp = 1, out_shift = 8, E0 = 20;
        uint8_t  *idx = malloc((size_t)M * K);
        uint16_t *scl = malloc(sizeof(uint16_t) * M * NB);
        for (int i = 0; i < M * K; i++)  idx[i] = (uint8_t)(rnd() & 15);
        for (int i = 0; i < M * NB; i++) scl[i] = (uint16_t)(8000 + (rnd() % 24000));
        int64_t *u = malloc(sizeof(int64_t) * K);

        int all_ok = 1;
        for (int N = 2; N <= 8; N *= 2) {
            const int SK = K / N, SNB = NB / N;
            for (int c = 0; c < N; c++) {
                int sh = 2 * c * (N == 2 ? 4 : (N == 4 ? 2 : 1));
                int64_t span = (1LL << 27) >> sh;      /* per-slice ramp */
                for (int k = c * SK; k < (c + 1) * SK; k++)
                    u[k] = (int64_t)(rnd() % (2 * span)) - span;
            }
            mv4i_result *rr = malloc(sizeof(mv4i_result) * (size_t)N);
            int ymin = 1 << 30, ymax = -(1 << 30);
            for (int c = 0; c < N; c++) {
                int16_t  *xs = malloc(sizeof(int16_t) * SK);
                int       ec = bfp_pack_vec(u + c * SK, SK, E0, xs);
                uint8_t  *ic = malloc((size_t)M * SK);
                uint16_t *sc = malloc(sizeof(uint16_t) * M * SNB);
                for (int r = 0; r < M; r++) {
                    memcpy(ic + (size_t)r * SK, idx + (size_t)r * K + c * SK, SK);
                    for (int b = 0; b < SNB; b++)
                        sc[r * SNB + b] = scl[r * NB + c * SNB + b];
                }
                size_t lc; uint8_t *pc = pack(M, SK, RI, w_exp, out_shift,
                                              IQ4_NL, ic, sc, &lc);
                mv4i_file fc; assert(mv4i_parse(&fc, pc, lc) == 0);
                rr[c].y_data = malloc(4*M); rr[c].y_acc = malloc(8*M);
                rr[c].y_mant = malloc(2*M);
                assert(mv4i_matvec(&fc, xs, ec, M, SK, MV4I_MODE_PARTIAL, &rr[c]) == 0);
                if (rr[c].y_exp < ymin) ymin = rr[c].y_exp;
                if (rr[c].y_exp > ymax) ymax = rr[c].y_exp;
                free(xs); free(ic); free(sc); free(pc);
            }
            int D = ymax - ymin, ok_b = 1, ok_w = 1, dmax = 0;
            for (int r = 0; r < M; r++) {
                int64_t  s1 = 0; __int128 s2 = 0;
                for (int c = 0; c < N; c++) {
                    s1 += floor_shr(rr[c].y_acc[r], rr[c].y_exp - ymin);
                    s2 += (__int128)rr[c].y_acc[r] << (ymax - rr[c].y_exp);
                }
                /* option-1 accumulator: s(48 + clog2(N)) */
                int aw = 48 + (N == 2 ? 1 : (N == 4 ? 2 : 3));
                if (!(s1 < (1LL << aw) && s1 > -(1LL << aw))) ok_w = 0;
                __int128 diff = s2 - ((__int128)s1 << D);
                if (diff < 0 || diff >= (__int128)(N - 1) << D) ok_b = 0;
                int32_t v1 = sat32(round_shift(s1, out_shift));
                int32_t v2 = sat32((int64_t)round_shift128(s2, out_shift + D));
                int d = v2 - v1; if (d < 0) d = -d;
                if (d > dmax) dmax = d;
            }
            printf("     N=%d: y_exp spread %-2d  opt1 err bound %d ulp  "
                   "measured post-round divergence %d\n", N, D, N - 1, dmax);
            if (!(ok_b && ok_w && dmax <= 1)) all_ok = 0;
            for (int c = 0; c < N; c++) {
                free(rr[c].y_data); free(rr[c].y_acc); free(rr[c].y_mant);
            }
            free(rr);
        }
        check("15.4b N-scaling: bound, width, <=1 count at N=2/4/8", all_ok);
        free(idx); free(scl); free(u);
    }

    /* ---- 15.4b adversarial: the CONTRACTUAL worst-case spread of 17.
     * x_exp = (upstream exponent) - ns with ns in [0,17] (s32 input to the
     * pack: amax <= 2^31 -> msb <= 31 -> ns <= 17), so with w_exp and
     * out_shift pinned equal across the shard group the y_exp spread is
     * bounded by 17.  One slice carries a full-scale s32 value (ns = 17),
     * the other stays tiny (ns = 0). ---- */
    {
        const int M = 4, K = 64, RI = 4, NB = 2, HK = 32, NBH = 1;
        const int w_exp = 0, out_shift = 4, E0 = 18;
        uint8_t  *idx = malloc((size_t)M * K);
        uint16_t *scl = malloc(sizeof(uint16_t) * M * NB);
        for (int i = 0; i < M * K; i++)  idx[i] = (uint8_t)(rnd() & 15);
        for (int i = 0; i < M * NB; i++) scl[i] = 30000;

        int64_t *u = malloc(sizeof(int64_t) * K);
        for (int k = 0; k < HK; k++) u[k] = (int64_t)(rnd() % (1 << 28)) - (1 << 27);
        u[0] = INT32_MIN;                       /* amax 2^31 -> ns 17 */
        for (int k = HK; k < K; k++) u[k] = (int64_t)(rnd() % 16384) - 8192;

        int16_t *xa = malloc(sizeof(int16_t) * HK), *xb = malloc(sizeof(int16_t) * HK);
        int ea = bfp_pack_vec(u,      HK, E0, xa);   /* E0 - 17 */
        int eb = bfp_pack_vec(u + HK, HK, E0, xb);   /* E0 -  0 */
        check("15.4b-adv spread reaches the contractual max 17", eb - ea == 17);

        uint8_t  *ia = malloc((size_t)M * HK), *ib = malloc((size_t)M * HK);
        uint16_t *sa = malloc(sizeof(uint16_t) * M * NBH);
        uint16_t *sb = malloc(sizeof(uint16_t) * M * NBH);
        for (int r = 0; r < M; r++) {
            memcpy(ia + (size_t)r * HK, idx + (size_t)r * K,      HK);
            memcpy(ib + (size_t)r * HK, idx + (size_t)r * K + HK, HK);
            sa[r] = scl[r * NB]; sb[r] = scl[r * NB + 1];
        }
        size_t la, lb;
        uint8_t *pa = pack(M, HK, RI, w_exp, out_shift, IQ4_NL, ia, sa, &la);
        uint8_t *pb = pack(M, HK, RI, w_exp, out_shift, IQ4_NL, ib, sb, &lb);
        mv4i_file fa, fb;
        assert(mv4i_parse(&fa, pa, la) == 0 && mv4i_parse(&fb, pb, lb) == 0);
        mv4i_result ra = { malloc(4*M), malloc(8*M), malloc(2*M), 0,0,0,0 };
        mv4i_result rb = { malloc(4*M), malloc(8*M), malloc(2*M), 0,0,0,0 };
        assert(mv4i_matvec(&fa, xa, ea, M, HK, MV4I_MODE_PARTIAL, &ra) == 0);
        assert(mv4i_matvec(&fb, xb, eb, M, HK, MV4I_MODE_PARTIAL, &rb) == 0);

        int ymin = ra.y_exp < rb.y_exp ? ra.y_exp : rb.y_exp;
        int ymax = ra.y_exp > rb.y_exp ? ra.y_exp : rb.y_exp;
        int D = ymax - ymin;
        int ok_bound = 1, ok_width = 1, diff_max = 0;
        for (int r = 0; r < M; r++) {
            int64_t s1 = floor_shr(ra.y_acc[r], ra.y_exp - ymin)
                       + floor_shr(rb.y_acc[r], rb.y_exp - ymin);
            /* E option-1 accumulator width at N=2: s49 (48 + clog2(2)) */
            if (!(s1 < (1LL << 48) && s1 > -(1LL << 48))) ok_width = 0;
            __int128 s2 = ((__int128)ra.y_acc[r] << (ymax - ra.y_exp))
                        + ((__int128)rb.y_acc[r] << (ymax - rb.y_exp));
            __int128 diff = s2 - ((__int128)s1 << D);
            if (diff < 0 || diff >= (__int128)1 << D) ok_bound = 0;
            int32_t v1 = sat32(round_shift(s1, out_shift));
            __int128 w = round_shift128(s2, out_shift + D);
            int32_t v2 = sat32((int64_t)w);
            int d = v2 - v1; if (d < 0) d = -d;
            if (d > diff_max) diff_max = d;
        }
        check("15.4b-adv option-1 bound holds at spread 17", ok_bound);
        check("15.4b-adv option-1 sum fits s49 at N=2", ok_width);
        printf("     measured divergence at spread 17: %d s32 count(s)\n", diff_max);
        check("15.4b-adv post-round divergence <= 1 count", diff_max <= 1);

        free(idx); free(scl); free(u); free(xa); free(xb);
        free(ia); free(ib); free(sa); free(sb); free(pa); free(pb);
        free(ra.y_data); free(ra.y_acc); free(ra.y_mant);
        free(rb.y_data); free(rb.y_acc); free(rb.y_mant);
    }

    /* ---- 15.4b spread statistics at production shapes.  No matvec needed:
     * the spread is a property of the per-slice packs alone.  Shapes are the
     * 27B row-parallel inputs (FFN down K=17408 contiguous slices; attn o
     * K=6144 = 24 heads x 256, split BY HEAD as 14.3 shards it).  The
     * head-structured case carries a random per-head magnitude (2^0..2^6),
     * the documented realistic disparity.  This measures TYPICAL spread; the
     * worst case stays 17 by contract and is not sizeable from statistics. */
    {
        enum { TRIALS = 200 };
        static const int NS[3] = { 2, 4, 8 };
        int worst = 0;
        printf("     x_exp spread, %d trials:  shape/dist         N=2 N=4 N=8 (max)\n",
               TRIALS);
        for (int shape = 0; shape < 4; shape++) {
            const int K = (shape == 3) ? 6144 : 17408;
            int mx[3] = { 0, 0, 0 };
            int64_t *u = malloc(sizeof(int64_t) * K);
            for (int t = 0; t < TRIALS; t++) {
                for (int k = 0; k < K; k++) {
                    int64_t v;
                    if (shape == 0)          /* uniform */
                        v = (int64_t)(rnd() % (1 << 28)) - (1 << 27);
                    else if (shape == 1) {   /* gaussian-ish: sum of 8 */
                        v = 0;
                        for (int j = 0; j < 8; j++)
                            v += (int64_t)(rnd() % (1 << 25)) - (1 << 24);
                    } else if (shape == 2) { /* heavy tail: 1/256 are 64x */
                        v = (int64_t)(rnd() % (1 << 21)) - (1 << 20);
                        if ((rnd() & 255) == 0) v <<= 6;
                    } else {                 /* per-head scale 2^0..2^6 */
                        static int hs; if (k % 256 == 0) hs = (int)(rnd() % 7);
                        v = ((int64_t)(rnd() % (1 << 21)) - (1 << 20)) << hs;
                    }
                    u[k] = v;
                }
                for (int ni = 0; ni < 3; ni++) {
                    int N = NS[ni], lo = 99, hi = -99;
                    for (int c = 0; c < N; c++) {
                        uint64_t amax = 0;
                        for (int k = c * (K / N); k < (c + 1) * (K / N); k++) {
                            uint64_t a = abs64(u[k]); if (a > amax) amax = a;
                        }
                        int ns = msb_pos_u(amax) - 14; if (ns < 0) ns = 0;
                        if (ns < lo) lo = ns;
                        if (ns > hi) hi = ns;
                    }
                    if (hi - lo > mx[ni]) mx[ni] = hi - lo;
                    if (hi - lo > worst)  worst  = hi - lo;
                }
            }
            static const char *nm[4] = { "17408 uniform    ", "17408 gaussian   ",
                                         "17408 heavy-tail ", " 6144 head-scaled" };
            printf("       %s                  %d   %d   %d\n",
                   nm[shape], mx[0], mx[1], mx[2]);
            free(u);
        }
        check("15.4b spread stats within contractual bound 17", worst <= 17);
    }

    /* ---- site 4 known-answer vectors, straight from 7.4's divergence table.
     * These are the ONLY places the spec hands over concrete expected numbers,
     * and they are exactly the cases that separate bias-and-saturate from a
     * bare shift. ---- */
    {
        int ok = 1;
        if (sat16(round_shift( 32769, 1)) !=  16385) ok = 0;   /* bias matters */
        if (sat16(round_shift(-32769, 1)) != -16384) ok = 0;   /* negative tie */
        if (sat16(round_shift((1LL << 30) - 1, 15)) != 32767) ok = 0;
        /* the third needs sat16: the biased path reaches 32768, which without
         * saturation wraps to -32768 in int16 -- full-scale positive read as
         * full-scale negative. */
        check("4  site-4 known answers (7.4 divergence table)", ok);
        check("4b round_shift has no bias at sh=0", round_shift(-3, 0) == -3);
        check("4c floor_shr floors, not truncates", floor_shr(-3, 1) == -2);
    }

    /* ---- 9/12: saturation.  out_shift=0 with extreme weights and activations
     * drives acc past 2^31 so sat32 must clamp and set the sticky flag. ---- */
    {
        const int M = 4, K = 1024, RI = 4, NB = K / MV4I_BLOCK;
        uint8_t *idx = malloc((size_t)M * K);
        uint16_t *scl = malloc(sizeof(uint16_t) * M * NB);
        for (int i = 0; i < M * K; i++) idx[i] = 0;          /* cb = -127 */
        for (int i = 0; i < M * NB; i++) scl[i] = 32767;
        size_t len; uint8_t *img = pack(M, K, RI, 0, 0, IQ4_NL, idx, scl, &len);
        mv4i_file f; assert(mv4i_parse(&f, img, len) == 0);
        int16_t *x = malloc(sizeof(int16_t) * K);
        for (int k = 0; k < K; k++) x[k] = -32768;
        mv4i_result r = { malloc(4*M), malloc(8*M), malloc(2*M), 0,0,0,0 };
        assert(mv4i_matvec(&f, x, 0, M, K, MV4I_MODE_RAW, &r) == 0);
        int clamped = 1;
        for (int i = 0; i < M; i++) if (r.y_data[i] != INT32_MAX) clamped = 0;
        check("12 sat32 clamps and sets sat_event",
              clamped && r.sat_event && r.sat_count == (uint64_t)M);
        free(idx); free(scl); free(img); free(x);
        free(r.y_data); free(r.y_acc); free(r.y_mant);
    }

    /* ---- 13: spec 6.5a, the byte layout at ARBITRARY AXI_DW.
     *
     * One set of logical weights and scales, packed at ten different
     * (ROWS_IF, AXI_DW) geometries, must decode to the SAME numbers.  That is
     * what "a sub-region is a bit slice of one tile word" means operationally:
     * WHICH sub-region a byte lands in is a property of the bus, never of the
     * matrix, so the arithmetic cannot move when the bus width does.
     *
     * The shape is deliberately awkward on both axes -- K = 200 is not a whole
     * number of blocks so the column mask runs, and M = 100 is not a multiple
     * of any ROWS_IF in the table so every geometry has pad rows.
     *
     * ROWS_IF=4/AXI_DW=128 is the control: it is the geometry that is already
     * in a bitstream, so if it moved, the generalisation broke something real.
     * The rows below it each add exactly one thing the control cannot see:
     * a sub-region NARROWER than a row chunk, GRP > 1 at a width other than
     * 128, n_scale_sub > 1, and the mixed regime where BOTH exceed 1. ---- */
    {
        static const struct { int ri, dw, nports, nss, grp; } G[] = {
            {  4, 128,  4, 1, 2 },   /* AXU3EG, built.  THE CONTROL.          */
            {  1, 128,  1, 1, 8 },
            {  2, 128,  2, 1, 4 },
            {  8, 128,  8, 1, 1 },
            {  4,  64,  8, 1, 1 },   /* sub-region NARROWER than a row chunk  */
            {  2,  32,  8, 1, 1 },
            {  8, 256,  4, 1, 2 },   /* GRP > 1 away from 128                 */
            { 48, 256, 24, 3, 1 },   /* FK33: 24 + 3 = 27 AXI read masters    */
            { 24, 256, 12, 3, 2 },   /* MIXED: n_scale_sub AND GRP both > 1   */
            {  6, 256,  3, 3, 8 },   /* MIXED, SW = 96 is not a power of two  */
        };
        const int NG = (int)(sizeof G / sizeof G[0]);
        const int M = 100, K = 200, NB = (K + MV4I_BLOCK - 1) / MV4I_BLOCK;
        uint8_t  *idx = malloc((size_t)M * K);
        uint16_t *scl = malloc(sizeof(uint16_t) * M * NB);
        uint32_t st = 4242;
        for (int i = 0; i < M * K; i++)  { st = st*1103515245u + 12345u; idx[i] = (st >> 16) & 15; }
        for (int i = 0; i < M * NB; i++) { st = st*1103515245u + 12345u; scl[i] = (uint16_t)(1 + ((st >> 12) % 32767)); }
        int16_t *x = malloc(sizeof(int16_t) * K);
        for (int k = 0; k < K; k++) { st = st*1103515245u + 12345u; x[k] = (int16_t)((int32_t)((st >> 8) % 40001) - 20000); }

        int32_t *ref0 = NULL;
        int same = 1, geom = 1, parsed = 1;
        for (int g = 0; g < NG; g++) {
            size_t len;
            uint8_t *img = pack_geom(M, K, G[g].ri, G[g].dw, 2, 3, IQ4_NL,
                                     idx, scl, &len);
            mv4i_file f;
            int rc = mv4i_parse(&f, img, len);
            if (rc) { parsed = 0; free(img); continue; }
            /* the header numbers, against 6.5a evaluated by hand in the table
             * above rather than by calling the same helper the packer used */
            if (f.h.nports_w != G[g].nports ||
                (int)f.h.n_scale_sub != G[g].nss || f.grp != G[g].grp) geom = 0;
            mv4i_result r = { malloc(4*(size_t)M), malloc(8*(size_t)M),
                              malloc(2*(size_t)M), 0,0,0,0 };
            assert(mv4i_matvec(&f, x, 5, M, K, MV4I_MODE_RAW, &r) == 0);
            if (!ref0) { ref0 = r.y_data; r.y_data = NULL; }
            else if (memcmp(ref0, r.y_data, sizeof(int32_t) * (size_t)M)) same = 0;
            free(r.y_data); free(r.y_acc); free(r.y_mant); free(img);
        }
        check("13 6.5a every geometry parses", parsed);
        check("13b 6.5a NPORTS_W/n_scale_sub/GRP as specified", geom);
        check("13c 6.5a same result at 10 (ROWS_IF, AXI_DW) geometries", same);
        free(ref0); free(idx); free(scl); free(x);
    }

    /* ---- 14: the geometry refusals still refuse.
     *
     * Generalising the layout retired the blanket `AXI_DW != 128` refusal.  It
     * did NOT make mv4i_parse a pass-through, and a refusal path nobody
     * exercises is indistinguishable from one that was deleted -- so each
     * surviving code is driven here by patching one header field of an
     * otherwise valid image.  A file that violates any of these is a file
     * whose weights are somewhere other than where this reader would look, and
     * misreading it produces plausible numbers, which is the worst outcome
     * available. ---- */
    {
        const int M = 100, K = 200, NB = (K + MV4I_BLOCK - 1) / MV4I_BLOCK;
        uint8_t  *idx = calloc((size_t)M * K, 1);
        uint16_t *scl = malloc(sizeof(uint16_t) * M * NB);
        for (int i = 0; i < M * NB; i++) scl[i] = 1000;
        size_t len;
        uint8_t *good = pack_geom(M, K, 48, 256, 2, 3, IQ4_NL, idx, scl, &len);
        uint8_t *bad  = malloc(len);
        mv4i_file f;

        check("14 the FK33 image itself parses",
              mv4i_parse(&f, good, len) == 0 && f.h.nports_w == 24
              && f.h.n_scale_sub == 3);

        /* -7: AXI_DW not an AXI4 width, at a geometry where the 6.5 invariant
         * still divides (ROWS_IF=3 -> 384 bits = 4 x 96), so -4 cannot mask it */
        memcpy(bad, good, len);
        *(uint16_t *)(void *)(bad + 0x18) = 3;      /* rows_if  */
        *(uint16_t *)(void *)(bad + 0x1A) = 4;      /* nports_w */
        *(uint16_t *)(void *)(bad + 0x1E) = 96;     /* axi_dw   */
        check("14a AXI_DW=96 refused (-7, not an AXI4 width)",
              mv4i_parse(&f, bad, len) == -7);

        /* -9: n_scale_sub that is not 6.5a's minimal value.  3 is right here;
         * 6 also divides, and describes a different file. */
        memcpy(bad, good, len);
        *(uint32_t *)(void *)(bad + 0x34) = 6;
        check("14b n_scale_sub=6 refused (-9, 6.5a minimality)",
              mv4i_parse(&f, bad, len) == -9);
        memcpy(bad, good, len);
        *(uint32_t *)(void *)(bad + 0x34) = 1;
        check("14c n_scale_sub=1 refused (-9, the OLD assumption)",
              mv4i_parse(&f, bad, len) == -9);

        /* -8: more weight sub-regions than the offset tables hold. */
        memcpy(bad, good, len);
        *(uint16_t *)(void *)(bad + 0x18) = 1024;   /* rows_if  */
        *(uint16_t *)(void *)(bad + 0x1A) = 512;    /* nports_w */
        check("14d NPORTS_W=512 refused (-8, offset table bound)",
              mv4i_parse(&f, bad, len) == -8);

        /* -4: the 6.5 invariant itself, still the first thing checked. */
        memcpy(bad, good, len);
        *(uint16_t *)(void *)(bad + 0x1A) = 23;
        check("14e NPORTS_W=23 refused (-4, 6.5 invariant)",
              mv4i_parse(&f, bad, len) == -4);

        free(idx); free(scl); free(good); free(bad);
    }

    /* ---- the generated primitives against the generated golden vectors.
     * rtl/mv4i_arith_pkg.vhd is checked against this SAME file by
     * sim/tb_arith.vhd, so C and VHDL are compared to one authority rather
     * than to each other. ---- */
    {
        FILE *vf = fopen("../sim/arith_vectors.txt", "r");
        if (!vf) vf = fopen("sim/arith_vectors.txt", "r");
        if (!vf) {
            check("A  golden arith vectors (file not found)", 0);
        } else {
            char op[24]; char a0h[32], exh[32]; int sh; long n = 0, bad = 0;
            while (fscanf(vf, "%23s", op) == 1) {
                if (op[0] == '#') { while (fgetc(vf) != '\n' && !feof(vf)) {} continue; }
                if (fscanf(vf, "%31s %d %31s", a0h, &sh, exh) != 3) break;
                int64_t a0 = (int64_t)strtoull(a0h, NULL, 16);
                int64_t ex = (int64_t)strtoull(exh, NULL, 16);
                int64_t got;
                if      (!strcmp(op, "floor_shr"))   got = mv4i_floor_shr(a0, sh);
                else if (!strcmp(op, "round_shift")) got = mv4i_round_shift(a0, sh);
                else if (!strcmp(op, "sat16"))       got = mv4i_sat16(a0);
                else if (!strcmp(op, "sat32"))       got = mv4i_sat32(a0, NULL);
                else if (!strcmp(op, "msb_pos"))     got = mv4i_msb_pos_u((uint64_t)a0);
                else if (!strcmp(op, "site4"))       got = mv4i_sat16(mv4i_round_shift(a0, sh));
                else continue;
                n++;
                if (got != ex) bad++;
            }
            fclose(vf);
            printf("  %-46s %s (%ld checked)\n",
                   "A  generated arith vs golden vectors",
                   bad ? "FAIL" : "PASS", n);
            if (bad) fails++;
        }
    }

    printf("%s (%d failure%s)\n", fails ? "FAILED" : "OK", fails, fails == 1 ? "" : "s");
    return fails != 0;
}
#endif /* MV4I_LIB */

#endif /* MV4I_LIB */
