#!/usr/bin/env python3
"""Extract the AXU3EG PS configuration from a known-good design.

WHY.  The Zynq MPSoC PS carries the DDR4 timing and the MIO assignment for
SD/UART/Ethernet.  Get any of it wrong and the board does not boot -- which is
not a failure this project can debug cheaply, since the only way in is JTAG.
So the configuration is not re-derived here: it is lifted verbatim from the
design that is already running on the board.

Source is design_2 in the hardware repo, which is the minimal PS + fan_pwm +
llama_engine_axi design that was built to bitstream and brought up on silicon.
The .xci is read directly rather than by opening the project, because that repo
currently has uncommitted work in it and opening a project rewrites files.

Only user-set parameters are emitted; the ~1,077 defaults are left to Vivado.
"""
import json
import os
import sys

SRC = os.path.expanduser(
    "~/GitHub/AlinxMigrated/axu3eg_trd.srcs/sources_1/bd/design_2/ip/"
    "design_2_zynq_ultra_ps_e_0_0/design_2_zynq_ultra_ps_e_0_0.xci")
DST = os.path.join(os.path.dirname(os.path.abspath(__file__)), "ps_config.tcl")

if not os.path.exists(SRC):
    sys.exit(f"source design not found: {SRC}")

d = json.load(open(SRC))
cp = d["ip_inst"]["parameters"]["component_parameters"]
ref = d["ip_inst"]["component_reference"]

# Values Vivado stores as Python list-reprs -- PSU__PROTECTION__* and
# PSU_MIO_TREE_* -- contain [ ] and ' and cannot survive a Tcl brace quote.
# They are DERIVED: the protection tables come from the peripheral enables and
# the MIO tree from the pin assignment, so Vivado regenerates both.  Anything
# else carrying Tcl-special characters is skipped too, and reported, rather
# than silently mangled.
BAD = set("[]'\"\\")

pairs, skipped = [], []
for k, v in sorted(cp.items()):
    e = v[0]
    if e.get("value_src") != "user":
        continue
    val = e.get("value", "")
    # Vivado stores long values as a JSON ARRAY of chunks, split at arbitrary
    # points (mid-word, even).  Concatenating is what reconstitutes them;
    # leaving it a list renders the Python repr into the Tcl, brackets, quotes
    # and all, which is what broke the first version of this.
    if isinstance(val, list):
        val = "".join(val)
    if any(c in BAD for c in val) or val.count("{") != val.count("}"):
        skipped.append(k)
        continue
    pairs.append((k, val))

with open(DST, "w") as f:
    f.write("# GENERATED by hw/gen_ps_config.py -- DO NOT EDIT.\n")
    f.write(f"# Lifted verbatim from {os.path.basename(SRC)}\n")
    f.write(f"# component_reference: {ref}\n")
    f.write(f"# {len(pairs)} user-set parameters; defaults left to Vivado.\n\n")
    f.write("proc apply_ps_config {cell} {\n")
    f.write("  set_property -dict [list \\\n")
    for k, val in pairs:
        f.write("    CONFIG.%s {%s} \\\n" % (k, val))
    f.write("  ] $cell\n}\n")

print(f"wrote {os.path.relpath(DST)}  ({len(pairs)} parameters, ref {ref})")
if skipped:
    print(f"  skipped {len(skipped)} derived/unquotable: " + ", ".join(skipped))
