-- fk33_bc_grant -- GENERATED by tools/gen_bd_wrapper.py from `bc_port_grant`.
-- DO NOT HAND-EDIT; edit the generator.
--
-- A BLOCK-DESIGN-LEGAL face for an entity the IP packager refuses.
-- It changes NO logic: every port is the same signal in a type the
-- packager accepts, converted at the boundary.
--     32 ports passed through unchanged
--      6 vector widths folded to literals   [IP_Flow 19-627]
--      0 integer/natural ports re-typed      [IP_Flow 19-734]
--     26 flattened port(s) un-flattened into named interfaces
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity fk33_bc_grant is
  port(
    clk                      : in     std_logic;
    rstn                     : in     std_logic;
    b_req                    : in     std_logic;
    c_req                    : in     std_logic;
    b_gnt                    : out    std_logic;
    c_gnt                    : out    std_logic;
    b_arvalid                : in     std_logic;
    b_araddr                 : in     std_logic_vector(32 downto 0);
    b_arlen                  : in     std_logic_vector(7 downto 0);
    b_arready                : out    std_logic;
    b_rvalid                 : out    std_logic;
    b_rdata                  : out    std_logic_vector(255 downto 0);
    b_rlast                  : out    std_logic;
    b_rready                 : in     std_logic;
    b_awvalid                : in     std_logic;
    b_awaddr                 : in     std_logic_vector(32 downto 0);
    b_awlen                  : in     std_logic_vector(7 downto 0);
    b_awready                : out    std_logic;
    b_wvalid                 : in     std_logic;
    b_wdata                  : in     std_logic_vector(255 downto 0);
    b_wlast                  : in     std_logic;
    b_wready                 : out    std_logic;
    b_bvalid                 : out    std_logic;
    b_bready                 : in     std_logic;
    c0_arvalid               : in     std_logic;
    c1_arvalid               : in     std_logic;
    c0_araddr                : in     std_logic_vector(32 downto 0);
    c1_araddr                : in     std_logic_vector(32 downto 0);
    c0_arlen                 : in     std_logic_vector(7 downto 0);
    c1_arlen                 : in     std_logic_vector(7 downto 0);
    c0_arready               : out    std_logic;
    c1_arready               : out    std_logic;
    c0_rvalid                : out    std_logic;
    c1_rvalid                : out    std_logic;
    c0_rdata                 : out    std_logic_vector(255 downto 0);
    c1_rdata                 : out    std_logic_vector(255 downto 0);
    c0_rlast                 : out    std_logic;
    c1_rlast                 : out    std_logic;
    c0_rready                : in     std_logic;
    c1_rready                : in     std_logic;
    c_awvalid                : in     std_logic;
    c_awaddr                 : in     std_logic_vector(32 downto 0);
    c_awlen                  : in     std_logic_vector(7 downto 0);
    c_awready                : out    std_logic;
    c_wvalid                 : in     std_logic;
    c_wdata                  : in     std_logic_vector(255 downto 0);
    c_wlast                  : in     std_logic;
    c_wready                 : out    std_logic;
    c_bvalid                 : out    std_logic;
    c_bready                 : in     std_logic;
    m0_arvalid               : out    std_logic;
    m1_arvalid               : out    std_logic;
    m0_araddr                : out    std_logic_vector(32 downto 0);
    m1_araddr                : out    std_logic_vector(32 downto 0);
    m0_arlen                 : out    std_logic_vector(3 downto 0);
    m1_arlen                 : out    std_logic_vector(3 downto 0);
    m0_arready               : in     std_logic;
    m1_arready               : in     std_logic;
    m0_rvalid                : in     std_logic;
    m1_rvalid                : in     std_logic;
    m0_rdata                 : in     std_logic_vector(255 downto 0);
    m1_rdata                 : in     std_logic_vector(255 downto 0);
    m0_rlast                 : in     std_logic;
    m1_rlast                 : in     std_logic;
    m0_rready                : out    std_logic;
    m1_rready                : out    std_logic;
    m0_awvalid               : out    std_logic;
    m1_awvalid               : out    std_logic;
    m0_awaddr                : out    std_logic_vector(32 downto 0);
    m1_awaddr                : out    std_logic_vector(32 downto 0);
    m0_awlen                 : out    std_logic_vector(3 downto 0);
    m1_awlen                 : out    std_logic_vector(3 downto 0);
    m0_awready               : in     std_logic;
    m1_awready               : in     std_logic;
    m0_wvalid                : out    std_logic;
    m1_wvalid                : out    std_logic;
    m0_wdata                 : out    std_logic_vector(255 downto 0);
    m1_wdata                 : out    std_logic_vector(255 downto 0);
    m0_wlast                 : out    std_logic;
    m1_wlast                 : out    std_logic;
    m0_wready                : in     std_logic;
    m1_wready                : in     std_logic;
    m0_bvalid                : in     std_logic;
    m1_bvalid                : in     std_logic;
    m0_bready                : out    std_logic;
    m1_bready                : out    std_logic;
    owner_is_c               : out    std_logic;
    draining                 : out    std_logic;
    err_switch_busy          : out    std_logic;
    err_len_ovf              : out    std_logic
  );
end entity;

architecture wrap of fk33_bc_grant is
  signal w_c_arvalid            : std_logic_vector(1 downto 0);
  signal w_c_araddr             : std_logic_vector(65 downto 0);
  signal w_c_arlen              : std_logic_vector(15 downto 0);
  signal w_c_arready            : std_logic_vector(1 downto 0);
  signal w_c_rvalid             : std_logic_vector(1 downto 0);
  signal w_c_rdata              : std_logic_vector(511 downto 0);
  signal w_c_rlast              : std_logic_vector(1 downto 0);
  signal w_c_rready             : std_logic_vector(1 downto 0);
  signal w_m_arvalid            : std_logic_vector(1 downto 0);
  signal w_m_araddr             : std_logic_vector(65 downto 0);
  signal w_m_arlen              : std_logic_vector(7 downto 0);
  signal w_m_arready            : std_logic_vector(1 downto 0);
  signal w_m_rvalid             : std_logic_vector(1 downto 0);
  signal w_m_rdata              : std_logic_vector(511 downto 0);
  signal w_m_rlast              : std_logic_vector(1 downto 0);
  signal w_m_rready             : std_logic_vector(1 downto 0);
  signal w_m_awvalid            : std_logic_vector(1 downto 0);
  signal w_m_awaddr             : std_logic_vector(65 downto 0);
  signal w_m_awlen              : std_logic_vector(7 downto 0);
  signal w_m_awready            : std_logic_vector(1 downto 0);
  signal w_m_wvalid             : std_logic_vector(1 downto 0);
  signal w_m_wdata              : std_logic_vector(511 downto 0);
  signal w_m_wlast              : std_logic_vector(1 downto 0);
  signal w_m_wready             : std_logic_vector(1 downto 0);
  signal w_m_bvalid             : std_logic_vector(1 downto 0);
  signal w_m_bready             : std_logic_vector(1 downto 0);
begin
  w_c_arvalid(0) <= c0_arvalid;
  w_c_arvalid(1) <= c1_arvalid;
  w_c_araddr(32 downto 0) <= c0_araddr;
  w_c_araddr(65 downto 33) <= c1_araddr;
  w_c_arlen(7 downto 0) <= c0_arlen;
  w_c_arlen(15 downto 8) <= c1_arlen;
  w_c_rready(0) <= c0_rready;
  w_c_rready(1) <= c1_rready;
  w_m_arready(0) <= m0_arready;
  w_m_arready(1) <= m1_arready;
  w_m_rvalid(0) <= m0_rvalid;
  w_m_rvalid(1) <= m1_rvalid;
  w_m_rdata(255 downto 0) <= m0_rdata;
  w_m_rdata(511 downto 256) <= m1_rdata;
  w_m_rlast(0) <= m0_rlast;
  w_m_rlast(1) <= m1_rlast;
  w_m_awready(0) <= m0_awready;
  w_m_awready(1) <= m1_awready;
  w_m_wready(0) <= m0_wready;
  w_m_wready(1) <= m1_wready;
  w_m_bvalid(0) <= m0_bvalid;
  w_m_bvalid(1) <= m1_bvalid;
  c0_arready <= w_c_arready(0);
  c1_arready <= w_c_arready(1);
  c0_rvalid <= w_c_rvalid(0);
  c1_rvalid <= w_c_rvalid(1);
  c0_rdata <= w_c_rdata(255 downto 0);
  c1_rdata <= w_c_rdata(511 downto 256);
  c0_rlast <= w_c_rlast(0);
  c1_rlast <= w_c_rlast(1);
  m0_arvalid <= w_m_arvalid(0);
  m1_arvalid <= w_m_arvalid(1);
  m0_araddr <= w_m_araddr(32 downto 0);
  m1_araddr <= w_m_araddr(65 downto 33);
  m0_arlen <= w_m_arlen(3 downto 0);
  m1_arlen <= w_m_arlen(7 downto 4);
  m0_rready <= w_m_rready(0);
  m1_rready <= w_m_rready(1);
  m0_awvalid <= w_m_awvalid(0);
  m1_awvalid <= w_m_awvalid(1);
  m0_awaddr <= w_m_awaddr(32 downto 0);
  m1_awaddr <= w_m_awaddr(65 downto 33);
  m0_awlen <= w_m_awlen(3 downto 0);
  m1_awlen <= w_m_awlen(7 downto 4);
  m0_wvalid <= w_m_wvalid(0);
  m1_wvalid <= w_m_wvalid(1);
  m0_wdata <= w_m_wdata(255 downto 0);
  m1_wdata <= w_m_wdata(511 downto 256);
  m0_wlast <= w_m_wlast(0);
  m1_wlast <= w_m_wlast(1);
  m0_bready <= w_m_bready(0);
  m1_bready <= w_m_bready(1);
  u : entity work.bc_port_grant
    port map(
      clk                      => clk,
      rstn                     => rstn,
      b_req                    => b_req,
      c_req                    => c_req,
      b_gnt                    => b_gnt,
      c_gnt                    => c_gnt,
      b_arvalid                => b_arvalid,
      b_araddr                 => b_araddr,
      b_arlen                  => b_arlen,
      b_arready                => b_arready,
      b_rvalid                 => b_rvalid,
      b_rdata                  => b_rdata,
      b_rlast                  => b_rlast,
      b_rready                 => b_rready,
      b_awvalid                => b_awvalid,
      b_awaddr                 => b_awaddr,
      b_awlen                  => b_awlen,
      b_awready                => b_awready,
      b_wvalid                 => b_wvalid,
      b_wdata                  => b_wdata,
      b_wlast                  => b_wlast,
      b_wready                 => b_wready,
      b_bvalid                 => b_bvalid,
      b_bready                 => b_bready,
      c_arvalid                => w_c_arvalid,
      c_araddr                 => w_c_araddr,
      c_arlen                  => w_c_arlen,
      c_arready                => w_c_arready,
      c_rvalid                 => w_c_rvalid,
      c_rdata                  => w_c_rdata,
      c_rlast                  => w_c_rlast,
      c_rready                 => w_c_rready,
      c_awvalid                => c_awvalid,
      c_awaddr                 => c_awaddr,
      c_awlen                  => c_awlen,
      c_awready                => c_awready,
      c_wvalid                 => c_wvalid,
      c_wdata                  => c_wdata,
      c_wlast                  => c_wlast,
      c_wready                 => c_wready,
      c_bvalid                 => c_bvalid,
      c_bready                 => c_bready,
      m_arvalid                => w_m_arvalid,
      m_araddr                 => w_m_araddr,
      m_arlen                  => w_m_arlen,
      m_arready                => w_m_arready,
      m_rvalid                 => w_m_rvalid,
      m_rdata                  => w_m_rdata,
      m_rlast                  => w_m_rlast,
      m_rready                 => w_m_rready,
      m_awvalid                => w_m_awvalid,
      m_awaddr                 => w_m_awaddr,
      m_awlen                  => w_m_awlen,
      m_awready                => w_m_awready,
      m_wvalid                 => w_m_wvalid,
      m_wdata                  => w_m_wdata,
      m_wlast                  => w_m_wlast,
      m_wready                 => w_m_wready,
      m_bvalid                 => w_m_bvalid,
      m_bready                 => w_m_bready,
      owner_is_c               => owner_is_c,
      draining                 => draining,
      err_switch_busy          => err_switch_busy,
      err_len_ovf              => err_len_ovf
    );
end architecture;
