#!/usr/bin/env python3
"""Generate rtl/hbm_tg_ip.vhd: hbm_tg with per-port NAMED AXI3 interfaces.

AXI3, NOT AXI4, and this is not a style choice.  The HBM IP's SAXI ports are
AXI3 (queried from the IP itself, 2026-08-25: CONFIG.PROTOCOL = AXI3), and
Vivado refuses the connection outright -- "The protocols of the interfaces
'/tg/m00_axi'(AXI4) and '/hbm/SAXI_01'(AXI3) are incompatible".  The
shape below is read off the real port list rather than assumed:

    ARADDR  33 b      ARLEN   4 b  <- AXI3, so a burst is at most 16 beats
    ARID     6 b      ARSIZE  3 b      ARBURST 2 b
    RDATA  256 b      RID     6 b      RRESP   2 b
    no ARPROT, no ARCACHE, no ARQOS -- emitting them breaks inference

The 4-bit ARLEN is the one that matters for the experiment: it caps a burst at
16 beats = 512 B, so the generator cannot amortise address overhead further
than that, and neither can subsystem A.  hbm_tg keeps an 8-bit arlen register
because it is protocol-agnostic; this wrapper passes the low 4 bits and the
control software must not ask for more.

WHY A GENERATOR.  Vivado infers an AXI interface from a port group only when
the ports follow the m<NN>_axi_* naming convention, so a flattened
m_arvalid(NPORT-1 downto 0) vector -- which is the right shape for RTL and for
simulation -- is invisible to the block designer.  The same split
rtl/matvec_int4_ip.vhd already makes for subsystem A.

At NPORT=16 that is 16 x 8 = 128 ports of pure boilerplate.  Hand-writing them
is how an off-by-one in one lane's index gets into a bitstream and is then
diagnosed on hardware, so they are generated and the mapping exists in exactly
one place.
"""
import sys

NPORT  = int(sys.argv[1]) if len(sys.argv) > 1 else 16
AXI_DW = 256
ADDR_W = 33

h = []
h.append("-- rtl/hbm_tg_ip.vhd -- GENERATED by tools/gen_hbm_tg_ip.py, do not hand-edit.")
h.append("--")
h.append("-- Board-facing wrapper for hbm_tg (rtl/hbm_tg.vhd): the same unit with its")
h.append("-- %d read/write masters exposed as individually NAMED AXI interfaces," % NPORT)
h.append("-- which is")
h.append("-- what Vivado's block designer needs in order to see them as AXI at all.")
h.append("-- All logic, and every counter, lives in hbm_tg; this file is wiring.")
h.append("--")
h.append("-- Regenerate with:  python3 tools/gen_hbm_tg_ip.py %d" % NPORT)
h.append("library ieee;")
h.append("use ieee.std_logic_1164.all;")
h.append("use ieee.numeric_std.all;")
h.append("")
h.append("entity hbm_tg_ip is")
h.append("  port(")
h.append("    clk  : in std_logic;")
h.append("    rstn : in std_logic;")
h.append("    -- HBM per-stack thermal, straight from the IP.  Unconnected in")
h.append("    -- the stock design, which is the gap this build closes.")
h.append("    hbm_temp0    : in std_logic_vector(6 downto 0);")
h.append("    hbm_temp1    : in std_logic_vector(6 downto 0);")
h.append("    hbm_cattrip0 : in std_logic;")
h.append("    hbm_cattrip1 : in std_logic;")
h.append("    -- AXI4-Lite control/status, from jtag_axi")
h.append("    s_axi_awvalid : in  std_logic;")
h.append("    s_axi_awready : out std_logic;")
h.append("    s_axi_awaddr  : in  std_logic_vector(15 downto 0);")
h.append("    s_axi_awprot  : in  std_logic_vector(2 downto 0);")
h.append("    s_axi_wvalid  : in  std_logic;")
h.append("    s_axi_wready  : out std_logic;")
h.append("    s_axi_wdata   : in  std_logic_vector(31 downto 0);")
h.append("    s_axi_wstrb   : in  std_logic_vector(3 downto 0);")
h.append("    s_axi_bvalid  : out std_logic;")
h.append("    s_axi_bready  : in  std_logic;")
h.append("    s_axi_bresp   : out std_logic_vector(1 downto 0);")
h.append("    s_axi_arvalid : in  std_logic;")
h.append("    s_axi_arready : out std_logic;")
h.append("    s_axi_araddr  : in  std_logic_vector(15 downto 0);")
h.append("    s_axi_arprot  : in  std_logic_vector(2 downto 0);")
h.append("    s_axi_rvalid  : out std_logic;")
h.append("    s_axi_rready  : in  std_logic;")
h.append("    s_axi_rdata   : out std_logic_vector(31 downto 0);")
h.append("    s_axi_rresp   : out std_logic_vector(1 downto 0)")
for i in range(NPORT):
    p = "m%02d_axi" % i
    h.append("    ;")
    h.append("    -- HBM SAXI port %d" % i)
    h.append("    %s_awvalid : out std_logic;" % p)
    h.append("    %s_awready : in  std_logic;" % p)
    h.append("    %s_awaddr  : out std_logic_vector(%d downto 0);" % (p, ADDR_W-1))
    h.append("    %s_awid    : out std_logic_vector(5 downto 0);" % p)
    h.append("    %s_awlen   : out std_logic_vector(3 downto 0);" % p)
    h.append("    %s_awsize  : out std_logic_vector(2 downto 0);" % p)
    h.append("    %s_awburst : out std_logic_vector(1 downto 0);" % p)
    h.append("    %s_wvalid  : out std_logic;" % p)
    h.append("    %s_wready  : in  std_logic;" % p)
    h.append("    %s_wdata   : out std_logic_vector(%d downto 0);" % (p, AXI_DW-1))
    h.append("    %s_wstrb   : out std_logic_vector(%d downto 0);" % (p, AXI_DW//8-1))
    h.append("    %s_wlast   : out std_logic;" % p)
    h.append("    %s_bvalid  : in  std_logic;" % p)
    h.append("    %s_bready  : out std_logic;" % p)
    h.append("    %s_bid     : in  std_logic_vector(5 downto 0);" % p)
    h.append("    %s_bresp   : in  std_logic_vector(1 downto 0);" % p)
    h.append("    %s_arvalid : out std_logic;" % p)
    h.append("    %s_arready : in  std_logic;" % p)
    h.append("    %s_araddr  : out std_logic_vector(%d downto 0);" % (p, ADDR_W-1))
    h.append("    %s_arid    : out std_logic_vector(5 downto 0);" % p)
    h.append("    %s_arlen   : out std_logic_vector(3 downto 0);" % p)
    h.append("    %s_arsize  : out std_logic_vector(2 downto 0);" % p)
    h.append("    %s_arburst : out std_logic_vector(1 downto 0);" % p)
    h.append("    %s_rvalid  : in  std_logic;" % p)
    h.append("    %s_rready  : out std_logic;" % p)
    h.append("    %s_rdata   : in  std_logic_vector(%d downto 0);" % (p, AXI_DW-1))
    h.append("    %s_rlast   : in  std_logic;" % p)
    h.append("    %s_rid     : in  std_logic_vector(5 downto 0);" % p)
    h.append("    %s_rresp   : in  std_logic_vector(1 downto 0)" % p)
# separator style is a LEADING ";" per port block, so this one supplies its own
h.append("    ;")
h.append("    aresetn_o : out std_logic")
h.append("  );")
h.append("end entity;")
h.append("")
h.append("architecture rtl of hbm_tg_ip is")
h.append("  constant NPORT  : positive := %d;" % NPORT)
h.append("  constant ADDR_W : positive := %d;" % ADDR_W)
h.append("  signal arvalid, arready, rvalid, rready, rlast")
h.append("       : std_logic_vector(NPORT-1 downto 0);")
h.append("  -- rresp was DECLARED on every port and then dropped on the floor:")
h.append("  -- the wrapper accepted it and connected nothing, so the generator")
h.append("  -- counted error beats as good ones and a mis-decoded address would")
h.append("  -- have reported HIGHER bandwidth, not a failure.  Now carried.")
h.append("  signal rresp   : std_logic_vector(NPORT*2-1 downto 0);")
h.append("  signal araddr  : std_logic_vector(NPORT*ADDR_W-1 downto 0);")
h.append("  signal arlen   : std_logic_vector(NPORT*8-1 downto 0);")
h.append("  signal arsize  : std_logic_vector(NPORT*3-1 downto 0);")
h.append("  signal arburst : std_logic_vector(NPORT*2-1 downto 0);")
h.append("  signal awvalid, awready, wvalid, wready, wlast, bvalid, bready")
h.append("       : std_logic_vector(NPORT-1 downto 0);")
h.append("  signal awaddr  : std_logic_vector(NPORT*ADDR_W-1 downto 0);")
h.append("  signal awlen   : std_logic_vector(NPORT*8-1 downto 0);")
h.append("  signal awsize  : std_logic_vector(NPORT*3-1 downto 0);")
h.append("  signal awburst : std_logic_vector(NPORT*2-1 downto 0);")
h.append("  signal wdata   : std_logic_vector(NPORT*%d-1 downto 0);" % AXI_DW)
h.append("  signal wstrb   : std_logic_vector(NPORT*%d-1 downto 0);" % (AXI_DW//8))
h.append("  signal bresp   : std_logic_vector(NPORT*2-1 downto 0);")
h.append("begin")
h.append("  u : entity work.hbm_tg")
h.append("    generic map(NPORT => NPORT, AXI_DW => %d, ADDR_W => ADDR_W," % AXI_DW)
h.append("                REGION_LOG2 => 28, PORT0 => 1)")
h.append("    port map(clk => clk, rstn => rstn,")
h.append("      hbm_temp0 => hbm_temp0, hbm_temp1 => hbm_temp1,")
h.append("      hbm_cattrip0 => hbm_cattrip0, hbm_cattrip1 => hbm_cattrip1,")
h.append("      s_awvalid => s_axi_awvalid, s_awready => s_axi_awready,")
h.append("      s_awaddr  => s_axi_awaddr,")
h.append("      s_wvalid  => s_axi_wvalid,  s_wready  => s_axi_wready,")
h.append("      s_wdata   => s_axi_wdata,")
h.append("      s_bvalid  => s_axi_bvalid,  s_bready  => s_axi_bready,")
h.append("      s_arvalid => s_axi_arvalid, s_arready => s_axi_arready,")
h.append("      s_araddr  => s_axi_araddr,")
h.append("      s_rvalid  => s_axi_rvalid,  s_rready  => s_axi_rready,")
h.append("      s_rdata   => s_axi_rdata,")
h.append("      m_arvalid => arvalid, m_arready => arready, m_araddr => araddr,")
h.append("      m_arlen   => arlen,   m_arsize  => arsize,  m_arburst => arburst,")
h.append("      m_rvalid  => rvalid,  m_rready  => rready,  m_rlast   => rlast,")
h.append("      m_rresp   => rresp,")
h.append("      m_awvalid => awvalid, m_awready => awready, m_awaddr => awaddr,")
h.append("      m_awlen   => awlen,   m_awsize  => awsize,  m_awburst => awburst,")
h.append("      m_wvalid  => wvalid,  m_wready  => wready,  m_wdata   => wdata,")
h.append("      m_wstrb   => wstrb,   m_wlast   => wlast,")
h.append("      m_bvalid  => bvalid,  m_bready  => bready,  m_bresp   => bresp,")
h.append("      aresetn_o => aresetn_o);")
h.append("")
h.append("  s_axi_bresp <= \"00\";")
h.append("  s_axi_rresp <= \"00\";")
h.append("")
for i in range(NPORT):
    p = "m%02d_axi" % i
    lo_a, hi_a = i*ADDR_W, (i+1)*ADDR_W-1
    h.append("  -- port %d" % i)
    h.append("  %s_arvalid <= arvalid(%d);" % (p, i))
    h.append("  arready(%d) <= %s_arready;" % (i, p))
    h.append("  %s_araddr  <= araddr(%d downto %d);" % (p, hi_a, lo_a))
    h.append("  -- AXI3: 4-bit ARLEN.  hbm_tg's register is 8-bit and protocol")
    h.append("  -- agnostic; anything above 15 would silently wrap, so it is")
    h.append("  -- truncated HERE, where the protocol is known.")
    h.append("  %s_arlen   <= arlen(%d downto %d);" % (p, i*8+3, i*8))
    h.append("  %s_arid    <= (others => '0');" % p)
    h.append("  %s_arsize  <= arsize(%d downto %d);" % (p, (i+1)*3-1, i*3))
    h.append("  %s_arburst <= arburst(%d downto %d);" % (p, (i+1)*2-1, i*2))
    h.append("  %s_rready  <= rready(%d);" % (p, i))
    h.append("  rvalid(%d) <= %s_rvalid;" % (i, p))
    h.append("  rlast(%d)  <= %s_rlast;" % (i, p))
    h.append("  rresp(%d downto %d) <= %s_rresp;" % ((i+1)*2-1, i*2, p))
    h.append("  -- write channel, live as of 2026-08-25.  It was tied off while the")
    h.append("  -- instrument was read-only; C 2.5's 2R+1W and B's four masters")
    h.append("  -- are write traffic, so every number measured before this")
    h.append("  -- described a pattern only subsystem A issues.")
    h.append("  %s_awvalid <= awvalid(%d);" % (p, i))
    h.append("  awready(%d) <= %s_awready;" % (i, p))
    h.append("  %s_awaddr  <= awaddr(%d downto %d);" % (p, hi_a, lo_a))
    h.append("  -- AXI3 again: 4-bit AWLEN, truncated HERE for the same reason")
    h.append("  -- ARLEN is.  A burst is at most 16 beats in EITHER direction.")
    h.append("  %s_awlen   <= awlen(%d downto %d);" % (p, i*8+3, i*8))
    h.append("  %s_awid    <= (others => '0');" % p)
    h.append("  %s_awsize  <= awsize(%d downto %d);" % (p, (i+1)*3-1, i*3))
    h.append("  %s_awburst <= awburst(%d downto %d);" % (p, (i+1)*2-1, i*2))
    h.append("  %s_wvalid  <= wvalid(%d);" % (p, i))
    h.append("  wready(%d) <= %s_wready;" % (i, p))
    h.append("  %s_wdata   <= wdata(%d downto %d);"
             % (p, (i+1)*AXI_DW-1, i*AXI_DW))
    h.append("  %s_wstrb   <= wstrb(%d downto %d);"
             % (p, (i+1)*(AXI_DW//8)-1, i*(AXI_DW//8)))
    h.append("  %s_wlast   <= wlast(%d);" % (p, i))
    h.append("  bvalid(%d) <= %s_bvalid;" % (i, p))
    h.append("  %s_bready  <= bready(%d);" % (p, i))
    h.append("  bresp(%d downto %d) <= %s_bresp;" % ((i+1)*2-1, i*2, p))
    h.append("  -- BID is returned and ignored: every burst uses ID 0, so there")
    h.append("  -- is nothing to demultiplex.  Note the HBM SAXI port has NO WID")
    h.append("  -- (checked against the IP's own port list, not assumed) -- it")
    h.append("  -- does not support write interleaving, which is exactly why one")
    h.append("  -- ID and in-order data is the only legal way to drive it.")
    h.append("")
h.append("end architecture;")

open("rtl/hbm_tg_ip.vhd", "w").write("\n".join(h) + "\n")
print("wrote rtl/hbm_tg_ip.vhd, NPORT=%d" % NPORT)
