#!/usr/bin/env python3
"""Emit THIS side of the Python/VHDL shape mirror so a bench can check it.

WHY THIS EXISTS.  `tools/gen_layer_program.py`'s `mk_shape_scaled` is a hand
transcription of `rtl/llama_map_pkg.vhd`'s function of the same name, and
NOTHING compared the two.  The divergence table in `llama_map_pkg.vhd` was
produced by hand, once, and then the two sides drifted: the VHDL comment warned
that the Python "emits a plan with TWO ZERO-SIZED REGIONS instead of refusing"
and that had been fixed 36 minutes after the comment was written.

That mattered little while nothing generated above attn_hd 32.  It matters now:
`C_KV_AXI` demands HEAD_DIM 64, so subsystem C cannot reach HBM at any smaller
shape, and the `attn_hd > 32` branch went from unused to load-bearing.

So this file writes the PYTHON numbers into a VHDL package and
`sim/tb_shape_mirror.vhd` compares them against the VHDL functions.  Neither
half is the oracle for the other in the usual sense -- they are two independent
implementations of one specification, and the bench is the only thing that has
ever compared them.

`--check` regenerates in memory and diffs against the committed file, so a
Python edit that is not reflected here turns the gate red instead of silently
producing a second unchecked claim.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, HERE)

import gen_layer_program as G

# The three points the VHDL branches over: below, at, and above the boundary.
# 64 is the one that exercises the `attn_hd > 32` branch, and 16 and 32 are the
# two shapes every published landmark was measured at.
HEAD_DIMS = (16, 32, 64)
BLOCKS = 1
ATTN_INTERVAL = 4

FIELDS = ("attn_head_dim", "blocks", "attn_interval", "hidden", "ffn",
          "key_heads", "val_heads", "head_dim", "attn_q_heads",
          "attn_kv_heads", "vocab_shard")
DERIVED = ("key_dim", "val_dim", "qkv_dim", "att_q", "att_qg", "att_kv")


def row(hd):
    s = G.mk_shape_scaled(BLOCKS, ATTN_INTERVAL, hd)
    vals = [getattr(s, f) for f in FIELDS]
    vals += [getattr(s, d) for d in DERIVED]
    vals.append(max(s.region_sizes()))
    return vals


NAMES = list(FIELDS) + list(DERIVED) + ["region_max"]


def render():
    out = []
    a = out.append
    a("-- sim/shape_mirror_pkg.vhd -- GENERATED by tools/gen_shape_mirror.py.")
    a("-- DO NOT HAND-EDIT; edit the generator.")
    a("--")
    a("-- The PYTHON side of the shape mirror: what")
    a("-- `tools/gen_layer_program.py`'s `mk_shape_scaled` computes.  Compared")
    a("-- field by field against `rtl/llama_map_pkg.vhd`'s function of the")
    a("-- same name by `sim/tb_shape_mirror.vhd`, which is the only thing that")
    a("-- has ever compared the two implementations.")
    a("--")
    a("-- A DIFFERENCE HERE IS NOT AUTOMATICALLY A PYTHON BUG.  These are two")
    a("-- transcriptions of one specification; the bench says they disagree and")
    a("-- says nothing about which is right.")
    a("library ieee;")
    a("use ieee.std_logic_1164.all;")
    a("")
    a("package shape_mirror_pkg is")
    a("  constant N_FIELD : natural := %d;" % len(NAMES))
    a("  constant N_ROW   : natural := %d;" % len(HEAD_DIMS))
    a("  type mirror_t is array (0 to N_ROW-1, 0 to N_FIELD-1) of integer;")
    a("  -- column order:")
    for i, n in enumerate(NAMES):
        a("  --   %2d %s" % (i, n))
    a("  constant PY_MIRROR : mirror_t := (")
    for j, hd in enumerate(HEAD_DIMS):
        vals = row(hd)
        assert len(vals) == len(NAMES)
        comma = "," if j < len(HEAD_DIMS) - 1 else ""
        a("    (%s)%s" % (", ".join("%d" % v for v in vals), comma))
    a("  );")
    a("  constant BLOCKS_C : integer := %d;" % BLOCKS)
    a("  constant ATTN_INT_C : integer := %d;" % ATTN_INTERVAL)
    a("end package;")
    return "\n".join(out) + "\n"


def main():
    out = os.path.join(REPO, "sim", "shape_mirror_pkg.vhd")
    text = render()
    if "--check" in sys.argv:
        if not os.path.exists(out):
            print("SHAPE_MIRROR_CHECK: MISSING %s -- run "
                  "tools/gen_shape_mirror.py" % out)
            return 1
        cur = open(out).read()
        if cur != text:
            print("SHAPE_MIRROR_CHECK: STALE %s -- the Python shape changed "
                  "and this file was not regenerated.  Run "
                  "tools/gen_shape_mirror.py." % out)
            for i, (a_, b_) in enumerate(zip(cur.splitlines(),
                                             text.splitlines())):
                if a_ != b_:
                    print("  first difference at line %d:" % (i + 1))
                    print("    committed: %s" % a_)
                    print("    generated: %s" % b_)
                    break
            return 1
        print("SHAPE_MIRROR_CHECK: OK (%d rows, %d fields)"
              % (len(HEAD_DIMS), len(NAMES)))
        return 0
    with open(out, "w") as fh:
        fh.write(text)
    print("wrote %s (%d rows, %d fields)" % (out, len(HEAD_DIMS), len(NAMES)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
