#!/usr/bin/env python3
"""Generate rtl/weights_pkg.vhd : a synthesizable VHDL-2008 constant package
holding ALL transformer weights for the full PL llama engine, as literal integer
aggregates (no TEXTIO at elaboration, no `real`).  DATA ONLY -- no logic.

Same proven pattern as tools/gen_wq_l0_rom_pkg.py / tools/gen_fixed_luts_pkg.py:
read one integer per line from the .mem source files and emit
    type intarr is array(natural range <>) of integer;
    constant NAME : intarr(0 to N-1) := (v0, v1, ...);
Values are bit-identical to the .mem files; the generator asserts exact lengths.

ADDRESSING SCHEME
-----------------
Model geometry (stories260K, fixed-point int16 mantissas + per-row int32 mult /
int shift):  DIM = 64, HIDDEN = 172, KV_DIM = 32, N_LAYERS = 5, VOCAB = 512.

Per matmul weight M in {WQ,WK,WV,WO,W1,W2,W3} three flat arrays span all 5
layers, concatenated in layer order (L0..L4):
    constant M         : intarr(0 to N_LAYERS*M_STRIDE-1)  -- int16 mantissas, row-major
    constant M_MULT    : intarr(0 to N_LAYERS*M_ROWS  -1)  -- int32 per-row multiplier
    constant M_SHIFT   : intarr(0 to N_LAYERS*M_ROWS  -1)  -- int   per-row shift
    constant M_ROWS    : natural   -- output rows per layer
    constant M_COLS    : natural   -- input cols per layer (in_dim)
    constant M_STRIDE  : natural   -- = M_ROWS * M_COLS  (mantissa elements per layer)

Index matrix M, layer L (0..4), output row R (0..M_ROWS-1), input col C (0..M_COLS-1):
    mantissa  M(L*M_STRIDE + R*M_COLS + C)
    row mult  M_MULT (L*M_ROWS + R)
    row shift M_SHIFT(L*M_ROWS + R)

RMSNorm weights (DIM=64 each) are also 5-layer flat arrays with a per-layer exp:
    ATT_RMS_W(0..N_LAYERS*DIM-1), ATT_RMS_W_EXP(0..N_LAYERS-1)   ; row L*DIM + i
    FFN_RMS_W(0..N_LAYERS*DIM-1), FFN_RMS_W_EXP(0..N_LAYERS-1)

Globals (single instance):
    EMBED(0..VOCAB*DIM-1) int16, row-major token*DIM+i ; EMBED_MULT/SHIFT(0..VOCAB-1)
    FINAL_RMS_W(0..DIM-1),  FINAL_RMS_W_EXP : integer
    CLASSIFIER  -- tied to the token embedding: alias of EMBED (not duplicated)

Regenerate:  python3 tools/gen_weights_pkg.py
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
W = os.path.join(ROOT, "mem", "weights")

N_LAYERS = 5
DIM = 64
HIDDEN = 172
KV_DIM = 32
VOCAB = 512

# matrix -> (rows, cols) per layer
MATS = {
    "WQ": (DIM,    DIM),      # 64 x 64  = 4096
    "WK": (KV_DIM, DIM),      # 32 x 64  = 2048
    "WV": (KV_DIM, DIM),      # 32 x 64  = 2048
    "WO": (DIM,    DIM),      # 64 x 64  = 4096
    "W1": (HIDDEN, DIM),      # 172 x 64 = 11008
    "W2": (DIM,    HIDDEN),   # 64 x 172 = 11008
    "W3": (HIDDEN, DIM),      # 172 x 64 = 11008
}


def read_mem(path, n=None):
    vals = [int(l) for l in open(path) if l.strip() != ""]
    if n is not None and len(vals) != n:
        raise SystemExit("ERROR: %s has %d values, expected %d" % (path, len(vals), n))
    return vals


def read_int(path):
    return int(open(path).read().strip())


def emit_aggregate(vals, indent="    "):
    """Positional aggregate, wrapped to ~16 per line for readability."""
    lines = []
    per = 16
    for k in range(0, len(vals), per):
        chunk = vals[k:k + per]
        tail = "," if (k + per) < len(vals) else ""
        lines.append(indent + ", ".join(str(v) for v in chunk) + tail)
    return "\n".join(lines)


def const_arr(out, name, vals):
    out.append("  constant %s : intarr(0 to %d) := (" % (name, len(vals) - 1))
    out.append(emit_aggregate(vals))
    out.append("  );")


def main():
    out = []
    out.append("-- rtl/weights_pkg.vhd  -- AUTO-GENERATED, do not edit by hand.")
    out.append("-- Generated by tools/gen_weights_pkg.py from mem/weights/*.mem .")
    out.append("-- Unified weight ROM for the full PL llama engine. DATA ONLY (no logic,")
    out.append("-- no `real`, no TEXTIO) -- Vivado-synthesizable constant aggregates,")
    out.append("-- bit-identical to the .mem source files.")
    out.append("--")
    out.append("-- ADDRESSING (DIM=64 HIDDEN=172 KV_DIM=32 N_LAYERS=5 VOCAB=512):")
    out.append("--   mantissa M(L*M_STRIDE + R*M_COLS + C)   [row-major, layer L, row R, col C]")
    out.append("--   row mult M_MULT (L*M_ROWS + R) ; row shift M_SHIFT(L*M_ROWS + R)")
    out.append("--   M in {WQ,WK,WV,WO,W1,W2,W3}; see tools/gen_weights_pkg.py header.")
    out.append("--   ATT_RMS_W/FFN_RMS_W: row L*DIM+i, per-layer exp in *_EXP(L).")
    out.append("--   EMBED token*DIM+i; CLASSIFIER is an alias of EMBED (tied weights).")
    out.append("library ieee; use ieee.std_logic_1164.all; use ieee.numeric_std.all;")
    out.append("")
    out.append("package weights_pkg is")
    out.append("  type intarr is array(natural range <>) of integer;")
    out.append("")
    out.append("  constant N_LAYERS : natural := %d;" % N_LAYERS)
    out.append("  constant DIM      : natural := %d;" % DIM)
    out.append("  constant HIDDEN   : natural := %d;" % HIDDEN)
    out.append("  constant KV_DIM   : natural := %d;" % KV_DIM)
    out.append("  constant VOCAB    : natural := %d;" % VOCAB)
    out.append("")

    total = 0

    # ---- matmul weights: mantissa + mult + shift, all 5 layers concatenated ----
    for name, (rows, cols) in MATS.items():
        stride = rows * cols
        mant, mult, shift = [], [], []
        for L in range(N_LAYERS):
            lo = name.lower()
            mant += read_mem(os.path.join(W, "L%d" % L, "%s.mem" % lo), stride)
            mult += read_mem(os.path.join(W, "L%d" % L, "%s_mult.mem" % lo), rows)
            shift += read_mem(os.path.join(W, "L%d" % L, "%s_shift.mem" % lo), rows)
        out.append("  -- %s : %d x %d per layer (stride %d)" % (name, rows, cols, stride))
        out.append("  constant %s_ROWS   : natural := %d;" % (name, rows))
        out.append("  constant %s_COLS   : natural := %d;" % (name, cols))
        out.append("  constant %s_STRIDE : natural := %d;" % (name, stride))
        const_arr(out, name, mant)
        const_arr(out, "%s_MULT" % name, mult)
        const_arr(out, "%s_SHIFT" % name, shift)
        out.append("")
        total += len(mant) + len(mult) + len(shift)

    # ---- rmsnorm weights (att / ffn), 5-layer flat + per-layer exponent ----
    for tag, base in (("ATT_RMS_W", "att_rmsnorm_w"), ("FFN_RMS_W", "ffn_rmsnorm_w")):
        w_all, exps = [], []
        for L in range(N_LAYERS):
            w_all += read_mem(os.path.join(W, "L%d" % L, "%s.mem" % base), DIM)
            exps.append(read_int(os.path.join(W, "L%d" % L, "%s_exp.txt" % base)))
        const_arr(out, tag, w_all)
        const_arr(out, "%s_EXP" % tag, exps)
        out.append("")
        total += len(w_all) + len(exps)

    # ---- globals: embedding (== tied classifier), final rmsnorm ----
    embed = read_mem(os.path.join(W, "embed.mem"), VOCAB * DIM)
    embed_mult = read_mem(os.path.join(W, "embed_mult.mem"), VOCAB)
    embed_shift = read_mem(os.path.join(W, "embed_shift.mem"), VOCAB)
    const_arr(out, "EMBED", embed)
    const_arr(out, "EMBED_MULT", embed_mult)
    const_arr(out, "EMBED_SHIFT", embed_shift)
    out.append("  -- Tied classifier: the output projection reuses the token embedding.")
    out.append("  alias CLASSIFIER       : intarr(0 to %d) is EMBED;" % (VOCAB * DIM - 1))
    out.append("  alias CLASSIFIER_MULT  : intarr(0 to %d) is EMBED_MULT;" % (VOCAB - 1))
    out.append("  alias CLASSIFIER_SHIFT : intarr(0 to %d) is EMBED_SHIFT;" % (VOCAB - 1))
    out.append("")
    total += len(embed) + len(embed_mult) + len(embed_shift)

    final_w = read_mem(os.path.join(W, "final_rmsnorm_w.mem"), DIM)
    final_exp = read_int(os.path.join(W, "final_rmsnorm_w_exp.txt"))
    const_arr(out, "FINAL_RMS_W", final_w)
    out.append("  constant FINAL_RMS_W_EXP : integer := %d;" % final_exp)
    total += len(final_w) + 1

    out.append("end package;")
    out.append("")

    dst = os.path.join(ROOT, "rtl", "weights_pkg.vhd")
    with open(dst, "w") as f:
        f.write("\n".join(out))
    print("wrote %s  (%d integer constants total)" % (dst, total))


if __name__ == "__main__":
    main()
