#!/usr/bin/env python3
"""Generate subsystem A's shared arithmetic primitives for C and VHDL.

WHY THIS EXISTS.  The C reference and the RTL are two hand-written
implementations of one contract, and every defect found so far has clustered in
five small functions: the four rounding sites of spec 7.4, the ns sign, the
no-bias-at-zero case, and msb_pos(0).  Hand-writing them twice makes drift a
testing problem.  Generating both from one description makes it structurally
impossible.

Emits:
  ref/mv4i_arith.h          static inline C
  rtl/mv4i_arith_pkg.vhd    VHDL package
  sim/arith_vectors.txt     exhaustive golden vectors, for BOTH sides

The Python implementations below are the authority: they generate the vectors
that the emitted C and VHDL are both tested against.  Three implementations,
one source of truth.

Usage:  tools/gen_arith.py            (writes all three)
        tools/gen_arith.py --check    (regenerate and diff, for CI)
"""

import argparse
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ---------------------------------------------------------------------------
# The authority.  Spec 7.4 rounding sites 1-4 and the BFP scan primitive.
# ---------------------------------------------------------------------------


def floor_shr(v: int, sh: int) -> int:
    """Arithmetic right shift: floor toward -infinity.  Site 1, and the shift
    inside sites 2/3/4.  NOT truncation -- floor(-5/2) = -3, trunc = -2, and
    C's `/` gives the wrong one."""
    return v >> sh if sh > 0 else v


def round_shift(v: int, sh: int) -> int:
    """Round half toward +infinity, matching fixed_pkg.scale_mul: bias by
    2^(sh-1) then arithmetic shift, with NO bias at sh = 0.  Sites 2, 3, 4."""
    if sh == 0:
        return v
    return floor_shr(v + (1 << (sh - 1)), sh)


def sat16(v: int) -> int:
    """Saturate to int16.  bfp_pack clamps to [-32768, 32767] after the biased
    shift; without it the biased path can reach 32768 and wrap to -32768."""
    return -32768 if v < -32768 else (32767 if v > 32767 else v)


def sat32(v: int) -> int:
    """Saturate to int32."""
    return -(2**31) if v < -(2**31) else (2**31 - 1 if v > 2**31 - 1 else v)


def msb_pos_u(a: int) -> int:
    """Index of the most significant set bit of an unsigned value, with
    msb_pos(0) = 0 NORMATIVE (matches bfp_pack.msb_pos_u).  The natural C idiom
    63 - __builtin_clzll(a) is undefined behaviour at zero, and an all-zero
    output vector is reachable via a zero-scale row."""
    return a.bit_length() - 1 if a else 0


# ---------------------------------------------------------------------------
# Emitters
# ---------------------------------------------------------------------------

BANNER = ("/* GENERATED by tools/gen_arith.py -- DO NOT EDIT.\n"
          " * Regenerate after any change, and run tools/gen_arith.py --check\n"
          " * to verify C, VHDL and the golden vectors are still in step. */\n")

VBANNER = ("-- GENERATED by tools/gen_arith.py -- DO NOT EDIT.\n"
           "-- Regenerate after any change, and run tools/gen_arith.py --check\n"
           "-- to verify C, VHDL and the golden vectors are still in step.\n")

C_SRC = BANNER + """
#ifndef MV4I_ARITH_H
#define MV4I_ARITH_H
#include <stdint.h>

/* Spec 7.4 site 1, and the shift inside sites 2/3/4.  Floor toward -infinity.
 * C's >> on a negative signed value is implementation-defined before C23 and
 * C's / truncates, so neither is used. */
static inline int64_t mv4i_floor_shr(int64_t v, int sh)
{
    if (sh <= 0) return v;
    /* sh = 63 makes (int64_t)1 << sh overflow, which is UNDEFINED behaviour,
     * not merely implementation-defined.  It is reachable: this project clamps
     * every shift count to [0, 63] by convention, so 63 is a value the callers
     * deliberately produce.  UBSan flags it on gdn_err.c at
     * --tokens 32 --se-init 127 --eg 0 --wbits 32.
     *
     * |v| < 2^63 for any int64_t, so a shift of 63 or more floors to 0 for
     * v >= 0 and to -1 for v < 0.  Stating that directly is exact and removes
     * the UB; it is NOT a behaviour change on gcc x86-64, where the overflow
     * happened to produce INT64_MIN and the division then gave the same
     * answer.  That coincidence is the whole problem: it is correct today and
     * unowned by any standard. */
    if (sh >= 63) return (v < 0) ? -1 : 0;
    int64_t d = (int64_t)1 << sh;
    int64_t q = v / d;
    if (v % d != 0 && v < 0) q -= 1;
    return q;
}

/* Sites 2, 3, 4.  Round half toward +infinity; no bias at sh = 0. */
static inline int64_t mv4i_round_shift(int64_t v, int sh)
{
    if (sh == 0) return v;
    /* Same hazard one shift up: sh = 64 would make 1 << 63 overflow here.  The
     * bias is half an LSB of the result, and at sh >= 64 the result is 0 or -1
     * regardless, so the bias cannot change it. */
    if (sh >= 64) return (v < 0) ? -1 : 0;
    return mv4i_floor_shr(v + ((int64_t)1 << (sh - 1)), sh);
}

static inline int32_t mv4i_sat32(int64_t v, int *sat_event)
{
    if (v >  INT32_MAX) { if (sat_event) *sat_event = 1; return INT32_MAX; }
    if (v <  INT32_MIN) { if (sat_event) *sat_event = 1; return INT32_MIN; }
    return (int32_t)v;
}

static inline int16_t mv4i_sat16(int64_t v)
{
    if (v >  32767) return  32767;
    if (v < -32768) return -32768;
    return (int16_t)v;
}

/* msb_pos(0) = 0 is NORMATIVE. */
static inline int mv4i_msb_pos_u(uint64_t a)
{
    int p = 0;
    if (a == 0) return 0;
    while (a >>= 1) p++;
    return p;
}

#endif /* MV4I_ARITH_H */
"""

VHDL_SRC = VBANNER + """
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package mv4i_arith_pkg is
  -- Spec 7.4 site 1 and the shift inside sites 2/3/4.  VHDL shift_right on a
  -- SIGNED value is already an arithmetic shift, i.e. floor toward -infinity,
  -- which is exactly what the contract requires.
  function floor_shr   (v : signed; sh : natural) return signed;

  -- Sites 2, 3, 4.  Round half toward +infinity, no bias at sh = 0.  Matches
  -- fixed_pkg.scale_mul.
  function round_shift (v : signed; sh : natural) return signed;

  function sat16 (v : signed) return signed;   -- returns 16 bits
  function sat32 (v : signed) return signed;   -- returns 32 bits

  -- msb_pos(0) = 0 is NORMATIVE, matching bfp_pack.msb_pos_u.
  function msb_pos_u (a : unsigned) return natural;
end package;

package body mv4i_arith_pkg is

  function floor_shr (v : signed; sh : natural) return signed is
  begin
    if sh = 0 then return v; end if;
    return shift_right(v, sh);
  end function;

  function round_shift (v : signed; sh : natural) return signed is
    -- widen by one bit so the bias add cannot overflow before the shift
    variable w : signed(v'length downto 0);
  begin
    if sh = 0 then return v; end if;
    w := resize(v, v'length + 1)
       + shift_left(to_signed(1, v'length + 1), sh - 1);
    return resize(shift_right(w, sh), v'length);
  end function;

  function sat16 (v : signed) return signed is
  begin
    if    v >  to_signed( 32767, v'length) then return to_signed( 32767, 16);
    elsif v < -to_signed( 32768, v'length) then return to_signed(-32768, 16);
    else  return resize(v, 16); end if;
  end function;

  function sat32 (v : signed) return signed is
    constant HI : signed(v'length-1 downto 0) := to_signed( 2147483647, v'length);
    constant LO : signed(v'length-1 downto 0) := to_signed(-2147483648, v'length);
  begin
    if    v > HI then return to_signed( 2147483647, 32);
    elsif v < LO then return to_signed(-2147483648, 32);
    else  return resize(v, 32); end if;
  end function;

  function msb_pos_u (a : unsigned) return natural is
    variable p : natural := 0;
  begin
    for i in a'range loop
      if a(i) = '1' then p := i; exit; end if;   -- a'range is descending
    end loop;
    return p;                                    -- 0 when a = 0
  end function;

end package body;
"""


def gen_vectors() -> str:
    """Exhaustive-where-possible golden vectors.

    round_shift and floor_shr are swept over EVERY shift in [0,63] against a
    corner set rather than sampled, because the defects that actually occurred
    were at sh = 0 (no bias), on negative ties, and at the saturation boundary.
    msb_pos is swept over every bit position.
    """
    def h64(v: int) -> str:
        """64-bit two's complement hex.  VHDL's `integer` is 32 bits, so the
        vectors cannot be decimal: several corners exceed 2^31."""
        return f"{v & ((1 << 64) - 1):016X}"

    lines = ["# GENERATED by tools/gen_arith.py -- DO NOT EDIT",
             "# op  arg0(hex64)  shift(dec)  expected(hex64)"]

    corners = [0, 1, -1, 2, -2, 3, -3, 5, -5,
               32767, -32768, 32768, -32769, 32769, -32767,
               65535, -65536, (1 << 30) - 1, -(1 << 30),
               (1 << 31) - 1, -(1 << 31), (1 << 31), -(1 << 31) - 1,
               (1 << 40) + 12345, -((1 << 40) + 12345),
               (1 << 46) - 1, -(1 << 46),
               133165088, -133165088, 133169152, -133169152]

    for sh in range(0, 64):
        for v in corners:
            if abs(v) >= (1 << 62):
                continue
            lines.append(f"floor_shr {h64(v)} {sh} {h64(floor_shr(v, sh))}")
            lines.append(f"round_shift {h64(v)} {sh} {h64(round_shift(v, sh))}")

    for v in corners:
        lines.append(f"sat16 {h64(v)} 0 {h64(sat16(v))}")
        lines.append(f"sat32 {h64(v)} 0 {h64(sat32(v))}")

    for b in range(0, 48):
        a = 1 << b
        lines.append(f"msb_pos {h64(a)} 0 {h64(msb_pos_u(a))}")
        lines.append(f"msb_pos {h64(a-1)} 0 {h64(msb_pos_u(a-1))}")
        lines.append(f"msb_pos {h64(a+1)} 0 {h64(msb_pos_u(a+1))}")
    lines.append(f"msb_pos {h64(0)} 0 {h64(msb_pos_u(0))}")   # the NORMATIVE corner

    # the three normative site-4 vectors from spec 7.4's divergence table
    for v, sh in ((32769, 1), (-32769, 1), ((1 << 30) - 1, 15)):
        lines.append(f"site4 {h64(v)} {sh} {h64(sat16(round_shift(v, sh)))}")

    return "\n".join(lines) + "\n"


TARGETS = [("ref/mv4i_arith.h",       lambda: C_SRC),
           ("rtl/mv4i_arith_pkg.vhd", lambda: VHDL_SRC),
           ("sim/arith_vectors.txt",  gen_vectors)]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="fail if any generated file is stale")
    a = ap.parse_args()

    stale = []
    for rel, fn in TARGETS:
        path = os.path.join(REPO, rel)
        want = fn()
        have = open(path).read() if os.path.exists(path) else None
        if a.check:
            if have != want:
                stale.append(rel)
        else:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w") as f:
                f.write(want)
            n = want.count("\n")
            print(f"  wrote {rel:28s} ({n} lines)")

    if a.check:
        if stale:
            print("STALE: " + ", ".join(stale), file=sys.stderr)
            return 1
        print("generated files are in step")
    return 0


if __name__ == "__main__":
    sys.exit(main())
