#!/usr/bin/env python3
"""tools/gen_cardtop.py -- generate the CARD's top level from llama_top.

TRACK CARDTOP item 3.  See docs/debugging/2026-08-31_cardtop-design-note.md,
section 8, for why this is a generator and not a hand-written fork:
`rtl/llama_top.vhd` is 5,684 lines and the card's decisions touch about 8.6%
of it, so the other 91% is a transcription task with a defect rate.  A first
hand-written attempt produced a 5,363-line draft that had to be quarantined
unreviewed.

D1 is unchanged: `llama_top` is the untouched ORACLE and the card top is a
SEPARATE entity.  This script only decides how the separate entity is
produced.

WHAT IT APPLIES, and nothing else:

  D3  the flat NREGION*REGMAX region array, with its eight muxed client
      slots, becomes an instance of `rtl/region_mem.vhd`.  That array is the
      structure that blocks Vivado elaboration at the real 9B shape.

  (D1/D2 -- the A binding -- and D4 -- the w_active gate -- are NOT applied
  yet.  They are item 3b.  This script fails loudly rather than pretending:
  see --require-a below.)

EVERY ANCHOR IS ASSERTED TO MATCH EXACTLY ONCE.  `sim/ooc_normadapt_extract.py`
is the cautionary precedent in this repository: it keyed on flat port NAMES,
those ports were removed by TRACK RMSWIRE, and it now aborts.  The anchors
here are structural (a type declaration, a named process, a specific
concurrent assignment) and each one that vanishes is a hard error with the
anchor printed, never a silent partial rewrite.

USAGE
    python3 tools/gen_cardtop.py                 # write rtl/fk33_llama_top.vhd
    python3 tools/gen_cardtop.py --check         # regenerate and diff; nonzero
                                                 # if the checked-in file is stale
    python3 tools/gen_cardtop.py --bench         # also emit the identity bench

--check is what the gate runs.  A generator nothing schedules is WORSE than
no generator, because its output looks authoritative: TRACK GAIN16 catalogued
eight dead hand-maintained closures in this repository, three of them
regenerated by a script nothing runs.
"""

import argparse
import difflib
import os
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(HERE, "rtl", "llama_top.vhd")
DST = os.path.join(HERE, "rtl", "fk33_llama_top.vhd")
TB_SRC = os.path.join(HERE, "sim", "tb_llama_top.vhd")
TB_DST = os.path.join(HERE, "sim", "tb_fk33_cardtop_ident.vhd")
EXPECT = os.path.join(HERE, "sim", "cardtop_ident_expect.txt")

OLD_ENTITY = "llama_top"
NEW_ENTITY = "fk33_llama_top"


def sub_once(text, old, new, what):
    """Replace `old` exactly once, or die naming the anchor."""
    n = text.count(old)
    if n != 1:
        sys.stderr.write(
            "gen_cardtop: ANCHOR %s matched %d times, expected exactly 1.\n"
            "The anchor was:\n---\n%s\n---\n"
            "llama_top has changed under this generator.  Fix the anchor\n"
            "deliberately; do NOT relax it to a substring.\n" % (what, n, old))
        sys.exit(2)
    return text.replace(old, new, 1)


def span_once(text, start_anchor, end_anchor, new, what):
    """Replace start_anchor .. end_anchor inclusive, exactly one span."""
    if text.count(start_anchor) != 1 or text.count(end_anchor) != 1:
        sys.stderr.write(
            "gen_cardtop: SPAN %s is not unique (start %d, end %d).\n"
            % (what, text.count(start_anchor), text.count(end_anchor)))
        sys.exit(2)
    i = text.index(start_anchor)
    j = text.index(end_anchor)
    if j <= i:
        sys.stderr.write("gen_cardtop: SPAN %s ends before it starts.\n" % what)
        sys.exit(2)
    return text[:i] + new + text[j + len(end_anchor):]


# ----------------------------------------------------------------------
# D3.  The region file.
# ----------------------------------------------------------------------
# `buf_t` is used in TWELVE other places in llama_top and must survive; only
# the flat `mem_t` subtype and the `mem` signal go, and `mem` is referenced
# nowhere outside the span replaced below (verified: llama_top.vhd:1303-1343).
D3_DECL_OLD = """  subtype mem_t is buf_t(0 to NREGION*REGMAX-1);
  signal mem : mem_t := (others => (others => '0'));
"""

D3_DECL_NEW = """  -- D3: the flat NREGION*REGMAX array is gone; see the region_mem instance
  -- in the statement part.  `buf_t` above stays, it has twelve other users.
  --
  -- THE 7-BIT MASK IS NOT COSMETIC AND IT IS WHY THESE THREE SIGNALS EXIST.
  -- llama_top's `memp` indexes with `v_reg_a(6 downto 0)`, `v_reg_b(6 downto
  -- 0)` and `v_reg_d(6 downto 0)` -- SEVEN bits of an eight-bit signal --
  -- while region_mem takes the full unsigned(7 downto 0) and does not mask.
  -- Passing the raw signals would be a behavioural difference on any value
  -- with bit 7 set, in the one direction the region_mem UNIT bench can never
  -- see, because that bench drives region_mem's own ports and never sees
  -- llama_top's masking.  It was found by pointing llama_top's own bench at
  -- the generated top, which is exactly the composition-level evidence
  -- CLAUDE.md says a per-unit evidence class cannot supply.
  signal cm_rega : unsigned(7 downto 0);
  signal cm_regb : unsigned(7 downto 0);
  signal cm_regd : unsigned(7 downto 0);
"""

D3_STMT_START = "  memp : process(clk) is"
D3_STMT_END = "  hr_data <= mem(hr_reg*REGMAX + hr_addr);"

D3_STMT_NEW = """  -- ======================================================================
  -- D3.  THE REGION FILE, as sized per-region BRAM banks.
  --
  -- GENERATED SUBSTITUTION.  llama_top's `memp` process plus its
  -- `hr_data <= mem(...)` window are replaced by one instance.  region_mem
  -- reproduces that process's contract exactly: registered one-cycle reads,
  -- pre-write (READ_FIRST) data on a collision, group-write-wins on a
  -- same-word tie, a combinational host window, and zero on a read past a
  -- region's real size.  See rtl/region_mem.vhd's header for the clause-by-
  -- clause statement and sim/tb_region_mem.vhd for the six mutations that
  -- hold it.
  --
  -- NREGION is passed as SZ'length rather than by name, deliberately: the
  -- two are the same number by construction and the attribute cannot drift
  -- out of step with the size vector the way a separate constant can.
  -- ======================================================================
  -- the mask llama_top applies, preserved verbatim; see the declarations
  cm_rega <= "0" & v_reg_a(6 downto 0);
  cm_regb <= "0" & v_reg_b(6 downto 0);
  cm_regd <= "0" & v_reg_d(6 downto 0);

  u_regmem : entity work.region_mem
    generic map (
      NREGION => SZ'length,
      REGMAX  => REGMAX,
      LANES   => LANES,
      MANT_W  => MANT_W,
      GA_W    => GA_W,
      SZ      => SZ)
    port map (
      clk      => clk,
      el_ren   => el_ren,   el_reg   => el_reg,   el_addr  => el_addr,
      el_rdata => el_rdata,
      el_we    => el_we,    el_wreg  => el_wreg,  el_waddr => el_waddr,
      el_wdata => el_wdata,
      r_en     => r_en,     r_rega   => cm_rega,  r_regb   => cm_regb,
      r_addr   => r_addr,   x_rdata  => x_rdata,  e_rdata  => e_rdata,
      w_we     => w_we,     w_regd   => cm_regd,  w_addr   => w_addr,
      w_be     => w_be,     w_data   => w_data,
      hr_reg   => hr_reg,   hr_addr  => hr_addr,  hr_data  => hr_data);
"""

BANNER = """-- rtl/fk33_llama_top.vhd
--
-- GENERATED BY tools/gen_cardtop.py FROM rtl/llama_top.vhd.  DO NOT EDIT.
-- Edit the generator, or llama_top, and regenerate.  The gate runs
-- `tools/gen_cardtop.py --check`, which regenerates and diffs, so an edit
-- made here is reverted with a failing gate rather than silently kept.
--
-- This is the CARD's top level.  llama_top stays the untouched oracle; see
-- docs/debugging/2026-08-31_cardtop-design-note.md, decision D1.
--
-- APPLIED HERE:  D3, the region file becomes sized per-region BRAM banks.
-- NOT YET APPLIED:  D1/D2, the A binding to matvec_int4_desc_axi via
-- rtl/a_desc_adapter.vhd; and D4, the w_active gate on the gain loader.
-- Until those land this top is llama_top with a different memory, which is
-- exactly what makes it testable against llama_top's own benches TODAY.
--
"""


def generate_rtl(src_text):
    t = src_text
    t = sub_once(t, D3_DECL_OLD, D3_DECL_NEW, "D3 declarations")
    t = span_once(t, D3_STMT_START, D3_STMT_END, D3_STMT_NEW, "D3 statements")
    t = sub_once(t, "entity %s is" % OLD_ENTITY,
                 "entity %s is" % NEW_ENTITY, "entity header")
    t = sub_once(t, "architecture rtl of %s is" % OLD_ENTITY,
                 "architecture rtl of %s is" % NEW_ENTITY, "architecture header")
    return BANNER + t


PIN_ANCHOR = (
    "    if fail = 0 then\n"
    "      report \"tb_fk33_cardtop_ident RESULT: PASS -- \" & integer'image(NSTEP)"
)


def read_expect():
    """The landmark llama_top itself produces, measured and checked in.

    Returned as (r_x0, xsum) or None.  None is NOT an error: it emits the
    bench with the pin omitted and a loud banner saying identity is
    UNPINNED, which is honest.  Silently emitting an unpinned bench that
    still prints PASS would be the exact defect class this repository keeps
    finding -- a guard that passes for the wrong reason.
    """
    if not os.path.exists(EXPECT):
        return None
    vals = {}
    for line in open(EXPECT):
        line = line.split("#")[0].strip()
        if not line:
            continue
        for tok in line.split():
            if "=" in tok:
                k, v = tok.split("=", 1)
                vals[k.strip()] = int(v.strip())
    if "R_X0" in vals and "HASH" in vals:
        return vals["R_X0"], vals["HASH"]
    return None


def inject_identity_pin(t):
    """Make the identity claim MECHANICAL rather than a human hash compare.

    The generated bench's own PASS line only proves the card top is
    bit-identical ACROSS DESCRIPTOR-LATENCY POINTS, which is
    self-consistency: a round trip, not an oracle.  A wrong-but-consistent
    card top passes it.  The pin below compares against the landmark
    `llama_top` ITSELF produces, which is the only statement that means
    identity.
    """
    exp = read_expect()
    if exp is None:
        return t.replace(PIN_ANCHOR,
            """    assert false
      report "tb_fk33_cardtop_ident: IDENTITY UNPINNED -- """
            """sim/cardtop_ident_expect.txt is missing, so this bench proves """
            """only self-consistency across descriptor latencies and NOT """
            """identity with llama_top.  Measure llama_top's landmark and """
            """write the file."
      severity failure;

""" + PIN_ANCHOR, 1)

    r_x0, xsum = exp
    pin = """    -- IDENTITY PIN, injected by tools/gen_cardtop.py from
    -- sim/cardtop_ident_expect.txt, which records the landmark `llama_top`
    -- ITSELF produces under this same bench.
    --
    -- WITHOUT THIS THE ROW IS NOT AN IDENTITY TEST.  The PASS line below
    -- says R_X is bit-identical across descriptor-latency points, which is
    -- SELF-consistency and is satisfied by a card top that is consistently
    -- wrong.  Only a comparison against the oracle's own number is identity.
    assert results(0)(NTOK-1)(0) = %d and xsum = %d
      report "tb_fk33_cardtop_ident: IDENTITY FAIL -- the card top does not "
           & "reproduce llama_top's landmark.  got R_X(0) = "
           & integer'image(results(0)(NTOK-1)(0)) & " hash = "
           & integer'image(xsum) & ", expected R_X(0) = %d hash = %d.  "
           & "Either a card-top substitution changed behaviour, or llama_top "
           & "moved and sim/cardtop_ident_expect.txt must be re-measured "
           & "from llama_top -- NOT from this bench."
      severity failure;

""" % (r_x0, xsum, r_x0, xsum)
    return sub_once(t, PIN_ANCHOR, pin + PIN_ANCHOR, "identity pin site")


def generate_bench(src_text):
    """The identity bench: llama_top's own bench, pointed at the card top.

    This is the cheapest possible instance of item 4's oracle and it is
    available NOW, before the A binding lands, because with only D3 applied
    the card top is REQUIRED to be behaviourally identical to llama_top.
    Any difference the bench sees is a defect in region_mem's contract, at
    the composition level, which no unit bench can reach.
    """
    n = src_text.count("entity work.%s" % OLD_ENTITY)
    if n != 1:
        sys.stderr.write(
            "gen_cardtop: the bench instantiates work.%s %d times, expected 1\n"
            % (OLD_ENTITY, n))
        sys.exit(2)
    t = src_text.replace("entity work.%s" % OLD_ENTITY,
                         "entity work.%s" % NEW_ENTITY)
    # SURGICAL, not a blanket rename.  The bench's comments refer to
    # tb_llama_top_real, _seq, _normw and _smp by name, and those are OTHER
    # files that still exist; a blanket replace would rewrite references to
    # real benches into references to files that do not exist, which reads
    # as documentation and is wrong.
    t = sub_once(t, "entity tb_llama_top is", "entity tb_fk33_cardtop_ident is",
                 "bench entity header")
    t = sub_once(t, "architecture tb of tb_llama_top is",
                 "architecture tb of tb_fk33_cardtop_ident is",
                 "bench architecture header")
    # the verdict strings, so the row is attributed to THIS bench
    n = t.count('"tb_llama_top RESULT:')
    if n < 1:
        sys.stderr.write("gen_cardtop: no verdict string found in the bench\n")
        sys.exit(2)
    t = t.replace('"tb_llama_top RESULT:', '"tb_fk33_cardtop_ident RESULT:')
    t = inject_identity_pin(t)
    return ("-- sim/tb_fk33_cardtop_ident.vhd\n"
            "--\n"
            "-- GENERATED BY tools/gen_cardtop.py FROM sim/tb_llama_top.vhd.\n"
            "-- DO NOT EDIT.  It is llama_top's own bench pointed at the card\n"
            "-- top, so a difference here is a real behavioural difference and\n"
            "-- not a difference between two benches.\n"
            "--\n") + t


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="regenerate and diff; nonzero exit if stale")
    ap.add_argument("--bench", action="store_true",
                    help="also emit the identity bench")
    args = ap.parse_args()

    src = open(SRC).read()
    out = generate_rtl(src)
    pairs = [(DST, out)]
    if args.bench:
        pairs.append((TB_DST, generate_bench(open(TB_SRC).read())))

    stale = False
    for path, text in pairs:
        if args.check:
            if not os.path.exists(path):
                print("STALE: %s does not exist" % path)
                stale = True
                continue
            have = open(path).read()
            if have != text:
                stale = True
                print("STALE: %s differs from what the generator emits" % path)
                for line in list(difflib.unified_diff(
                        have.splitlines(True), text.splitlines(True),
                        "checked-in", "generated"))[:40]:
                    sys.stdout.write(line)
        else:
            open(path, "w").write(text)
            print("wrote %s (%d lines)" % (path, text.count("\n")))

    if args.check:
        if stale:
            print("GEN_CARDTOP_CHECK: STALE")
            return 1
        print("GEN_CARDTOP_CHECK: OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
