#!/usr/bin/env python3
# tools/gen_imrope_pkg.py
# Generate rtl/imrope_pkg.vhd: the stateless twiddle constants for subsystem
# C's IMROPE (C spec 3.4, sites R1/R2).
#
# WHY THIS AND NOT rope_rom_pkg.vhd.  That package is a PER-POSITION table --
# 512 positions x 4 pairs for stories260K.  At the 27B geometry the same shape
# is MAXCTX x 32 pairs x 2 tables x 16 b = 58 RAMB36 at 2K context and ~930 at
# the 32K cap, which the C spec rejects outright.  This package is 32 u32
# constants plus one 1,024-entry Q15 quarter-wave-symmetric sine table, and it
# is independent of the context length.
#
#   W[j]   = round( 2^32 * base^(-j/NPAIR) / (2*pi) )   turns per position
#   SIN[i] = round( 32767 * sin(2*pi*i/1024) )          Q15
#
# THE C REFERENCE DELIBERATELY DOES NOT INCLUDE THIS OUTPUT.  ref/attn_twiddle_vec.c
# recomputes both tables from libm rather than reading anything this tool
# emits.  That is a deviation from subsystem A's 6.4 "one tool emits both"
# discipline and it is deliberate: for a table defined by a closed-form
# formula, two independent computations that must agree BIT FOR BIT is a
# stronger check than one computation used twice, and the bit-exact testbench
# is the drift detector.  The reference additionally checks every entry against
# libm to half an ulp, so the table is validated rather than trusted.
import math, os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

NPAIR = 32          # N_ROT / 2
TBL   = 1024        # sine table entries, one full turn
BASE  = 1.0e7       # GGUF qwen35.rope.freq_base
QMAX  = 32767       # Q15

def emit(vals, per_line_width=96):
    lines, row = [], "    "
    for i, v in enumerate(vals):
        piece = str(v) + ("," if i != len(vals) - 1 else "")
        if len(row) + len(piece) + 1 > per_line_width and row.strip():
            lines.append(row.rstrip())
            row = "    "
        row += piece + " "
    if row.strip():
        lines.append(row.rstrip())
    return "\n".join(lines)

W   = [round(2.0**32 * BASE**(-j/float(NPAIR)) / (2.0*math.pi)) for j in range(NPAIR)]
SIN = [round(QMAX * math.sin(2.0*math.pi*i/TBL)) for i in range(TBL)]

assert all(0 <= w < 2**31 for w in W), "W must fit a VHDL integer"
assert SIN[0] == 0 and SIN[TBL//4] == QMAX and SIN[TBL//2] == 0
assert all(SIN[i + TBL//2] == -SIN[i] for i in range(TBL//2))

out = os.path.join(ROOT, "rtl", "imrope_pkg.vhd")
with open(out, "w") as f:
    f.write("""-- rtl/imrope_pkg.vhd
-- AUTO-GENERATED by tools/gen_imrope_pkg.py.  DO NOT EDIT BY HAND.
-- Regenerate: python3 tools/gen_imrope_pkg.py
--
-- Subsystem C, sites R1/R2: the stateless IMROPE twiddle constants.
--
--   IMROPE_W(j) = round( 2^32 * %g^(-j/%d) / (2*pi) )   turns per position, u32
--   SIN_TBL(i)  = round( %d * sin(2*pi*i/%d) )          Q15, one full turn
--
-- These replace a per-position ROM.  At the 27B geometry a per-position table
-- would be 58 RAMB36 at 2K context and ~930 at 32K; this is 128 B plus one
-- RAMB18-class table and does not scale with the context length at all.
--
-- ref/attn_twiddle_vec.c RECOMPUTES both of these from libm rather than
-- reading this file, so a drift between the two is a bit-exact testbench
-- FAILURE on the first vector rather than a shared error.
library ieee; use ieee.std_logic_1164.all; use ieee.numeric_std.all;

package imrope_pkg is
  constant IMROPE_NPAIR : integer := %d;
  constant IMROPE_TBL   : integer := %d;
  constant IMROPE_W : integer_vector(0 to %d) := (
%s
  );
  constant SIN_TBL : integer_vector(0 to %d) := (
%s
  );
end package;
""" % (BASE, NPAIR, QMAX, TBL, NPAIR, TBL, NPAIR-1, emit(W), TBL-1, emit(SIN)))
print("wrote %s: %d W constants, %d sine entries" % (out, len(W), len(SIN)))
print("W[0] = %d, W[%d] = %d" % (W[0], NPAIR-1, W[NPAIR-1]))
