#!/usr/bin/env python3
# tools/gen_fixed_luts_pkg.py
# Generate rtl/fixed_luts_pkg.vhd from the mem/luts/*.mem files so that
# fixed_pkg.vhd needs no std.textio at elaboration (synthesizable in Vivado).
# The emitted constants are bit-identical, in order, to what load_mem() read.
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
LUTS = os.path.join(ROOT, "mem", "luts")

# (VHDL constant name, mem file, expected length) -- must match fixed_pkg.vhd
TABLES = [
    ("RSQRT_ROM", "rsqrt_seed.mem", 64),
    ("EXP_ROM",   "exp_lut.mem",    257),
    ("SIG_ROM",   "sig_lut.mem",    513),
]


def read_mem(fn, n):
    vals = []
    with open(os.path.join(LUTS, fn)) as f:
        for line in f:
            line = line.strip()
            if line == "":
                continue
            vals.append(int(line))
    if len(vals) != n:
        raise SystemExit("%s: expected %d values, got %d" % (fn, n, len(vals)))
    return vals


def emit_aggregate(vals):
    # Positional aggregate, wrapped for readability.
    items = [str(v) for v in vals]
    lines = []
    row = "    "
    for i, it in enumerate(items):
        piece = it + ("," if i != len(items) - 1 else "")
        if len(row) + len(piece) + 1 > 100 and row.strip():
            lines.append(row.rstrip())
            row = "    "
        row += piece + " "
    if row.strip():
        lines.append(row.rstrip())
    return "\n".join(lines)


def main():
    out = []
    out.append("-- rtl/fixed_luts_pkg.vhd")
    out.append("-- AUTO-GENERATED by tools/gen_fixed_luts_pkg.py from mem/luts/*.mem")
    out.append("-- DO NOT EDIT BY HAND. Values are bit-identical to the .mem ROM files")
    out.append("-- and replace the former std.textio load_mem() init so fixed_pkg.vhd")
    out.append("-- is synthesizable (Vivado). Regenerate: python3 tools/gen_fixed_luts_pkg.py")
    out.append("library ieee; use ieee.std_logic_1164.all; use ieee.numeric_std.all;")
    out.append("")
    out.append("package fixed_luts_pkg is")
    for name, fn, n in TABLES:
        vals = read_mem(fn, n)
        out.append("  constant %s : integer_vector(0 to %d) := (" % (name, n - 1))
        out.append(emit_aggregate(vals))
        out.append("  );")
    out.append("end package;")
    out.append("")

    dst = os.path.join(ROOT, "rtl", "fixed_luts_pkg.vhd")
    with open(dst, "w") as f:
        f.write("\n".join(out))
    print("wrote", dst)


if __name__ == "__main__":
    main()
