#!/usr/bin/env python3
"""Generate rtl/wq_l0_rom_pkg.vhd : a synthesizable VHDL constant package holding
the layer-0 Wq weight mantissas (int16) as an on-chip ROM.  No TEXTIO at
elaboration, so it is Vivado-synthesizable.

SOURCE OF TRUTH
---------------
The int16 fixed-point golden model (mem/golden/fx_matvec_wq_l0.txt) is the
bit-exact spec.  The weight mantissas that reproduce that golden live in
    mem/weights/L0/wq.mem      (row-major d*n = 64*64 = 4096 int16 values)
NOT in the older mem/weights/wq_l0.mem, which is the *stale int8* quantization
(all 4096 values differ from the golden; superseded by the "int8 -> int16"
numeric-format change).  This script cross-checks the chosen source against the
golden weight rows and refuses to emit if they disagree, so the ROM can never
silently drift from the spec.

Usage:  python3 tools/gen_wq_l0_rom_pkg.py [--src <mem>] [--out <vhd>]
"""
import argparse, os, sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEF_SRC = os.path.join(REPO, "mem/weights/L0/wq.mem")
DEF_GOLD = os.path.join(REPO, "mem/golden/fx_matvec_wq_l0.txt")
DEF_OUT = os.path.join(REPO, "rtl/wq_l0_rom_pkg.vhd")

def load_mem(path):
    return [int(l) for l in open(path) if l.strip()]

def load_golden_weights(path):
    lines = [l.strip() for l in open(path) if l.strip()]
    d, n = map(int, lines[0].split())
    rows = []
    for i in range(d):
        parts = [int(x) for x in lines[3 + i].split()]
        rows.append(parts[:n])
    return d, n, rows

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default=DEF_SRC)
    ap.add_argument("--gold", default=DEF_GOLD)
    ap.add_argument("--out", default=DEF_OUT)
    a = ap.parse_args()

    mem = load_mem(a.src)
    d, n, rows = load_golden_weights(a.gold)
    total = d * n
    if len(mem) != total:
        sys.exit(f"ERROR: {a.src} has {len(mem)} values, golden expects {total}")

    # Bit-exact cross-check against the golden weight rows.
    bad = 0
    for i in range(d):
        for j in range(n):
            if mem[i * n + j] != rows[i][j]:
                bad += 1
                if bad <= 5:
                    print(f"  mismatch [{i}][{j}] src={mem[i*n+j]} golden={rows[i][j]}",
                          file=sys.stderr)
    if bad:
        sys.exit(f"ERROR: {bad}/{total} weights in {a.src} do not match the golden "
                 f"({a.gold}); refusing to emit a ROM that would not reproduce the spec.")

    lo, hi = min(mem), max(mem)
    if lo < -32768 or hi > 32767:
        sys.exit(f"ERROR: value out of int16 range (min {lo}, max {hi})")

    with open(a.out, "w") as f:
        w = f.write
        w("-- rtl/wq_l0_rom_pkg.vhd  -- AUTO-GENERATED, do not edit by hand.\n")
        w(f"-- Generated by tools/gen_wq_l0_rom_pkg.py from {os.path.relpath(a.src, REPO)}\n")
        w(f"-- Cross-checked bit-exact against {os.path.relpath(a.gold, REPO)} ({total} values).\n")
        w("-- Layer-0 Wq weight mantissas (int16), row-major OUT_DIM*IN_DIM = 64*64 = 4096.\n")
        w("library ieee; use ieee.std_logic_1164.all; use ieee.numeric_std.all;\n")
        w("package wq_l0_rom_pkg is\n")
        w("  type intarr is array(natural range <>) of integer;\n")
        w(f"  constant WQ_L0_OUT_DIM : natural := {d};\n")
        w(f"  constant WQ_L0_IN_DIM  : natural := {n};\n")
        w(f"  constant WQ_L0 : intarr(0 to {total-1}) := (\n")
        # 16 values per line for readability
        per = 16
        for k in range(0, total, per):
            chunk = mem[k:k + per]
            sep = "," if (k + per) < total else ""
            w("    " + ", ".join(str(v) for v in chunk) + ("," if (k + per) < total else "") + "\n")
        w("  );\n")
        w("end package;\n")

    print(f"OK: wrote {a.out}  ({total} int16 values, range [{lo},{hi}], "
          f"cross-checked against golden)")

if __name__ == "__main__":
    main()
