#!/usr/bin/env python3
"""Emit the FK33 host/device register map as a C header, from ONE source.

WHY THIS EXISTS.  The map was defined twice: as Python constants in
gen_pcieep.py, which configures the block design and therefore decides what the
hardware actually does, and again as #define lines in host/fk33_bringup.c with
a comment reading "Must match hw/fk33/gen_pcieep.py".  A comment is not a
mechanism.  The two copies agreed only for as long as someone remembered.

That was survivable inside one repository and is not survivable across two: the
host runtime now lives in its own repo, so a silent divergence would put a
correct-looking host program against a differently-mapped bitstream, and the
symptom would be reads returning plausible values from the wrong peripheral.

So gen_pcieep.py stays the single source and this emits the header from it.
Run with --check to verify the checked-in header is in step; that is the same
pattern tools/gen_arith.py already uses in this project, and it exists because
a generated file that nobody verifies drifts exactly as fast as a duplicated
one.  Note what happened there: someone hand-added a real fix to the GENERATED
file and every build silently deleted it.  Do not edit fk33_regs.h.
"""
import argparse
import importlib.util
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
TARGET = HERE / "host" / "fk33_regs.h"


def load_source():
    spec = importlib.util.spec_from_file_location("gen_pcieep", HERE / "gen_pcieep.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def size_bytes(v):
    """gen_pcieep spells sizes as Vivado strings: '8K', '64K'."""
    if isinstance(v, int):
        return v
    s = str(v).strip().upper()
    if s.endswith("K"):
        return int(s[:-1]) * 1024
    if s.endswith("M"):
        return int(s[:-1]) * 1024 * 1024
    return int(s, 0)


def render(g):
    return f'''/* GENERATED by hw/fk33/gen_fk33_regs.py from hw/fk33/gen_pcieep.py.
 *
 * DO NOT EDIT.  gen_pcieep.py configures the block design, so it decides what
 * the hardware does; this file only reports it.  An edit here changes what the
 * host believes and not what the card implements, which is the one failure
 * mode this header exists to prevent.
 *
 * Verify with:  python3 hw/fk33/gen_fk33_regs.py --check
 */
#ifndef FK33_REGS_H
#define FK33_REGS_H

#include <stdint.h>

/* ---- AXI-Lite BAR, 128 KB, /dev/xdma0_user ----------------------------- */

/* Read-only identity, axi_gpio with both channels all-inputs.  A correct read
 * is not something a merely-loaded driver can fake: 0xFFFFFFFF means the BAR
 * is mapped with nothing answering, and 0x00000000 means the fabric is in
 * reset, so both of the plausible wrong answers are distinguishable. */
#define FK33_ID_BASE        0x{g.ID_BASE:08X}u
#define FK33_ID_MAGIC_OFF   (FK33_ID_BASE + 0x0u)
#define FK33_ID_BUILD_OFF   (FK33_ID_BASE + 0x8u)
#define FK33_ID_MAGIC       0x{g.ID_MAGIC:08X}u   /* "FK33" in ASCII */
#define FK33_ID_BUILD       0x{g.ID_BUILD:08X}u   /* yyyymmdd */

/* Read/write scratch BRAM.  The only thing in the design that proves MMIO
 * WRITES land without driving a real board pin. */
#define FK33_SCRATCH_BASE   0x{g.SCRATCH_BASE:08X}u
#define FK33_SCRATCH_SIZE   0x{size_bytes(g.SCRATCH_SIZE):X}u

/* ---- DMA master space, /dev/xdma0_h2c_0 and _c2h_0 --------------------- */
/* The file offset IS the AXI address, which is the whole reason XDMA was
 * chosen over QDMA. */

/* Deliberately ABOVE the 8 GB of HBM, so a DMA fault can never be confused
 * with an HBM fault and an off-by-one in a host offset lands on nothing
 * rather than silently in memory. */
#define FK33_DMABRAM_BASE   0x{g.DMABRAM_BASE:X}ull
#define FK33_DMABRAM_SIZE   0x{size_bytes(g.DMABRAM_SIZE):X}ull
#define FK33_HBM_TOP        0x{g.DMABRAM_BASE:X}ull

/* ---- Thermal protection ------------------------------------------------ */
/* Five status words plus one control word, produced by rtl/fk33_thermal.vhd on
 * the free-running aux clock and resynchronised into the AXI-Lite clock domain
 * by the module itself.  The SAME five words are also readable over the
 * jtag_aux master with the PCIe link DOWN, at a different address space -- so a
 * card that has halted and dropped off the bus can still be asked why.
 *
 * THERM_STATUS bit 31 is a constant 1.  A bitstream WITHOUT the thermal guard
 * reads 0 there, so "is this card protected" is one read and not a guess. */
#define FK33_THERM_BASE     0x{g.THERM_BASE:08X}u
#define FK33_THERM_STATUS   (FK33_THERM_BASE  + 0x0u)
#define FK33_THERM_TEMPS    (FK33_THERM_BASE  + 0x8u)
#define FK33_THERMP_BASE    0x{g.THERMP_BASE:08X}u
#define FK33_THERM_PEAK     (FK33_THERMP_BASE + 0x0u)
#define FK33_THERM_TRIP     (FK33_THERMP_BASE + 0x8u)
#define FK33_THERMC_BASE    0x{g.THERMC_BASE:08X}u
#define FK33_THERM_CTL      (FK33_THERMC_BASE + 0x0u)   /* write */
#define FK33_THERM_CANARY   (FK33_THERMC_BASE + 0x8u)

/* THERM_CTL[31:16] must be the key or the write does nothing, and both clears
 * are EDGE triggered: write the key with the bit set, then write 0. */
#define FK33_THERM_KEY      0x{g.THERM_CTL_KEY:04X}u
#define FK33_THERM_CLR_TRIP 0x1u
#define FK33_THERM_CLR_PEAK 0x2u

/* THERM_STATUS fields */
#define FK33_THERM_HALTED   (1u << 0)
#define FK33_THERM_WARN     (1u << 1)
#define FK33_THERM_ARMED    (1u << 2)
#define FK33_THERM_DIE_OK   (1u << 3)
#define FK33_THERM_HBM_OK   (1u << 4)
#define FK33_THERM_DIE_HOT  (1u << 5)
#define FK33_THERM_HBM_HOT  (1u << 6)
#define FK33_THERM_TRIPPED  (1u << 7)
#define FK33_THERM_PRESENT  (1u << 31)
#define FK33_THERM_CAUSE(v)      (((v) >> 8) & 0xFu)
#define FK33_THERM_TRIP_CAUSE(v) (((v) >> 12) & 0xFu)
#define FK33_THERM_TRIP_COUNT(v) (((v) >> 16) & 0xFFu)

/* cause codes */
#define FK33_CAUSE_NONE      0u
#define FK33_CAUSE_DIE_OT    1u   /* SYSMON's armed over-temperature alarm */
#define FK33_CAUSE_DIE_ALARM 2u   /* SYSMON user temperature alarm */
#define FK33_CAUSE_DIE_OVER  3u
#define FK33_CAUSE_DIE_STALE 4u   /* not live, or an implausible reading */
#define FK33_CAUSE_HBM_CAT   5u   /* a stack asserted CATTRIP */
#define FK33_CAUSE_HBM_OVER  6u
#define FK33_CAUSE_HBM_STALE 7u

/* The thresholds the bitstream enforces, in degrees C.  The HBM ones are in
 * RAW 7-bit stack-code units: the code-to-Celsius mapping of
 * DRAM_x_STAT_TEMP is NOT calibrated on this card. */
#define FK33_THERM_DIE_WARN    {g.THERM_DIE_WARN_C}
#define FK33_THERM_DIE_HALT    {g.THERM_DIE_HALT_C}
#define FK33_THERM_DIE_RESUME  {g.THERM_DIE_RESUME_C}
#define FK33_THERM_HBM_WARN    {g.THERM_HBM_WARN_C}
#define FK33_THERM_HBM_HALT    {g.THERM_HBM_HALT_C}
#define FK33_THERM_HBM_RESUME  {g.THERM_HBM_RESUME_C}

/* ---- PCIe identity ------------------------------------------------------ */
/* Already carried by dma_ip_drivers, so new_id should not be needed. */
#define FK33_PCI_VENDOR     0x10EEu
#define FK33_PCI_DEVICE     0x9034u

#endif /* FK33_REGS_H */
'''


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="verify the checked-in header matches, exit 1 if not")
    args = ap.parse_args()

    text = render(load_source())

    if args.check:
        if not TARGET.exists():
            print(f"MISSING: {TARGET} does not exist", file=sys.stderr)
            return 1
        if TARGET.read_text() != text:
            print(f"STALE: {TARGET} does not match hw/fk33/gen_pcieep.py.\n"
                  f"  Regenerate with: python3 {pathlib.Path(__file__).name}\n"
                  f"  Do NOT hand-edit the header -- gen_pcieep.py decides what "
                  f"the hardware does, and this file only reports it.",
                  file=sys.stderr)
            return 1
        print("fk33_regs.h is in step with gen_pcieep.py")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(text)
    print(f"wrote {TARGET}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
