"""tools/rate/shell.py -- a registered-I/O wrapper so a block is timed register to
register, as it sits in the card, not against unconstrained OOC pins.
The shell RE-DECLARES the block's generics (defaults = the manifest's values) so port
types that reference them, e.g. std_logic_vector(W-1 downto 0), resolve."""
import fnmatch, re

def _strip(t):
    return re.sub(r"--[^\n]*", "", t)

def _clause(block, kw):
    m = re.search(r"\b%s\s*\(" % kw, block, re.I)
    if not m:
        return ""
    i, depth = m.end(), 1
    while depth:
        c = block[i]
        depth += (c == "(") - (c == ")")
        i += 1
    return block[m.end():i - 1]

def _items(inner):
    out, depth, cur = [], 0, ""
    for c in inner:
        depth += (c == "(") - (c == ")")
        if c == ";" and depth == 0:
            out.append(cur.strip()); cur = ""
        else:
            cur += c
    if cur.strip():
        out.append(cur.strip())
    return out

def parse_entity(text, name):
    t = _strip(text)
    m = re.search(r"\bentity\s+%s\s+is(.*?)\bend\s+(entity|%s)\b" % (name, name), t, re.I | re.S)
    if not m:
        raise SystemExit("entity %s not found" % name)
    block = m.group(1)
    context = t[:m.start()].strip()
    gens, ports = [], []
    for it in _items(_clause(block, "generic")):
        names, rest = it.split(":", 1)
        typ, _, dflt = rest.partition(":=")
        for n in names.split(","):
            gens.append((n.strip(), typ.strip(), dflt.strip()))
    for it in _items(_clause(block, "port")):
        names, rest = it.split(":", 1)
        rest = rest.split(":=")[0].strip()
        mode, typ = rest.split(None, 1)
        for n in names.split(","):
            ports.append((n.strip(), mode.lower(), typ.strip()))
    return {"context": context, "generics": gens, "ports": ports}

def port_clock(row, port):
    clocks = row["clocks"]
    for c, globs in clocks.items():
        if globs != "*" and any(fnmatch.fnmatch(port, g) for g in globs):
            return c
    return next(iter(clocks))

def gen_shell(row, entity_text):
    e = parse_entity(entity_text, row["top"])
    bad = [p for p in e["ports"] if p[1] not in ("in", "out")]
    if bad:
        raise SystemExit("rate shell: port %s is %s; inout/buffer ports need an adapter row" % (bad[0][0], bad[0][1]))
    clocks = sorted(row["clocks"])   # never a set: its order follows PYTHONHASHSEED, and the text is keyed
    gl = ["    %s : %s := %s" % (n, typ, row["generics"].get(n, d)) for (n, typ, d) in e["generics"]]
    missing = [n for (n, _, d) in e["generics"] if n not in row["generics"] and not d]
    if missing:
        raise SystemExit("rate shell: generic %s has no default and no manifest value" % missing[0])
    pl = ["    %s : %s %s" % (n, m, t) for (n, m, t) in e["ports"]]
    sigs, regs, pmap = [], {c: [] for c in clocks}, []
    for (n, m, t) in e["ports"]:
        if n in clocks:
            pmap.append("%s => %s" % (n, n)); continue
        c = port_clock(row, n)
        if m == "in":
            sigs.append("  signal %s_q : %s;" % (n, t))
            regs[c].append("      %s_q <= %s;" % (n, n))
            pmap.append("%s => %s_q" % (n, n))
        else:
            sigs.append("  signal %s_q : %s;" % (n, t))
            regs[c].append("      %s <= %s_q;" % (n, n))
            pmap.append("%s => %s_q" % (n, n))
    procs = []
    for c, lines in regs.items():
        if lines:
            procs.append("  process(%s) begin\n    if rising_edge(%s) then\n%s\n    end if;\n  end process;"
                         % (c, c, "\n".join(lines)))
    gclause = "  generic(\n%s);\n" % ";\n".join(gl) if gl else ""
    gmap = ("    generic map(%s)\n" % ", ".join("%s => %s" % (n, n) for (n, _, _) in e["generics"])
            if gl else "")
    return ("-- GENERATED by tools/rate/shell.py for block %s; DO NOT HAND-EDIT.\n%s\n\n"
            "entity rate_shell is\n%s  port(\n%s);\nend entity;\n\n"
            "architecture rtl of rate_shell is\n%s\nbegin\n"
            "  u_dut : entity work.%s\n%s    port map(%s);\n%s\nend architecture;\n"
            % (row["top"], e["context"], gclause, ";\n".join(pl), "\n".join(sigs),
               row["top"], gmap, ",\n      ".join(pmap), "\n".join(procs)))
